// Agent Rory: Operation Eclipse — the story as data.
// Everything here is transcribed from STORY.md. Dialogue lines are
// [speaker, text]; speakers are keys of CHARS. Sophia, Rory and Dylan Games, Inc.

export const CHARS = {
  rory:    { name: "Rory", voice: { g: "m", langs: ["en-GB"], pitch: 1.15, rate: 1.05 },
             face: { skin: "#f3cfae", hair: "#6b4423", style: "short", eyes: "#3b5f8a", clothes: "#2c3e6b", accessory: "earpiece" } },
  hale:    { name: "Commander Hale", voice: { g: "f", langs: ["en-GB"], pitch: 0.8, rate: 0.9 },
             face: { skin: "#e9c1a0", hair: "#d8d8d8", style: "bun", eyes: "#4a4a4a", clothes: "#1b2a4a", accessory: "medal", brows: "stern" } },
  vi:      { name: "Aunt Vi", voice: { g: "f", langs: ["en-GB"], pitch: 1.35, rate: 1.12 },
             face: { skin: "#f0c9a6", hair: "#c9462f", style: "curly", eyes: "#3d7a3a", glasses: "round", clothes: "#7a3fa0", accessory: "pencil" } },
  eclipse: { name: "Madame Eclipse", voice: { g: "f", langs: ["fr-FR"], pitch: 0.85, rate: 0.85 },
             face: { skin: "#f1d6c1", hair: "#101010", style: "sleek", eyes: "#222", glasses: "dark", clothes: "#0a0a0a", accessory: "collar", lips: "#b0102a" } },
  kolya:   { name: "Kolya", voice: { g: "m", langs: ["ru-RU"], pitch: 0.7, rate: 0.9 },
             face: { skin: "#e8b995", hair: "#3a2a1a", style: "ushanka", eyes: "#4a4a4a", facial: "beard", clothes: "#5a4a3a", big: true, accessory: "food" } },
  dave:    { name: "Dave", voice: { g: "m", langs: ["en-GB"], pitch: 1.0, rate: 1.05 },
             face: { skin: "#d9a57c", hair: "#2a2a2a", style: "flatcap", eyes: "#3a3a3a", clothes: "#3a3a3a", accessory: "scarf" } },
  lorenzo: { name: "Lorenzo", voice: { g: "m", langs: ["it-IT"], pitch: 1.0, rate: 1.0 },
             face: { skin: "#e2b48c", hair: "#1e1410", style: "boater", eyes: "#3a2a1a", facial: "moustache", clothes: "#c0392b", stripes: true } },
  nadia:   { name: "Dr Farouk", voice: { g: "f", langs: ["en-GB"], pitch: 1.05, rate: 0.95 },
             face: { skin: "#c9946a", hair: "#2a1a10", style: "scarf", eyes: "#3a2a1a", clothes: "#b8860b", accessory: "brush" } },
  yuki:    { name: "Yuki", voice: { g: "f", langs: ["en-US"], pitch: 1.25, rate: 1.12 },
             face: { skin: "#f3d9c4", hair: "#141414", style: "bandana", eyes: "#222", clothes: "#c0392b", accessory: "chopsticks" } },
  sal:     { name: "Detective Sal", voice: { g: "m", langs: ["en-US"], pitch: 0.9, rate: 1.0 },
             face: { skin: "#e0b08a", hair: "#4a3a2a", style: "trilby", eyes: "#3a3a3a", facial: "stubble", clothes: "#6b5b45", accessory: "badge" } },
  tiago:   { name: "Tiago", voice: { g: "m", langs: ["pt-BR"], pitch: 1.0, rate: 1.0 },
             face: { skin: "#b57a4e", hair: "#1a1a1a", style: "surfer", eyes: "#2a1a10", clothes: "#27ae60", accessory: "shades_up" } },
  natasha: { name: "Natasha", voice: { g: "f", langs: ["ru-RU"], pitch: 1.1, rate: 0.95 },
             face: { skin: "#f2d5c2", hair: "#e8c070", style: "long", eyes: "#4a7aa0", clothes: "#4a5a6a", accessory: "headset" } },
  nigel:   { name: "Nigel Pratt", voice: { g: "m", langs: ["en-GB"], pitch: 1.3, rate: 1.0 },
             face: { skin: "#f1c9a5", hair: "#8a7a5a", style: "bald", eyes: "#4a4a4a", facial: "moustache", clothes: "#2a4a8a", accessory: "capguard", sweaty: true } },
  watch:   { name: "Spy Watch", voice: { g: "n", langs: ["en-GB"], pitch: 1.0, rate: 1.1 },
             face: { skin: "#223", hair: "#223", style: "watch", eyes: "#7fd", clothes: "#223" } },
  // Act 2
  chairman:{ name: "The Chairman", voice: { g: "m", langs: ["de-DE"], pitch: 0.7, rate: 0.85 },
             face: { skin: "#e8d0c0", hair: "#c8c8c8", style: "sleek", eyes: "#3a3a3a", glasses: "round", clothes: "#101018", accessory: "collar", brows: "stern", facial: "moustache" } },
  colette: { name: "Colette", voice: { g: "f", langs: ["fr-FR"], pitch: 1.15, rate: 1.05 },
             face: { skin: "#f1d2b8", hair: "#3a2a1a", style: "beret", eyes: "#3a5a3a", clothes: "#8a1a2a", accessory: "scarf", lips: "#c0304a" } },
  jeanluc: { name: "Jean-Luc", voice: { g: "m", langs: ["fr-FR"], pitch: 1.05, rate: 1.0 },
             face: { skin: "#e8c8a8", hair: "#1a1a1a", style: "short", eyes: "#2a2a2a", facial: "stubble", clothes: "#2a2a30", accessory: "collar", sweaty: true } },
  amani:   { name: "Amani", voice: { g: "m", langs: ["en-GB"], pitch: 0.95, rate: 0.95 },
             face: { skin: "#6b4226", hair: "#111111", style: "short", eyes: "#2a1a10", clothes: "#8a7a4a", accessory: "badge" } },
  priya:   { name: "Priya", voice: { g: "f", langs: ["en-IN", "en-GB"], pitch: 1.2, rate: 1.08 },
             face: { skin: "#b8845a", hair: "#1a1010", style: "long", eyes: "#2a1a10", clothes: "#d0407a", accessory: "pencil" } },
  mei:     { name: "Mei", voice: { g: "f", langs: ["en-US"], pitch: 1.15, rate: 1.0 },
             face: { skin: "#f3ddc4", hair: "#141414", style: "bun", eyes: "#222", clothes: "#c0392b", accessory: "chopsticks" } },
  matilda: { name: "Matilda", voice: { g: "f", langs: ["en-AU", "en-GB"], pitch: 1.1, rate: 1.1 },
             face: { skin: "#e8b890", hair: "#e8c070", style: "surfer", eyes: "#3a7aa0", clothes: "#e63946", accessory: "shades_up" } },
  diego:   { name: "Diego", voice: { g: "m", langs: ["es-MX", "es-ES"], pitch: 1.0, rate: 1.0 },
             face: { skin: "#c08a5a", hair: "#1a1a1a", style: "sombrero", eyes: "#2a1a10", facial: "moustache", clothes: "#1a1a1a", accessory: "guitar" } },
  klaus:   { name: "Klaus", voice: { g: "m", langs: ["de-DE"], pitch: 0.9, rate: 0.95 },
             face: { skin: "#f0c8a8", hair: "#8a6a3a", style: "ushanka", eyes: "#3a5a8a", facial: "beard", clothes: "#3a5a3a", accessory: "scarf" } },
};

// Abort-code symbols for the finale keypad, drawn by the UI (no fonts needed).
export const SYMBOLS = ["sun", "moon", "star", "bolt", "eye", "key", "wave", "diamond", "skull"];


// Missions: id, title, game, level (1-4), station (in the scene), stationLabel,
// icon, intro/outro dialogue, intel, and optional params for the mini-game.
const NIGEL = [
  ["My name is Nigel Pratt and I have guarded this Observatory for eleven years.", false],
  ["I was at my desk all night. I never let anybody in.", true],
  ["I take three sugars in my tea. Maybe four.", false],
  ["I have never in my life heard of a man called Fingers Malone.", true],
  ["Nobody gave me an envelope of cash. Nobody at all.", true],
  ["The door code was changed by the day shift, not by me.", true],
  ["My mum thinks I work at the library.", false],
  ["I'm very, very sorry.", false],
];
const JEANLUC = [
  ["I am Jean-Luc Fauve. I deliver flowers. Only flowers.", true],
  ["I have lived in Paris all my life.", false],
  ["I have never met a woman called Madame Eclipse.", true],
  ["The crate I carried last night was full of tulips.", true],
  ["I am afraid of pigeons. It is not funny.", false],
  ["The Louvre? I have never been inside. Too many paintings.", true],
  ["My van is painted white. It has always been white.", false],
  ["I do not know what a Shadow Lantern is.", true],
];
const CHAIRMAN = [
  ["Welcome, Agent Rory. I have followed your little tour with interest.", false],
  ["Madame Eclipse works for me. She always has.", false],
  ["The seventh lantern is not in this mountain. You are wasting your time.", true],
  ["I have never been to London. Dreadful weather.", true],
  ["The master switch cannot be turned off. It has no off.", true],
  ["My real name is Otto. I dislike it.", false],
  ["Madame Eclipse is already on a plane to the other side of the world.", true],
  ["Nobody has ever beaten me. Nobody ever will.", true],
];

export const COUNTRIES = [
  // ================================================================ ACT ONE
  {
    id: "london", act: 1, city: "London", country: "England", flag: "uk", lat: 51.5, lon: -0.12,
    chapter: "The Greenwich Job", sky: "night", ambience: "rain", contact: "dave",
    arrive: [
      ["dave", "Evening, Agent Rory. Dave, M.I.S.T. wheelman. Lovely night for it. If you're a duck."],
      ["dave", "The Observatory's up the hill, past the phone box. The thieves changed the door code on their way out. Cheeky."],
      ["vi", "Rory, it's Vi. Walk with the left thumb, look with the right, and tap the green button when you reach something glowing."],
    ],
    missions: [
      { id: "lon1", title: "The Door Code", game: "codebreaker", level: 1, station: "obsdoor", stationLabel: "The Observatory's locked door", icon: "keypad",
        intro: [["vi", "A five-star UMBRA lock. Guess a code and it tells you how many symbols are right and in the right place, and how many are right but in the wrong place."], ["vi", "Use every answer. Eight guesses is plenty for a spy."]],
        outro: [["rory", "It's open. And the door log says it was opened at fourteen minutes past two. From the INSIDE."], ["hale", "Then somebody let them in. The night guard is called Nigel Pratt. Ask him. Nicely, then not nicely."]],
        intel: { title: "The door log", text: "The Observatory was opened from the inside at 2:14 am. Somebody let the thieves in." } },
      { id: "lon2", title: "Nothing But the Truth", game: "lie", level: 2, station: "observatory", stationLabel: "Royal Observatory", icon: "dome",
        params: { statements: NIGEL, suspect: "nigel" },
        intro: [["nigel", "I never saw nothing. Nothing at all. I was at my desk with my tea."], ["vi", "He's wired to the polygraph. Smooth waves mean the truth. Jumpy spikes mean a fib. Some fibs are sneaky and small, so watch closely."]],
        outro: [["nigel", "Alright! ALRIGHT! A lady with a voice like silk paid me. I let a man in. Fingers Malone."], ["nigel", "He's hiding in the flat above the chip shop on Baker Street. Please don't tell my mum."], ["hale", "Good work. Dave has been parked outside that flat for an hour. Ask him what his camera saw."]],
        intel: { title: "The thief", text: "\"Fingers\" Malone stole the blueprints. He is hiding in the flat above the chip shop on Baker Street." } },
      { id: "lon3", title: "Dashcam", game: "spotdiff", level: 1, station: "cab", stationLabel: "Dave's cab", icon: "camera",
        intro: [["dave", "My dashcam takes a picture of that flat every ten minutes, guv. Here's one from before Fingers legged it and one from after."], ["vi", "Spot everything that changed between the two pictures. Tap the differences on the right-hand one."]],
        outro: [["rory", "The painting of the horse has moved. There's something behind it. A safe!"], ["dave", "And he's took the telly. Charming."]],
        intel: { title: "The dashcam", text: "Fingers left in a hurry and moved the painting of the horse. There is a wall safe behind it." } },
      { id: "lon4", title: "Fingers' Flat", game: "safe", level: 2, station: "flat", stationLabel: "Flat above the chip shop", icon: "door",
        intro: [["rory", "A safe behind the painting. Four numbers on this one, Vi."], ["vi", "My stethoscope gadget. Drag the dial round; the closer you get to a number, the louder the tick. When the light goes green, tap SET. Four numbers and the door opens."]],
        outro: [["rory", "A letter. \"The blueprints go to Venice. The Glassmaker will build the lens. Carnival night, Murano.\" Signed E."], ["rory", "And a photograph. A woman in dark glasses."], ["vi", "Oh no. That's Madame Eclipse. Head of UMBRA. If she's got the Helios plans, the whole world's in trouble."]],
        intel: { title: "The letter from \"E\"", text: "The blueprints go to Venice. The Glassmaker will build the lens on carnival night. The photo shows Madame Eclipse, head of UMBRA." } },
    ],
    leave: [["dave", "Oi! Big fella in two coats just squeezed into a taxi with a bag of chips. Yours?"], ["hale", "Kolya Zima. UMBRA's henchman. Where he goes, Eclipse follows. Venice, Agent Rory. Go."]],
  },
  {
    id: "venice", act: 1, city: "Venice", country: "Italy", flag: "it", lat: 45.44, lon: 12.33,
    chapter: "The Glassmaker", sky: "sunset", ambience: "water", contact: "lorenzo",
    arrive: [["lorenzo", "Benvenuto a Venezia! Lorenzo. Mind the step, the canal is wetter than it looks."], ["lorenzo", "The Glassmaker's workshop is by the furnace. Tonight is carnival, so everybody wears a mask. Even the pigeons."]],
    missions: [
      { id: "ven1", title: "Il Vetraio", game: "cipher", level: 2, station: "workshop", stationLabel: "The Glassmaker's workshop", icon: "furnace",
        params: { pages: ["ONE MIRROR LENS FORTY METRES FOR MADAME E - VETRI", "PAYMENT ARRIVES AT THE CARNIVAL - THE COURIER WEARS THE GOLDEN MASK - VETRI"] },
        intro: [["rory", "His order book. Every page is gibberish. It's in code."], ["vi", "A cipher wheel. Every letter has been slid along the alphabet. Drag the inner ring until the words come out. He signs everything VETRI."]],
        outro: [["rory", "\"One mirror lens, forty metres, for Madame E.\" Forty metres! That's bigger than a house."], ["rory", "Page two: \"Payment arrives at the carnival. The courier wears the golden mask.\""], ["lorenzo", "And the delivery note will be in his ring vault. Nobody has opened that vault since his grandmother."]],
        intel: { title: "The order book", text: "One mirror lens, forty metres, for Madame E. Payment arrives at the carnival. The courier wears the golden mask." } },
      { id: "ven2", title: "The Glass Vault", game: "vaultrings", level: 1, station: "vault", stationLabel: "The Glassmaker's ring vault", icon: "vault",
        intro: [["vi", "Three glass rings, each with a notch. Drag a ring to turn it and line every notch up at the top."], ["vi", "Careful: some rings drag their neighbour round with them. Start from the middle and work outwards."]],
        outro: [["rory", "The delivery note. \"Lens crated Thursday. Courier pays in gold at the carnival, then takes the manifest to the loft.\""], ["lorenzo", "Then to the piazza! Half of Venice is wearing gold tonight."]],
        intel: { title: "The delivery note", text: "The lens is crated on Thursday. The courier pays in gold at the carnival and keeps the manifest in a loft." } },
      { id: "ven3", title: "Carnival of Masks", game: "masks", level: 2, station: "piazza", stationLabel: "The carnival piazza", icon: "mask",
        intro: [["vi", "Twenty masked dancers and one of them is UMBRA's courier. I'll feed you clues on the watch."], ["vi", "Tap the one who matches every clue. Tap a tourist and you'll just get told off in Italian."]],
        outro: [["rory", "Got you! And the manifest? \"In the loft, behind the lasers,\" he says. Lasers?"], ["lorenzo", "UMBRA rented the loft over the bakery. It hums at night. I thought it was the ovens."]],
        intel: { title: "The courier", text: "The courier is caught. The shipping manifest is in UMBRA's loft over the bakery, behind a laser grid." } },
      { id: "ven4", title: "Lasers in the Loft", game: "laserhall", level: 1, station: "loft", stationLabel: "The loft over the bakery", icon: "laser",
        intro: [["vi", "Sweeping laser beams. Touch one and the alarm sends you back to the door. Drag to move, and wait for a gap."], ["vi", "The manifest is on the desk at the far end."]],
        outro: [["rory", "\"One lens, crated. Ship to Cairo, Egypt. Test on the Great Pyramid at noon, Thursday.\""], ["hale", "A test on the pyramids. She's going to switch off the sun over Cairo. Egypt. Now."]],
        intel: { title: "The manifest", text: "The lens ships to Cairo, Egypt, to be tested on the Great Pyramid at noon on Thursday." } },
    ],
    leave: [["lorenzo", "There! The big man in two coats, in the speedboat, with a paper cone of cicchetti!"], ["kolya", "Is not fair! I was eating!"], ["lorenzo", "I will sing you to the airport. It is a long song."]],
  },
  {
    id: "cairo", act: 1, city: "Cairo", country: "Egypt", flag: "eg", lat: 30.04, lon: 31.24,
    chapter: "Shadow Over Cairo", sky: "desert", ambience: "wind", contact: "nadia",
    arrive: [["nadia", "Agent Rory. Dr Nadia Farouk. Welcome to Cairo. Yesterday at noon the pyramids across the river went dark for one whole minute. The camels fainted."], ["nadia", "UMBRA left a radio mast on the roof of the bazaar. And they have been sniffing around my tomb in the old ridge. Nobody sniffs around my tomb."]],
    missions: [
      { id: "cai1", title: "The Listening Post", game: "radio", level: 2, station: "mast", stationLabel: "UMBRA's radio mast", icon: "mast",
        params: { messages: ["Channel check. The code word for the tomb is SCARAB. Say it to nobody.", "The test was perfect. Sixty seconds of night at noon. Kolya: fetch the Eye from the tomb before the diggers find it. Without it, the Engine cannot focus."] },
        intro: [["vi", "Their relay's still switched on. Drag the needle along the band. Less crackle means you're getting warm."], ["vi", "There are two UMBRA channels tonight, and a pop station in between. Find them both and hold each one."]],
        outro: [["rory", "That was HER. \"Fetch the Eye from the tomb.\" Whatever the Eye is, the Engine can't focus without it."], ["nadia", "The Eye of Ra. A crystal lens the old astronomers kept in the tomb of light. Sealed for three thousand years. The door is opened by stone and by sunlight, in that order."]],
        intel: { title: "Eclipse's transmission", text: "The test was perfect: sixty seconds of night at noon. Kolya must fetch the Eye from the tomb, or the Engine cannot focus." } },
      { id: "cai2", title: "The Sun Rods", game: "hanoi", level: 1, station: "rods", stationLabel: "The tomb's counterweights", icon: "rods",
        intro: [["nadia", "Three stone discs on the first pillar. Move them all to the third pillar, one at a time, and never put a big disc on a small one."], ["vi", "It's the oldest puzzle in the world. The old builders were showing off."]],
        outro: [["rory", "The discs are across and something's grinding inside the ridge."], ["nadia", "The light chamber. Now the sun does the rest."]],
        intel: { title: "The counterweights", text: "The stone discs are stacked on the third pillar. The tomb's inner door is unlocked and waits for sunlight." } },
      { id: "cai3", title: "The Tomb of Light", game: "mirror", level: 2, station: "tomb", stationLabel: "The tomb of light", icon: "tomb",
        intro: [["nadia", "A beam of sun comes through the door. Tap the bronze mirrors to turn them and steer it onto the sun disc."], ["vi", "Stone blocks stop the beam, and some mirrors are only there to confuse you. Two chambers."]],
        outro: [["rory", "The door's opening... and there it is. The Eye of Ra. It's warm."], ["kolya", "Hey! Little spy! That is MY crystal! ...Is not fair."], ["vi", "First time we've beaten them to it! Now they'll need a computer chip to focus that mirror instead. But where have they gone?"]],
        intel: { title: "The Eye of Ra", text: "Recovered before UMBRA. Without it they need a guidance chip to focus the mirror. Kolya fled." } },
      { id: "cai4", title: "Satellite Sweep", game: "satphoto", level: 1, station: "tent", stationLabel: "Nadia's tent", icon: "screen",
        intro: [["vi", "I've got a satellite picture of the airfield, but it came down in scrambled tiles. Slide them back into place."], ["vi", "Tap a tile next to the gap to slide it in."]],
        outro: [["rory", "A plane on the runway, tail number UMB-7. And the flight plan on the wing crate says Tokyo, Haneda."], ["vi", "Only one lab in the world makes a chip good enough: Kaito Labs, Tokyo. That's where they've gone. So that's where you go."]],
        intel: { title: "The satellite picture", text: "UMBRA's plane UMB-7 left Cairo for Tokyo. Only Kaito Labs makes a chip that can focus the mirror." } },
    ],
    leave: [["nadia", "He ran off through the bazaar, shouting about his lunch. Go well, Agent Rory. Bring me back a postcard."]],
  },
  {
    id: "tokyo", act: 1, city: "Tokyo", country: "Japan", flag: "jp", lat: 35.68, lon: 139.69,
    chapter: "Neon Ghost", sky: "night", ambience: "city_rain", contact: "yuki",
    arrive: [["yuki", "Rory-san. Yuki. Ramen chef. Also the best hacker in Japan, but the ramen pays better."], ["yuki", "Kaito Labs is the glass tower. Keypad door, laser corridor, server room, and a terminal with a password nobody knows. Eat first. Then hack."]],
    missions: [
      { id: "tok1", title: "Kaito Labs", game: "keypad", level: 2, station: "lab", stationLabel: "Kaito Labs, keypad door", icon: "keypad",
        intro: [["yuki", "I watched the guard type the code from across the street. I remember the pattern. Watch the keys light up, then press them in the same order."], ["vi", "Three codes, each one longer, and they get quicker."]],
        outro: [["rory", "We're in. But there's a corridor of red lines between us and the lift."], ["yuki", "Lasers. Kaito likes lasers."]],
        intel: { title: "Kaito Labs, ground floor", text: "The keypad door is open. A laser corridor guards the lift to floor 44." } },
      { id: "tok2", title: "The Corridor", game: "laserhall", level: 2, station: "corridor", stationLabel: "The laser corridor", icon: "laser",
        intro: [["vi", "Four beams this time, and they sweep faster. Drag to move. Wait for the gap, then go."]],
        outro: [["rory", "Floor forty-four... the chip cabinet's empty. Someone took it an hour ago."], ["yuki", "They left through the server room. Servers remember everything. Come."]],
        intel: { title: "Floor 44", text: "The guidance chip was stolen tonight. The thief left through the server room, and the servers remember everything." } },
      { id: "tok3", title: "Trace the Ghost", game: "circuit", level: 2, station: "servers", stationLabel: "The server room", icon: "server",
        intro: [["yuki", "The data lines are scrambled. Tap the tiles to turn them. Connect the port on the left to the port on the right."], ["vi", "Bigger boards than a hobby kit. Two of them."]],
        outro: [["yuki", "The log is here but it's locked behind the root password."], ["rory", "Then we crack the password."]],
        intel: { title: "The server log", text: "The shipping log exists but is locked behind Kaito's root password." } },
      { id: "tok4", title: "Root Password", game: "codebreaker", level: 2, station: "terminal", stationLabel: "The root terminal", icon: "screen",
        intro: [["vi", "Four symbols again, but six to choose from. The terminal tells you how many are right and in place, and how many are right but misplaced."]],
        outro: [["yuki", "\"Chip shipped. Paid by STERLING HOLDINGS, New York. Forty million dollars.\""], ["rory", "\"Contact: Marcus Sterling. Sterling Tower, penthouse.\""], ["hale", "Sterling. Wall Street's slipperiest banker. New York, Agent Rory. Detective Romano will meet you."]],
        intel: { title: "The root log", text: "The chip was paid for by Sterling Holdings, New York: forty million dollars. Contact Marcus Sterling, Sterling Tower penthouse." } },
    ],
    leave: [["yuki", "Look. The bullet train. Big man, two coats, box of takoyaki. He is waving at you."], ["kolya", "Bye bye, little spy!"]],
  },
  {
    id: "newyork", act: 1, city: "New York", country: "USA", flag: "us", lat: 40.71, lon: -74.0,
    chapter: "The Money Man", sky: "night", ambience: "city", contact: "sal",
    arrive: [["sal", "Kid. Sal Romano, NYPD. Hot dog? No? Suit yourself."], ["sal", "Sterling skipped town this morning. I've had a camera on his penthouse window for a week. This town's got more crooks than pigeons."]],
    missions: [
      { id: "nyc1", title: "Window Watch", game: "spotdiff", level: 2, station: "cart", stationLabel: "Sal's hot-dog cart", icon: "camera",
        intro: [["sal", "Two photos of the penthouse, kid. Monday and this morning. Something moved. Find everything that's different."]],
        outro: [["rory", "The bookcase has swung out. There's a vault door behind it. And the desk lamp's gone."], ["sal", "Pin-tumbler vault. Six pins. Your Aunt Vi's gonna love this."]],
        intel: { title: "The penthouse photos", text: "Sterling's vault is behind the bookcase in the penthouse. It has a six-pin lock." } },
      { id: "nyc2", title: "Sterling's Vault", game: "lock", level: 2, station: "tower", stationLabel: "Sterling Tower, penthouse", icon: "vault",
        intro: [["vi", "Six pins. The marker bounces up and down each one. Tap PICK when it's in the green. Miss and a pin drops. They get quicker."]],
        outro: [["rory", "It's open. A ledger. \"Paid: one mirror, Venice. One chip, Tokyo. One rocket, Brazil.\""], ["rory", "\"Ship rocket from Rio de Janeiro, Pier 9.\" A ROCKET? And... Sal, something in here is ticking."], ["sal", "Oh, that's not good. That's really not good."]],
        intel: { title: "Sterling's ledger", text: "Paid: one mirror (Venice), one chip (Tokyo), one rocket (Brazil). The rocket ships from Rio de Janeiro, Pier 9." } },
      { id: "nyc3", title: "Ticking", game: "wires", level: 2, station: "device", stationLabel: "The ticking device", icon: "bomb",
        intro: [["vi", "UMBRA rigged it to burn the ledger. Seventy seconds. Four devices this time."], ["vi", "The manual's on your watch. Read the rules in order and cut the first wire that fits."]],
        outro: [["rory", "It stopped. The ledger's last page is a bit singed. \"Rocket sails Friday. Pier 9, Rio. Crate marked ZIMA.\""], ["sal", "Nice work, kid. And there's something else in this office. It's been squeaking at my radio all week."]],
        intel: { title: "The last page", text: "The rocket sails on Friday from Pier 9, Rio de Janeiro, in a crate marked ZIMA." } },
      { id: "nyc4", title: "The Bug", game: "sonar", level: 1, station: "office", stationLabel: "Sterling's office", icon: "sonar",
        intro: [["vi", "An UMBRA transmitter is hidden somewhere in that office. My sniffer pings a square and tells you how many steps away the bug is."], ["vi", "Ten pings. Use the numbers to narrow it down before you tap FOUND."]],
        outro: [["rory", "Got it. Inside the globe. It's tuned to a harbour channel in Rio: Pier 9's crane."], ["hale", "Then Zima is not a person, it is a place, and it is where that rocket is going. Rio, Agent Rory. Friday is the day after tomorrow."]],
        intel: { title: "The transmitter", text: "UMBRA's bug was tuned to the crane at Pier 9, Rio. ZIMA is a place, not a person." } },
    ],
    leave: [["sal", "We grabbed Sterling at the airport with a suitcase of cash. He cried. Cab to the airport's on me."]],
  },
  {
    id: "rio", act: 1, city: "Rio de Janeiro", country: "Brazil", flag: "br", lat: -22.9, lon: -43.2,
    chapter: "The Rocket at Pier 9", sky: "sunset", ambience: "waves", contact: "tiago",
    arrive: [["tiago", "Rory! Tiago. Surfer, harbour pilot, part-time spy. Relax. The tide does the work."], ["tiago", "Pier 9 is across the bay. Big crate, big crane, big men. The harbour office keeps the crew photos, and the best view is from the cable car."]],
    missions: [
      { id: "rio1", title: "Crew Manifest", game: "passport", level: 1, station: "harbouroffice", stationLabel: "The harbour office", icon: "door",
        intro: [["vi", "The crew photos are face down on the desk. Flip two at a time and find the matching pairs. Every pair is a crew member."], ["vi", "Remember where you saw each face."]],
        outro: [["rory", "A pair I know. \"K. Zima, cook.\" Kolya's on the crew of the Severnaya."], ["tiago", "Then the Severnaya is our ship. Let's get a look at her."]],
        intel: { title: "The crew list", text: "Kolya Zima is aboard the freighter Severnaya as the ship's cook." } },
      { id: "rio2", title: "Sugarloaf Lens", game: "photo", level: 2, station: "cablecar", stationLabel: "The cable-car platform", icon: "camera",
        intro: [["vi", "My camera. Drag to aim, slide the zoom, hold the target in the ring until it focuses, then SNAP. Four photographs this time."]],
        outro: [["rory", "The crate says ZIMA STATION. The ship is the Severnaya. Kolya's on the quay with a coconut, and the crane's cab has an UMBRA logo."], ["vi", "Zima means winter. Somewhere very, very cold. We need to know exactly where. Tonight, the yard."]],
        intel: { title: "The photographs", text: "The crate is stencilled ZIMA STATION. The freighter is the Severnaya. Kolya is in Rio. Zima means winter." } },
      { id: "rio3", title: "Pier 9", game: "stealth", level: 2, station: "docks", stationLabel: "Pier 9, the container yard", icon: "crate",
        intro: [["tiago", "Four guards with torches, and a searchlight on the crane. Stay out of the light and slip between the containers."], ["vi", "Drag to move. Reach the crate and the tracker plants itself. Spotted, and it's back to the fence."]],
        outro: [["vi", "Tracker's pinging! Sixty-four degrees north, one hundred degrees east. Siberia. Zima Station."], ["hale", "And the launch is in three days. Get me a picture of that place before you fly."]],
        intel: { title: "The tracker", text: "The rocket crate pings from 64°N 100°E: Zima Station, Siberia. The launch is in three days." } },
      { id: "rio4", title: "Winter Satellite", game: "satphoto", level: 2, station: "boat", stationLabel: "Tiago's boat", icon: "screen",
        intro: [["vi", "The satellite's over Siberia now. Sixteen tiles this time. Slide them home and we'll see what Zima Station looks like."]],
        outro: [["rory", "A fortress in the snow, a rocket on a pad, a boiler-room door on the west side and a lit window on the east."], ["hale", "Pack a coat, Agent Rory. Two coats."]],
        intel: { title: "Zima Station from orbit", text: "A fortress with a rocket pad behind it. Boiler room on the west, control room on the east. Launch in three days." } },
    ],
    leave: [["tiago", "There goes the Severnaya, lights out, heading north. My boat will take you to the airport. Hold on to your hat."]],
  },
  {
    id: "siberia", act: 1, city: "Zima Station", country: "Russia", flag: "ru", lat: 64, lon: 100,
    chapter: "Zima Station", sky: "aurora", ambience: "blizzard", contact: "natasha",
    arrive: [["natasha", "Agent Rory. Natasha Volkova. Radio officer of UMBRA, and M.I.S.T.'s only friend inside these walls. Quietly."], ["natasha", "The rocket is on the pad behind the station. Ten minutes to launch at midnight. Office, reactor, vault door, control room. In that order, and the cameras blink every ninety seconds."]],
    missions: [
      { id: "sib1", title: "The Ice Fortress", game: "shredder", level: 2, station: "office", stationLabel: "The station office", icon: "door",
        params: { doc: "zima" },
        intro: [["natasha", "The shredder bin. Ten strips. Kolya is thorough, but not clever."], ["vi", "Drag the strips back into order, then tape it. The abort code should be on there somewhere."]],
        outro: [["rory", "\"ECLIPSE ENGINE. Launch at midnight. ABORT CODE...\" four symbols. I've got them, Vi."], ["natasha", "The reactor is next door. If we stall it, the countdown pauses. Briefly."]],
        intel: { title: "The launch schedule", text: "Eclipse Engine launches at midnight, T-minus ten minutes. The abort code is four symbols, written in the Dossier." } },
      { id: "sib2", title: "The Reactor", game: "hanoi", level: 2, station: "reactor", stationLabel: "The reactor hall", icon: "rods",
        intro: [["natasha", "Four fuel rods. Move the stack to the cooling rack on the right, one rod at a time, never a big one on a small one."], ["vi", "Same puzzle as the tomb, with one more rod. That's twice the moves."]],
        outro: [["rory", "The rods are in the rack. The clock's paused at T-minus ninety."], ["natasha", "For ninety seconds, once the vault door opens. Hurry."]],
        intel: { title: "The reactor", text: "The reactor is stalled. The countdown will pause at T-minus ninety seconds once the control room opens." } },
      { id: "sib3", title: "The Vault Door", game: "vaultrings", level: 2, station: "vaultdoor", stationLabel: "The control room vault door", icon: "vault",
        intro: [["vi", "Four steel rings, and every one drags its outer neighbour. Innermost first, then work outwards."]],
        outro: [["rory", "It's open. That's the control room. And that's HER on the big screen."]],
        intel: { title: "The vault door", text: "The control room is open. Madame Eclipse is watching on the big screen." } },
      { id: "sib4", title: "Countdown", game: "override", level: 2, station: "control", stationLabel: "The control room", icon: "screen",
        intro: [["eclipse", "Agent Rory. You have come a very long way to watch the lights go out."], ["eclipse", "Eighty seconds, little spy. Then every city on Earth learns what midnight at noon feels like."], ["vi", "Ignore her. Three things, fast. Type the abort code. Turn the dial to the number on the screen. Then cut the wires by the rules."]],
        outro: [["rory", "Engines... off. Three seconds to spare. The Engine's just sitting on the pad."], ["kolya", "Is not fair. I was eating a pirozhok."], ["eclipse", "We will meet again, little spy. Somewhere the sun still shines."], ["natasha", "She took the snowmobile. Kolya took the pirozhok. You, Agent Rory, take the plane home."]],
        intel: { title: "Operation Eclipse: stopped", text: "The Eclipse Engine never left the ground. Kolya arrested. Madame Eclipse escaped on a snowmobile." } },
    ],
    leave: [],
  },
  // ================================================================ ACT TWO
  {
    id: "paris", act: 2, city: "Paris", country: "France", flag: "fr", lat: 48.86, lon: 2.35,
    chapter: "The Lantern of Paris", sky: "dusk", ambience: "city", contact: "colette",
    arrive: [["colette", "Bonsoir, Agent Rory. Colette. I run the café, and the café hears everything in Paris."], ["colette", "A flower man called Jean-Luc delivered a very heavy crate to the Louvre last night. He is inside, eating my croissants and sweating. Start with him."]],
    missions: [
      { id: "par1", title: "The Flower Man", game: "lie", level: 3, station: "cafe", stationLabel: "Colette's café", icon: "dome",
        params: { statements: JEANLUC, suspect: "jeanluc" },
        intro: [["jeanluc", "Flowers! I deliver flowers. Tulips, roses, nothing else, I swear it."], ["vi", "He's on the polygraph. His fibs are sneakier than Nigel's, so watch for smaller spikes."]],
        outro: [["jeanluc", "D'accord, d'accord! The crate is in the roof of the glass pyramid. A balloon, a mirror, a very nasty lock. And the lady in dark glasses paid me in cash."], ["colette", "The Louvre closes at six. After that, it belongs to the lasers."]],
        intel: { title: "Jean-Luc's confession", text: "The Lantern of Paris is inside the roof of the Louvre's glass pyramid, behind the museum's lasers." } },
      { id: "par2", title: "Louvre After Dark", game: "laserhall", level: 3, station: "louvre", stationLabel: "The glass pyramid", icon: "laser",
        intro: [["vi", "Five beams in that gallery, and two of them go round and round. Take your time in the gaps."]],
        outro: [["rory", "I'm under the pyramid. The lantern's up in the roof, and its panel wants a five-symbol code."]],
        intel: { title: "The lantern's panel", text: "The Lantern of Paris hangs in the pyramid roof. Its disarm panel takes a five-symbol code." } },
      { id: "par3", title: "The Panel", game: "codebreaker", level: 3, station: "panel", stationLabel: "The lantern's disarm panel", icon: "keypad",
        intro: [["vi", "Five symbols, six to pick from, nine guesses. Same rules as the Observatory door: use every answer it gives you."]],
        outro: [["rory", "The lantern's dark! And its memory chip names the next one: Nairobi, Kenya."], ["colette", "Before you go: Madame Eclipse is meeting someone at the Eiffel Tower tonight. Take the camera."]],
        intel: { title: "Lantern 1 of 7", text: "The Lantern of Paris is disarmed. Its memory names the next city: Nairobi, Kenya." } },
      { id: "par4", title: "The Iron Lady", game: "photo", level: 3, station: "tower", stationLabel: "The Eiffel Tower deck", icon: "camera", params: { where: "they are down on the far bank of the river, by the parked van" },
        intro: [["vi", "Four targets across the river: the lady herself, the person she's meeting, the van, and the crate. Zoom right in and hold steady."]],
        outro: [["rory", "The van says ALPINE DAIRY. The man has a grey moustache and never turns round."], ["hale", "A dairy van at the Eiffel Tower. The Chairman keeps cows, apparently. Nairobi, Agent Rory."]],
        intel: { title: "The meeting", text: "Madame Eclipse met a man with a grey moustache. His van is marked ALPINE DAIRY. The next lantern is in Nairobi." } },
    ],
    leave: [["eclipse", "Bravo, little spy. One lantern of seven. The Chairman is not worried. He is never worried."]],
  },
  {
    id: "kenya", act: 2, city: "Nairobi", country: "Kenya", flag: "ke", lat: -1.29, lon: 36.82,
    chapter: "The Lantern of the Savanna", sky: "desert", ambience: "wind", contact: "amani",
    arrive: [["amani", "Jambo, Agent Rory. Amani, park ranger. The elephants have been nervous all week, and elephants are never wrong."], ["amani", "A truck with no lights drove into the park three nights ago. My camera trap saw it. Come and look."]],
    missions: [
      { id: "ken1", title: "Camera Trap", game: "spotdiff", level: 3, station: "cameratrap", stationLabel: "The camera trap", icon: "camera",
        intro: [["amani", "Two pictures from the same camera, one hour apart. Find everything that changed."]],
        outro: [["rory", "Truck tracks, a dropped crate lid, and an elephant that's moved... towards the old watering hole."], ["amani", "Elephants follow the tether cable. It hums."]],
        intel: { title: "The camera trap", text: "UMBRA's truck went towards the old watering hole. The elephants are following a humming cable." } },
      { id: "ken2", title: "The Watering Hole", game: "sonar", level: 3, station: "watering", stationLabel: "The watering hole", icon: "sonar",
        intro: [["vi", "The lantern's tether is buried somewhere on this grid. Nine pings. Each one tells you how many steps away it is."]],
        outro: [["rory", "Found the cable. It runs to a camp under the acacias, and the camp has guards."]],
        intel: { title: "The tether", text: "The tether cable runs to UMBRA's camp under the acacia trees." } },
      { id: "ken3", title: "The Camp", game: "stealth", level: 3, station: "camp", stationLabel: "UMBRA's camp", icon: "crate",
        intro: [["amani", "Five guards, one searchlight, and a very sleepy lion on the far side. Do not wake the lion."], ["vi", "Reach the crate and read what's on it."]],
        outro: [["rory", "The crate says: DISARM FREQUENCY ON RANGER TOWER CHANNEL. Sneaky."], ["amani", "My old tower. The radio still works, if you kick it."]],
        intel: { title: "The crate", text: "The lantern's disarm frequency is broadcast on the old ranger tower's channel." } },
      { id: "ken4", title: "The Ranger Tower", game: "radio", level: 3, station: "rangertower", stationLabel: "The old ranger tower", icon: "mast",
        params: { messages: ["Lantern two. Disarm sequence armed. Say the frequency twice.", "Lantern two, disarm on my mark. Mark. The next lantern waits in Agra, at the old sundial observatory."] },
        intro: [["vi", "Two channels to find, and the lock window is narrow. Hold the needle dead still."]],
        outro: [["rory", "Lantern two's dark. And she said Agra. India."], ["hale", "The Taj Mahal, a sundial and a lantern. Priya will meet you. Bring a hat."]],
        intel: { title: "Lantern 2 of 7", text: "The Lantern of the Savanna is disarmed. The next one is in Agra, India, at the old sundial observatory." } },
    ],
    leave: [["amani", "The elephants are calm again. Go well. And Rory: you did not wake the lion. Nobody has ever not woken the lion."]],
  },
  {
    id: "india", act: 2, city: "Agra", country: "India", flag: "in", lat: 27.18, lon: 78.02,
    chapter: "The Lantern of the Taj", sky: "sunset", ambience: "city", contact: "priya",
    arrive: [["priya", "Agent Rory! Priya. Tuk-tuk driver, inventor, and the only person in Agra who has read your file. Get in."], ["priya", "It is Holi today. Everybody is covered in colour, so UMBRA's courier will be too. He is somewhere in that crowd."]],
    missions: [
      { id: "ind1", title: "Festival of Colour", game: "masks", level: 3, station: "festival", stationLabel: "The Holi crowd", icon: "mask",
        params: { theme: "holi" },
        intro: [["vi", "Twenty dancers and four clues this time. Tap the one who matches all of them."]],
        outro: [["rory", "Got him. A folded message in his pocket, and it's in code again."], ["priya", "Everyone in this town writes in code. It is a very old town."]],
        intel: { title: "The courier's message", text: "The courier carried a coded message. Priya's tuk-tuk has a cipher wheel in the glovebox." } },
      { id: "ind2", title: "The Coded Message", game: "cipher", level: 3, station: "tuktuk", stationLabel: "Priya's tuk-tuk", icon: "door",
        params: { pages: ["THE LANTERN OF THE TAJ SLEEPS IN THE SUNDIAL OBSERVATORY - E", "ITS LOCK OPENS ONLY WHEN THE BEAM TOUCHES THE STAR DISC - E", "THEN THE KEYPAD - THREE CODES - DO NOT LOSE THEM AGAIN KOLYA - E"] },
        intro: [["vi", "Three pages, each with its own shift. She signs them E."]],
        outro: [["rory", "The lantern's in the sundial observatory, the lock opens with a beam of light, and then there's a keypad."], ["priya", "The observatory is stone and mirrors. The old astronomers would have liked you."]],
        intel: { title: "The coded pages", text: "The Lantern of the Taj is in the sundial observatory. Its lock opens with a beam on the star disc, then a keypad." } },
      { id: "ind3", title: "The Sundial", game: "mirror", level: 3, station: "sundial", stationLabel: "The sundial observatory", icon: "tomb",
        intro: [["vi", "Three chambers this time, bigger each time, and plenty of mirrors that are only there to fool you."]],
        outro: [["rory", "The star disc is lit and the lantern's keypad has popped out of the stone."]],
        intel: { title: "The star disc", text: "The star disc is lit. The lantern's keypad is exposed." } },
      { id: "ind4", title: "The Keypad", game: "keypad", level: 3, station: "lanternpad", stationLabel: "The lantern's keypad", icon: "keypad",
        intro: [["priya", "I filmed Kolya typing three codes into it last week. He types with one finger. Watch, then copy."], ["vi", "Long ones. Say the numbers out loud."]],
        outro: [["rory", "Lantern three's dark. The memory chip says: Beijing, the Great Wall."], ["hale", "Mei runs a tea house by the wall. She also runs half of Beijing. Go."]],
        intel: { title: "Lantern 3 of 7", text: "The Lantern of the Taj is disarmed. The next one is on the Great Wall near Beijing." } },
    ],
    leave: [["priya", "Kolya's tuk-tuk broke down at the airport. He is pushing it. With a samosa in his mouth."]],
  },
  {
    id: "china", act: 2, city: "Beijing", country: "China", flag: "cn", lat: 39.9, lon: 116.4,
    chapter: "The Lantern of the Wall", sky: "dusk", ambience: "wind", contact: "mei",
    arrive: [["mei", "Agent Rory. Mei. Tea, dumplings, and the best view of the Great Wall in China."], ["mei", "UMBRA hired one of the watchtowers. They left a map in my tea-house safe, thinking I would not look. I looked. But I could not open it."]],
    missions: [
      { id: "chn1", title: "The Tea-House Safe", game: "safe", level: 3, station: "teahouse", stationLabel: "Mei's tea house", icon: "door",
        intro: [["vi", "Four numbers, and the tick only starts when you're close. Slowly."]],
        outro: [["rory", "A map of the wall with a tower circled... but the circle's smudged. Three towers it could be."], ["mei", "Then look from above. My dish on the roof talks to the satellite. Sometimes."]],
        intel: { title: "The wall map", text: "The lantern is in one of three watchtowers on the Great Wall." } },
      { id: "chn2", title: "The Dish", game: "satphoto", level: 3, station: "satdish", stationLabel: "Mei's satellite dish", icon: "screen",
        intro: [["vi", "Sixteen tiles, and a fiddly picture. Slide them home."]],
        outro: [["rory", "The third tower has a balloon crate on its roof. That's the one."]],
        intel: { title: "The satellite picture", text: "The lantern is on the third watchtower. Its lift is wired through the tower's old fuse board." } },
      { id: "chn3", title: "Watchtower Wiring", game: "circuit", level: 3, station: "watchtower", stationLabel: "The third watchtower", icon: "server",
        intro: [["vi", "Two big boards. Connect left to right and the lantern's lift comes down."]],
        outro: [["rory", "The lift's down. The lantern's on five stone rods, like the tomb in Cairo."], ["mei", "The old builders again. They travelled."]],
        intel: { title: "The lift", text: "The lantern's lift is down. Its lock is a five-disc rod puzzle." } },
      { id: "chn4", title: "The Lantern's Lock", game: "hanoi", level: 3, station: "lanternlift", stationLabel: "The lantern's rod lock", icon: "rods",
        intro: [["vi", "Five discs. Thirty-one moves if you don't waste any. Small disc first, and it always goes the same way round."]],
        outro: [["rory", "Lantern four's dark. Next: Sydney."], ["hale", "Matilda will meet you at the beach. Do not let her teach you to surf. There isn't time."]],
        intel: { title: "Lantern 4 of 7", text: "The Lantern of the Wall is disarmed. The next one is in Sydney, Australia." } },
    ],
    leave: [["mei", "Kolya tried to leave without paying for his dumplings. He is washing up. For a week."]],
  },
  {
    id: "australia", act: 2, city: "Sydney", country: "Australia", flag: "au", lat: -33.87, lon: 151.21,
    chapter: "The Lantern of the Harbour", sky: "sunset", ambience: "waves", contact: "matilda",
    arrive: [["matilda", "G'day, Agent Rory. Matilda, surf lifesaver. An UMBRA diver's been going under the harbour bridge every night. Reckon your lantern's under there."], ["matilda", "He takes the ferry across. Ferry keeps passenger photos. Let's find his."]],
    missions: [
      { id: "aus1", title: "Ferry Passengers", game: "passport", level: 2, station: "ferry", stationLabel: "The ferry wharf", icon: "door",
        intro: [["vi", "More faces this time. Flip two at a time and remember where they were."]],
        outro: [["rory", "The diver: a pair of photos, wetsuit, UMBRA badge on the tank. He surfaces at the bridge's south pylon."]],
        intel: { title: "The diver", text: "UMBRA's diver surfaces at the south pylon of the harbour bridge each night." } },
      { id: "aus2", title: "The Lookout", game: "photo", level: 4, station: "lookout", stationLabel: "The harbour lookout", icon: "camera", params: { where: "they are spread right round the harbour: the water, the pylon, the barge, the opera roof and the quay" },
        intro: [["vi", "Five targets round the harbour, and a swaying lens. Patience."]],
        outro: [["rory", "The diver, the hatch under the pylon, the balloon crate on the barge, the Opera House roof camera, and Kolya. With a meat pie."], ["matilda", "The hatch has a lock. Seven pins. My mate says nobody's picked it."]],
        intel: { title: "The harbour photos", text: "The lantern hatch is under the south pylon. It has a seven-pin lock." } },
      { id: "aus3", title: "The Hatch", game: "lock", level: 3, station: "hatch", stationLabel: "The pylon hatch", icon: "vault",
        intro: [["vi", "Seven pins, quick ones with small green bands. One at a time."]],
        outro: [["rory", "It's open. The lantern's wired to a timer, and the timer is counting."]],
        intel: { title: "The hatch", text: "The hatch is open. The Lantern of the Harbour is on a wired timer." } },
      { id: "aus4", title: "The Timer", game: "wires", level: 3, station: "lantern", stationLabel: "The lantern's timer", icon: "bomb",
        intro: [["vi", "Five devices, and a new rule on the manual. Read them all in order every time."]],
        outro: [["rory", "Lantern five's dark. Two to go. The chip says: Chichen Itza, Mexico."], ["hale", "Diego is an archaeologist who sings. You'll hear him before you see him."]],
        intel: { title: "Lantern 5 of 7", text: "The Lantern of the Harbour is disarmed. The next one is at the pyramid of Chichen Itza, Mexico." } },
    ],
    leave: [["matilda", "Kolya tried to surf. Kolya cannot surf. He's fine. The board isn't."]],
  },
  {
    id: "mexico", act: 2, city: "Chichen Itza", country: "Mexico", flag: "mx", lat: 20.68, lon: -88.57,
    chapter: "The Lantern of the Pyramid", sky: "dusk", ambience: "jungle", contact: "diego",
    arrive: [["diego", "Agent Rory! Diego. Archaeologist by day, mariachi by night, and today is a long day."], ["diego", "UMBRA has been inside the pyramid. They shredded a map at the market. Kolya shreds everything. It is his one skill."]],
    missions: [
      { id: "mex1", title: "The Shredded Map", game: "shredder", level: 3, station: "market", stationLabel: "The market stall", icon: "door",
        params: { doc: "pyramid" },
        intro: [["vi", "Twelve strips. Match the edges of the drawing and the writing."]],
        outro: [["rory", "The lantern's in the jaguar chamber, halfway up the serpent stairs, and there are guards on every step."]],
        intel: { title: "The pyramid map", text: "The lantern is in the jaguar chamber, reached by the serpent stairs, which UMBRA guards at night." } },
      { id: "mex2", title: "The Serpent Stairs", game: "stealth", level: 4, station: "stairs", stationLabel: "The serpent stairs", icon: "crate",
        intro: [["diego", "Six guards, two searchlights, and they walk fast. Wait, watch, then go."]],
        outro: [["rory", "I'm in the chamber. A ring lock on the jaguar's door. Five rings."]],
        intel: { title: "The jaguar chamber", text: "The jaguar door has a five-ring lock." } },
      { id: "mex3", title: "The Jaguar Vault", game: "vaultrings", level: 3, station: "jaguar", stationLabel: "The jaguar door", icon: "vault",
        intro: [["vi", "Five rings, each dragging the one outside it. Innermost first."]],
        outro: [["rory", "The jaguar's open. The lantern's panel is the biggest yet: five symbols from seven."]],
        intel: { title: "The jaguar door", text: "The jaguar door is open. The lantern's panel takes five symbols from seven." } },
      { id: "mex4", title: "The Old Code", game: "codebreaker", level: 4, station: "chamber", stationLabel: "The lantern's panel", icon: "keypad",
        intro: [["vi", "Five from seven, nine guesses. Think before every guess."]],
        outro: [["rory", "Lantern six's dark. And the chip's last line: \"The seventh lantern stays with me. The mountain. O.\""], ["hale", "O. Otto. The Chairman. The Alps, Agent Rory. Klaus runs the cable car. This is the last one."]],
        intel: { title: "Lantern 6 of 7", text: "The Lantern of the Pyramid is disarmed. The seventh is with the Chairman in his mountain lair in the Alps." } },
    ],
    leave: [["diego", "I wrote you a song. It has eleven verses. Kolya is in the second one, stuck in a cactus."]],
  },
  {
    id: "alps", act: 2, city: "The Alps", country: "Switzerland", flag: "ch", lat: 46.5, lon: 8.0,
    chapter: "The Chairman", sky: "aurora", ambience: "blizzard", contact: "klaus",
    arrive: [["klaus", "Grüezi, Agent Rory. Klaus. My cable car goes to the top, where the Chairman's dairy is. It is not a dairy."], ["klaus", "The entrance hall is full of lasers, the Chairman likes to talk on the intercom, and the master switch is somewhere in a hundred rooms. Natasha is already inside."]],
    missions: [
      { id: "alp1", title: "The Entrance Hall", game: "laserhall", level: 4, station: "cablecar", stationLabel: "The cable-car station", icon: "laser",
        intro: [["vi", "Six beams. The fastest yet. There is always a gap; find the rhythm."]],
        outro: [["chairman", "Agent Rory. Welcome to my mountain. Do stop and talk. I insist."]],
        intel: { title: "The entrance hall", text: "Inside the lair. The Chairman is on the intercom and wants to talk." } },
      { id: "alp2", title: "The Chairman's Lie", game: "lie", level: 4, station: "intercom", stationLabel: "The intercom", icon: "dome",
        params: { statements: CHAIRMAN, suspect: "chairman" },
        intro: [["chairman", "You may ask me anything. I shall answer. Whether I answer truthfully is your problem."], ["vi", "He's on the intercom, and I've patched the polygraph into the line. His fibs are tiny. Look very hard."]],
        outro: [["rory", "So the seventh lantern IS in the mountain, the switch DOES turn off, and Eclipse is still here."], ["natasha", "She is on the peak, waiting for a helicopter. Find the switch room first. There are a hundred rooms."]],
        intel: { title: "The Chairman's lies", text: "The seventh lantern is in the mountain, the master switch can be turned off, and Madame Eclipse is still on the peak." } },
      { id: "alp3", title: "A Hundred Rooms", game: "sonar", level: 4, station: "lair", stationLabel: "The lair's corridors", icon: "sonar",
        intro: [["vi", "The switch room hums. Eight pings on a big grid. Make every one count."]],
        outro: [["rory", "Found it. The switch room. Seventy seconds on the clock and the Chairman's on the screen."]],
        intel: { title: "The switch room", text: "The master switch room is found. The Chairman has started the seventh lantern's countdown." } },
      { id: "alp4", title: "Midnight", game: "override", level: 4, station: "switch", stationLabel: "The master switch", icon: "screen",
        intro: [["chairman", "Seventy seconds, Agent Rory. Then seven cities go dark and the world pays me for the sunrise."], ["vi", "The abort code is five symbols this time. It's on the shredded map in your Dossier. Code, dial, wires. Go."]],
        outro: [["rory", "Switch... OFF. All seven lanterns dark."], ["chairman", "Impossible. Nobody has ever... Kolya, do something!"], ["kolya", "Is not my job any more. I work at chip shop now."], ["natasha", "Madame Eclipse slid off the peak on a tea tray. Straight into Dave's cab. He'd driven up the mountain. He said it was on the meter."]],
        intel: { title: "Operation Midnight: stopped", text: "All seven Shadow Lanterns are dark. The Chairman is arrested. Madame Eclipse landed in Dave's cab." } },
    ],
    leave: [],
  },
];

export const ACTS = [
  { n: 1, title: "Operation Eclipse", countries: ["london", "venice", "cairo", "tokyo", "newyork", "rio", "siberia"],
    briefing: [
      ["hale", "Agent Rory. Sit down. Last night the Royal Observatory in Greenwich was robbed."],
      ["hale", "They took the plans for the Helios Lens: a forty-metre mirror in orbit, built to beam a little sunshine onto cloudy cities."],
      ["vi", "Only if you point it the other way, it can throw a whole city into darkness at noon."],
      ["hale", "The night guard says he saw nothing. He is lying. Prove it, find the thief, and follow the plans wherever they go."],
      ["vi", "Your Spy Watch will show the objective. I'll be in your ear the whole way. Dave's outside with the cab."],
      ["hale", "The lights of the world are in your hands, Agent Rory. Don't drop them."],
    ],
    ending: [
      ["hale", "Agent Rory. For the first time in eleven years I am going to smile. There. Did you see it?"],
      ["hale", "The Eclipse Engine is in pieces, Sterling is in a cell, and Kolya has asked for seconds."],
      ["vi", "And Madame Eclipse is out there somewhere in the snow, plotting. Which means we'll need you again."],
      ["hale", "The world stays bright because of you. This medal is yours. Now go and sleep. That is an order."],
    ] },
  { n: 2, title: "Operation Midnight", countries: ["paris", "kenya", "india", "china", "australia", "mexico", "alps"],
    briefing: [
      ["hale", "Three weeks, Agent Rory. That is how long the world was safe."],
      ["hale", "Madame Eclipse has surfaced in Paris, and she is taking orders. UMBRA has a Chairman. Nobody has ever seen his face."],
      ["vi", "We intercepted one message: \"Seven lanterns. One midnight.\" Seven little mirrors on balloons, hidden over seven cities."],
      ["hale", "At the next new moon they all light at once. Seven capitals go dark, and the ransom is the sunrise."],
      ["vi", "Each lantern has a different lock, a different city and a different UMBRA cell guarding it. Seven countries. Four jobs in each."],
      ["hale", "Find them. Put them out. And find the Chairman. Kolya, by the way, escaped in a bread van. Of course he did."],
    ],
    ending: [
      ["hale", "Agent Rory. Seven lanterns, seven countries, one Chairman, and a Madame Eclipse in the back of a black cab."],
      ["vi", "The Chairman's mountain is now a very expensive dairy. Real cows this time."],
      ["kolya", "Chip shop gives me free chips. Is fair. Is finally fair."],
      ["hale", "Two medals, Agent Rory. Nobody in the history of M.I.S.T. has two. Try not to lose them."],
      ["rory", "Thank you, Commander. Same time next week?"],
    ] },
];
export const BRIEFING = ACTS[0].briefing;
export const ENDING = ACTS[1].ending;

export const CREDITS = [
  "AGENT RORY: OPERATION ECLIPSE",
  "",
  "Starring Rory as Agent R",
  "with Aunt Vi, Commander Hale, Dave, Lorenzo, Dr Farouk,",
  "Yuki, Detective Sal, Tiago, Natasha and Nigel Pratt",
  "and in Act Two: Colette, Amani, Priya, Mei, Matilda, Diego and Klaus",
  "",
  "Madame Eclipse, Kolya Zima and the Chairman as themselves",
  "",
  "London  ·  Venice  ·  Cairo  ·  Tokyo  ·  New York  ·  Rio  ·  Zima Station",
  "Paris  ·  Nairobi  ·  Agra  ·  Beijing  ·  Sydney  ·  Chichen Itza  ·  The Alps",
  "",
  "Every voice is the iPad's own",
  "Textures from the Godot TPS demo (CC-BY 3.0) and three.js examples (MIT)",
  "Built with three.js (MIT)",
  "",
  "Sophia, Rory and Dylan Games, Inc",
];
export const ALL_MISSIONS = COUNTRIES.flatMap(c => c.missions);
export function missionIndex(id) { return ALL_MISSIONS.findIndex(m => m.id === id); }
export function countryOf(mission) { return COUNTRIES.find(c => c.missions.includes(mission)); }
