// Agent Rory: Operation Meltdown — the story as data, written by the story generator.
// Dialogue lines are [speaker, text]; speakers are keys of CHARS in story.js.
// Sophia, Rory and Dylan Games, Inc.
export const OP = {
  id: "meltdown", n: 1, title: "MELTDOWN", name: "Operation Meltdown", saveKey: "save",
  coldOpenLine: "SOMEWHERE ON THE ICE, RIGHT NOW", villain: "Baron Kaldera", bugName: "Kaldera", bugLine: "One of the Baron's listening bugs. Off it goes.",
  tagline: "Eighteen places. Ninety missions. One very hot plan.", blurb: "Baron Kaldera is melting Antarctica from underneath.",
  finished: "Antarctica is still frozen, the penguins are safe, and Baron Kaldera is in a very cold cell. Watch the credits, or pick another operation.",
  view: null, colors: ["#ffd166","#ff7a1a","#c0200a"],
  countries: [
    // ============================================================ ACT ONE
    {
      id: "greenland", act: 1, city: "Ilulissat", country: "Greenland", flag: "gl", lat: 69.22, lon: -51.1,
      chapter: "Thin Ice", sky: "polar_day", ambience: "wind", contact: "nuka",
      chat: ["The ice has been groaning at night. My dogs won't sleep.","Floes don't drift like that in winter. Something is warming the water.","That rig wasn't there last month. Nobody built it. It just appeared.","The big man drove off on a snowcat. He was humming. To a penguin.","Go! Before the whole fjord cracks!"],
      arrive: [["pip","Agent Rory, can you hear me? It's Pip. Welcome to Greenland, the coldest job you've ever had."],["pip","Something is melting the glaciers here from underneath. In the middle of winter! That's impossible."],["nuka","You're the spy? I'm Nuka. My dogs found the problem. Follow me, and mind the thin ice."]],
      missions: [
        { id: "grn1", title: "Across the Icefjord", game: "floehop", level: 1, station: "floes", stationLabel: "The drifting floes", icon: "door",
          intro: [["nuka","The rig is out past the floes. The ice keeps breaking into pieces and drifting."],["pip","Hop from floe to floe. Tap or swipe to jump, and ride them, but don't ride off the edge!"]],
          outro: [["rory","Made it across. And the water under the floes is warm!"]],
          intel: {"title":"Warm Water","text":"The sea under the ice is as warm as a bath. Something down there is heating it."} },
        { id: "grn2", title: "The Research Hut", game: "iceslide", level: 1, station: "hut", stationLabel: "The frozen research hut", icon: "tomb",
          intro: [["pip","This research hut froze solid overnight. The floor is pure ice."],["pip","You'll slide until something stops you. Use the rocks to steer and slide out through the gap."]],
          outro: [["rory","Found the scientist's notebook. The last page just says: THE HEAT IS COMING FROM BELOW."]],
          intel: {"title":"The Scientist's Notes","text":"Before she left, the scientist wrote that the heat is coming from deep below the ice."} },
        { id: "grn3", title: "Eyes Inside", game: "drone", level: 1, station: "rig", stationLabel: "The drilling rig", icon: "screen",
          intro: [["pip","I've built a drone the size of a sandwich. Let's fly it into that rig through the air vents."],["pip","Hold the screen to fly up, let go to drop. Squeeze through the gaps!"]],
          outro: [["pip","Look at the camera. A giant drill, glowing orange, boring straight down through the ice."],["rory","And there's a logo on it. A flame in a circle."]],
          intel: {"title":"The Drill","text":"A glowing drill is boring down through the ice. It is stamped with a flame logo: Kaldera Heating."} },
        { id: "grn4", title: "Who Was Here?", game: "identikit", level: 1, station: "sled", stationLabel: "Nuka's dog sled", icon: "camera",
          intro: [["nuka","I saw the man who drove the rig's snowcat away. I'll tell you what I remember."],["pip","Build his face from Nuka's clues, then show it to Nuka."]],
          outro: [["nuka","That's him! Big as a bear. And he had a penguin sticking out of his coat."]],
          intel: {"title":"The Big Man","text":"The rig's driver is enormous, wears a woolly hat, and carries a penguin in his coat."} },
        { id: "grn5", title: "Thin Ice", game: "run", level: 1, station: "snowmobile", stationLabel: "The POLARIS snowmobile", icon: "laser",
          params: {"ride":"snowmobile","objective":"escape","theme":"icefjord","pursuer":"crack","label":"The ice is cracking"},
          intro: [["pip","Uh oh. The drill's going deeper. The whole fjord is starting to crack!"],["nuka","Take the POLARIS snowmobile. Go, go, go!"],["pip","Drag to steer. BOOST when the crack gets close!"]],
          outro: [["rory","Phew! Made it off the ice just in time."],["pip","Admiral Frost is sending the Narwhal to pick you up. You'll want to see this, Rory."]],
          intel: {"title":"Made in Norway","text":"The drill's parts were built in a shipyard in Geiranger, Norway."} },
      ],
      leave: [["pip","That rig had a logo on its side. A flame in a circle: Kaldera Heating."],["pip","And the drill was made in a shipyard in Norway. Admiral Frost wants to see you. Now."]],
    },
    {
      id: "norway", act: 1, city: "Geiranger", country: "Norway", flag: "no", lat: 62.1, lon: 7.21,
      chapter: "The Shipyard", sky: "fjord_day", ambience: "waves", contact: "lars",
      chat: ["Olaf says hello. Well, Olaf says 'SQUAWK', but it means hello.","Cameras everywhere on that quay. Paint them, I say!","Those crates were too hot to touch. My gloves melted.","The lorries are all going the same way. Towards the tender.","The tender's getting away! My speedboat's yours!"],
      arrive: [["lars","Ahoy, young spy! Captain Lars. Forty years I've sailed this fjord. And this is my parrot, Olaf."],["lars","That shipyard started building strange things last spring. Orange things. Hot things. Olaf doesn't like it."]],
      missions: [
        { id: "nor1", title: "Cameras on the Quay", game: "pellets", level: 1, station: "quay", stationLabel: "The shipyard quay", icon: "camera",
          intro: [["lars","The shipyard's quay is covered in security cameras. They turn and turn."],["pip","Flick paint pellets at them. The pellets take time to fly, so aim ahead of the camera!"]],
          outro: [["rory","All painted. They can't see a thing."]],
          intel: {"title":"Blind Cameras","text":"Kaldera's cameras are blinded with POLARIS paint. Nobody saw Rory arrive."} },
        { id: "nor2", title: "Lights Out", game: "blackout", level: 1, station: "gatehouse", stationLabel: "The gatehouse panel", icon: "keypad",
          intro: [["pip","The gatehouse panel controls the lights. Every switch flips itself and its neighbours."],["pip","Turn every light off and the gatehouse goes dark. Then we slip in."]],
          outro: [["lars","Lights out! Olaf, stop squawking, you'll give us away!"]],
          intel: {"title":"Lights Out","text":"The gatehouse is dark. The shipyard gate is open."} },
        { id: "nor3", title: "The Big Crane", game: "claw", level: 1, station: "crane", stationLabel: "The dockside crane", icon: "crate",
          intro: [["lars","The big crane is loading crates onto the tender. Some have the flame on them."],["pip","Drop the claw on the flame crates only. Leave our POLARIS supplies alone."]],
          outro: [["rory","Got them. They're full of drill parts. Still warm!"]],
          intel: {"title":"Hot Crates","text":"The crates are full of drill parts, made here and shipped out on the rig's tender."} },
        { id: "nor4", title: "Lorry Jam", game: "gridlock", level: 1, station: "yard", stationLabel: "The lorry yard", icon: "door",
          intro: [["pip","Your spy car is stuck in the lorry yard. The lorries are blocking the gate."],["pip","Slide the lorries and cars along their lanes. Get the orange car out!"]],
          outro: [["rory","I'm out! And every lorry here is heading for the tender."]],
          intel: {"title":"The Lorry Yard","text":"Every lorry in the yard is taking Kaldera's parts to the tender."} },
        { id: "nor5", title: "Down the Fjord", game: "run", level: 1, station: "boat", stationLabel: "Lars's speedboat", icon: "laser",
          params: {"ride":"speedboat","objective":"catch","theme":"fjord","quarry":"tender","label":"The rig's tender"},
          intro: [["lars","The tender's casting off! She's heading down the fjord!"],["pip","Catch it in Lars's speedboat. BOOST to catch up, then TAG it with a tracking dart!"]],
          outro: [["pip","Tagged! And look what fell out of the wheelhouse: an invitation with gold letters."]],
          intel: {"title":"An Invitation","text":"Baron Kaldera is holding a Winter Gala at the casino in Monte Carlo."} },
      ],
      leave: [["pip","Rory, the tender was carrying an invitation. Gold letters. Very fancy."],["pip","Baron Kaldera's Winter Gala. In Monte Carlo. Tomorrow night. I'll find you a bow tie!"]],
    },
    {
      id: "monaco", act: 1, city: "Monte Carlo", country: "Monaco", flag: "mc", lat: 43.74, lon: 7.42, pinDx: 8,
      chapter: "The Baron's Gala", sky: "night_glam", ambience: "city", contact: "luca",
      chat: ["Nice bow tie! You look like a very small waiter.","The Baron's guards watch the casino floor. Freeze when they turn!","The Baron's yacht is parked in the harbour. Black and orange. Very loud.","Scorch drives like she's on fire. She probably is.","Get in the car! The pit lane is open!"],
      arrive: [["luca","Psst! Agent Rory? I'm Luca. I fix racing cars. The Baron's party is at the casino tonight."],["luca","Everyone important is here. And so is Scorch, his stunt rider. She never takes her helmet off."]],
      missions: [
        { id: "mon1", title: "Black Tie", game: "blendin", level: 1, station: "casino", stationLabel: "The casino floor", icon: "mask",
          intro: [["luca","The Baron is on the casino floor, talking to his guests. We need to get close."],["pip","Hold to sneak forward. When the guard turns round, let go and freeze like a waiter!"]],
          outro: [["rory","I heard him. He said: 'Soon the whole world will pay me to switch it off.'"]],
          intel: {"title":"Switch It Off","text":"The Baron boasted that soon the whole world will pay him to 'switch it off'."} },
        { id: "mon2", title: "The High Roller", game: "crowd", level: 1, station: "terrace", stationLabel: "The casino terrace", icon: "camera",
          intro: [["luca","One of the Baron's henchmen is on the terrace in disguise. He has the Baron's plans."],["pip","Read the clues and tap the henchman. Don't tap the tourists!"]],
          outro: [["rory","Got him. And his briefcase has two words on it: PROJECT MELTDOWN."]],
          intel: {"title":"Project Meltdown","text":"The Baron's secret plan is called Project Meltdown."} },
        { id: "mon3", title: "The Baron's Office", game: "powerlines", level: 1, station: "office", stationLabel: "The Baron's yacht", icon: "server",
          intro: [["pip","The Baron's yacht has a computer in the office. We need to power it up without anyone noticing."],["pip","Join each pair of sockets with a cable. Cables can't cross, and every square must be filled."]],
          outro: [["pip","It's on! A map of the world with six red dots... and one of them is at the South Pole."]],
          intel: {"title":"Six Red Dots","text":"The Baron's computer shows six red dots on a map. One of them is at the South Pole."} },
        { id: "mon4", title: "Party Crashers", game: "whack", level: 1, station: "balcony", stationLabel: "The ballroom balconies", icon: "mask",
          intro: [["luca","Uh oh. The henchmen know you're here. They're on the ballroom balconies!"],["pip","Tag the henchmen in red with paint before they raise the alarm. Not the guests!"]],
          outro: [["rory","That's all of them. Now where's Scorch?"]],
          intel: {"title":"Guards Down","text":"The Baron's balcony guards are covered in paint and very embarrassed."} },
        { id: "mon5", title: "Grand Prix", game: "run", level: 2, station: "pits", stationLabel: "The pit lane", icon: "laser",
          params: {"ride":"sportscar","objective":"catch","theme":"circuit","quarry":"scorchcar","label":"Scorch"},
          intro: [["luca","Scorch is in the pit lane! She's taking the Baron's race car round the circuit!"],["pip","Catch her in the POLARIS car. Close the gap, then TAG!"]],
          outro: [["rory","Tagged! But she got away. She dropped this: a train ticket to Barcelona."]],
          intel: {"title":"Scorch","text":"Scorch, the Baron's stunt rider, is heading to Barcelona."} },
      ],
      leave: [["pip","Scorch dropped a ticket when you tagged her. Barcelona, first train in the morning."],["pip","And Rory... I heard the words on the yacht. Project Meltdown. I don't like the sound of that."]],
    },
    {
      id: "spain", act: 1, city: "Barcelona", country: "Spain", flag: "es", lat: 41.39, lon: 2.17, pinBelow: true, pinDx: -10,
      chapter: "The Blueprints", sky: "sunset", ambience: "city", contact: "ines",
      chat: ["The old town streets are so narrow, lorries get stuck all the time.","The park has mosaic dragons. And cameras. Lots of cameras.","The fish market floor is covered in ice. Slippy!","From the rooftops you can see the whole city. And Scorch.","My motorbike! Take it! Just bring it back!"],
      arrive: [["ines","Hola! I'm Inés. I know every rooftop in Barcelona. Skateboard's faster than a taxi."],["ines","A rider in a flame helmet rode in this morning. She went into the old town with a long tube. Blueprints, I bet."]],
      missions: [
        { id: "spa1", title: "Gothic Quarter Jam", game: "gridlock", level: 2, station: "alley", stationLabel: "The narrow streets", icon: "door",
          intro: [["ines","Scorch's van is stuck in the narrow streets. So is our car!"],["pip","Slide the cars out of the way and get the spy car through."]],
          outro: [["rory","Through! The van went into the park."]],
          intel: {"title":"The Van","text":"Scorch's van left the old town and drove to the mosaic park."} },
        { id: "spa2", title: "Mosaic Cameras", game: "pellets", level: 2, station: "park", stationLabel: "The mosaic park", icon: "camera",
          intro: [["pip","The park has cameras hidden in the mosaics. Kaldera's cameras."],["pip","Paint them. Aim where they're going to be, not where they are!"]],
          outro: [["ines","Now nobody can see us. This way!"]],
          intel: {"title":"Painted Dragons","text":"Every camera in the mosaic park has been painted over."} },
        { id: "spa3", title: "The Slippery Floor", game: "iceslide", level: 2, station: "market", stationLabel: "The market hall", icon: "tomb",
          intro: [["ines","Scorch ran into the market hall. The fish floor is solid ice!"],["pip","You'll slide until something stops you. Use the crates. Slide out through the gap!"]],
          outro: [["rory","Out! And she dropped something: the blueprint tube is empty. She's got them on her."]],
          intel: {"title":"The Empty Tube","text":"Scorch is carrying the blueprints herself."} },
        { id: "spa4", title: "Rooftop Drone", game: "drone", level: 2, station: "rooftops", stationLabel: "The rooftops", icon: "screen",
          intro: [["ines","She's on the rooftops! I can't follow her up there."],["pip","My drone can. Fly it between the chimneys. Hold to go up, let go to drop."]],
          outro: [["pip","Got her on camera. She's heading down to her motorbike!"]],
          intel: {"title":"Rooftop Run","text":"Pip's drone followed Scorch across the rooftops to her motorbike."} },
        { id: "spa5", title: "Scorch!", game: "run", level: 2, station: "bike", stationLabel: "Inés's motorbike", icon: "laser",
          params: {"ride":"motorbike","objective":"catch","theme":"barcelona","quarry":"scorchbike","label":"Scorch"},
          intro: [["ines","Take my motorbike! Catch her!"],["pip","Get close and TAG her. If she drops the blueprints, grab them!"]],
          outro: [["rory","Tagged! She dropped half the blueprints. INFERNO ENGINE... Test drill: Santorini."]],
          intel: {"title":"Inferno Engine","text":"The blueprints are for a giant drilling machine called the Inferno Engine. A test is planned in Santorini."} },
      ],
      leave: [["pip","We got half the blueprints back. Look at the title: INFERNO ENGINE."],["pip","And a note at the bottom: 'Test drill: Santorini'. That's a volcano, Rory."]],
    },
    {
      id: "greece", act: 1, city: "Santorini", country: "Greece", flag: "gr", lat: 36.39, lon: 25.46,
      chapter: "The Test Drill", sky: "bright_day", ambience: "waves", contact: "nikos",
      chat: ["The whole caldera smells like boiled eggs today.","Papa says the man who took his boat was very nervous. And very sweaty.","That barge has a crane. It's pulling hot rocks out of the sea!","The steps down to the harbour are very, very long. Five hundred of them!","The water's boiling! Take my jet ski!"],
      arrive: [["nikos","Yassou! I'm Nikos. My papa is a fisherman. Somebody borrowed his boat last night and brought it back all sooty!"],["nikos","And look down there in the volcano's lagoon. A drill barge. It's been bubbling all morning."]],
      missions: [
        { id: "gre1", title: "The Fisherman's Story", game: "identikit", level: 2, station: "harbour", stationLabel: "The old harbour", icon: "camera",
          intro: [["nikos","My papa saw the man who borrowed his boat. Can you draw him?"],["pip","Build the face from Papa's clues, then show him."]],
          outro: [["nikos","That's him! Papa says he kept saying sorry to the boat."]],
          intel: {"title":"The Nervous Man","text":"A bald, nervous man with round glasses borrowed the boat to reach the drill barge."} },
        { id: "gre2", title: "The Drill Sample", game: "claw", level: 2, station: "drillship", stationLabel: "The drill barge", icon: "crate",
          intro: [["pip","The barge's crane is pulling samples out of the volcano. We need one."],["pip","Drop the claw on the crates with the flame. The belt moves, so drop it early!"]],
          outro: [["rory","Got one. It's a rock. And it's glowing."]],
          intel: {"title":"Glowing Rocks","text":"The drill is pulling up rocks so hot they glow. It's reaching the volcano's heat."} },
        { id: "gre3", title: "Shut It Down", game: "blackout", level: 2, station: "control", stationLabel: "The drill control hut", icon: "keypad",
          intro: [["pip","The drill's control hut is on the cliff. Every switch flips its neighbours."],["pip","Switch off all the heaters and the drill stops."]],
          outro: [["rory","Switched off! But I think we were too late. Listen..."]],
          intel: {"title":"Too Late","text":"The test drill is stopped, but it has already opened a crack into the volcano."} },
        { id: "gre4", title: "Among the Tourists", game: "crowd", level: 2, station: "steps", stationLabel: "The white steps", icon: "camera",
          intro: [["nikos","The nervous man is running away down the white steps! He's in a disguise!"],["pip","Read the clues. Find him in the crowd."]],
          outro: [["rory","Found him! Oh no, he's jumped on a donkey. It's surprisingly fast."]],
          intel: {"title":"Dr Cinder","text":"The nervous man is Dr Cinder, the engineer who designed the Inferno Engine."} },
        { id: "gre5", title: "Caldera Run", game: "run", level: 2, station: "jetski", stationLabel: "Nikos's jet ski", icon: "laser",
          params: {"ride":"jetski","objective":"escape","theme":"caldera","pursuer":"wave","label":"The eruption wave"},
          intro: [["pip","The drill's blown! A giant wave is coming across the lagoon!"],["nikos","Take my jet ski! Outrun it!"]],
          outro: [["rory","Whoa! That was the biggest wave I've ever seen."],["pip","Dr Cinder got away on the ferry. He's booked on a train in Canada."]],
          intel: {"title":"The Wave","text":"The test drill made the volcano's lagoon boil. If the Inferno Engine works, it could melt anything."} },
      ],
      leave: [["pip","The nervous man is called Dr Cinder. He designed the Inferno Engine."],["pip","And he's just bought a ticket on a train through the Canadian Rockies. We're going to Canada!"]],
    },
    {
      id: "canada", act: 1, city: "Banff", country: "Canada", flag: "ca", lat: 51.18, lon: -115.57,
      chapter: "The Mountain Train", sky: "snow_day", ambience: "wind", contact: "mac",
      chat: ["Gerald says hello. He also says he'd like a sandwich.","The dining car serves the best pancakes in Canada. Also, henchmen.","The train's radio is broken. Somebody snipped the wires.","The logs on the river go faster than the train on the bends.","Scorch jumped off the train on skis! The slope's this way!"],
      arrive: [["mac","Welcome to Banff, Agent Rory! I'm Ranger Mac. And this is Gerald. He's a moose."],["mac","The Rocky Mountain train leaves today. A nervous man got on it with far too many suitcases."]],
      missions: [
        { id: "can1", title: "The Dining Car", game: "blendin", level: 2, station: "dining", stationLabel: "The dining car", icon: "mask",
          intro: [["mac","Dr Cinder is hiding in the dining car. There's a guard watching the door."],["pip","Move while the guard looks away. Freeze when he turns. You're just a waiter with pancakes."]],
          outro: [["rory","Found his seat. He left a napkin covered in sums. Six of something. Times one trillion."]],
          intel: {"title":"Six Times","text":"Dr Cinder's napkin sums: six of something, and the number one trillion."} },
        { id: "can2", title: "Radio Silence", game: "powerlines", level: 2, station: "radio", stationLabel: "The baggage-car radio", icon: "server",
          intro: [["pip","The baggage car radio is broken. Fix it and we can call POLARIS."],["pip","Join each pair of sockets. No crossing, and fill every square!"]],
          outro: [["frost","Frost here. Good work, Agent. The Narwhal is racing north to meet the train."]],
          intel: {"title":"A Call Home","text":"The radio works. The Narwhal is coming."} },
        { id: "can3", title: "Carriage Windows", game: "whack", level: 2, station: "carriages", stationLabel: "The sleeper carriages", icon: "mask",
          intro: [["mac","Henchmen! They're popping out of the sleeper carriage windows!"],["pip","Tag the ones in red. Not the passengers in pyjamas!"]],
          outro: [["rory","That's the last one. Dr Cinder's cabin is empty, though."]],
          intel: {"title":"The Empty Cabin","text":"Dr Cinder's cabin is empty. He's left the train."} },
        { id: "can4", title: "Log Jam", game: "floehop", level: 2, station: "river", stationLabel: "The log river", icon: "door",
          intro: [["mac","Cinder's floating down the river on a log! Follow him!"],["pip","Hop across the logs. Don't fall in, it's freezing!"]],
          outro: [["rory","Caught up with him on the bank. He's out of breath. And he's saying sorry again."]],
          intel: {"title":"Caught on the Bank","text":"Dr Cinder has been caught on the riverbank. Scorch is still loose."} },
        { id: "can5", title: "Off the Rails", game: "run", level: 2, station: "slope", stationLabel: "The ski slope", icon: "laser",
          params: {"ride":"skis","objective":"catch","theme":"slope","quarry":"scorchski","label":"Scorch"},
          intro: [["mac","There's Scorch, skiing off down the mountain!"],["pip","On your skis, Rory! Catch her and TAG her!"]],
          outro: [["rory","Tagged her! She's stuck in a snowdrift. Just her helmet showing."],["pip","Dr Cinder wants to talk. And he says it's worse than we think."]],
          intel: {"title":"Worse Than We Think","text":"Dr Cinder has agreed to tell POLARIS everything about the Inferno Engines."} },
      ],
      leave: [["frost","Rory. Frost here. We have Dr Cinder aboard the Narwhal. He's been talking."],["frost","Come home, Agent. You need to hear this yourself."]],
    },
    // ============================================================ ACT TWO
    {
      id: "dubai", act: 2, city: "Dubai", country: "United Arab Emirates", flag: "ae", lat: 25.2, lon: 55.27,
      chapter: "Follow the Money", sky: "desert_day", ambience: "city", contact: "omar",
      chat: ["From the top of the tower you can see the sea. And the Baron's helicopter.","The cable is safe. Mostly. Don't look down.","The bank vault has a lock made of switches. Very clever. Very annoying.","The gold souk sells everything. Even gadget cases.","The courier's getting away with the gold! The supercar's yours!"],
      arrive: [["omar","Marhaba, Agent Rory! I'm Omar. I clean the windows on the tallest tower in the world. I see everything."],["omar","Every day a man in an orange tie goes into the bank. Every day he comes out with gold."]],
      missions: [
        { id: "dub1", title: "Tower Drop", game: "skydive", level: 2, station: "helipad", stationLabel: "The helipad", icon: "mast",
          intro: [["omar","The Baron's meeting is on the helipad. We'll drop in from above."],["pip","Steer your parachute onto the pad. Watch the wind!"]],
          outro: [["rory","Landed! He was talking about a desert. And a telescope."]],
          intel: {"title":"Drop In","text":"Rory landed on the helipad and heard the Baron talk about a desert and a telescope."} },
        { id: "dub2", title: "High Wire", game: "tightrope", level: 2, station: "cable", stationLabel: "The window-cleaning cable", icon: "mast",
          intro: [["omar","The Baron's bank office is on the fortieth floor. My window-cleaning cable goes right past it."],["pip","Keep your balance. Push against the wind!"]],
          outro: [["rory","I can see inside. Stacks of gold. And a sign: 'For the guidance systems'."]],
          intel: {"title":"Guidance Systems","text":"The Baron's gold is paying for guidance systems to steer the Inferno Engines."} },
        { id: "dub3", title: "The Gold Vault", game: "gates", level: 2, station: "vault", stationLabel: "The bank vault", icon: "vault",
          intro: [["pip","The vault lock is made of switches and gates. AND needs both on. OR needs one. NOT flips it."],["pip","Set the switches so the lamp lights."]],
          outro: [["rory","Open! Account books. Every payment goes to... Atacama, Chile."]],
          intel: {"title":"The Account Books","text":"Every payment from the Baron's vault goes to a laboratory in the Atacama Desert."} },
        { id: "dub4", title: "Pack the Evidence", game: "packing", level: 2, station: "souk", stationLabel: "The gold souk", icon: "crate",
          intro: [["omar","We need to smuggle the account books out through the souk."],["pip","Fit every gadget into the case. Tap one to turn it."]],
          outro: [["omar","Packed! Nobody will look twice at a boy with a suitcase."]],
          intel: {"title":"Packed Up","text":"The account books are hidden in Pip's gadget case."} },
        { id: "dub5", title: "Desert Highway", game: "run", level: 3, station: "garage", stationLabel: "The supercar garage", icon: "laser",
          params: {"ride":"sportscar","objective":"catch","theme":"desert_highway","quarry":"courier","label":"The money courier"},
          intro: [["omar","The courier's driving the gold out on the desert highway!"],["pip","Catch him in the supercar. BOOST, then TAG!"]],
          outro: [["rory","Tagged! The gold's going back to the bank."],["pip","But the parts are already made. Next stop: the Atacama Desert."]],
          intel: {"title":"The Gold Courier","text":"The courier is caught, but the guidance systems are already being built in Chile."} },
      ],
      leave: [["pip","The Baron's gold is paying for the engines' guidance systems. They're being made in the Atacama Desert, in Chile."],["pip","And Rory, they steer by the stars."]],
    },
    {
      id: "chile", act: 2, city: "Atacama", country: "Chile", flag: "cl", lat: -23, lon: -67.75,
      chapter: "Desert Eyes", sky: "desert_dusk", ambience: "wind", contact: "valentina",
      chat: ["The sky here is so clear you can see a million stars.","The old mine railway still works. The Baron's men use it.","My telescope is stuck pointing at a satellite. An orange one.","The cold lab should be minus eighty degrees. It isn't.","Trucks! Coming over the dunes! Take the buggy!"],
      arrive: [["valentina","Welcome to the Atacama, the driest desert on Earth. I'm Dr Valentina. I watch the stars."],["valentina","Somebody has been borrowing my telescope at night. And my cold lab smells of burnt toast."]],
      missions: [
        { id: "chi1", title: "Ore Carts", game: "railway", level: 2, station: "mine", stationLabel: "The old mine railway", icon: "door",
          intro: [["valentina","The Baron's ore carts are carrying the guidance parts out of the mine."],["pip","Tap the junctions to send each train to the platform of its colour."]],
          outro: [["rory","Every cart's in the wrong place. That'll slow them down!"]],
          intel: {"title":"Ore Carts","text":"The Baron's guidance parts have all gone to the wrong platforms."} },
        { id: "chi2", title: "Telescope Gears", game: "gears", level: 2, station: "telescope", stationLabel: "The big telescope", icon: "dome",
          intro: [["valentina","My telescope's gearbox has been sabotaged. It can't turn."],["pip","Add gears so the motor turns the telescope the right way. Three in a triangle will jam!"]],
          outro: [["valentina","It's turning! And look. That orange satellite is the Baron's."]],
          intel: {"title":"The Orange Satellite","text":"The Baron has a satellite in the sky to guide his engines."} },
        { id: "chi3", title: "Liquid Nitrogen", game: "jugs", level: 2, station: "lab", stationLabel: "The cold lab", icon: "rods",
          intro: [["valentina","The cold lab's coolant is all mixed up. The guidance chips need exactly the right amount."],["pip","Pour between the tanks to measure it exactly."]],
          outro: [["rory","Cooled. The chips say: 'Target: Antarctica'."]],
          intel: {"title":"Target: Antarctica","text":"The guidance chips are programmed to steer the engines to Antarctica."} },
        { id: "chi4", title: "Desert Landing", game: "lander", level: 2, station: "pad", stationLabel: "The desert helipad", icon: "mast",
          intro: [["valentina","The Baron's helicopter is coming to collect the chips. Land first and we'll swap them!"],["pip","Hold LIFT to go up. Land gently on the pad."]],
          outro: [["rory","Swapped! His chips will now steer his engines to... a very nice beach."]],
          intel: {"title":"Swapped Chips","text":"Some of the Baron's guidance chips have been swapped for POLARIS fakes."} },
        { id: "chi5", title: "Dune Escape", game: "run", level: 3, station: "buggy", stationLabel: "The dune buggy", icon: "laser",
          params: {"ride":"buggy","objective":"escape","theme":"dunes","pursuer":"trucks","label":"Kaldera's trucks"},
          intro: [["valentina","His trucks are coming over the dunes!"],["pip","Escape in the buggy! Don't let them catch you!"]],
          outro: [["rory","Lost them in the dunes."],["pip","The trucks were heading for a ship. Its next stop is Java. Mount Bromo."]],
          intel: {"title":"Over the Dunes","text":"The Baron's trucks were taking parts to a ship bound for Mount Bromo in Indonesia."} },
      ],
      leave: [["pip","The guidance chips are programmed to steer the engines to the South Pole."],["pip","But they need magma cores to heat up. Those are coming from a volcano in Indonesia."]],
    },
    {
      id: "indonesia", act: 2, city: "Mount Bromo", country: "Indonesia", flag: "id", lat: -7.94, lon: 112.95,
      chapter: "Fire Mountain", sky: "dawn", ambience: "jungle", contact: "budi",
      chat: ["Bromo is always smoking. But today it's grumpy.","The warehouse is full of crates. Heavy crates.","The magma core is glowing like a little sun.","It's the village festival tonight! Everyone dances.","Scorch is flying round the volcano! Here's a wingsuit!"],
      arrive: [["budi","Selamat pagi, Agent Rory! I'm Budi, a volcano guide. Welcome to Mount Bromo at sunrise."],["budi","The Baron has built a warehouse inside the crater. His machines are scooping out the volcano's heat."]],
      missions: [
        { id: "ind1", title: "Steam Pipes", game: "pipes", level: 2, station: "plant", stationLabel: "The geothermal plant", icon: "furnace",
          intro: [["budi","The geothermal plant's pipes have been twisted round to feed the Baron's machines."],["pip","Turn the pipes so the coolant runs from the tank to the engine."]],
          outro: [["rory","The plant's back to normal. And the Baron's machines are getting cold."]],
          intel: {"title":"Steam Pipes","text":"The geothermal plant is running for the villagers again."} },
        { id: "ind2", title: "The Warehouse", game: "sokoban", level: 2, station: "warehouse", stationLabel: "The crater warehouse", icon: "crate",
          intro: [["budi","The crater warehouse is full of the Baron's crates. They're on the wrong squares."],["pip","Push every crate onto a marked square. You can push, but you can't pull!"]],
          outro: [["rory","All in place. And behind the crates: a magma core, glowing."]],
          intel: {"title":"The Magma Core","text":"The Baron is packing the volcano's heat into glowing magma cores."} },
        { id: "ind3", title: "Hot Core", game: "cooling", level: 2, station: "core", stationLabel: "The magma core", icon: "furnace",
          intro: [["pip","The magma core is overheating. If it blows, the whole crater goes with it!"],["pip","Tap a valve to cool its gauge. Keep every needle out of the red!"]],
          outro: [["budi","Phew. You saved the mountain, Agent Rory."]],
          intel: {"title":"Cooled Down","text":"The overheating magma core is cooled. Mount Bromo is safe."} },
        { id: "ind4", title: "Festival Dance", game: "dance", level: 2, station: "festival", stationLabel: "The village festival", icon: "mask",
          intro: [["budi","The Baron's henchmen are at the festival. Dance and they won't notice you!"],["pip","Tap the pads in time as the arrows reach the line."]],
          outro: [["rory","They were talking while they danced. The cores are going to Seoul."]],
          intel: {"title":"Festival Gossip","text":"The henchmen said the magma cores are going to Seoul."} },
        { id: "ind5", title: "Wingsuit", game: "run", level: 3, station: "ridge", stationLabel: "The crater ridge", icon: "laser",
          params: {"ride":"wingsuit","objective":"catch","theme":"volcano_air","quarry":"scorchwing","label":"Scorch"},
          intro: [["budi","Scorch is flying off with a magma core!"],["pip","Put on the wingsuit and catch her. Fly through the rings for a boost!"]],
          outro: [["rory","Tagged! She dropped the core into the sea. Sizzle."],["pip","Next stop Seoul. Pack your dancing shoes."]],
          intel: {"title":"Wingsuit","text":"Scorch has lost one magma core. The rest are already on their way to Seoul."} },
      ],
      leave: [["pip","The magma cores are going to Seoul, to be joined to control chips."],["pip","And Rory, Scorch said something about 'the boss's concert'."]],
    },
    {
      id: "korea", act: 2, city: "Seoul", country: "South Korea", flag: "kr", lat: 37.57, lon: 126.98,
      chapter: "The Chip", sky: "night_neon", ambience: "city", contact: "minjun",
      chat: ["The concert's sold out. We'll have to dance our way in.","The chip factory's lock is made of gates. I love gates.","The clean room is so clean, you have to wear a space suit.","The TV tower has the best view in Seoul.","The courier's on a motorbike! Take mine!"],
      arrive: [["minjun","Annyeong! I'm Min-jun. I'm eleven, and I can hack anything. Mostly."],["minjun","The Baron's chip factory makes control chips. Tonight he's collecting them at a concert. A K-pop concert!"]],
      missions: [
        { id: "kor1", title: "Encore", game: "dance", level: 3, station: "stage", stationLabel: "The concert stage", icon: "mask",
          intro: [["minjun","The Baron's deal happens during the concert. Dance and nobody will notice you!"],["pip","Tap the pads in time. Fill the BLEND IN meter!"]],
          outro: [["rory","Great dancing. And the Baron's courier has the chips in a guitar case."]],
          intel: {"title":"Encore","text":"The Baron's control chips are hidden in a guitar case."} },
        { id: "kor2", title: "Chip Factory Lock", game: "gates", level: 3, station: "factory", stationLabel: "The chip factory", icon: "keypad",
          intro: [["minjun","The chip factory door has a lock made of logic gates."],["pip","Set the switches so the lamps light."]],
          outro: [["minjun","We're in! I told you I love gates."]],
          intel: {"title":"Logic","text":"Rory is inside the chip factory."} },
        { id: "kor3", title: "Chip Tray", game: "packing", level: 3, station: "cleanroom", stationLabel: "The clean room", icon: "server",
          intro: [["minjun","In the clean room, we'll swap the Baron's chips for our fakes."],["pip","Pack every piece into the case. Tap to turn them."]],
          outro: [["rory","Swapped. His engines will now play K-pop instead of drilling."]],
          intel: {"title":"The Clean Room","text":"Some of the Baron's control chips are now fakes that play music."} },
        { id: "kor4", title: "Tower Jump", game: "skydive", level: 3, station: "tower", stationLabel: "The TV tower", icon: "mast",
          intro: [["minjun","The courier's meeting Scorch at the bottom of the TV tower. Skydive down!"],["pip","Steer onto the pad. Watch the wind round the tower!"]],
          outro: [["rory","Landed! The courier's getting on a motorbike."]],
          intel: {"title":"Tower Drop","text":"The chip courier is escaping on a motorbike."} },
        { id: "kor5", title: "Neon Streets", game: "run", level: 3, station: "bike", stationLabel: "Min-jun's motorbike", icon: "laser",
          params: {"ride":"motorbike","objective":"catch","theme":"neon","quarry":"courierbike","label":"The chip courier"},
          intro: [["minjun","Take my bike! Follow the neon!"],["pip","Catch the courier. BOOST and TAG!"]],
          outro: [["rory","Tagged! The guitar case is ours."],["pip","But the engines are almost done. The last test is on a glacier in Nepal."]],
          intel: {"title":"Neon Chase","text":"The courier is caught. The engines' last test is in the Himalaya."} },
      ],
      leave: [["pip","The chips and the cores are being joined into six Inferno Engines."],["pip","The last test is on a glacier in the Himalaya. In Nepal."]],
    },
    {
      id: "nepal", act: 2, city: "Khumbu", country: "Nepal", flag: "np", lat: 27.99, lon: 86.83,
      chapter: "The Roof of the World", sky: "high_day", ambience: "wind", contact: "tenzing",
      chat: ["Walk slowly up here. The air is thin.","The rope bridge is old, but it has never dropped anyone. Yet.","The monks let the Baron store boxes in their storeroom. They didn't know.","The test engine is melting the glacier. The river below is rising.","Avalanche! Grab a snowboard! Go!"],
      arrive: [["tenzing","Namaste, Agent Rory. I'm Tenzing. My family have guided climbers here for a hundred years."],["tenzing","Three weeks ago, a machine started drilling into our glacier. The ice is weeping."]],
      missions: [
        { id: "nep1", title: "The Rope Bridge", game: "tightrope", level: 3, station: "bridge", stationLabel: "The rope bridge", icon: "mast",
          intro: [["tenzing","The only way to the test site is over the rope bridge."],["pip","Keep your balance. Push against the wind!"]],
          outro: [["rory","Across! I can hear the engine humming from here."]],
          intel: {"title":"The Rope Bridge","text":"Rory has crossed the gorge to the test site."} },
        { id: "nep2", title: "High Camp", game: "lander", level: 3, station: "helipad", stationLabel: "The high-camp helipad", icon: "mast",
          intro: [["tenzing","Pip's helicopter is bringing climbing gear. The pad is tiny!"],["pip","Hold LIFT and steer gently onto the pad."]],
          outro: [["pip","Landed! Not bad for a ten-year-old pilot."]],
          intel: {"title":"High Camp","text":"Pip's helicopter has landed at high camp with climbing gear."} },
        { id: "nep3", title: "The Monastery Store", game: "sokoban", level: 3, station: "store", stationLabel: "The monastery storeroom", icon: "crate",
          intro: [["tenzing","The Baron's boxes are hidden in the monastery storeroom."],["pip","Push them onto the marked squares so the monks can have their room back."]],
          outro: [["rory","Tidy! And the boxes are full of maps of Antarctica."]],
          intel: {"title":"The Storeroom","text":"The Baron's boxes are full of maps of Antarctica."} },
        { id: "nep4", title: "The Test Engine", game: "cooling", level: 3, station: "engine", stationLabel: "The test engine", icon: "furnace",
          intro: [["tenzing","The test engine is overheating. The glacier will melt!"],["pip","Vent the gauges before they go red!"]],
          outro: [["tenzing","It's cooling. The ice has stopped weeping."]],
          intel: {"title":"The Test Engine","text":"The Inferno Engine's test is over. The engines work."} },
        { id: "nep5", title: "Avalanche!", game: "run", level: 3, station: "summit", stationLabel: "The summit ridge", icon: "laser",
          params: {"ride":"snowboard","objective":"escape","theme":"himalaya","pursuer":"avalanche","label":"The avalanche"},
          intro: [["tenzing","The engine's shaken the snow loose. Avalanche!"],["pip","Snowboard down the mountain! Don't let it catch you!"]],
          outro: [["rory","Outran an avalanche. Can I do that again?"],["pip","No! The engines are being loaded onto ships in Cape Town. Go!"]],
          intel: {"title":"Avalanche","text":"The engines are finished and being loaded onto ships in Cape Town."} },
      ],
      leave: [["pip","The test is finished. The engines are ready, Rory."],["pip","Six ships are loading them in Cape Town. Next stop, South Africa."]],
    },
    {
      id: "southafrica", act: 2, city: "Cape Town", country: "South Africa", flag: "za", lat: -33.92, lon: 18.42,
      chapter: "Ships to the South", sky: "day", ambience: "waves", contact: "thandi",
      chat: ["My penguins have names. That one's Captain Wobble.","The big man in the beanie was here again. He brought the good sardines.","The Baron's ship is enormous. Orange, with a flame on the funnel.","Table Mountain's got its tablecloth of cloud today.","The ship's leaving! Take the speedboat!"],
      arrive: [["thandi","Sawubona, Agent Rory! I'm Thandi. I look after the penguins at Boulders Beach."],["thandi","Something strange: a huge man keeps coming to feed my penguins sardines. He cries a little when he leaves."]],
      missions: [
        { id: "saf1", title: "Harbour Railway", game: "railway", level: 3, station: "sidings", stationLabel: "The harbour sidings", icon: "door",
          intro: [["thandi","The engine wagons are in the harbour sidings, waiting for the ship."],["pip","Switch the points so every train goes to the platform of its colour."]],
          outro: [["rory","Mixed up! Half the Baron's wagons are going to the fish market."]],
          intel: {"title":"The Sidings","text":"Half the engine wagons have been sent the wrong way."} },
        { id: "saf2", title: "Ballast Pipes", game: "pipes", level: 3, station: "ship", stationLabel: "The engine ship", icon: "furnace",
          intro: [["pip","The engine ship's coolant pipes are wrong. If we fix them, the engines can't heat up on the voyage."],["pip","Turn the pipes to join the tank to the engine."]],
          outro: [["rory","Fixed. The engines will arrive cold and cross."]],
          intel: {"title":"Cold Engines","text":"The engines on the ship are now full of coolant."} },
        { id: "saf3", title: "Cable Car", game: "gears", level: 3, station: "cablecar", stationLabel: "The cable-car station", icon: "dome",
          intro: [["thandi","The Baron is watching from the cable car. Its gearbox is jammed!"],["pip","Place the gears so the cable car turns the right way."]],
          outro: [["rory","Moving! From up here I can see the big man. He's feeding Captain Wobble."]],
          intel: {"title":"The Big Man Again","text":"The Baron's henchman Bruno keeps coming to feed the penguins."} },
        { id: "saf4", title: "Fuel Tanks", game: "jugs", level: 3, station: "tanks", stationLabel: "The fuel tanks", icon: "rods",
          intro: [["thandi","The ship's fuel tanks need exactly the right mix, or the Baron will notice."],["pip","Measure it exactly!"]],
          outro: [["rory","Perfect. The ship will run out of fuel just before Antarctica."]],
          intel: {"title":"Fuel","text":"The engine ship will run out of fuel just before Antarctica."} },
        { id: "saf5", title: "The Ship", game: "run", level: 3, station: "jetty", stationLabel: "The jetty", icon: "laser",
          params: {"ride":"speedboat","objective":"catch","theme":"harbour","quarry":"ship","label":"The engine ship"},
          intro: [["thandi","The ship's leaving! Take the speedboat!"],["pip","Catch it and TAG it with a tracker!"]],
          outro: [["rory","Tagged. We can follow it anywhere."],["pip","And it's going exactly where we thought. Antarctica."]],
          intel: {"title":"The Engine Ship","text":"A POLARIS tracker is fixed to the engine ship. It is heading for Antarctica."} },
      ],
      leave: [["frost","Rory, the engine ships are heading south. To Antarctica."],["frost","Come home. The Narwhal sails south tonight."]],
    },
    // ============================================================ ACT THREE
    {
      id: "newzealand", act: 3, city: "Rotorua", country: "New Zealand", flag: "nz", lat: -38.14, lon: 176.25,
      chapter: "The Last Volcano", sky: "day", ambience: "water", contact: "aroha",
      chat: ["Rotorua smells of eggs. You get used to it.","The geyser goes off every few minutes. Stand back!","The meeting house has watched over this valley for a hundred years.","The helicopter can take us over the steam.","Scorch is in the canyon! The jet boat's ready!"],
      arrive: [["aroha","Kia ora, Agent Rory! I'm Aroha, a geothermal guide. Welcome to Rotorua."],["aroha","The Baron is taking our hot springs' heat for his engines. Our pools are going cold."]],
      missions: [
        { id: "nzl1", title: "Geothermal Pipes", game: "pipes", level: 4, station: "plant", stationLabel: "The geothermal station", icon: "furnace",
          intro: [["aroha","The Baron has rewired our geothermal station to feed his ships."],["pip","Turn the pipes to send the heat back to the village."]],
          outro: [["aroha","Our pools are warm again. Thank you!"]],
          intel: {"title":"Hot Springs","text":"Rotorua's heat is going back to the village, not the Baron."} },
        { id: "nzl2", title: "Stepping Stones", game: "floehop", level: 3, station: "pools", stationLabel: "The boiling pools", icon: "door",
          intro: [["aroha","His machines are on the far side of the boiling pools."],["pip","Hop across on the stepping rafts. Don't fall in, it's boiling!"]],
          outro: [["rory","Across! His machines are packing up. He's leaving."]],
          intel: {"title":"Boiling Pools","text":"The Baron's machines are leaving Rotorua."} },
        { id: "nzl3", title: "Spot the Spy", game: "crowd", level: 3, station: "village", stationLabel: "The hot-springs village", icon: "camera",
          intro: [["aroha","Scorch is hiding in the village in disguise!"],["pip","Read the clues. Find her!"]],
          outro: [["rory","Found her! Oh no, she's heading for the river."]],
          intel: {"title":"In Disguise","text":"Scorch was hiding in the hot-springs village."} },
        { id: "nzl4", title: "White Island", game: "lander", level: 4, station: "helipad", stationLabel: "The helipad", icon: "mast",
          intro: [["aroha","We'll follow her from the air. Land by the river!"],["pip","Hold LIFT and land gently on the pad."]],
          outro: [["rory","Down! There she is, in a jet boat."]],
          intel: {"title":"Landed","text":"Scorch is escaping by jet boat."} },
        { id: "nzl5", title: "Jet Boat", game: "run", level: 4, station: "jetboat", stationLabel: "The jet boat", icon: "laser",
          params: {"ride":"jetboat","objective":"catch","theme":"canyon","quarry":"scorchboat","label":"Scorch"},
          intro: [["aroha","Take the jet boat through the canyon!"],["pip","Catch her! BOOST and TAG!"]],
          outro: [["rory","Tagged! She's heading south. Everyone's heading south."]],
          intel: {"title":"The Canyon","text":"Scorch is on her way to Antarctica to join the Baron."} },
      ],
      leave: [["pip","The Baron's last supply ship leaves from Ushuaia, in Argentina. The last port before the ice."],["pip","After that, Rory, it's Antarctica."]],
    },
    {
      id: "argentina", act: 3, city: "Ushuaia", country: "Argentina", flag: "ar", lat: -54.8, lon: -68.3,
      chapter: "The End of the World", sky: "overcast_cold", ambience: "wind", contact: "lucia",
      chat: ["It's always cold here. Even in summer.","The End of the World Train has been running for a hundred years.","The container port is full of the Baron's boxes.","Our icebreaker can break ice as thick as a house.","The convoy's racing to the port! Take the jeep!"],
      arrive: [["lucia","Hola! I'm Lucía, deckhand on the icebreaker. This is Ushuaia, the end of the world."],["lucia","The Baron's convoy arrived this morning. Tomorrow they sail for Antarctica."]],
      missions: [
        { id: "arg1", title: "End of the World Train", game: "railway", level: 4, station: "train", stationLabel: "The End of the World Train", icon: "door",
          intro: [["lucia","The Baron's boxes are on the End of the World Train."],["pip","Switch the points. Send every train to its own colour."]],
          outro: [["rory","Sent! The boxes are going to the museum."]],
          intel: {"title":"The Train","text":"The Baron's supplies are going to the railway museum."} },
        { id: "arg2", title: "Container Jam", game: "gridlock", level: 3, station: "port", stationLabel: "The container port", icon: "crate",
          intro: [["lucia","Our icebreaker's jeep is stuck in the container port."],["pip","Slide the lorries out of the way!"]],
          outro: [["rory","Free! And look, those lorries are Kaldera's."]],
          intel: {"title":"The Port","text":"Kaldera's lorries are waiting at the port."} },
        { id: "arg3", title: "On Deck", game: "whack", level: 3, station: "icebreaker", stationLabel: "The icebreaker deck", icon: "mask",
          intro: [["lucia","The Baron's henchmen are trying to take over the icebreaker!"],["pip","Tag the henchmen. Not the crew!"]],
          outro: [["lucia","The icebreaker's ours. It'll carry you south."]],
          intel: {"title":"The Icebreaker","text":"The icebreaker will take Rory south."} },
        { id: "arg4", title: "Polar Kit", game: "packing", level: 4, station: "kit", stationLabel: "The polar kit store", icon: "crate",
          intro: [["lucia","You'll need polar kit for Antarctica."],["pip","Pack everything into the case. Tap to turn."]],
          outro: [["rory","Packed. Snow goggles, cocoa, and a spare penguin costume. Just in case."]],
          intel: {"title":"Polar Kit","text":"Rory is packed for Antarctica. Including a penguin costume."} },
        { id: "arg5", title: "Race to the Port", game: "run", level: 4, station: "jeep", stationLabel: "The jeep", icon: "laser",
          params: {"ride":"jeep","objective":"escape","theme":"patagonia","pursuer":"convoy","label":"Kaldera's convoy"},
          intro: [["lucia","The convoy's racing us to the port!"],["pip","Get there first in the jeep! Don't let them catch you!"]],
          outro: [["rory","Made it! The icebreaker's waiting."]],
          intel: {"title":"The Convoy","text":"Rory beat Kaldera's convoy to the port."} },
      ],
      leave: [["frost","Rory, this is it. Antarctica."],["frost","The Narwhal will surface at the Peninsula. Wrap up warm, Agent."]],
    },
    {
      id: "peninsula", act: 3, city: "The Peninsula", country: "Antarctica", flag: "aq", lat: -64.8, lon: -62.9, pinBelow: true,
      chapter: "Penguins", sky: "polar_day", ambience: "wind", contact: "ellie",
      chat: ["There are ten thousand penguins here. I've counted. Twice.","The station's been busy. Somebody's been using our radio.","The crevasse opened last week. It wasn't there before.","The generator keeps overheating. Just like everything else.","Scorch is on a snowmobile! Take ours!"],
      arrive: [["ellie","Hello, hello! Dr Ellie. I count penguins. It's the best job in the world."],["ellie","Something's wrong. The ice is getting soft, and there's a very big man hiding in my penguin colony."]],
      missions: [
        { id: "pen1", title: "Waddle", game: "blendin", level: 3, station: "colony", stationLabel: "The penguin colony", icon: "mask",
          intro: [["ellie","The big man is hiding in the penguin colony. Let's sneak up on him."],["pip","Put on the penguin costume. Move when he looks away, freeze when he turns!"]],
          outro: [["rory","Got close. He's talking to the penguins. He's telling them he's sorry."]],
          intel: {"title":"Waddle","text":"The Baron's henchman Bruno is hiding with the penguins. He seems very sad."} },
        { id: "pen2", title: "The Pilot", game: "identikit", level: 3, station: "station", stationLabel: "The research station", icon: "camera",
          intro: [["ellie","Someone used our station radio last night. I saw them from the window."],["pip","Build the face from Ellie's clues."]],
          outro: [["rory","That's Scorch! She radioed the Baron: 'The engines start in two days'."]],
          intel: {"title":"Two Days","text":"The Baron's engines start drilling in two days."} },
        { id: "pen3", title: "Crevasse", game: "tightrope", level: 4, station: "crevasse", stationLabel: "The crevasse", icon: "mast",
          intro: [["ellie","Bruno has run off across the crevasse!"],["pip","Cross on the ladder. Keep your balance!"]],
          outro: [["rory","Across. He's waiting for me. He's holding a penguin."]],
          intel: {"title":"The Crevasse","text":"Rory followed Bruno across the crevasse."} },
        { id: "pen4", title: "Hot Floor", game: "cooling", level: 4, station: "generator", stationLabel: "The station generator", icon: "furnace",
          intro: [["ellie","The station generator's overheating. If it goes, the station freezes."],["pip","Keep the gauges out of the red!"]],
          outro: [["ellie","Saved! My penguins thank you."]],
          intel: {"title":"The Generator","text":"The research station is safe."} },
        { id: "pen5", title: "Across the Ice", game: "run", level: 4, station: "snowmobile", stationLabel: "The snowmobile", icon: "laser",
          params: {"ride":"snowmobile","objective":"catch","theme":"icefield","quarry":"scorchsled","label":"Scorch"},
          intro: [["ellie","Scorch is escaping to the ice shelf!"],["pip","Catch her on the snowmobile!"]],
          outro: [["rory","Tagged! She's stuck in a snowbank. Again."],["bruno","Small spy. I will tell you everything. The engines are on the Ross Ice Shelf."]],
          intel: {"title":"Bruno Changes Sides","text":"Bruno has left the Baron to help POLARIS save the penguins."} },
      ],
      leave: [["bruno","Small spy. I am Bruno. I work for the Baron. But the Baron's engines will cook the penguins."],["bruno","I don't want that. I will help you. The engines are on the Ross Ice Shelf."]],
    },
    {
      id: "iceshelf", act: 3, city: "The Ross Ice Shelf", country: "Antarctica", flag: "aq", lat: -81.5, lon: -175, pinDx: 18,
      chapter: "The Engines", sky: "blizzard", ambience: "blizzard", contact: "zara",
      chat: ["Stay close. You can't see your hand in this blizzard.","The relay mast links all six engines together.","The sentry towers have spotlights. Stay in the dark.","The fuel depot keeps the engines running.","The shelf's cracking! Get in the hovercraft!"],
      arrive: [["zara","Rory! Zara, in person. Good to see you out of the phone."],["zara","That tower's Inferno Engine One. Five more are further out. If they fire, the ice melts in a week."]],
      missions: [
        { id: "ice1", title: "Jam the Gearbox", game: "gears", level: 4, station: "engine1", stationLabel: "Inferno Engine One", icon: "furnace",
          intro: [["zara","Inferno Engine One. Its gearbox is right there."],["pip","Add gears so the brake turns the right way. That jams the drill!"]],
          outro: [["rory","Engine One is jammed. Five to go."]],
          intel: {"title":"Jam the Gearbox","text":"Inferno Engine One has been jammed."} },
        { id: "ice2", title: "The Relay", game: "powerlines", level: 4, station: "relay", stationLabel: "The relay mast", icon: "server",
          intro: [["zara","The relay mast links all six engines."],["pip","Rewire it. Join each pair, fill every square."]],
          outro: [["rory","The engines can't talk to each other any more."]],
          intel: {"title":"The Relay","text":"The six engines have lost their link."} },
        { id: "ice3", title: "Sentry Cameras", game: "pellets", level: 4, station: "sentries", stationLabel: "The sentry towers", icon: "camera",
          intro: [["zara","The sentry drones are watching the depot."],["pip","Paint them! Aim ahead!"]],
          outro: [["rory","Blind drones. Clear to the depot."]],
          intel: {"title":"Sentries","text":"The Baron's sentry drones are blinded."} },
        { id: "ice4", title: "Fuel Drums", game: "sokoban", level: 4, station: "depot", stationLabel: "The fuel depot", icon: "crate",
          intro: [["zara","The fuel drums need moving so the engines run dry."],["pip","Push them onto the marked squares!"]],
          outro: [["rory","Done. The engines are running out of fuel."]],
          intel: {"title":"Fuel Depot","text":"The Inferno Engines are running out of fuel."} },
        { id: "ice5", title: "The Crack", game: "run", level: 4, station: "hovercraft", stationLabel: "Zara's hovercraft", icon: "laser",
          params: {"ride":"hovercraft","objective":"escape","theme":"shelf","pursuer":"crack","label":"The crack"},
          intro: [["zara","The Baron's switched the engines to full power. The shelf's cracking!"],["pip","Get to the hovercraft! Escape!"]],
          outro: [["rory","That was close. The engines are dying, but the Baron's gone."],["zara","His submarine was seen heading for the ice caves."]],
          intel: {"title":"Cracking Up","text":"The engines are failing. The Baron is escaping by submarine."} },
      ],
      leave: [["pip","The engines are jammed, but the Baron has a submarine hidden in the ice caves."],["pip","I'm coming with you, Rory. In person. I've got a mini-sub!"]],
    },
    {
      id: "icecaves", act: 3, city: "The Ice Caves", country: "Antarctica", flag: "aq", lat: -78.5, lon: 106.8,
      chapter: "Under the Ice", sky: "cave", ambience: "water", contact: "pip",
      chat: ["These caves are beautiful. Blue ice everywhere.","The frozen cavern has something inside the ice.","The submarine dock has a logic lock. Of course it does.","My mini-sub needs exactly the right ballast.","The Baron's sub is diving! Into the moon pool!"],
      arrive: [["pip","Rory! It's me, Pip! In real life! Look, I brought the mini-sub."],["pip","The Baron's submarine is docked in these caves. And it's full of spare engine parts."]],
      missions: [
        { id: "cav1", title: "Tunnel Drone", game: "drone", level: 4, station: "tunnel", stationLabel: "The ice tunnel", icon: "screen",
          intro: [["pip","The ice tunnel goes deep. Let's send the drone first."],["pip","Hold to go up, let go to drop. Mind the icicles!"]],
          outro: [["rory","The tunnel leads to the dock."]],
          intel: {"title":"Tunnel Drone","text":"The ice tunnel leads to the Baron's submarine dock."} },
        { id: "cav2", title: "Frozen Floor", game: "iceslide", level: 4, station: "cavern", stationLabel: "The frozen cavern", icon: "tomb",
          intro: [["pip","The cavern floor is smooth ice. Slide carefully!"],["pip","Slide out through the gap."]],
          outro: [["rory","Inside the ice... spare engine parts. Frozen solid."]],
          intel: {"title":"The Frozen Cavern","text":"The Baron's spare engine parts are frozen in the cavern ice."} },
        { id: "cav3", title: "Sub Dock Lock", game: "gates", level: 4, station: "dock", stationLabel: "The submarine dock", icon: "keypad",
          intro: [["pip","The dock's lock uses logic gates."],["pip","Light the lamps!"]],
          outro: [["rory","Open. The Baron's submarine is right there."]],
          intel: {"title":"The Dock","text":"Rory has opened the Baron's submarine dock."} },
        { id: "cav4", title: "Ballast", game: "jugs", level: 4, station: "minisub", stationLabel: "Pip's mini-sub", icon: "rods",
          intro: [["pip","My mini-sub needs exactly the right amount of ballast water."],["pip","Measure it exactly!"]],
          outro: [["pip","Perfect. We can dive."]],
          intel: {"title":"Ballast","text":"Pip's mini-sub is ready to dive."} },
        { id: "cav5", title: "Under the Ice", game: "run", level: 4, station: "moonpool", stationLabel: "The moon pool", icon: "laser",
          params: {"ride":"minisub","objective":"catch","theme":"icecave_water","quarry":"baronsub","label":"Kaldera's submarine"},
          intro: [["pip","The Baron's sub is escaping through the moon pool!"],["pip","Catch it! BOOST and TAG!"]],
          outro: [["rory","Tagged! It's heading for Mount Erebus."]],
          intel: {"title":"The Chase Under the Ice","text":"Kaldera's submarine is heading for his lair in Mount Erebus."} },
      ],
      leave: [["pip","The Baron's sub is heading for Mount Erebus. The real volcano at the bottom of the world."],["pip","That's his lair, Rory. That's where it ends."]],
    },
    {
      id: "erebus", act: 3, city: "Mount Erebus", country: "Antarctica", flag: "aq", lat: -77.53, lon: 167.15, pinDx: -18,
      chapter: "Meltdown", sky: "volcano_night", ambience: "hum", contact: "bruno",
      chat: ["The lava lake is very hot. Do not touch.","The great hall has a disco. The Baron loves disco.","The lava-pit crane holds the master keys.","The master control room switches off all six engines.","The Baron is running for the ice chute! Take my bobsled!"],
      arrive: [["bruno","Small spy. Welcome to the Baron's lair. I know every room."],["bruno","He is having a party. He thinks he has won. He has not."]],
      missions: [
        { id: "ere1", title: "Into the Crater", game: "skydive", level: 4, station: "rim", stationLabel: "The crater rim", icon: "mast",
          intro: [["bruno","The way in is from above. Jump into the crater!"],["pip","Steer onto the rim. Watch the hot wind!"]],
          outro: [["rory","Landed on the rim. I can see the lava lake."]],
          intel: {"title":"Into the Crater","text":"Rory has dropped into the Baron's volcano."} },
        { id: "ere2", title: "Countdown Party", game: "dance", level: 4, station: "hall", stationLabel: "The great hall", icon: "mask",
          intro: [["bruno","The Baron's party is in the great hall. Dance!"],["pip","Tap in time. Blend in!"]],
          outro: [["rory","He's making a speech. 'Tomorrow, the world pays me a trillion dollars!'"]],
          intel: {"title":"The Party","text":"The Baron is celebrating too soon."} },
        { id: "ere3", title: "The Ignition Key", game: "claw", level: 4, station: "lavapit", stationLabel: "The lava-pit crane", icon: "crate",
          intro: [["bruno","The master keys hang over the lava pit."],["pip","Drop the claw on the flame crate. Carefully!"]],
          outro: [["rory","Got the keys. And they're only a bit melted."]],
          intel: {"title":"The Master Keys","text":"Rory has the keys to the master control room."} },
        { id: "ere4", title: "Master Panel", game: "blackout", level: 4, station: "control", stationLabel: "The master control room", icon: "keypad",
          intro: [["bruno","The master control room. Every switch flips its neighbours."],["pip","Switch off all six engines!"]],
          outro: [["kaldera","No! My beautiful engines! Who switched them off?"],["rory","POLARIS did. Your ice is safe, Baron."]],
          intel: {"title":"Engines Off","text":"All six Inferno Engines are off. The ice is freezing again."} },
        { id: "ere5", title: "Downhill", game: "run", level: 4, station: "chute", stationLabel: "The ice chute", icon: "laser",
          params: {"ride":"bobsled","objective":"catch","theme":"chute","quarry":"baronsled","label":"Baron Kaldera"},
          intro: [["kaldera","You will never catch me! I have a gold bobsled!"],["bruno","Take mine! It is faster. It has penguin stickers."],["pip","Catch the Baron, Rory! One last TAG!"]],
          outro: [["kaldera","Curses! Stuck in a snowdrift. How undignified."],["rory","Baron Kaldera, you're coming with us."]],
          intel: {"title":"Baron Kaldera","text":"Baron Magnus Kaldera has been caught at the bottom of Mount Erebus."} },
      ],
      leave: [["pip","You did it, Rory."]],
    },
  ],
  acts: [
    { n: 1, title: "Thin Ice", coldOpen: true, countries: ["greenland","norway","monaco","spain","greece","canada"],
      after: "The Inferno Engines are real.",
      briefing: [["frost","Agent Rory. Welcome aboard the Narwhal. Sit down. Have some cocoa."],["frost","Greenland's glaciers are melting from underneath. In winter. Somebody is drilling for heat."],["frost","The drill had a flame on it. Kaldera Heating. 'Keeping the world toasty since 1896'."],["frost","It belongs to Baron Magnus Kaldera. He lives inside a volcano. Of course he does."],["pip","The drill parts came from a shipyard in Norway. That's where we start."],["frost","Find out what the Baron is up to, Agent. And Rory... be careful."]],
      ending: [["cinder","I'm so sorry. I only wanted to build a nice big heater!"],["cinder","The Baron calls them Inferno Engines. Six of them. They drill down and pour volcano heat under the ice."],["frost","Under Antarctica?"],["cinder","Yes. Fire all six, and the ice melts in a week. The seas rise sixty metres."],["cinder","Unless the world pays him one trillion dollars to switch them off."],["frost","Then we stop them being built. Well done, Agent Rory. Act One is yours."]] },
    { n: 2, title: "Heatwave", countries: ["dubai","chile","indonesia","korea","nepal","southafrica"],
      after: "The engines are sailing south.",
      briefing: [["frost","Agent Rory. The Baron is building his engines in pieces, all over the world."],["frost","Money in Dubai. Guidance in the Atacama Desert. Magma cores from a volcano in Java."],["frost","Control chips in Seoul. A test on a glacier in the Himalaya. And ships in Cape Town."],["pip","Break enough pieces and the engines won't work. Or at least, not very well."],["frost","The Narwhal is at your service. Go."]],
      ending: [["frost","The engine ships have left Cape Town. They're heading south."],["zara","To Antarctica. Six engines, and the Baron with them."],["frost","We'll slow him down with every piece you broke, Rory. But it won't be enough."],["frost","The Narwhal sails south tonight. Act Two is yours, Agent."]] },
    { n: 3, title: "Meltdown", countries: ["newzealand","argentina","peninsula","iceshelf","icecaves","erebus"],
      after: "The ice is safe.",
      briefing: [["frost","Agent Rory. This is it. The engines are in Antarctica."],["frost","The Baron's last supplies come from New Zealand and Argentina. Stop them, then go south."],["zara","I'll meet you on the ice. Bring a warm hat."],["pip","And I'm bringing the mini-sub! In person! I'm very excited."],["frost","Save the ice, Agent. And the penguins."]],
      ending: [["frost","The engines are off. The ice is freezing again."],["zara","And the Baron is sitting in a snowdrift, being told off by a penguin."],["bruno","I am staying here. Dr Ellie says I can be a penguin keeper."],["pip","I made you something, Rory. A gadget. It's a cup of cocoa. It's just cocoa."],["frost","Agent Rory. For saving the ice at the bottom of the world, POLARIS awards you the Order of the Narwhal."],["frost","Well done, Agent. Mission complete."]] },
  ],
  credits: ["AGENT RORY: MELTDOWN","","Starring Rory as Agent R","","An idea by Rory","","Admiral Frost .... himself","Pip .... the gadget genius","Zara .... the best driver in POLARIS","Baron Magnus Kaldera .... the villain","Scorch .... the stunt rider","Bruno .... the penguin keeper","Dr Cinder .... very sorry","","Nuka, Lars and Olaf the parrot, Luca, Inés, Nikos,","Ranger Mac and Gerald the moose, Omar, Dr Valentina,","Budi, Min-jun, Tenzing, Thandi and Captain Wobble,","Aroha, Lucía and Dr Ellie","","No penguins were harmed in the making of this game","","Sophia, Rory and Dylan Games, Inc"],
};
