// Agent Rory: Operation Hurricane — the story as data, written by the story generator.
// Dialogue lines are [speaker, text]; speakers are keys of CHARS in story.js.
// Sophia, Rory and Dylan Games, Inc.
export const OP = {
  id: "hurricane", n: 3, title: "HURRICANE", name: "Operation Hurricane", saveKey: "save3",
  coldOpenLine: "HAWAII. A PERFECTLY CALM DAY.", villain: "Doctor Tempest", bugName: "Tempest", bugLine: "One of Doctor Tempest's listening bugs. Achoo. Off it goes.",
  tagline: "Ten places. Fifty missions. One very big storm.", blurb: "Doctor Tempest is sending the biggest hurricane ever at Washington DC.",
  finished: "Hurricane Hilda went back out to sea, the sun is shining on Washington, and Doctor Tempest's forecast is prison. Watch the credits, or pick another operation.",
  view: {"lon":-111,"lat":29,"span":112}, colors: ["#bfefff","#4ab0ff","#1a3a8a"],
  countries: [
    // ============================================================ ACT ONE
    {
      id: "hawaii", act: 1, city: "North Shore", country: "Hawaii, USA", flag: "us", lat: 21.6, lon: -158.1,
      chapter: "The Big Wave", sky: "tropical_day", ambience: "waves", contact: "kai",
      chat: ["The sea was flat as a pancake this morning. Then, whoosh!","There's a weather buoy out past the reef. It's been beeping all week.","Little flying things were buzzing round the palm trees. When they went past, it hailed. In Hawaii!","A small man with an umbrella was on a boat out there. On a sunny day. Suspicious.","Here it comes! Grab my board and ride it out!"],
      arrive: [["pip","Rory! Sorry to interrupt your holiday. I know it's your first one in ages. But look at the sea."],["pip","The sky is blue, the wind has stopped, and there's a wave out there the size of a skyscraper. That is not normal."],["kai","Aloha! I'm Kai. I've surfed here since I was four. I've never seen a wave like that. Somebody's making them."]],
      missions: [
        { id: "haw1", title: "Surf's Up", game: "surf", level: 1, station: "beach", stationLabel: "The surf beach", icon: "door",
          intro: [["kai","The weather buoy is out past the waves. Surf out to it!"],["pip","Tilt by dragging up and down. Ride the face of the wave, grab the stars, and don't wipe out!"]],
          outro: [["rory","Made it to the buoy. There's a sticker on it: a cloud with a lightning bolt. TEMPEST WEATHER."]],
          intel: {"title":"Tempest Weather","text":"The strange weather buoy belongs to a company called Tempest Weather."} },
        { id: "haw2", title: "The Weather Buoy", game: "powerlines", level: 1, station: "buoy", stationLabel: "The weather buoy", icon: "server",
          intro: [["kai","The buoy's cables have been pulled out. If we fix them, we can read what it's been doing."],["pip","Join each pair of sockets with a cable. Cables can't cross, and every square must be filled."]],
          outro: [["pip","It's been sending signals down into the sea. It made that wave, Rory. On purpose."]],
          intel: {"title":"A Wave on Purpose","text":"The Tempest Weather buoy made the giant wave on purpose."} },
        { id: "haw3", title: "Drones in the Palms", game: "stormgrid", level: 1, station: "palms", stationLabel: "The palm grove", icon: "screen",
          intro: [["kai","The little hail-makers are hiding in the palm grove. Find them all!"],["pip","Each number tells you how many drones are hiding next to that square. Tap to check a square. Hold to mark a drone!"]],
          outro: [["rory","Got them all. Tiny drones with ice-makers inside. That's how it hailed."]],
          intel: {"title":"Hail Drones","text":"Tempest Weather has tiny drones that make hail wherever they fly."} },
        { id: "haw4", title: "Who Was on the Boat?", game: "identikit", level: 1, station: "shack", stationLabel: "The surf shack", icon: "camera",
          intro: [["kai","I saw the man on the boat. I'll tell you what he looked like."],["pip","Build his face from Kai's clues, then show it to Kai."]],
          outro: [["kai","That's him! Small, nervous, with a big umbrella. He kept sneezing."]],
          intel: {"title":"The Man with the Umbrella","text":"The drones were dropped by a small, nervous man who carries an umbrella and sneezes a lot."} },
        { id: "haw5", title: "The Giant Wave", game: "run", level: 1, station: "board", stationLabel: "Kai's surfboard", icon: "laser",
          params: {"ride":"surfboard","objective":"escape","theme":"northshore","pursuer":"wave","label":"The giant wave"},
          intro: [["kai","The big wave is coming for the beach! Take my board and ride it!"],["pip","Drag to steer. BOOST when the wave gets close. Stay ahead of it!"]],
          outro: [["rory","Rode it all the way to the beach! Everyone's safe."],["kai","That was the best ride I've ever seen. And I'm very jealous."]],
          intel: {"title":"Wave Ridden","text":"Rory rode the giant wave safely to shore. Everyone on the beach is safe."} },
      ],
      leave: [["pip","The boat that dropped the drones belongs to a film studio. In Hollywood."],["pip","And Admiral Frost says there's somebody very important waiting to talk to you."]],
    },
    {
      id: "hollywood", act: 1, city: "Hollywood", country: "California, USA", flag: "us", lat: 34.1, lon: -118.33,
      chapter: "Lights, Camera, Weather!", sky: "la_sunny", ambience: "city", contact: "maya",
      chat: ["The director shouts 'Action!' and then it actually rains. Inside. On Stage Seven.","The director wears a cape and a hat shaped like a cloud. She's called Doctor Tempest.","She used to read the weather on TV. Her forecasts were always wrong. Everybody laughed.","Her assistant has an umbrella. Even indoors. He says 'you never know'.","The limo's leaving! Take my mum's car. It's very loud!"],
      arrive: [["maya","Hi, I'm Maya. I'm a stunt kid. I fall off things for movies. It's the best job in the world."],["maya","The studio's making a new film called 'Storm of the Century'. It's got real storms in it. Not pretend ones. Real."]],
      missions: [
        { id: "hol1", title: "The Stunt", game: "stunt", level: 1, station: "set", stationLabel: "Stage Seven", icon: "door",
          intro: [["maya","The only way onto Stage Seven is as a stunt double. Do the stunt!"],["pip","Tap to jump, swipe down to duck. Hit every mark!"]],
          outro: [["maya","Cut! Perfect! And look at the set. It's a model of Washington DC. With a hurricane on top."]],
          intel: {"title":"Storm of the Century","text":"Doctor Tempest's film is about a giant hurricane hitting Washington DC."} },
        { id: "hol2", title: "Spot the Fake", game: "spot", level: 1, station: "trailer", stationLabel: "The director's trailer", icon: "camera",
          intro: [["maya","The storm maps on the wall don't match the ones in the script. Something's been changed."],["pip","Spot the differences between the two pictures. Tap each one you find!"]],
          outro: [["rory","The real maps show real storms. Hawaii, the Grand Canyon, Kansas... and Washington DC."]],
          intel: {"title":"The Storm Maps","text":"Tempest's real storm maps show Hawaii, the Grand Canyon, Kansas and Washington DC."} },
        { id: "hol3", title: "The Studio Lot", game: "gridlock", level: 1, station: "lot", stationLabel: "The studio lot", icon: "door",
          intro: [["maya","The golf carts are all parked in a jam. We need to get the prop truck out."],["pip","Slide the carts along their lanes. Get the truck out!"]],
          outro: [["maya","Out! Nobody parks worse than film people."]],
          intel: {"title":"Unstuck","text":"The prop truck is out of the studio lot."} },
        { id: "hol4", title: "The Extras", game: "crowd", level: 2, station: "backlot", stationLabel: "The western town", icon: "camera",
          intro: [["maya","Drizzle's hiding among the cowboy extras on the western set."],["pip","Read the clues and tap Drizzle. Don't tap the real cowboys!"]],
          outro: [["rory","Found him! Cowboys don't carry umbrellas."],["drizzle","Achoo! You'll never catch me! I have a limo!"]],
          intel: {"title":"Drizzle","text":"Tempest's assistant is called Drizzle. He escaped in a limo."} },
        { id: "hol5", title: "Freeway", game: "run", level: 2, station: "car", stationLabel: "Maya's mum's muscle car", icon: "laser",
          params: {"ride":"musclecar","objective":"catch","theme":"freeway","quarry":"limo","label":"Drizzle's limo"},
          intro: [["maya","Drizzle's limo is heading for the freeway! Mum's car is yours!"],["pip","Drag to steer. Close the gap and TAG the limo!"]],
          outro: [["rory","Tagged! He ran off with his umbrella. But he dropped a booking. Rafting. Grand Canyon."]],
          intel: {"title":"Rafting","text":"Drizzle dropped a rafting booking for the Grand Canyon."} },
      ],
      leave: [["pip","Drizzle dropped a booking for a rafting trip. The Grand Canyon."],["pip","Why would a weather scientist go rafting? Unless she's planning a flood."]],
    },
    {
      id: "canyon", act: 1, city: "Grand Canyon", country: "Arizona, USA", flag: "us", lat: 36.1, lon: -112.1,
      chapter: "Flash Flood", sky: "canyon_day", ambience: "wind", contact: "ruby",
      chat: ["The river has turned brown and fast. It's full of rain from nowhere.","There's a machine on the rim that makes clouds. It hums. The mules don't like it.","If you shout from the rim, the canyon shouts back. Try it. HELLO!","The river camp is right on the bank. If the water rises, it'll be washed away.","Flash flood! Everybody in the raft!"],
      arrive: [["ruby","Howdy! I'm Ruby. I'm a junior ranger. I've got a badge, a hat and a very loud whistle."],["ruby","The Grand Canyon is almost two thousand metres deep. It never rains here in summer. This week it's rained every single day."]],
      missions: [
        { id: "gca1", title: "The Rope Bridge", game: "tightrope", level: 1, station: "bridge", stationLabel: "The rope bridge", icon: "door",
          intro: [["ruby","The rain machine is across the canyon. The only way over is the old rope bridge. It wobbles."],["pip","Keep your balance. Push against the wind!"]],
          outro: [["rory","Across! And don't ask me to do that again."]],
          intel: {"title":"The Rope Bridge","text":"Rory crossed the canyon on the old rope bridge."} },
        { id: "gca2", title: "The Rain Machine", game: "pipes", level: 2, station: "pumps", stationLabel: "The rain machine", icon: "gear",
          intro: [["ruby","The rain machine pumps river water up into the sky. Send it back down to the river instead!"],["pip","Turn the pipes so the water flows from the pump to every drain. No leaks!"]],
          outro: [["ruby","It's pouring into the river! The sky's going blue again."]],
          intel: {"title":"The Rain Machine","text":"Tempest's rain machine has been switched round. It is pouring its water back into the river."} },
        { id: "gca3", title: "Canyon Echoes", game: "chimes", level: 2, station: "rim", stationLabel: "The canyon rim", icon: "keypad",
          intro: [["ruby","The rangers need to hear us. Shout the ranger call into the canyon, and the echo will carry it."],["pip","Listen to the echoes, then repeat them in the same order."]],
          outro: [["ruby","The rangers heard! They're clearing the river camp."]],
          intel: {"title":"Canyon Echoes","text":"The rangers heard the echo and are clearing the river camp."} },
        { id: "gca4", title: "The Flood Wall", game: "sandbags", level: 1, station: "wall", stationLabel: "The river camp", icon: "crate",
          intro: [["ruby","The river's rising. Build a wall of sandbags round the camp!"],["pip","Tap to drop each sandbag. Line it up with the one below. The better you stack, the higher the wall!"]],
          outro: [["rory","The wall's holding! The camp is dry."]],
          intel: {"title":"The Flood Wall","text":"Rory's sandbag wall kept the river camp dry."} },
        { id: "gca5", title: "Rapids", game: "run", level: 2, station: "raft", stationLabel: "The river raft", icon: "laser",
          params: {"ride":"raft","objective":"escape","theme":"grandcanyon","pursuer":"flood","label":"The flash flood"},
          intro: [["ruby","The flash flood's coming down the canyon! Into the raft!"],["pip","Drag to steer round the rocks. BOOST to stay ahead of the flood!"]],
          outro: [["rory","Made it out! The flood's slowing down."],["ruby","That was better than any theme park."]],
          intel: {"title":"Flood Escaped","text":"Rory rafted ahead of the flash flood to safety."} },
      ],
      leave: [["pip","The rain machine was built for testing. Tempest is practising, Rory."],["pip","And Drizzle's map has one more test on it. Kansas. Tornado Alley."]],
    },
    {
      id: "kansas", act: 1, city: "Tornado Alley", country: "Kansas, USA", flag: "us", lat: 38.5, lon: -98,
      chapter: "Tornado Alley", sky: "storm_plains", ambience: "wind", contact: "dusty",
      chat: ["Tornadoes don't keep appointments. These ones do. Three o'clock, every day.","The chickens are stuck in the barn loft. Mum says chickens are not good in storms.","The weather station's radar picture got all scrambled. Somebody messed with it.","There's a big man in the cornfield. He hasn't moved for an hour. He isn't a scarecrow.","It's three o'clock! Here comes the twister! Into the truck!"],
      arrive: [["dusty","Hey! I'm Dusty. My mum chases storms for a living. I help. I hold the snacks."],["dusty","This is Tornado Alley. We get lots of twisters. But this week they've been coming at the same time every day. Like a timetable."]],
      missions: [
        { id: "kan1", title: "Storm Cells", game: "stormgrid", level: 2, station: "radar", stationLabel: "The storm-chaser van", icon: "screen",
          intro: [["dusty","Mum's radar shows the storm cells. Some of them are Tempest's."],["pip","Each number tells you how many storm cells are next to that square. Tap to check. Hold to mark a storm!"]],
          outro: [["rory","Every one of Tempest's storms is lined up in a row. Pointing east."]],
          intel: {"title":"Pointing East","text":"Tempest's storms are lined up and pointing east."} },
        { id: "kan2", title: "Chicken Rescue", game: "claw", level: 2, station: "barn", stationLabel: "The barn hoist", icon: "crate",
          intro: [["dusty","The chickens are up in the barn loft. Use the hoist to lift them out!"],["pip","Drop the claw on the chickens only. Leave the hay bales alone."]],
          outro: [["dusty","All safe! Mum will be so pleased. So will the chickens."]],
          intel: {"title":"Chickens Saved","text":"The chickens are safe from the storm."} },
        { id: "kan3", title: "The Radar Picture", game: "slider", level: 1, station: "station", stationLabel: "The weather station", icon: "screen",
          intro: [["dusty","The weather station's radar picture is all scrambled."],["pip","Slide the tiles back into place. Only a tile next to the gap can move."]],
          outro: [["rory","Look at the top. A shape above the clouds. Like a giant anvil. It's an airship!"]],
          intel: {"title":"The Anvil","text":"Tempest has a giant airship shaped like a storm cloud. It is called the Anvil."} },
        { id: "kan4", title: "Scarecrow", game: "blendin", level: 2, station: "field", stationLabel: "The cornfield", icon: "mask",
          intro: [["dusty","The big man is searching the cornfield. Get close and listen."],["pip","Hold to sneak forward. When he turns, freeze like a scarecrow!"]],
          outro: [["rory","He's on the phone. He only says one word. 'BOOM.'"],["dusty","That's Thunder. Drizzle's big friend. He only ever says BOOM."]],
          intel: {"title":"Thunder","text":"Tempest's other henchman is enormous and only says one word: BOOM."} },
        { id: "kan5", title: "Twister", game: "run", level: 2, station: "truck", stationLabel: "The storm-chaser truck", icon: "laser",
          params: {"ride":"stormtruck","objective":"escape","theme":"plains","pursuer":"tornado","label":"The tornado"},
          intro: [["dusty","It's here! The twister! Mum's truck is yours. Go!"],["pip","Drag to steer. BOOST to stay ahead of the tornado!"]],
          outro: [["rory","It missed us! And it's fading away. Just like that."],["dusty","Mum's going to be so jealous she missed it."]],
          intel: {"title":"Twister Escaped","text":"Rory escaped the tornado. It faded away as fast as it came."} },
      ],
      leave: [["pip","Thunder's phone had one word in it, over and over. MAELSTROM."],["pip","Frost wants you back on the Narwhal. He knows what it means."]],
    },
    // ============================================================ ACT TWO
    {
      id: "niagara", act: 2, city: "Niagara Falls", country: "Canada", flag: "ca", lat: 43.08, lon: -79.07,
      chapter: "The Falls", sky: "mist_day", ambience: "waves", contact: "chloe",
      chat: ["The falls make so much noise you have to shout. WHAT? I SAID YOU HAVE TO SHOUT!","There are new cables running from the power station into the river. Not ours.","The mist makes rainbows every afternoon. This week the rainbows were grey. Grey!","The helicopter tours stopped. A big man took the helicopter. He said BOOM.","Thunder's boat is heading for the whirlpool! Take the jet boat!"],
      arrive: [["chloe","Hi! I'm Chloe. My dad drives the tour boats. Welcome to Niagara Falls! Mind the mist, you'll get soaked."],["chloe","The power station here makes electricity from the falls. This week, somebody's been stealing it. Lots of it."]],
      missions: [
        { id: "nia1", title: "The Power Station", game: "powerlines", level: 2, station: "power", stationLabel: "The power station", icon: "server",
          intro: [["chloe","Tempest's cables are stealing power from the station. Reconnect the proper ones!"],["pip","Join each pair of sockets with a cable. Cables can't cross, and every square must be filled."]],
          outro: [["chloe","The lights are back on! Tempest's cables have gone dead."]],
          intel: {"title":"The Power Station","text":"The power station is back to normal. Tempest's cables are dead."} },
        { id: "nia2", title: "In the Mist", game: "spot", level: 2, station: "deck", stationLabel: "The viewing deck", icon: "camera",
          intro: [["chloe","Two photos of the falls, one from last week and one from today. Something's been added."],["pip","Spot the differences. Tap each one you find!"]],
          outro: [["rory","There. Behind the falls. A giant battery, hidden in the rock."]],
          intel: {"title":"The Battery","text":"Tempest hid a giant battery behind the falls to store stolen power."} },
        { id: "nia3", title: "The Turbines", game: "gears", level: 3, station: "turbine", stationLabel: "The turbine hall", icon: "gear",
          intro: [["chloe","The turbines are jammed. Tempest's men took some of the gears."],["pip","Add gears so the motor turns the turbine the right way. Three in a triangle will jam!"]],
          outro: [["chloe","It's turning! The power's going to the people who need it."]],
          intel: {"title":"The Turbines","text":"The turbines are turning again."} },
        { id: "nia4", title: "Helicopter Tour", game: "lander", level: 2, station: "helipad", stationLabel: "The helipad", icon: "door",
          intro: [["chloe","Thunder is loading the battery onto a boat. Fly the tour helicopter down to the rock!"],["pip","Hold to fire the engine. Land gently on the pad. Not too fast!"]],
          outro: [["rory","Landed. And Thunder is getting away in a boat!"]],
          intel: {"title":"Landed","text":"Rory landed on the rock just as Thunder escaped by boat."} },
        { id: "nia5", title: "Whirlpool", game: "run", level: 3, station: "jetboat", stationLabel: "The jet boat", icon: "laser",
          params: {"ride":"jetboat","objective":"catch","theme":"niagara","quarry":"thunderboat","label":"Thunder"},
          intro: [["chloe","Thunder's heading for the whirlpool! The jet boat is yours!"],["pip","Drag to steer. Close the gap and TAG him!"]],
          outro: [["rory","Tagged! He jumped onto the rocks. BOOM, he said. But we've got the batteries."]],
          intel: {"title":"The Batteries","text":"Rory stopped Thunder's boat full of stolen batteries. Its label points to Florida."} },
      ],
      leave: [["pip","Thunder's boat was full of batteries. Charged with electricity from the falls."],["pip","And there's a shipping label. The Everglades, Florida."]],
    },
    {
      id: "florida", act: 2, city: "The Everglades", country: "Florida, USA", flag: "us", lat: 25.85, lon: -80.9, pinDx: 16,
      chapter: "Hurricane Hunters", sky: "swamp_day", ambience: "waves", contact: "leo",
      chat: ["Don't worry about the alligators. They're mostly asleep. Mostly.","The hurricane hunters' computers keep saying 'SUNNY'. It's pouring.","The satellite dish on the base turned round by itself. It points at Cuba.","A small man with an umbrella is hiding in the swamp. Achoo! There he goes again.","Drizzle's in a hovercraft! Take Dad's airboat!"],
      arrive: [["leo","Hey, I'm Leo. My dad runs airboat tours in the Everglades. Alligators, snakes, mosquitoes the size of birds. Welcome!"],["leo","The hurricane hunters fly into storms to measure them. This week, their planes keep flying the wrong way. Somebody's messing with them."]],
      missions: [
        { id: "fla1", title: "Lily Pads", game: "floehop", level: 3, station: "swamp", stationLabel: "The swamp", icon: "door",
          intro: [["leo","The swamp is full of lily pads. Hop across to the hangar. Not on the alligators!"],["pip","Tap or swipe to jump. Ride the lily pads, but don't ride off the edge!"]],
          outro: [["rory","Across! And the alligator just yawned at me."]],
          intel: {"title":"Across the Swamp","text":"Rory crossed the swamp to the hurricane hunters' hangar."} },
        { id: "fla2", title: "Hurricane Hunters", game: "stormgrid", level: 3, station: "hangar", stationLabel: "The hurricane hunters' hangar", icon: "screen",
          intro: [["leo","The hurricane hunters' data has fake storms hidden in it. Find the real ones!"],["pip","Each number shows how many storms are next to that square. Tap to check, hold to mark!"]],
          outro: [["rory","Found them. And one of the real storms is enormous. It's called Hurricane Hilda."]],
          intel: {"title":"Hurricane Hilda","text":"Hidden in the data is a real storm, bigger than any other. It is called Hurricane Hilda."} },
        { id: "fla3", title: "The Satellite Picture", game: "slider", level: 2, station: "dish", stationLabel: "The satellite dish", icon: "screen",
          intro: [["leo","The satellite picture has been scrambled. Put it back together."],["pip","Slide the tiles back into place. Only a tile next to the gap can move."]],
          outro: [["rory","Hurricane Hilda. It's sitting in the Caribbean. And it's not moving at all. Hurricanes always move."]],
          intel: {"title":"It Doesn't Move","text":"Hurricane Hilda is sitting still in the Caribbean. Real hurricanes never do that."} },
        { id: "fla4", title: "Kite Surf", game: "surf", level: 3, station: "bay", stationLabel: "The bay", icon: "door",
          intro: [["leo","Drizzle dropped a radar part in the bay. Kite surf out and grab it!"],["pip","Drag up and down to ride the waves. Grab the stars and don't wipe out!"]],
          outro: [["rory","Got it! It's a tracking chip. It's tracking Hurricane Hilda."]],
          intel: {"title":"The Tracking Chip","text":"The radar part is a chip that tracks Hurricane Hilda."} },
        { id: "fla5", title: "Airboat", game: "run", level: 3, station: "airboat", stationLabel: "Leo's airboat", icon: "laser",
          params: {"ride":"airboat","objective":"catch","theme":"everglades","quarry":"hover","label":"Drizzle's hovercraft"},
          intro: [["leo","Drizzle's hovercraft is getting away! Dad's airboat is yours!"],["pip","Drag to steer round the mangroves. Close the gap and TAG him!"]],
          outro: [["rory","Tagged! He dived into the swamp. The alligators are looking at him. He's swimming very fast."],["leo","He'll be fine. They're mostly asleep."]],
          intel: {"title":"Radar Parts","text":"Drizzle escaped into the swamp, but his hovercraft was full of radar parts for Havana."} },
      ],
      leave: [["pip","Drizzle's hovercraft was full of radar parts. Going to Havana."],["pip","There's an old lighthouse there. Tempest has been using it as a radar station."]],
    },
    {
      id: "havana", act: 2, city: "Havana", country: "Cuba", flag: "cu", lat: 23.14, lon: -82.36, pinBelow: true, pinDx: -8,
      chapter: "The Lighthouse", sky: "havana_sunset", ambience: "city", contact: "elena",
      chat: ["Grandpa's car is seventy years old. It still goes faster than yours.","The lighthouse used to shine a light. Now it spins a dish. It beeps at night.","A big man keeps loading boxes onto a van at the harbour. He says BOOM when he lifts them.","At the dance hall, somebody left a hat shaped like a cloud.","The weather van is getting away! Grandpa's car is yours!"],
      arrive: [["elena","¡Hola! I'm Elena. I play the trumpet in my grandpa's band. Very loud. Very good."],["elena","Havana is full of old cars, old music and old buildings. And an old lighthouse that's been doing new things."]],
      missions: [
        { id: "hav1", title: "Dance Hall", game: "dance", level: 3, station: "hall", stationLabel: "The dance hall", icon: "mask",
          intro: [["elena","Tempest's men meet at the dance hall. Dance, and nobody will notice you listening!"],["pip","Tap the pads in time as the arrows reach the line."]],
          outro: [["rory","I heard them. 'The Doctor wants the lighthouse ready by Friday.'"]],
          intel: {"title":"By Friday","text":"Tempest's men need the lighthouse radar ready by Friday."} },
        { id: "hav2", title: "Classic Cars", game: "gridlock", level: 3, station: "garage", stationLabel: "The car garage", icon: "door",
          intro: [["elena","The garage is jammed with classic cars. We need Grandpa's out."],["pip","Slide the cars along their lanes. Get Grandpa's convertible out!"]],
          outro: [["elena","Out! Grandpa says thank you. He says it in trumpet."]],
          intel: {"title":"Grandpa's Car","text":"Grandpa's convertible is out of the garage and ready to go."} },
        { id: "hav3", title: "The Lighthouse", game: "mirrors", level: 2, station: "lighthouse", stationLabel: "The lighthouse", icon: "laser",
          intro: [["elena","The lighthouse is Tempest's radar station. Its beam is steering Hurricane Hilda!"],["pip","Tap the mirrors to turn them. Bounce the beam onto every target to scramble the radar!"]],
          outro: [["rory","Scrambled! For a minute, Hilda wobbled. The lighthouse was steering it, Rory."]],
          intel: {"title":"The Lighthouse","text":"Tempest's lighthouse radar is steering Hurricane Hilda. Rory scrambled it."} },
        { id: "hav4", title: "Harbour Cranes", game: "claw", level: 3, station: "harbour", stationLabel: "The harbour", icon: "crate",
          intro: [["elena","Thunder is loading crates of cloud seeds at the harbour. Unload the right ones!"],["pip","Drop the claw on the cloud seed crates only. Leave the fruit alone!"]],
          outro: [["rory","Got them. Silver seeds. When you throw them in the sky, they make clouds."]],
          intel: {"title":"Cloud Seeds","text":"Tempest makes clouds with silver seeds shipped from Havana."} },
        { id: "hav5", title: "The Malecón", game: "run", level: 3, station: "classic", stationLabel: "Elena's grandpa's convertible", icon: "laser",
          params: {"ride":"classiccar","objective":"catch","theme":"malecon","quarry":"weathervan","label":"The weather van"},
          intro: [["elena","Thunder's in the weather van! Grandpa's convertible is yours!"],["pip","Drag to steer along the seawall. Watch out for the waves! Close in and TAG him!"]],
          outro: [["rory","Tagged! Thunder's caught!"],["thunder","...BOOM."],["elena","I think that means 'I give up'."]],
          intel: {"title":"Thunder Caught","text":"Thunder is caught. His van was full of cloud seeds for Costa Rica."} },
      ],
      leave: [["pip","Thunder's caught! And the van was full of seeds for making clouds. Going to Costa Rica."],["pip","There's a cloud factory up on a volcano there. Of course there is."]],
    },
    {
      id: "costarica", act: 2, city: "Arenal", country: "Costa Rica", flag: "cr", lat: 10.46, lon: -84.7,
      chapter: "The Cloud Factory", sky: "rainforest", ambience: "wind", contact: "mateo",
      chat: ["A sloth takes a month to digest a leaf. A month! I love them.","The rain here is warm. But this week it's been cold and grey and it won't stop.","The frogs are hiding. They only hide when something's wrong.","Drizzle came through on a mountain bike. He sneezed and scared a toucan.","Drizzle's getting away down the trail! Take my bike!"],
      arrive: [["mateo","¡Pura vida! I'm Mateo. I look after the sloths at the rescue centre. They're very slow. I'm very patient."],["mateo","Up on the volcano there's a factory that makes clouds. Real clouds. It's been puffing them out day and night."]],
      missions: [
        { id: "cos1", title: "Mud Slide", game: "iceslide", level: 3, station: "slope", stationLabel: "The muddy slope", icon: "tomb",
          intro: [["mateo","The road to the factory is a mud slide. Once you start sliding, you don't stop!"],["pip","You'll slide until something stops you. Use the rocks to steer and slide out through the gap."]],
          outro: [["rory","Made it! And I'm completely covered in mud."],["mateo","It suits you."]],
          intel: {"title":"Mud Slide","text":"Rory slid all the way up to the cloud factory."} },
        { id: "cos2", title: "Canopy Run", game: "stunt", level: 3, station: "canopy", stationLabel: "The treetop walkway", icon: "door",
          intro: [["mateo","The walkway through the treetops leads to the factory. Parts of it are broken!"],["pip","Tap to jump, swipe down to duck. Don't miss a step!"]],
          outro: [["rory","Through the canopy! And a sloth waved at me. Very slowly."]],
          intel: {"title":"The Canopy","text":"Rory ran the treetop walkway to the cloud factory."} },
        { id: "cos3", title: "Spot the Frog", game: "spot", level: 3, station: "station", stationLabel: "The frog station", icon: "camera",
          intro: [["mateo","Tempest's men have changed something at the frog station. The frogs know. Can you see it?"],["pip","Spot the differences. Tap each one you find!"]],
          outro: [["rory","Cloud-making pipes, hidden in the trees. That's why the frogs are hiding."]],
          intel: {"title":"The Pipes","text":"Cloud-making pipes are hidden in the rainforest trees."} },
        { id: "cos4", title: "The Cloud Factory", game: "pipes", level: 3, station: "factory", stationLabel: "The cloud factory", icon: "gear",
          intro: [["mateo","The cloud factory pumps steam up into the sky. Send it back into the volcano!"],["pip","Turn the pipes so the steam goes from the boiler to every vent. No leaks!"]],
          outro: [["mateo","The clouds are stopping! There's the sun!"]],
          intel: {"title":"The Cloud Factory","text":"The cloud factory is switched off. The sun is shining on the rainforest."} },
        { id: "cos5", title: "Jungle Trail", game: "run", level: 3, station: "bike", stationLabel: "Mateo's mountain bike", icon: "laser",
          params: {"ride":"mtb","objective":"catch","theme":"jungle","quarry":"drizzlebike","label":"Drizzle"},
          intro: [["mateo","Drizzle's escaping down the jungle trail! Take my mountain bike!"],["pip","Drag to steer. Close the gap and TAG him!"]],
          outro: [["rory","Tagged! Drizzle, you're coming with us."],["drizzle","Achoo! I only joined for the free umbrella."]],
          intel: {"title":"Drizzle Caught","text":"Drizzle is caught. Only Doctor Tempest is left."} },
      ],
      leave: [["pip","Drizzle's caught, and the cloud factory's shut. But Hurricane Hilda is still growing."],["pip","Frost has found where the Maelstrom is hiding. You're not going to like it."]],
    },
    // ============================================================ ACT THREE
    {
      id: "eye", act: 3, city: "The Eye of the Storm", country: "The Caribbean Sea", flag: "polaris", lat: 17.5, lon: -68,
      chapter: "The Eye", sky: "storm_eye", ambience: "wind", contact: "nia",
      chat: ["Aunt Stella wasn't always like this. She just wanted to get the weather right for once.","The hail drones guard the deck. They're very cold and very rude.","The lab floods every time the storm spins. Bring a towel.","The Maelstrom is the big machine in the middle. It keeps Hilda spinning in one place.","She's getting away in the Anvil! Take the POLARIS jet!"],
      arrive: [["zara","Hold on, Rory! We're flying into the hurricane. It's going to be bumpy, and then it's going to be very, very quiet."],["pip","The middle of a hurricane is called the eye. It's calm and sunny. And there's an island floating in it."],["nia","Psst! Over here! I'm Nia. Doctor Tempest is my aunt. I came to help her with her forecasts. But she's gone too far."]],
      missions: [
        { id: "eye1", title: "Hail Drones", game: "whack", level: 4, station: "deck", stationLabel: "The landing deck", icon: "camera",
          intro: [["nia","The hail drones are guarding the landing deck. Tag them!"],["pip","Tag the hail drones with paint. Leave the seagulls alone!"]],
          outro: [["rory","Deck clear! Nia, which way?"],["nia","Follow me. And mind the puddles."]],
          intel: {"title":"Deck Clear","text":"The hail drones on the landing deck are all tagged."} },
        { id: "eye2", title: "Sandbag the Lab", game: "sandbags", level: 3, station: "lab", stationLabel: "The flooded lab", icon: "crate",
          intro: [["nia","The lab is flooding! Build a wall so we can get to the computer."],["pip","Tap to drop each sandbag. Line it up with the one below!"]],
          outro: [["rory","The water's held back. The computer's still dry!"]],
          intel: {"title":"Sandbagged","text":"Rory held back the water in Tempest's lab."} },
        { id: "eye3", title: "Tempest's Computer", game: "slider", level: 3, station: "computer", stationLabel: "Tempest's computer", icon: "server",
          intro: [["nia","Aunt Stella's computer has a picture password. It's all scrambled."],["pip","Slide the tiles back into place."]],
          outro: [["rory","We're in! It says: WHEN THE MAELSTROM STOPS, HILDA GOES TO WASHINGTON."],["nia","It's a trap. Switch it off, and the hurricane goes to Washington. Leave it on, and it grows forever."]],
          intel: {"title":"The Trap","text":"If the Maelstrom stops, Hurricane Hilda will head for Washington DC."} },
        { id: "eye4", title: "Wind Tunnels", game: "drone", level: 4, station: "tunnels", stationLabel: "The wind tunnels", icon: "screen",
          intro: [["nia","The only way to the Maelstrom is through the wind tunnels. The wind is fierce!"],["pip","Hold to fly the drone up, let go to drop. Squeeze through the gaps!"]],
          outro: [["rory","The drone's in the Maelstrom! Pip, switch it off. We'll deal with Hilda."],["tempest","You fools! Now nothing can stop Hilda. I'll be watching from the best seat in the house."]],
          intel: {"title":"The Maelstrom","text":"The Maelstrom is switched off. Tempest has fled in the Anvil to watch Hilda hit Washington."} },
        { id: "eye5", title: "The Anvil", game: "run", level: 4, station: "jet", stationLabel: "The POLARIS jet", icon: "laser",
          params: {"ride":"jet","objective":"catch","theme":"storm","quarry":"anvil","label":"The Anvil"},
          intro: [["zara","She's getting away in the Anvil! The POLARIS jet is yours, Rory. Mine's the one with the cup holder."],["pip","Drag to steer through the storm. Fly through the rings and TAG the Anvil!"]],
          outro: [["rory","Tagged! The Anvil's losing height!"],["tempest","You haven't won, little spy! I have the remote. See you in Washington!"]],
          intel: {"title":"The Anvil","text":"The Anvil is damaged, but Doctor Tempest escaped to Washington with the Maelstrom's remote."} },
      ],
      leave: [["pip","The Maelstrom is off, Rory. But Tempest set Hilda free before she ran."],["pip","Hurricane Hilda is heading straight for Washington DC. And so is the Anvil."]],
    },
    {
      id: "washington", act: 3, city: "Washington DC", country: "USA", flag: "us", lat: 38.9, lon: -77.04,
      chapter: "The Capital", sky: "dc_storm", ambience: "city", contact: "president",
      chat: ["The Oval Office is oval. People always ask. It really is.","The Lincoln Memorial is full of tourists sheltering from the rain. One of them has a cloud-shaped hat.","The river is rising. The Reflecting Pool is starting to overflow.","The tallest thing in the city is the Washington Monument. If you wanted to control a storm, that's where you'd stand.","The whole country is counting on you, Agent Rory."],
      arrive: [["president","Agent Rory. Welcome to the White House. I wish it were on a sunnier day."],["president","Hurricane Hilda will be here by tonight. Doctor Tempest is somewhere in the city, with a remote that controls the storm."],["president","Everyone says you're the best young agent in the world. I'd like to find out if they're right."]],
      missions: [
        { id: "was1", title: "The Oval Office", game: "spot", level: 4, station: "office", stationLabel: "The Oval Office", icon: "camera",
          intro: [["president","Something in my office has been changed. My staff can't see what. Maybe you can."],["pip","Spot the differences. Tap each one you find!"]],
          outro: [["rory","The globe on the desk. It's a transmitter. Tempest was listening to everything!"],["president","Well, that's very rude."]],
          intel: {"title":"The Transmitter","text":"Tempest hid a transmitter in the globe in the Oval Office."} },
        { id: "was2", title: "Lincoln Memorial", game: "crowd", level: 4, station: "memorial", stationLabel: "The Lincoln Memorial", icon: "camera",
          intro: [["president","The Secret Service thinks Tempest is at the Lincoln Memorial, in disguise."],["pip","Read the clues and tap Tempest. Don't tap the tourists!"]],
          outro: [["rory","Found her! Cloud hat. Very obvious."],["tempest","Too late! Hilda is here! And I'm going somewhere much higher!"]],
          intel: {"title":"Tempest Spotted","text":"Tempest was hiding at the Lincoln Memorial. She ran for somewhere higher."} },
        { id: "was3", title: "Storm Surge", game: "run", level: 4, station: "limo", stationLabel: "The President's car", icon: "laser",
          params: {"ride":"limo","objective":"escape","theme":"mall","pursuer":"surge","label":"The storm surge"},
          intro: [["president","The storm surge is coming up the river! Take my car. It's armoured. It floats. Mostly."],["pip","Drag to steer down the Mall. BOOST to stay ahead of the water!"]],
          outro: [["rory","Made it! We're at the Washington Monument."],["president","Please don't tell anyone I said my car floats."]],
          intel: {"title":"The Storm Surge","text":"Rory drove the President's car ahead of the storm surge to the Washington Monument."} },
        { id: "was4", title: "The Flood Wall", game: "sandbags", level: 4, station: "wall", stationLabel: "The Reflecting Pool", icon: "crate",
          intro: [["president","The Reflecting Pool is overflowing towards the monument. We need a wall, fast!"],["pip","Tap to drop each sandbag. Line it up with the one below!"]],
          outro: [["rory","The wall's holding! Now, up the monument."]],
          intel: {"title":"The Flood Wall","text":"Rory's sandbag wall kept the flood away from the Washington Monument."} },
        { id: "was5", title: "The Last Forecast", game: "stormgrid", level: 4, station: "monument", stationLabel: "The Washington Monument", icon: "screen",
          intro: [["tempest","Welcome to the top, Agent Rory. With this remote, I am the Queen of the Weather! Sunshine only for those who pay!"],["pip","Rory, the remote shows Hilda's storm cells. Find every one and mark it, and the remote will send Hilda back out to sea!"]],
          outro: [["tempest","No! My beautiful hurricane! It's... turning round?"],["rory","Today's forecast, Doctor: sunny. With a chance of prison."],["president","Look! The sun's coming out."]],
          intel: {"title":"Sunshine","text":"Hurricane Hilda has turned out to sea. Doctor Tempest is caught, and the sun is shining on Washington."} },
      ],
      leave: [["president","Agent Rory. On behalf of the whole country, thank you."],["pip","Rory, the President's having a ceremony in the Rose Garden. For you! Wear your good socks."]],
    },
  ],
  acts: [
    { n: 1, title: "Storm Warning", coldOpen: true, countries: ["hawaii","hollywood","canyon","kansas"],
      after: "Somebody is making the weather.",
      briefing: [["frost","Agent Rory. Welcome aboard the Narwhal. Sit down. The President of the United States is on the line."],["president","Agent Rory. Giant waves in Hawaii. Hail on the beach. Floods in the desert. Somebody is making our weather."],["president","I asked for the best young agent in the world. They said, 'Ask POLARIS for Rory'."],["frost","The buoy belongs to Tempest Weather. It's owned by Doctor Stella Tempest. She used to read the weather on television."],["pip","Her forecasts were always wrong. So now she makes the weather herself. That way, she's always right."],["frost","Her assistant's boat came from a film studio in Hollywood. Start there. And Rory... take an umbrella."]],
      ending: [["frost","Sit down, Rory. We know what MAELSTROM means now."],["frost","It's a weather machine. It can hold a hurricane in one place and make it grow. And grow."],["pip","Tempest has been practising. Waves, hail, floods, tornadoes. Now she's making the biggest storm ever."],["frost","She says she'll send it at Washington DC, unless the world gives her every weather satellite in the sky."],["president","Then she'll sell sunshine to whoever pays the most. Agent Rory, please stop her."],["frost","Act One is yours, Agent."]] },
    { n: 2, title: "Hurricane Season", countries: ["niagara","florida","havana","costarica"],
      after: "Hurricane Hilda is growing.",
      briefing: [["frost","Agent Rory. The Maelstrom needs four things: power, tracking, radar and clouds."],["frost","Power from Niagara Falls. Tracking from the hurricane hunters in Florida. Radar from an old lighthouse in Havana. And clouds from a factory in Costa Rica."],["pip","Break them all, and the Maelstrom gets weaker. Weaker is good."],["frost","Off you go, Agent. Try not to get wet. You'll get wet."]],
      ending: [["frost","Well done, Agent. Thunder and Drizzle are both caught. And the Maelstrom is weaker."],["zara","But we've found where it's hiding. In the eye of Hurricane Hilda. On a floating island."],["frost","Nobody has ever flown into a storm that big. Except Zara."],["zara","Twice. Bring a sick bag."],["frost","Act Two is yours, Agent Rory."]] },
    { n: 3, title: "The Eye", countries: ["eye","washington"],
      after: "The sun is out.",
      briefing: [["frost","Agent Rory. This is it. The Maelstrom is in the eye of the hurricane."],["president","Agent Rory, if Hilda reaches Washington, it'll be the worst storm in a hundred years. We're counting on you."],["zara","I'll fly you in. Hold onto your cocoa."],["pip","And I've built you a raincoat with a jet pack. It's not tested. It's probably fine."],["frost","Go, Agent. Stop the storm."]],
      ending: [["frost","Doctor Tempest is on her way to prison. She says it'll rain tomorrow. It won't."],["nia","I'm going to be a real weather forecaster. The kind who's right."],["pip","I made you a gadget, Rory. It's an umbrella. It's just an umbrella. I'm very proud of it."],["president","Agent Rory. For saving Washington, and the weather of the whole world, I present you with this medal."],["president","Thank you, Agent. Your country, and every country, is grateful."],["frost","Well done, Agent. Mission complete."]] },
  ],
  credits: ["AGENT RORY: HURRICANE","","Starring Rory as Agent R","","An idea by Rory","","Admiral Frost .... himself","Pip .... the gadget genius","Zara .... the best pilot in POLARIS","Doctor Stella Tempest .... the villain","Drizzle .... the one with the umbrella","Thunder .... BOOM","The President .... the President","","Kai, Maya, Ruby, Dusty, Chloe, Leo, Elena,","Mateo and the sloths, and Nia","","No weather was harmed in the making of this game","","Sophia, Rory and Dylan Games, Inc"],
};
