// Agent Rory: Meltdown — the story as data.
// Dialogue lines are [speaker, text]; speakers are keys of CHARS.
// Sophia, Rory and Dylan Games, Inc.

export const CHARS = {
  rory:     { name: "Rory", voice: { g: "m", langs: ["en-GB"], pitch: 1.15, rate: 1.05 },
              face: { skin: "#f3cfae", hair: "#6b4423", style: "short", eyes: "#3b5f8a", clothes: "#16324f", accessory: "earpiece" } },
  frost:    { name: "Admiral Frost", voice: { g: "m", langs: ["en-GB"], pitch: 0.7, rate: 0.9 },
              face: { skin: "#f0c8a8", hair: "#f4f4f4", style: "captain", eyes: "#3a4a5a", facial: "bigbeard", eyepatch: true, clothes: "#10233d", accessory: "medal", brows: "stern" } },
  pip:      { name: "Pip", voice: { g: "f", langs: ["en-AU", "en-GB"], pitch: 1.35, rate: 1.12 },
              face: { skin: "#f6d7bf", hair: "#e0a040", style: "messy", eyes: "#3a7a4a", goggles: true, clothes: "#f4f4f4", accessory: "labcoat" } },
  zara:     { name: "Zara", voice: { g: "f", langs: ["en-US"], pitch: 1.12, rate: 1.08 },
              face: { skin: "#8a5a3a", hair: "#1a1010", style: "ponytail", eyes: "#2a1a10", clothes: "#e0442a", accessory: "headset" } },
  kaldera:  { name: "Baron Kaldera", voice: { g: "m", langs: ["es-ES"], pitch: 0.62, rate: 0.82 },
              face: { skin: "#e8c8a8", hair: "#1a1a1a", style: "sleek", eyes: "#2a1a10", facial: "goatee", monocle: true, clothes: "#e05a10", accessory: "cape", brows: "stern" } },
  scorch:   { name: "Scorch", voice: { g: "f", langs: ["en-US"], pitch: 0.95, rate: 1.05 },
              face: { skin: "#f0c8a8", hair: "#c0202a", style: "helmet", eyes: "#222", clothes: "#b01020", accessory: "flames" } },
  bruno:    { name: "Bruno", voice: { g: "m", langs: ["sv-SE", "en-GB"], pitch: 0.6, rate: 0.85 },
              face: { skin: "#f0c8a8", hair: "#3a2a1a", style: "beanie", eyes: "#3a5a8a", facial: "stubble", clothes: "#3a3a44", big: true, accessory: "penguin" } },
  cinder:   { name: "Dr Cinder", voice: { g: "m", langs: ["en-GB"], pitch: 1.3, rate: 1.1 },
              face: { skin: "#f1c9a5", hair: "#8a7a5a", style: "bald", eyes: "#4a4a4a", glasses: "round", clothes: "#f0f0f0", accessory: "pencil", sweaty: true } },
  watch:    { name: "Spy Watch", voice: { g: "n", langs: ["en-GB"], pitch: 1.0, rate: 1.1 },
              face: { skin: "#223", hair: "#223", style: "watch", eyes: "#7fd", clothes: "#223" } },
  // the contacts
  nuka:     { name: "Nuka", voice: { g: "f", langs: ["da-DK", "en-GB"], pitch: 1.25, rate: 1.05 },
              face: { skin: "#d8a878", hair: "#141414", style: "furhood", eyes: "#2a1a10", clothes: "#3a6aa0" } },
  lars:     { name: "Captain Lars", voice: { g: "m", langs: ["nb-NO", "en-GB"], pitch: 0.85, rate: 0.95 },
              face: { skin: "#f0c8a8", hair: "#d0c8b8", style: "captain", eyes: "#3a5a8a", facial: "beard", clothes: "#1b2a4a", accessory: "pipe" } },
  luca:     { name: "Luca", voice: { g: "m", langs: ["fr-FR"], pitch: 1.2, rate: 1.1 },
              face: { skin: "#f0d0b0", hair: "#3a2414", style: "cap", eyes: "#3a2a1a", clothes: "#c01818", accessory: "wrench" } },
  ines:     { name: "Inés", voice: { g: "f", langs: ["es-ES"], pitch: 1.2, rate: 1.1 },
              face: { skin: "#e0b48c", hair: "#2a1810", style: "long", eyes: "#3a2a1a", clothes: "#f0a020", accessory: "skateboard" } },
  nikos:    { name: "Nikos", voice: { g: "m", langs: ["el-GR", "en-GB"], pitch: 1.1, rate: 1.05 },
              face: { skin: "#d8a878", hair: "#1a1a1a", style: "curly", eyes: "#2a1a10", clothes: "#2a6ab0", stripes: true } },
  mac:      { name: "Ranger Mac", voice: { g: "f", langs: ["en-CA", "en-US"], pitch: 1.0, rate: 1.0 },
              face: { skin: "#f0c8a8", hair: "#a0502a", style: "ranger", eyes: "#3a6a3a", clothes: "#3a5a2a", accessory: "badge" } },
  omar:     { name: "Omar", voice: { g: "m", langs: ["ar-SA", "en-GB"], pitch: 1.1, rate: 1.05 },
              face: { skin: "#c8946a", hair: "#1a1010", style: "short", eyes: "#2a1a10", clothes: "#2a8ac0", accessory: "harness" } },
  valentina:{ name: "Dr Valentina", voice: { g: "f", langs: ["es-CL", "es-ES"], pitch: 1.05, rate: 1.0 },
              face: { skin: "#d8a878", hair: "#2a1810", style: "bun", eyes: "#2a1a10", glasses: "round", clothes: "#5a3a8a" } },
  budi:     { name: "Budi", voice: { g: "m", langs: ["id-ID", "en-GB"], pitch: 1.0, rate: 1.0 },
              face: { skin: "#b07a4e", hair: "#141414", style: "short", eyes: "#2a1a10", clothes: "#c05a20", accessory: "scarf" } },
  minjun:   { name: "Min-jun", voice: { g: "m", langs: ["ko-KR", "en-US"], pitch: 1.2, rate: 1.1 },
              face: { skin: "#f0d8c0", hair: "#141414", style: "swept", eyes: "#222", clothes: "#8a2ae0", accessory: "headset" } },
  tenzing:  { name: "Tenzing", voice: { g: "m", langs: ["en-IN", "en-GB"], pitch: 1.15, rate: 1.0 },
              face: { skin: "#b8845a", hair: "#141414", style: "beanie", eyes: "#2a1a10", clothes: "#e0a020", accessory: "scarf" } },
  thandi:   { name: "Thandi", voice: { g: "f", langs: ["en-ZA", "en-GB"], pitch: 1.1, rate: 1.05 },
              face: { skin: "#6b4226", hair: "#111111", style: "puffs", eyes: "#2a1a10", clothes: "#2a8a4a", accessory: "badge" } },
  aroha:    { name: "Aroha", voice: { g: "f", langs: ["en-NZ", "en-AU"], pitch: 1.05, rate: 1.0 },
              face: { skin: "#b07a52", hair: "#1a1010", style: "long", eyes: "#2a1a10", clothes: "#1a6a6a", accessory: "pendant" } },
  lucia:    { name: "Lucía", voice: { g: "f", langs: ["es-AR", "es-ES"], pitch: 1.1, rate: 1.05 },
              face: { skin: "#e0b890", hair: "#5a3018", style: "beanie", eyes: "#3a2a1a", clothes: "#d02a2a" } },
  ellie:    { name: "Dr Ellie", voice: { g: "f", langs: ["en-IE", "en-GB"], pitch: 1.05, rate: 1.0 },
              face: { skin: "#f4d8c4", hair: "#c05a20", style: "curly", eyes: "#3a7a4a", clothes: "#e06a1a", accessory: "clipboard" } },
};

// kept for the engine's symbol drawing
export const SYMBOLS = ["sun", "moon", "star", "bolt", "eye", "key", "wave", "diamond", "skull"];

export const COUNTRIES = [
  // ================================================================ ACT ONE
  {
    id: "greenland", act: 1, city: "Ilulissat", country: "Greenland", flag: "gl", lat: 69.22, lon: -51.1,
    chapter: "Thin Ice", sky: "polar_day", ambience: "wind", contact: "nuka",
    chat: ["TBD greenland chat 1", "TBD greenland chat 2", "TBD greenland chat 3", "TBD greenland chat 4", "TBD greenland chat 5"],
    arrive: [["nuka", "TBD greenland arrive"]],
    missions: [
      { id: "grn1", title: "Across the Icefjord", game: "floehop", level: 1, station: "floes", stationLabel: "The drifting floes", icon: "door",
        intro: [["pip","TBD grn1 intro"]],
        outro: [["rory","TBD grn1 outro"]],
        intel: {"title":"TBD","text":"TBD grn1 intel"} },
      { id: "grn2", title: "The Research Hut", game: "iceslide", level: 1, station: "hut", stationLabel: "The frozen research hut", icon: "tomb",
        intro: [["pip","TBD grn2 intro"]],
        outro: [["rory","TBD grn2 outro"]],
        intel: {"title":"TBD","text":"TBD grn2 intel"} },
      { id: "grn3", title: "Eyes Inside", game: "drone", level: 1, station: "rig", stationLabel: "The drilling rig", icon: "screen",
        intro: [["pip","TBD grn3 intro"]],
        outro: [["rory","TBD grn3 outro"]],
        intel: {"title":"TBD","text":"TBD grn3 intel"} },
      { id: "grn4", title: "Who Was Here?", game: "identikit", level: 1, station: "sled", stationLabel: "Nuka's dog sled", icon: "camera",
        intro: [["pip","TBD grn4 intro"]],
        outro: [["rory","TBD grn4 outro"]],
        intel: {"title":"TBD","text":"TBD grn4 intel"} },
      { id: "grn5", title: "Thin Ice", game: "run", level: 1, station: "snowmobile", stationLabel: "The POLARIS snowmobile", icon: "laser",
        params: {"ride":"snowmobile","objective":"escape","theme":"icefjord","pursuer":"crack","label":"The ice is cracking"},
        intro: [["pip","TBD grn5 intro"]],
        outro: [["rory","TBD grn5 outro"]],
        intel: {"title":"TBD","text":"TBD grn5 intel"} },
    ],
    leave: [],
  },
  {
    id: "norway", act: 1, city: "Geiranger", country: "Norway", flag: "no", lat: 62.1, lon: 7.21,
    chapter: "The Shipyard", sky: "fjord_day", ambience: "waves", contact: "lars",
    chat: ["TBD norway chat 1", "TBD norway chat 2", "TBD norway chat 3", "TBD norway chat 4", "TBD norway chat 5"],
    arrive: [["lars", "TBD norway arrive"]],
    missions: [
      { id: "nor1", title: "Cameras on the Quay", game: "pellets", level: 1, station: "quay", stationLabel: "The shipyard quay", icon: "camera",
        intro: [["pip","TBD nor1 intro"]],
        outro: [["rory","TBD nor1 outro"]],
        intel: {"title":"TBD","text":"TBD nor1 intel"} },
      { id: "nor2", title: "Lights Out", game: "blackout", level: 1, station: "gatehouse", stationLabel: "The gatehouse panel", icon: "keypad",
        intro: [["pip","TBD nor2 intro"]],
        outro: [["rory","TBD nor2 outro"]],
        intel: {"title":"TBD","text":"TBD nor2 intel"} },
      { id: "nor3", title: "The Big Crane", game: "claw", level: 1, station: "crane", stationLabel: "The dockside crane", icon: "crate",
        intro: [["pip","TBD nor3 intro"]],
        outro: [["rory","TBD nor3 outro"]],
        intel: {"title":"TBD","text":"TBD nor3 intel"} },
      { id: "nor4", title: "Lorry Jam", game: "gridlock", level: 1, station: "yard", stationLabel: "The lorry yard", icon: "door",
        intro: [["pip","TBD nor4 intro"]],
        outro: [["rory","TBD nor4 outro"]],
        intel: {"title":"TBD","text":"TBD nor4 intel"} },
      { id: "nor5", title: "Down the Fjord", game: "run", level: 1, station: "boat", stationLabel: "Lars's speedboat", icon: "laser",
        params: {"ride":"speedboat","objective":"catch","theme":"fjord","quarry":"tender","label":"The rig's tender"},
        intro: [["pip","TBD nor5 intro"]],
        outro: [["rory","TBD nor5 outro"]],
        intel: {"title":"TBD","text":"TBD nor5 intel"} },
    ],
    leave: [],
  },
  {
    id: "monaco", act: 1, city: "Monte Carlo", country: "Monaco", flag: "mc", lat: 43.74, lon: 7.42,
    chapter: "The Baron's Gala", sky: "night_glam", ambience: "city", contact: "luca",
    chat: ["TBD monaco chat 1", "TBD monaco chat 2", "TBD monaco chat 3", "TBD monaco chat 4", "TBD monaco chat 5"],
    arrive: [["luca", "TBD monaco arrive"]],
    missions: [
      { id: "mon1", title: "Black Tie", game: "blendin", level: 1, station: "casino", stationLabel: "The casino floor", icon: "mask",
        intro: [["pip","TBD mon1 intro"]],
        outro: [["rory","TBD mon1 outro"]],
        intel: {"title":"TBD","text":"TBD mon1 intel"} },
      { id: "mon2", title: "The High Roller", game: "crowd", level: 1, station: "terrace", stationLabel: "The casino terrace", icon: "camera",
        intro: [["pip","TBD mon2 intro"]],
        outro: [["rory","TBD mon2 outro"]],
        intel: {"title":"TBD","text":"TBD mon2 intel"} },
      { id: "mon3", title: "The Baron's Office", game: "powerlines", level: 1, station: "office", stationLabel: "The Baron's yacht", icon: "server",
        intro: [["pip","TBD mon3 intro"]],
        outro: [["rory","TBD mon3 outro"]],
        intel: {"title":"TBD","text":"TBD mon3 intel"} },
      { id: "mon4", title: "Party Crashers", game: "whack", level: 1, station: "balcony", stationLabel: "The ballroom balconies", icon: "mask",
        intro: [["pip","TBD mon4 intro"]],
        outro: [["rory","TBD mon4 outro"]],
        intel: {"title":"TBD","text":"TBD mon4 intel"} },
      { id: "mon5", title: "Grand Prix", game: "run", level: 2, station: "pits", stationLabel: "The pit lane", icon: "laser",
        params: {"ride":"sportscar","objective":"catch","theme":"circuit","quarry":"scorchcar","label":"Scorch"},
        intro: [["pip","TBD mon5 intro"]],
        outro: [["rory","TBD mon5 outro"]],
        intel: {"title":"TBD","text":"TBD mon5 intel"} },
    ],
    leave: [],
  },
  {
    id: "spain", act: 1, city: "Barcelona", country: "Spain", flag: "es", lat: 41.39, lon: 2.17,
    chapter: "The Blueprints", sky: "sunset", ambience: "city", contact: "ines",
    chat: ["TBD spain chat 1", "TBD spain chat 2", "TBD spain chat 3", "TBD spain chat 4", "TBD spain chat 5"],
    arrive: [["ines", "TBD spain arrive"]],
    missions: [
      { id: "spa1", title: "Gothic Quarter Jam", game: "gridlock", level: 2, station: "alley", stationLabel: "The narrow streets", icon: "door",
        intro: [["pip","TBD spa1 intro"]],
        outro: [["rory","TBD spa1 outro"]],
        intel: {"title":"TBD","text":"TBD spa1 intel"} },
      { id: "spa2", title: "Mosaic Cameras", game: "pellets", level: 2, station: "park", stationLabel: "The mosaic park", icon: "camera",
        intro: [["pip","TBD spa2 intro"]],
        outro: [["rory","TBD spa2 outro"]],
        intel: {"title":"TBD","text":"TBD spa2 intel"} },
      { id: "spa3", title: "The Slippery Floor", game: "iceslide", level: 2, station: "market", stationLabel: "The market hall", icon: "tomb",
        intro: [["pip","TBD spa3 intro"]],
        outro: [["rory","TBD spa3 outro"]],
        intel: {"title":"TBD","text":"TBD spa3 intel"} },
      { id: "spa4", title: "Rooftop Drone", game: "drone", level: 2, station: "rooftops", stationLabel: "The rooftops", icon: "screen",
        intro: [["pip","TBD spa4 intro"]],
        outro: [["rory","TBD spa4 outro"]],
        intel: {"title":"TBD","text":"TBD spa4 intel"} },
      { id: "spa5", title: "Scorch!", game: "run", level: 2, station: "bike", stationLabel: "Inés's motorbike", icon: "laser",
        params: {"ride":"motorbike","objective":"catch","theme":"barcelona","quarry":"scorchbike","label":"Scorch"},
        intro: [["pip","TBD spa5 intro"]],
        outro: [["rory","TBD spa5 outro"]],
        intel: {"title":"TBD","text":"TBD spa5 intel"} },
    ],
    leave: [],
  },
  {
    id: "greece", act: 1, city: "Santorini", country: "Greece", flag: "gr", lat: 36.39, lon: 25.46,
    chapter: "The Test Drill", sky: "bright_day", ambience: "waves", contact: "nikos",
    chat: ["TBD greece chat 1", "TBD greece chat 2", "TBD greece chat 3", "TBD greece chat 4", "TBD greece chat 5"],
    arrive: [["nikos", "TBD greece arrive"]],
    missions: [
      { id: "gre1", title: "The Fisherman's Story", game: "identikit", level: 2, station: "harbour", stationLabel: "The old harbour", icon: "camera",
        intro: [["pip","TBD gre1 intro"]],
        outro: [["rory","TBD gre1 outro"]],
        intel: {"title":"TBD","text":"TBD gre1 intel"} },
      { id: "gre2", title: "The Drill Sample", game: "claw", level: 2, station: "drillship", stationLabel: "The drill barge", icon: "crate",
        intro: [["pip","TBD gre2 intro"]],
        outro: [["rory","TBD gre2 outro"]],
        intel: {"title":"TBD","text":"TBD gre2 intel"} },
      { id: "gre3", title: "Shut It Down", game: "blackout", level: 2, station: "control", stationLabel: "The drill control hut", icon: "keypad",
        intro: [["pip","TBD gre3 intro"]],
        outro: [["rory","TBD gre3 outro"]],
        intel: {"title":"TBD","text":"TBD gre3 intel"} },
      { id: "gre4", title: "Among the Tourists", game: "crowd", level: 2, station: "steps", stationLabel: "The white steps", icon: "camera",
        intro: [["pip","TBD gre4 intro"]],
        outro: [["rory","TBD gre4 outro"]],
        intel: {"title":"TBD","text":"TBD gre4 intel"} },
      { id: "gre5", title: "Caldera Run", game: "run", level: 2, station: "jetski", stationLabel: "Nikos's jet ski", icon: "laser",
        params: {"ride":"jetski","objective":"escape","theme":"caldera","pursuer":"wave","label":"The eruption wave"},
        intro: [["pip","TBD gre5 intro"]],
        outro: [["rory","TBD gre5 outro"]],
        intel: {"title":"TBD","text":"TBD gre5 intel"} },
    ],
    leave: [],
  },
  {
    id: "canada", act: 1, city: "Banff", country: "Canada", flag: "ca", lat: 51.18, lon: -115.57,
    chapter: "The Mountain Train", sky: "snow_day", ambience: "wind", contact: "mac",
    chat: ["TBD canada chat 1", "TBD canada chat 2", "TBD canada chat 3", "TBD canada chat 4", "TBD canada chat 5"],
    arrive: [["mac", "TBD canada arrive"]],
    missions: [
      { id: "can1", title: "The Dining Car", game: "blendin", level: 2, station: "dining", stationLabel: "The dining car", icon: "mask",
        intro: [["pip","TBD can1 intro"]],
        outro: [["rory","TBD can1 outro"]],
        intel: {"title":"TBD","text":"TBD can1 intel"} },
      { id: "can2", title: "Radio Silence", game: "powerlines", level: 2, station: "radio", stationLabel: "The baggage-car radio", icon: "server",
        intro: [["pip","TBD can2 intro"]],
        outro: [["rory","TBD can2 outro"]],
        intel: {"title":"TBD","text":"TBD can2 intel"} },
      { id: "can3", title: "Carriage Windows", game: "whack", level: 2, station: "carriages", stationLabel: "The sleeper carriages", icon: "mask",
        intro: [["pip","TBD can3 intro"]],
        outro: [["rory","TBD can3 outro"]],
        intel: {"title":"TBD","text":"TBD can3 intel"} },
      { id: "can4", title: "Log Jam", game: "floehop", level: 2, station: "river", stationLabel: "The log river", icon: "door",
        intro: [["pip","TBD can4 intro"]],
        outro: [["rory","TBD can4 outro"]],
        intel: {"title":"TBD","text":"TBD can4 intel"} },
      { id: "can5", title: "Off the Rails", game: "run", level: 2, station: "slope", stationLabel: "The ski slope", icon: "laser",
        params: {"ride":"skis","objective":"catch","theme":"slope","quarry":"scorchski","label":"Scorch"},
        intro: [["pip","TBD can5 intro"]],
        outro: [["rory","TBD can5 outro"]],
        intel: {"title":"TBD","text":"TBD can5 intel"} },
    ],
    leave: [],
  },
  // ================================================================ ACT TWO
  {
    id: "dubai", act: 2, city: "Dubai", country: "United Arab Emirates", flag: "ae", lat: 25.2, lon: 55.27,
    chapter: "Follow the Money", sky: "desert_day", ambience: "city", contact: "omar",
    chat: ["TBD dubai chat 1", "TBD dubai chat 2", "TBD dubai chat 3", "TBD dubai chat 4", "TBD dubai chat 5"],
    arrive: [["omar", "TBD dubai arrive"]],
    missions: [
      { id: "dub1", title: "Tower Drop", game: "skydive", level: 2, station: "helipad", stationLabel: "The helipad", icon: "mast",
        intro: [["pip","TBD dub1 intro"]],
        outro: [["rory","TBD dub1 outro"]],
        intel: {"title":"TBD","text":"TBD dub1 intel"} },
      { id: "dub2", title: "High Wire", game: "tightrope", level: 2, station: "cable", stationLabel: "The window-cleaning cable", icon: "mast",
        intro: [["pip","TBD dub2 intro"]],
        outro: [["rory","TBD dub2 outro"]],
        intel: {"title":"TBD","text":"TBD dub2 intel"} },
      { id: "dub3", title: "The Gold Vault", game: "gates", level: 2, station: "vault", stationLabel: "The bank vault", icon: "vault",
        intro: [["pip","TBD dub3 intro"]],
        outro: [["rory","TBD dub3 outro"]],
        intel: {"title":"TBD","text":"TBD dub3 intel"} },
      { id: "dub4", title: "Pack the Evidence", game: "packing", level: 2, station: "souk", stationLabel: "The gold souk", icon: "crate",
        intro: [["pip","TBD dub4 intro"]],
        outro: [["rory","TBD dub4 outro"]],
        intel: {"title":"TBD","text":"TBD dub4 intel"} },
      { id: "dub5", title: "Desert Highway", game: "run", level: 3, station: "garage", stationLabel: "The supercar garage", icon: "laser",
        params: {"ride":"sportscar","objective":"catch","theme":"desert_highway","quarry":"courier","label":"The money courier"},
        intro: [["pip","TBD dub5 intro"]],
        outro: [["rory","TBD dub5 outro"]],
        intel: {"title":"TBD","text":"TBD dub5 intel"} },
    ],
    leave: [],
  },
  {
    id: "chile", act: 2, city: "Atacama", country: "Chile", flag: "cl", lat: -23, lon: -67.75,
    chapter: "Desert Eyes", sky: "desert_dusk", ambience: "wind", contact: "valentina",
    chat: ["TBD chile chat 1", "TBD chile chat 2", "TBD chile chat 3", "TBD chile chat 4", "TBD chile chat 5"],
    arrive: [["valentina", "TBD chile arrive"]],
    missions: [
      { id: "chi1", title: "Ore Carts", game: "railway", level: 2, station: "mine", stationLabel: "The old mine railway", icon: "door",
        intro: [["pip","TBD chi1 intro"]],
        outro: [["rory","TBD chi1 outro"]],
        intel: {"title":"TBD","text":"TBD chi1 intel"} },
      { id: "chi2", title: "Telescope Gears", game: "gears", level: 2, station: "telescope", stationLabel: "The big telescope", icon: "dome",
        intro: [["pip","TBD chi2 intro"]],
        outro: [["rory","TBD chi2 outro"]],
        intel: {"title":"TBD","text":"TBD chi2 intel"} },
      { id: "chi3", title: "Liquid Nitrogen", game: "jugs", level: 2, station: "lab", stationLabel: "The cold lab", icon: "rods",
        intro: [["pip","TBD chi3 intro"]],
        outro: [["rory","TBD chi3 outro"]],
        intel: {"title":"TBD","text":"TBD chi3 intel"} },
      { id: "chi4", title: "Desert Landing", game: "lander", level: 2, station: "pad", stationLabel: "The desert helipad", icon: "mast",
        intro: [["pip","TBD chi4 intro"]],
        outro: [["rory","TBD chi4 outro"]],
        intel: {"title":"TBD","text":"TBD chi4 intel"} },
      { id: "chi5", title: "Dune Escape", game: "run", level: 3, station: "buggy", stationLabel: "The dune buggy", icon: "laser",
        params: {"ride":"buggy","objective":"escape","theme":"dunes","pursuer":"trucks","label":"Kaldera's trucks"},
        intro: [["pip","TBD chi5 intro"]],
        outro: [["rory","TBD chi5 outro"]],
        intel: {"title":"TBD","text":"TBD chi5 intel"} },
    ],
    leave: [],
  },
  {
    id: "indonesia", act: 2, city: "Mount Bromo", country: "Indonesia", flag: "id", lat: -7.94, lon: 112.95,
    chapter: "Fire Mountain", sky: "dawn", ambience: "jungle", contact: "budi",
    chat: ["TBD indonesia chat 1", "TBD indonesia chat 2", "TBD indonesia chat 3", "TBD indonesia chat 4", "TBD indonesia chat 5"],
    arrive: [["budi", "TBD indonesia arrive"]],
    missions: [
      { id: "ind1", title: "Steam Pipes", game: "pipes", level: 2, station: "plant", stationLabel: "The geothermal plant", icon: "furnace",
        intro: [["pip","TBD ind1 intro"]],
        outro: [["rory","TBD ind1 outro"]],
        intel: {"title":"TBD","text":"TBD ind1 intel"} },
      { id: "ind2", title: "The Warehouse", game: "sokoban", level: 2, station: "warehouse", stationLabel: "The crater warehouse", icon: "crate",
        intro: [["pip","TBD ind2 intro"]],
        outro: [["rory","TBD ind2 outro"]],
        intel: {"title":"TBD","text":"TBD ind2 intel"} },
      { id: "ind3", title: "Hot Core", game: "cooling", level: 2, station: "core", stationLabel: "The magma core", icon: "furnace",
        intro: [["pip","TBD ind3 intro"]],
        outro: [["rory","TBD ind3 outro"]],
        intel: {"title":"TBD","text":"TBD ind3 intel"} },
      { id: "ind4", title: "Festival Dance", game: "dance", level: 2, station: "festival", stationLabel: "The village festival", icon: "mask",
        intro: [["pip","TBD ind4 intro"]],
        outro: [["rory","TBD ind4 outro"]],
        intel: {"title":"TBD","text":"TBD ind4 intel"} },
      { id: "ind5", title: "Wingsuit", game: "run", level: 3, station: "ridge", stationLabel: "The crater ridge", icon: "laser",
        params: {"ride":"wingsuit","objective":"catch","theme":"volcano_air","quarry":"scorchwing","label":"Scorch"},
        intro: [["pip","TBD ind5 intro"]],
        outro: [["rory","TBD ind5 outro"]],
        intel: {"title":"TBD","text":"TBD ind5 intel"} },
    ],
    leave: [],
  },
  {
    id: "korea", act: 2, city: "Seoul", country: "South Korea", flag: "kr", lat: 37.57, lon: 126.98,
    chapter: "The Chip", sky: "night_neon", ambience: "city", contact: "minjun",
    chat: ["TBD korea chat 1", "TBD korea chat 2", "TBD korea chat 3", "TBD korea chat 4", "TBD korea chat 5"],
    arrive: [["minjun", "TBD korea arrive"]],
    missions: [
      { id: "kor1", title: "Encore", game: "dance", level: 3, station: "stage", stationLabel: "The concert stage", icon: "mask",
        intro: [["pip","TBD kor1 intro"]],
        outro: [["rory","TBD kor1 outro"]],
        intel: {"title":"TBD","text":"TBD kor1 intel"} },
      { id: "kor2", title: "Chip Factory Lock", game: "gates", level: 3, station: "factory", stationLabel: "The chip factory", icon: "keypad",
        intro: [["pip","TBD kor2 intro"]],
        outro: [["rory","TBD kor2 outro"]],
        intel: {"title":"TBD","text":"TBD kor2 intel"} },
      { id: "kor3", title: "Chip Tray", game: "packing", level: 3, station: "cleanroom", stationLabel: "The clean room", icon: "server",
        intro: [["pip","TBD kor3 intro"]],
        outro: [["rory","TBD kor3 outro"]],
        intel: {"title":"TBD","text":"TBD kor3 intel"} },
      { id: "kor4", title: "Tower Jump", game: "skydive", level: 3, station: "tower", stationLabel: "The TV tower", icon: "mast",
        intro: [["pip","TBD kor4 intro"]],
        outro: [["rory","TBD kor4 outro"]],
        intel: {"title":"TBD","text":"TBD kor4 intel"} },
      { id: "kor5", title: "Neon Streets", game: "run", level: 3, station: "bike", stationLabel: "Min-jun's motorbike", icon: "laser",
        params: {"ride":"motorbike","objective":"catch","theme":"neon","quarry":"courierbike","label":"The chip courier"},
        intro: [["pip","TBD kor5 intro"]],
        outro: [["rory","TBD kor5 outro"]],
        intel: {"title":"TBD","text":"TBD kor5 intel"} },
    ],
    leave: [],
  },
  {
    id: "nepal", act: 2, city: "Khumbu", country: "Nepal", flag: "np", lat: 27.99, lon: 86.83,
    chapter: "The Roof of the World", sky: "high_day", ambience: "wind", contact: "tenzing",
    chat: ["TBD nepal chat 1", "TBD nepal chat 2", "TBD nepal chat 3", "TBD nepal chat 4", "TBD nepal chat 5"],
    arrive: [["tenzing", "TBD nepal arrive"]],
    missions: [
      { id: "nep1", title: "The Rope Bridge", game: "tightrope", level: 3, station: "bridge", stationLabel: "The rope bridge", icon: "mast",
        intro: [["pip","TBD nep1 intro"]],
        outro: [["rory","TBD nep1 outro"]],
        intel: {"title":"TBD","text":"TBD nep1 intel"} },
      { id: "nep2", title: "High Camp", game: "lander", level: 3, station: "helipad", stationLabel: "The high-camp helipad", icon: "mast",
        intro: [["pip","TBD nep2 intro"]],
        outro: [["rory","TBD nep2 outro"]],
        intel: {"title":"TBD","text":"TBD nep2 intel"} },
      { id: "nep3", title: "The Monastery Store", game: "sokoban", level: 3, station: "store", stationLabel: "The monastery storeroom", icon: "crate",
        intro: [["pip","TBD nep3 intro"]],
        outro: [["rory","TBD nep3 outro"]],
        intel: {"title":"TBD","text":"TBD nep3 intel"} },
      { id: "nep4", title: "The Test Engine", game: "cooling", level: 3, station: "engine", stationLabel: "The test engine", icon: "furnace",
        intro: [["pip","TBD nep4 intro"]],
        outro: [["rory","TBD nep4 outro"]],
        intel: {"title":"TBD","text":"TBD nep4 intel"} },
      { id: "nep5", title: "Avalanche!", game: "run", level: 3, station: "summit", stationLabel: "The summit ridge", icon: "laser",
        params: {"ride":"snowboard","objective":"escape","theme":"himalaya","pursuer":"avalanche","label":"The avalanche"},
        intro: [["pip","TBD nep5 intro"]],
        outro: [["rory","TBD nep5 outro"]],
        intel: {"title":"TBD","text":"TBD nep5 intel"} },
    ],
    leave: [],
  },
  {
    id: "southafrica", act: 2, city: "Cape Town", country: "South Africa", flag: "za", lat: -33.92, lon: 18.42,
    chapter: "Ships to the South", sky: "day", ambience: "waves", contact: "thandi",
    chat: ["TBD southafrica chat 1", "TBD southafrica chat 2", "TBD southafrica chat 3", "TBD southafrica chat 4", "TBD southafrica chat 5"],
    arrive: [["thandi", "TBD southafrica arrive"]],
    missions: [
      { id: "saf1", title: "Harbour Railway", game: "railway", level: 3, station: "sidings", stationLabel: "The harbour sidings", icon: "door",
        intro: [["pip","TBD saf1 intro"]],
        outro: [["rory","TBD saf1 outro"]],
        intel: {"title":"TBD","text":"TBD saf1 intel"} },
      { id: "saf2", title: "Ballast Pipes", game: "pipes", level: 3, station: "ship", stationLabel: "The engine ship", icon: "furnace",
        intro: [["pip","TBD saf2 intro"]],
        outro: [["rory","TBD saf2 outro"]],
        intel: {"title":"TBD","text":"TBD saf2 intel"} },
      { id: "saf3", title: "Cable Car", game: "gears", level: 3, station: "cablecar", stationLabel: "The cable-car station", icon: "dome",
        intro: [["pip","TBD saf3 intro"]],
        outro: [["rory","TBD saf3 outro"]],
        intel: {"title":"TBD","text":"TBD saf3 intel"} },
      { id: "saf4", title: "Fuel Tanks", game: "jugs", level: 3, station: "tanks", stationLabel: "The fuel tanks", icon: "rods",
        intro: [["pip","TBD saf4 intro"]],
        outro: [["rory","TBD saf4 outro"]],
        intel: {"title":"TBD","text":"TBD saf4 intel"} },
      { id: "saf5", title: "The Ship", game: "run", level: 3, station: "jetty", stationLabel: "The jetty", icon: "laser",
        params: {"ride":"speedboat","objective":"catch","theme":"harbour","quarry":"ship","label":"The engine ship"},
        intro: [["pip","TBD saf5 intro"]],
        outro: [["rory","TBD saf5 outro"]],
        intel: {"title":"TBD","text":"TBD saf5 intel"} },
    ],
    leave: [],
  },
  // ================================================================ ACT THREE
  {
    id: "newzealand", act: 3, city: "Rotorua", country: "New Zealand", flag: "nz", lat: -38.14, lon: 176.25,
    chapter: "The Last Volcano", sky: "day", ambience: "water", contact: "aroha",
    chat: ["TBD newzealand chat 1", "TBD newzealand chat 2", "TBD newzealand chat 3", "TBD newzealand chat 4", "TBD newzealand chat 5"],
    arrive: [["aroha", "TBD newzealand arrive"]],
    missions: [
      { id: "nzl1", title: "Geothermal Pipes", game: "pipes", level: 4, station: "plant", stationLabel: "The geothermal station", icon: "furnace",
        intro: [["pip","TBD nzl1 intro"]],
        outro: [["rory","TBD nzl1 outro"]],
        intel: {"title":"TBD","text":"TBD nzl1 intel"} },
      { id: "nzl2", title: "Stepping Stones", game: "floehop", level: 3, station: "pools", stationLabel: "The boiling pools", icon: "door",
        intro: [["pip","TBD nzl2 intro"]],
        outro: [["rory","TBD nzl2 outro"]],
        intel: {"title":"TBD","text":"TBD nzl2 intel"} },
      { id: "nzl3", title: "Spot the Spy", game: "crowd", level: 3, station: "village", stationLabel: "The hot-springs village", icon: "camera",
        intro: [["pip","TBD nzl3 intro"]],
        outro: [["rory","TBD nzl3 outro"]],
        intel: {"title":"TBD","text":"TBD nzl3 intel"} },
      { id: "nzl4", title: "White Island", game: "lander", level: 4, station: "helipad", stationLabel: "The helipad", icon: "mast",
        intro: [["pip","TBD nzl4 intro"]],
        outro: [["rory","TBD nzl4 outro"]],
        intel: {"title":"TBD","text":"TBD nzl4 intel"} },
      { id: "nzl5", title: "Jet Boat", game: "run", level: 4, station: "jetboat", stationLabel: "The jet boat", icon: "laser",
        params: {"ride":"jetboat","objective":"catch","theme":"canyon","quarry":"scorchboat","label":"Scorch"},
        intro: [["pip","TBD nzl5 intro"]],
        outro: [["rory","TBD nzl5 outro"]],
        intel: {"title":"TBD","text":"TBD nzl5 intel"} },
    ],
    leave: [],
  },
  {
    id: "argentina", act: 3, city: "Ushuaia", country: "Argentina", flag: "ar", lat: -54.8, lon: -68.3,
    chapter: "The End of the World", sky: "overcast_cold", ambience: "wind", contact: "lucia",
    chat: ["TBD argentina chat 1", "TBD argentina chat 2", "TBD argentina chat 3", "TBD argentina chat 4", "TBD argentina chat 5"],
    arrive: [["lucia", "TBD argentina arrive"]],
    missions: [
      { id: "arg1", title: "End of the World Train", game: "railway", level: 4, station: "train", stationLabel: "The End of the World Train", icon: "door",
        intro: [["pip","TBD arg1 intro"]],
        outro: [["rory","TBD arg1 outro"]],
        intel: {"title":"TBD","text":"TBD arg1 intel"} },
      { id: "arg2", title: "Container Jam", game: "gridlock", level: 3, station: "port", stationLabel: "The container port", icon: "crate",
        intro: [["pip","TBD arg2 intro"]],
        outro: [["rory","TBD arg2 outro"]],
        intel: {"title":"TBD","text":"TBD arg2 intel"} },
      { id: "arg3", title: "On Deck", game: "whack", level: 3, station: "icebreaker", stationLabel: "The icebreaker deck", icon: "mask",
        intro: [["pip","TBD arg3 intro"]],
        outro: [["rory","TBD arg3 outro"]],
        intel: {"title":"TBD","text":"TBD arg3 intel"} },
      { id: "arg4", title: "Polar Kit", game: "packing", level: 4, station: "kit", stationLabel: "The polar kit store", icon: "crate",
        intro: [["pip","TBD arg4 intro"]],
        outro: [["rory","TBD arg4 outro"]],
        intel: {"title":"TBD","text":"TBD arg4 intel"} },
      { id: "arg5", title: "Race to the Port", game: "run", level: 4, station: "jeep", stationLabel: "The jeep", icon: "laser",
        params: {"ride":"jeep","objective":"escape","theme":"patagonia","pursuer":"convoy","label":"Kaldera's convoy"},
        intro: [["pip","TBD arg5 intro"]],
        outro: [["rory","TBD arg5 outro"]],
        intel: {"title":"TBD","text":"TBD arg5 intel"} },
    ],
    leave: [],
  },
  {
    id: "peninsula", act: 3, city: "The Peninsula", country: "Antarctica", flag: "aq", lat: -64.8, lon: -62.9,
    chapter: "Penguins", sky: "polar_day", ambience: "wind", contact: "ellie",
    chat: ["TBD peninsula chat 1", "TBD peninsula chat 2", "TBD peninsula chat 3", "TBD peninsula chat 4", "TBD peninsula chat 5"],
    arrive: [["ellie", "TBD peninsula arrive"]],
    missions: [
      { id: "pen1", title: "Waddle", game: "blendin", level: 3, station: "colony", stationLabel: "The penguin colony", icon: "mask",
        intro: [["pip","TBD pen1 intro"]],
        outro: [["rory","TBD pen1 outro"]],
        intel: {"title":"TBD","text":"TBD pen1 intel"} },
      { id: "pen2", title: "The Pilot", game: "identikit", level: 3, station: "station", stationLabel: "The research station", icon: "camera",
        intro: [["pip","TBD pen2 intro"]],
        outro: [["rory","TBD pen2 outro"]],
        intel: {"title":"TBD","text":"TBD pen2 intel"} },
      { id: "pen3", title: "Crevasse", game: "tightrope", level: 4, station: "crevasse", stationLabel: "The crevasse", icon: "mast",
        intro: [["pip","TBD pen3 intro"]],
        outro: [["rory","TBD pen3 outro"]],
        intel: {"title":"TBD","text":"TBD pen3 intel"} },
      { id: "pen4", title: "Hot Floor", game: "cooling", level: 4, station: "generator", stationLabel: "The station generator", icon: "furnace",
        intro: [["pip","TBD pen4 intro"]],
        outro: [["rory","TBD pen4 outro"]],
        intel: {"title":"TBD","text":"TBD pen4 intel"} },
      { id: "pen5", title: "Across the Ice", game: "run", level: 4, station: "snowmobile", stationLabel: "The snowmobile", icon: "laser",
        params: {"ride":"snowmobile","objective":"catch","theme":"icefield","quarry":"scorchsled","label":"Scorch"},
        intro: [["pip","TBD pen5 intro"]],
        outro: [["rory","TBD pen5 outro"]],
        intel: {"title":"TBD","text":"TBD pen5 intel"} },
    ],
    leave: [],
  },
  {
    id: "iceshelf", act: 3, city: "The Ross Ice Shelf", country: "Antarctica", flag: "aq", lat: -81.5, lon: -175,
    chapter: "The Engines", sky: "blizzard", ambience: "blizzard", contact: "zara",
    chat: ["TBD iceshelf chat 1", "TBD iceshelf chat 2", "TBD iceshelf chat 3", "TBD iceshelf chat 4", "TBD iceshelf chat 5"],
    arrive: [["zara", "TBD iceshelf arrive"]],
    missions: [
      { id: "ice1", title: "Jam the Gearbox", game: "gears", level: 4, station: "engine1", stationLabel: "Inferno Engine One", icon: "furnace",
        intro: [["pip","TBD ice1 intro"]],
        outro: [["rory","TBD ice1 outro"]],
        intel: {"title":"TBD","text":"TBD ice1 intel"} },
      { id: "ice2", title: "The Relay", game: "powerlines", level: 4, station: "relay", stationLabel: "The relay mast", icon: "server",
        intro: [["pip","TBD ice2 intro"]],
        outro: [["rory","TBD ice2 outro"]],
        intel: {"title":"TBD","text":"TBD ice2 intel"} },
      { id: "ice3", title: "Sentry Cameras", game: "pellets", level: 4, station: "sentries", stationLabel: "The sentry towers", icon: "camera",
        intro: [["pip","TBD ice3 intro"]],
        outro: [["rory","TBD ice3 outro"]],
        intel: {"title":"TBD","text":"TBD ice3 intel"} },
      { id: "ice4", title: "Fuel Drums", game: "sokoban", level: 4, station: "depot", stationLabel: "The fuel depot", icon: "crate",
        intro: [["pip","TBD ice4 intro"]],
        outro: [["rory","TBD ice4 outro"]],
        intel: {"title":"TBD","text":"TBD ice4 intel"} },
      { id: "ice5", title: "The Crack", game: "run", level: 4, station: "hovercraft", stationLabel: "Zara's hovercraft", icon: "laser",
        params: {"ride":"hovercraft","objective":"escape","theme":"shelf","pursuer":"crack","label":"The crack"},
        intro: [["pip","TBD ice5 intro"]],
        outro: [["rory","TBD ice5 outro"]],
        intel: {"title":"TBD","text":"TBD ice5 intel"} },
    ],
    leave: [],
  },
  {
    id: "icecaves", act: 3, city: "The Ice Caves", country: "Antarctica", flag: "aq", lat: -78.5, lon: 106.8,
    chapter: "Under the Ice", sky: "cave", ambience: "water", contact: "pip",
    chat: ["TBD icecaves chat 1", "TBD icecaves chat 2", "TBD icecaves chat 3", "TBD icecaves chat 4", "TBD icecaves chat 5"],
    arrive: [["pip", "TBD icecaves arrive"]],
    missions: [
      { id: "cav1", title: "Tunnel Drone", game: "drone", level: 4, station: "tunnel", stationLabel: "The ice tunnel", icon: "screen",
        intro: [["pip","TBD cav1 intro"]],
        outro: [["rory","TBD cav1 outro"]],
        intel: {"title":"TBD","text":"TBD cav1 intel"} },
      { id: "cav2", title: "Frozen Floor", game: "iceslide", level: 4, station: "cavern", stationLabel: "The frozen cavern", icon: "tomb",
        intro: [["pip","TBD cav2 intro"]],
        outro: [["rory","TBD cav2 outro"]],
        intel: {"title":"TBD","text":"TBD cav2 intel"} },
      { id: "cav3", title: "Sub Dock Lock", game: "gates", level: 4, station: "dock", stationLabel: "The submarine dock", icon: "keypad",
        intro: [["pip","TBD cav3 intro"]],
        outro: [["rory","TBD cav3 outro"]],
        intel: {"title":"TBD","text":"TBD cav3 intel"} },
      { id: "cav4", title: "Ballast", game: "jugs", level: 4, station: "minisub", stationLabel: "Pip's mini-sub", icon: "rods",
        intro: [["pip","TBD cav4 intro"]],
        outro: [["rory","TBD cav4 outro"]],
        intel: {"title":"TBD","text":"TBD cav4 intel"} },
      { id: "cav5", title: "Under the Ice", game: "run", level: 4, station: "moonpool", stationLabel: "The moon pool", icon: "laser",
        params: {"ride":"minisub","objective":"catch","theme":"icecave_water","quarry":"baronsub","label":"Kaldera's submarine"},
        intro: [["pip","TBD cav5 intro"]],
        outro: [["rory","TBD cav5 outro"]],
        intel: {"title":"TBD","text":"TBD cav5 intel"} },
    ],
    leave: [],
  },
  {
    id: "erebus", act: 3, city: "Mount Erebus", country: "Antarctica", flag: "aq", lat: -77.53, lon: 167.15,
    chapter: "Meltdown", sky: "volcano_night", ambience: "hum", contact: "bruno",
    chat: ["TBD erebus chat 1", "TBD erebus chat 2", "TBD erebus chat 3", "TBD erebus chat 4", "TBD erebus chat 5"],
    arrive: [["bruno", "TBD erebus arrive"]],
    missions: [
      { id: "ere1", title: "Into the Crater", game: "skydive", level: 4, station: "rim", stationLabel: "The crater rim", icon: "mast",
        intro: [["pip","TBD ere1 intro"]],
        outro: [["rory","TBD ere1 outro"]],
        intel: {"title":"TBD","text":"TBD ere1 intel"} },
      { id: "ere2", title: "Countdown Party", game: "dance", level: 4, station: "hall", stationLabel: "The great hall", icon: "mask",
        intro: [["pip","TBD ere2 intro"]],
        outro: [["rory","TBD ere2 outro"]],
        intel: {"title":"TBD","text":"TBD ere2 intel"} },
      { id: "ere3", title: "The Ignition Key", game: "claw", level: 4, station: "lavapit", stationLabel: "The lava-pit crane", icon: "crate",
        intro: [["pip","TBD ere3 intro"]],
        outro: [["rory","TBD ere3 outro"]],
        intel: {"title":"TBD","text":"TBD ere3 intel"} },
      { id: "ere4", title: "Master Panel", game: "blackout", level: 4, station: "control", stationLabel: "The master control room", icon: "keypad",
        intro: [["pip","TBD ere4 intro"]],
        outro: [["rory","TBD ere4 outro"]],
        intel: {"title":"TBD","text":"TBD ere4 intel"} },
      { id: "ere5", title: "Downhill", game: "run", level: 4, station: "chute", stationLabel: "The ice chute", icon: "laser",
        params: {"ride":"bobsled","objective":"catch","theme":"chute","quarry":"baronsled","label":"Baron Kaldera"},
        intro: [["pip","TBD ere5 intro"]],
        outro: [["rory","TBD ere5 outro"]],
        intel: {"title":"TBD","text":"TBD ere5 intel"} },
    ],
    leave: [],
  },
];

export const ACTS = [
  { n: 1, title: "Thin Ice", coldOpen: true, countries: ["greenland","norway","monaco","spain","greece","canada"],
    after: "TBD after act 1",
    briefing: [["frost", "TBD act 1 briefing"]],
    ending: [["frost", "TBD act 1 ending"]] },
  { n: 2, title: "Heatwave", countries: ["dubai","chile","indonesia","korea","nepal","southafrica"],
    after: "TBD after act 2",
    briefing: [["frost", "TBD act 2 briefing"]],
    ending: [["frost", "TBD act 2 ending"]] },
  { n: 3, title: "Meltdown", countries: ["newzealand","argentina","peninsula","iceshelf","icecaves","erebus"],
    after: "TBD after act 3",
    briefing: [["frost", "TBD act 3 briefing"]],
    ending: [["frost", "TBD act 3 ending"]] },
];
export const BRIEFING = ACTS[0].briefing;
export const ENDING = ACTS[ACTS.length - 1].ending;
export const ACT_WORDS = ["ONE", "TWO", "THREE", "FOUR", "FIVE"];
export const actWord = n => ACT_WORDS[n - 1] || String(n);

export const CREDITS = [
  "AGENT RORY: MELTDOWN",
  "",
  "Starring Rory as Agent R",
  "",
  "Sophia, Rory and Dylan Games, Inc",
];
export const ALL_MISSIONS = COUNTRIES.flatMap(c => c.missions);
export function missionIndex(id) { return ALL_MISSIONS.findIndex(m => m.id === id); }
export function countryOf(mission) { return COUNTRIES.find(c => c.missions.includes(mission)); }
