// Deep Red's clues (clues.js, puzzles.js): the missions that end with a puzzle for Rory
// to crack. p is the kind of puzzle, lv its level (1 is the gentlest), say the lines
// before it, after the line once it's solved. The kinds are Deep Red's own (pressure
// locks, depth gauges, tide charts, fish tallies, pearl necklaces, the depth line, air
// tanks, measuring, porthole shapes), plus the three spy clues every game has (the
// line-up, the coded note, the spy map). Every place has four or five puzzles out of six.
export const THEME = {
  things: ["Drips", "Tide Pearls", "pumps", "crates"],
  boxes: ["crates", "boats", "nets"],
  words: ["SEA", "TIDE", "PEARL", "DRIP", "PUMP", "DEEP"],
  names: ["Max", "Ivy", "Sam", "Nell", "Otto", "Ruby", "Jay", "Mo", "Lena", "Finn"],
  // the code's symbols: a sailor's
  glyphs: [["⚓", "#2a6ad8"], ["〰", "#2ab8c8"], ["◎", "#e03a3a"], ["▲", "#2aa84a"], ["◆", "#9a4ad8"], ["✚", "#ff8a1a"], ["☾", "#d8a020"], ["★", "#d83a8a"], ["●", "#6a8a2a"], ["■", "#8a5a2a"], ["▼", "#4a6a9a"], ["◐", "#d84a2a"]],
  map: { tile: "#2a6a9a", ink: "#ffffff", start: "⚓" },
};

export const CLUES = {
  // ================================================================ ACT ONE
  // ---------------------------------------------------------------- the Sub Pen
  pen2: { p: "sides", lv: 1, title: "SPOT THE PORTHOLE",
    say: [["pip", "Good swimming! A spy has to notice things, too. The training pool has portholes of every shape."], ["pip", "Find the one I ask for, Rory."]] },
  pen4: { p: "suspect", lv: 1, title: "THE TRAINING SPY",
    say: [["pip", "Last test. Somebody here has been sending secrets to the Drips."], ["pip", "Three suspects. Read the clues and pick out the spy."]],
    after: [["frost", "That was me, in a disguise. Well spotted, Agent."]] },
  pen5: { p: "pressure", lv: 1, title: "THE NARWHAL HATCH",
    say: [["frost", "The Narwhal's hatch has a pressure lock. Add up the gauges and it opens."], ["pip", "Every POLARIS agent can do it. Go on, Rory."]] },
  // ---------------------------------------------------------------- Porthcarrow
  cor2: { p: "map", lv: 1, title: "THE SMUGGLERS' MAP",
    say: [["morwenna", "Gran's old smugglers' map! It shows the way through the cave."], ["pip", "Follow the steps, Rory. Where does it lead?"]] },
  cor3: { p: "chart", lv: 1, title: "THE KEEPER'S TIDE CHART",
    say: [["morwenna", "The lighthouse keeper draws a chart of the tide every day. Since the pearls came, it's gone funny."], ["pip", "Read the chart, Rory."]],
    after: [["rory", "The tide's lowest when the lamp flashes. That's the Drips' pump."]] },
  cor5: { p: "cipher", lv: 1, word: "PUMP", title: "THE LABEL",
    say: [["rory", "There's a label on the machine. It's in number code."], ["pip", "A is 1, B is 2. What does it say?"]] },
  // ---------------------------------------------------------------- Bay of Fundy
  fun1: { p: "numberline", lv: 1, who: "The tide", unit: "metres", place: "up the rock", further: "higher", title: "THE TIDE MARKS",
    say: [["emile", "The Flowerpot Rocks have tide marks painted up the side, like a ruler."], ["pip", "Find the right mark on the line, Rory."]] },
  fun3: { p: "sides", lv: 1, thing: "pump", title: "THE PUMP PLAN",
    say: [["emile", "The Drips dropped their pump plan in the mud. Every pump is drawn as a shape!"], ["pip", "Find the shape the plan asks for, Rory."]] },
  fun6: { p: "measure", lv: 1, thing: "weir stone", title: "MEASURE THE STONES",
    say: [["emile", "The weir stones have to be the right length to fit back in the gaps."], ["pip", "Measure them with the ruler, Rory."]] },
  // ---------------------------------------------------------------- Panama Canal
  pan2: { p: "tally", lv: 1, rows: [["Tide Pearls", "#f4f4f0"], ["pumps", "#8ea4c4"], ["crates", "#d8a060"]], title: "THE SHIP'S TALLY",
    say: [["valeria", "The Drips kept a tally of what they hid on the ship. Little lines, in fives."], ["pip", "Count the tally, Rory."]] },
  pan3: { p: "chart", lv: 1, title: "THE VALVE CHART",
    say: [["valeria", "The control desk has a chart of the water in the lake. Look how it's dropping!"], ["pip", "Read the chart, Rory."]] },
  pan6: { p: "map", lv: 1, title: "BOLT'S MAP",
    say: [["bolt", "I can see where the Drips are hiding. I drew a map. It is a good map."], ["pip", "Follow BOLT's steps, Rory."]] },
  // ---------------------------------------------------------------- Galápagos Islands
  gal1: { p: "tally", lv: 1, rows: [["baby turtles", "#3ad06a"], ["iguanas", "#8ea4c4"], ["sea lions", "#d8a060"]], title: "THE TURTLE TALLY",
    say: [["mateo", "The rangers keep a tally of every animal on the beach. Can you read it?"]],
    after: [["mateo", "Every one of them. Safe in the water."]] },
  gal3: { p: "beads", lv: 1, title: "THE SEA LIONS' NECKLACE",
    say: [["mateo", "The sea lions have been playing with a string of Tide Pearls. Some fell off!"], ["pip", "The pearls go in a pattern, Rory. Which one comes next?"]] },
  gal6: { p: "suspect", lv: 1, title: "THE CAPTAIN",
    say: [["mateo", "Three boats were here when the Drips dropped that pump. One of the captains is working for them!"], ["pip", "Read the clues, Rory."]] },
  // ---------------------------------------------------------------- Big Island
  haw1: { p: "numberline", lv: 1, who: "The pearls", unit: "metres", place: "out to sea", further: "further out", title: "THE SURF BUOYS",
    say: [["kai", "The surf buoys are out on a line, with numbers on. The pearls are by one of them."], ["pip", "Find it on the line, Rory."]] },
  haw2: { p: "bonds", lv: 1, title: "FILL THE AIR TANK",
    say: [["kai", "The lava tube is full of smoke. You'll need a full air tank to go in."], ["pip", "How much more to fill it, Rory?"]],
    after: [["kai", "Full tank. Now we can go into the lava tube."]] },
  haw3: { p: "cipher", lv: 2, word: "DRIP", title: "THE MACHINE",
    say: [["rory", "There's writing on the machine. Number code again."], ["pip", "Crack it, Rory."]] },
  haw4: { p: "beads", lv: 2, title: "THE REEF PEARLS",
    say: [["kai", "The turtles found a string of pearls on the reef, with gaps in it."], ["pip", "Which pearl is missing, Rory?"]] },
  // ---------------------------------------------------------------- Great Barrier Reef
  reef1: { p: "pressure", lv: 2, title: "THE DIVE COMPUTER",
    say: [["ruby", "My dive computer's locked! The Drips turned the code into pressure gauges."], ["pip", "Add them up, Rory."]] },
  reef3: { p: "map", lv: 2, title: "THE SONAR MAP",
    say: [["torpedo", "The sonar made a map of the pipe. It is very twisty."], ["pip", "Follow the steps, Rory. Where does it go?"]] },
  reef4: { p: "measure", lv: 2, thing: "boulder", title: "WILL IT FIT?",
    say: [["torpedo", "The boulders must be big enough to block the pipe. Measure them, please."], ["pip", "Use the ruler, Rory."]] },
  reef6: { p: "bonds", lv: 2, title: "TOP UP THE TANK",
    say: [["ruby", "Before we look for the last clownfish, top up your air tank."], ["pip", "How much more to fill it, Rory?"]] },
  // ---------------------------------------------------------------- Hong Kong
  hk1: { p: "depth", lv: 2, water: "The harbour", title: "THE DRYING HARBOUR",
    say: [["ming", "Grandpa measures the harbour every morning. It's getting shallower!"], ["pip", "Work it out, Rory. How deep now?"]] },
  hk2: { p: "chart", lv: 2, title: "THE CAPTAIN'S CHART",
    say: [["rory", "The captain's chart of the tide, every day this week. And a note: pearls go aboard when it's lowest."], ["pip", "Read the chart, Rory."]] },
  hk5: { p: "suspect", lv: 2, title: "THE TOWER LOBBY",
    say: [["ming", "Four people in the tower lobby. One of them let the Drip up onto the roof!"], ["pip", "Read the clues, Rory."]] },
  // ---------------------------------------------------------------- The Maldives
  mal1: { p: "depth", lv: 2, water: "The lagoon", title: "THE LAGOON GAUGE",
    say: [["aisha", "The lagoon gauge. It's dropping so fast! The new sandbanks are the sea floor showing."], ["pip", "How deep is it now, Rory?"]] },
  mal3: { p: "tally", lv: 2, rows: [["mantas", "#7fb8ff"], ["turtles", "#3ad06a"], ["reef sharks", "#8ea4c4"]], title: "THE MANTA COUNT",
    say: [["aisha", "The divers keep a tally of the mantas at the cleaning station. Fewer and fewer come."], ["pip", "Count the tally, Rory."]] },
  mal4: { p: "bonds", lv: 2, tank: "fuel tank", title: "THE SEAPLANE'S TANK",
    say: [["aisha", "The Drips' seaplane is fuelling up by the villas! Its tank gauge is right here."], ["pip", "How much more till it's full, Rory? That's how long we've got."]],
    after: [["aisha", "Then we can still catch it!"]] },
  // ---------------------------------------------------------------- The Bermuda Triangle
  ber1: { p: "pressure", lv: 2, title: "THE MAIN HATCH",
    say: [["nia", "The main hatch has a pressure lock. Undertow loves her locks."], ["pip", "Add up the gauges, Rory. Quickly!"]] },
  ber2: { p: "cipher", lv: 2, word: "UNDER", title: "THE CONTROL PANEL",
    say: [["rory", "There's a message on the control panel. Number code."], ["pip", "Crack it, Rory!"]] },
  ber4: { p: "numberline", lv: 2, title: "THE MARKERS BELOW",
    say: [["torpedo", "The markers are on a line going down under the base. Each one is a depth."], ["pip", "Find the right one, Rory."]] },

  // ================================================================ ACT TWO
  // ---------------------------------------------------------------- The Sunlight Zone
  sun1: { p: "sides", lv: 2, thing: "shape", title: "THE SUIT'S SCANNER",
    say: [["lani", "The suit's scanner draws round everything on the wreck. Find the shape it's looking for, Rory."]] },
  sun3: { p: "measure", lv: 2, thing: "pipe section", title: "MEASURE THE PIPE",
    say: [["lani", "The Drips were laying pipe along the sea bed. Measure a section, and we'll know how far it goes."]] },
  sun5: { p: "suspect", lv: 2, title: "THE MOLE",
    say: [["rory", "Photos of Undertow's crew. And one of them still works at POLARIS!"], ["pip", "Read the clues, Rory. Who's the spy?"]],
    after: [["frost", "I'll have them picked up at once. Good work, Agent."]] },
  sun6: { p: "map", lv: 2, title: "THE DRIP SUB'S TRAIL",
    say: [["torpedo", "I have made a map of the Drip sub's trail."], ["pip", "Follow the steps, Rory."]] },
  // ---------------------------------------------------------------- The Kelp Forest
  kel1: { p: "numberline", lv: 2, who: "The pearls", unit: "metres", place: "down", further: "deeper", title: "THE KELP POSTS",
    say: [["rosa", "The kelp posts are on a line, with the depths marked. The pearls are at one of them."], ["pip", "Find it, Rory."]] },
  kel2: { p: "depth", lv: 2, who: "TORPEDO", title: "LIFTING THE NETS",
    say: [["torpedo", "I lifted the nets up from the sea bed. Work out how deep I am now, please. My gauge is shy."]],
    after: [["rosa", "Every net gone! Thank you, TORPEDO."]] },
  kel3: { p: "cipher", lv: 2, word: "LINER", title: "THE DROPPED NOTE",
    say: [["torpedo", "The Drip sub dropped a note! It is in number code."], ["pip", "Crack it, Rory."]] },
  kel6: { p: "chart", lv: 2, what: "otter pups", title: "ROSA'S PUP CHART",
    say: [["rosa", "I chart how many otter pups I see every day. Can you read it?"]] },
  // ---------------------------------------------------------------- The Sunken Liner
  lin2: { p: "pressure", lv: 2, title: "THE STAIRCASE GATE",
    say: [["barnaby", "The grand staircase has an old pressure gate. The gauges still work."], ["pip", "Add them up, Rory."]] },
  lin3: { p: "suspect", lv: 3, title: "THE BALLROOM PHOTO",
    say: [["barnaby", "An old photo from the ballroom. Five passengers, and one of them was a spy, even back then!"], ["pip", "Read the clues, Rory. Some of them say NOT."]] },
  lin5: { p: "beads", lv: 3, title: "THE CAPTAIN'S SAFE",
    say: [["barnaby", "The captain's safe has a pearl lock. The pearls go in a pattern, and some are missing."], ["pip", "Which pearl goes in the gap, Rory?"]] },
  // ---------------------------------------------------------------- The Twilight Zone
  twi1: { p: "numberline", lv: 3, who: "The Drip sub", unit: "metres", place: "down", further: "deeper", title: "THE PIPE'S DEPTH MARKS",
    say: [["hiro", "The pipe has depth marks on it, all the way down. Find the one I say."]] },
  twi2: { p: "sides", lv: 3, thing: "glowing shape", title: "HAPPY LANTERNFISH",
    say: [["hiro", "Lanternfish glow in shapes when they're happy. Which shape is it, Rory?"]] },
  twi3: { p: "depth", lv: 3, title: "THE DEPTH GAUGE",
    say: [["hiro", "Check the depth gauge. Work out how deep we are now."], ["pip", "Take away, Rory."]] },
  // ---------------------------------------------------------------- The Midnight Zone
  mid1: { p: "depth", lv: 3, who: "Glim", title: "GLIM'S DEPTH",
    say: [["glim", "I keep track of how deep I am. But I got confused in all the lights. Work it out for me?"]] },
  mid3: { p: "chart", lv: 3, what: "Drips", title: "GLIM'S CHART",
    say: [["glim", "I chart every Drip I see down here. Read it for me!"]] },
  mid6: { p: "bonds", lv: 3, tank: "battery", title: "CHARGE GLIM UP",
    say: [["torpedo", "Glim's battery is nearly flat. How much more to fill it up, Rory?"]] },
  // ---------------------------------------------------------------- The Hydrothermal Vents
  ven1: { p: "chart", lv: 3, what: "pearls on the chimneys", title: "THE CHIMNEY CHART",
    say: [["ama", "My chart of the pearls I find on the chimneys every day. Read it, Rory."]] },
  ven2: { p: "map", lv: 3, title: "THE WORM FOREST MAP",
    say: [["ama", "Here's my map of the worm forest. The lab is at the end of the steps."], ["pip", "Follow the steps, Rory."]] },
  ven5: { p: "tally", lv: 3, rows: [["tube worms", "#ff6a6a"], ["crabs", "#ff8a1a"], ["shrimps", "#ff8ac8"]], title: "THE SENSOR TALLY",
    say: [["ama", "Each sensor keeps a tally of what swims past. Read them, Rory."]] },
  // ---------------------------------------------------------------- The Glass Station
  gla2: { p: "suspect", lv: 3, title: "WHO'S THE SPY?",
    say: [["pip", "One of the scientists up here is on our side. But one of these is Undertow's spy!"], ["pip", "Read the clues, Rory, and keep away from the spy."]] },
  gla5: { p: "pressure", lv: 3, title: "THE MOON POOL DOOR",
    say: [["silt", "The moon pool door! It's a pressure lock. Quickly, Rory!"]] },
  // ---------------------------------------------------------------- The Mariana Trench
  mar4: { p: "cipher", lv: 3, word: "SPACE", title: "UNDERTOW'S LOGBOOK",
    say: [["rory", "Her logbook's written in symbol code!"], ["silt", "She always did love a code. Use the key, Rory."]] },
  mar5: { p: "depth", lv: 3, who: "Silt's probe", title: "THE TRENCH FLOOR",
    say: [["silt", "The markers show how deep the Engine sits. Work out the depth, Rory."]] },
  // ---------------------------------------------------------------- The Tidal Engine
  eng2: { p: "tally", lv: 3, rows: [["Drip divers", "#7fe3ff"], ["Drip subs", "#ffd166"], ["Drip guards", "#ff8ac8"]], title: "THE DRIP ARMY",
    say: [["glim", "I kept a tally of the whole army! Help me read it for the report."]] },
  eng5: { p: "map", lv: 3, title: "THE LIFT SHAFT MAP",
    say: [["torpedo", "The pod is heading for the elevator. I have mapped the way."], ["pip", "Follow the steps, Rory. Where does it come out?"]] },
  eng6: { p: "numberline", lv: 3, who: "Undertow's pod", unit: "metres", place: "up the shaft", further: "higher", title: "UP THE SHAFT",
    say: [["silt", "The shaft has depth marks all the way up. Find where she is, Rory."]] },
  // ---------------------------------------------------------------- the Ice Trench
  ice1: { p: "bonds", lv: 4, title: "BREATHE UNDER THE ICE",
    say: [["nuka", "There's no surface here, only ice. Fill your tank at the air hole before we go on."]] },
  ice2: { p: "pressure", lv: 4, title: "THE CONTROL ROOM DOOR",
    say: [["silt", "The control room door has a pressure lock. Three sets of gauges."], ["pip", "Add them up, Rory."]] },
  ice6: { p: "measure", lv: 4, thing: "narwhal tusk", title: "THE NARWHAL'S TUSK",
    say: [["nuka", "The biggest narwhal wants you to measure his tusk. He's very proud of it."]],
    after: [["nuka", "He's singing! I think he's pleased."]] },

  // ================================================================ ACT THREE
  // ---------------------------------------------------------------- The Sea-Launch Platform
  lau1: { p: "pressure", lv: 3, title: "FUEL PRESSURE",
    say: [["vega", "Last pre-flight check: the fuel pressure. Add up the gauges, Agent."]] },
  lau3: { p: "measure", lv: 3, thing: "crate", title: "WILL IT FIT THE POD?",
    say: [["vega", "The supply crates have to fit in the pod. Measure them, Agent."]] },
  lau4: { p: "suspect", lv: 3, title: "THE RIG CREW",
    say: [["vega", "One of the rig crew let the Drips on board. Five people were on shift."], ["pip", "Read the clues, Rory. Some of them say NOT."]] },
  // ---------------------------------------------------------------- The Space Elevator
  ele1: { p: "numberline", lv: 3, who: "The climber", unit: "kilometres", place: "up", further: "higher", title: "THE CLIMBER'S HEIGHT",
    say: [["otis", "The control room shows the climber on a line, going up. Where is it now?"]] },
  ele2: { p: "bonds", lv: 3, tank: "battery", title: "THE CLIMBER'S BATTERY",
    say: [["otis", "The climber can't go up with a half-empty battery. How much more to fill it?"]] },
  ele4: { p: "sides", lv: 3, thing: "hatch", title: "THE TOWER HATCHES",
    say: [["otis", "Every hatch on the maintenance tower is a different shape. The power cells are behind one."]] },
  // ---------------------------------------------------------------- The Orbital Dock
  doc1: { p: "pressure", lv: 4, title: "THE AIRLOCK CODE",
    say: [["juno", "The airlock needs the pressure right to let you back in. Three sets of gauges!"]] },
  doc2: { p: "tally", lv: 3, rows: [["crates", "#d8a060"], ["fuel pods", "#7fe3ff"], ["ice bricks", "#cfe8ff"]], title: "THE CARGO TALLY",
    say: [["juno", "Let's check the cargo tally. Read it for me, Agent."]] },
  doc6: { p: "chart", lv: 3, what: "cargo pods", title: "THE DOCK CHART",
    say: [["juno", "The dock's chart shows her ship's cargo, day by day. Read it before you sneak aboard."]] },
  // ---------------------------------------------------------------- Phobos
  pho1: { p: "numberline", lv: 4, who: "The boulder", unit: "metres", place: "along the crater", further: "further", title: "THE BOULDER LINE",
    say: [["tycho", "The boulders are on a numbered line across the crater. Find the one I say."]] },
  pho3: { p: "chart", lv: 4, what: "bots home", title: "TYCHO'S BOT CHART",
    say: [["tycho", "I chart how many bots come home each day. Read it, Agent."]] },
  pho6: { p: "measure", lv: 4, thing: "ice brick", title: "MEASURE THE BRICK",
    say: [["tycho", "How big are her ice bricks? Measure one, Agent."]] },
  // ---------------------------------------------------------------- Jezero Crater
  jez1: { p: "map", lv: 3, title: "THE ROVER MAP",
    say: [["amani", "Here's the rover map. Undertow's ship landed somewhere in this crater."], ["pip", "Follow the steps, Rory."]] },
  jez3: { p: "tally", lv: 4, rows: [["red rocks", "#ff6a6a"], ["grey rocks", "#8ea4c4"], ["ice samples", "#cfe8ff"]], title: "THE SAMPLE TALLY",
    say: [["amani", "I keep a tally of every rock sample from the delta. Read it for me, Agent."]] },
  jez5: { p: "bonds", lv: 4, tank: "rover battery", title: "CHARGE THE ROVERS",
    say: [["amani", "My little rovers ran their batteries down chasing her ship. How much more to fill one up?"]] },
  // ---------------------------------------------------------------- Valles Marineris
  val2: { p: "sides", lv: 4, thing: "valve handle", title: "THE VALVE HANDLES",
    say: [["lucia", "Every valve has a different shaped handle. The real one is on my list."]] },
  val5: { p: "map", lv: 4, title: "THE CANYON MAP",
    say: [["lucia", "The helicopter's camera made a map of the canyon."], ["pip", "Start at the square it says, Rory. Where's the pump station?"]] },
  val6: { p: "cipher", lv: 4, word: "NORTH", title: "HER PLANS",
    say: [["rory", "Her plans! In symbol code again."], ["pip", "Use the key, Rory."]] },
  // ---------------------------------------------------------------- The Dust Storm
  sto2: { p: "numberline", lv: 4, who: "The next beacon", unit: "metres", place: "along the path", further: "further", title: "THE PATH BEACONS",
    say: [["sol", "The beacons are on a line, all the way to the station. Find the one I say."]] },
  sto3: { p: "chart", lv: 4, what: "Drips caught", title: "THE STORM CHART",
    say: [["sol", "My chart of the Drips we've caught each day of the storm. Read it, Rory."]] },
  sto4: { p: "bonds", lv: 4, title: "THE SHELTER'S AIR",
    say: [["sol", "The shelter has its own air tank. How much more to fill it before the storm hits?"]] },
  // ---------------------------------------------------------------- Olympus Mons
  oly1: { p: "measure", lv: 4, thing: "climbing rope", title: "THE CLIMBING ROPE",
    say: [["hana", "Measure the climbing rope. We need to know it'll reach."]] },
  oly2: { p: "suspect", lv: 4, title: "THE CLIMBERS' PHOTO",
    say: [["hana", "Six people in the climbers' photo, and one of them is Undertow's lookout."], ["pip", "Read the clues, Rory. Watch out for NOT."]] },
  oly4: { p: "tally", lv: 4, rows: [["big rocks", "#d8a060"], ["small rocks", "#8ea4c4"], ["pebbles", "#cfe8ff"]], title: "THE ROCK TALLY",
    say: [["hana", "I keep a tally of the rocks that fall. Read it for me, Agent."]] },
  // ---------------------------------------------------------------- The Polar Cap
  pol1: { p: "sides", lv: 4, thing: "tower top", title: "THE TOWER TOPS",
    say: [["silt", "Each ice-brick tower has a shaped top. The trackers are on the one she's melting."]] },
  pol3: { p: "pressure", lv: 4, title: "THE MELT SWITCH",
    say: [["silt", "The melt switch has a pressure lock. Three sets of gauges, Rory."]] },
  pol5: { p: "measure", lv: 4, thing: "crack", title: "MEASURE THE CRACK",
    say: [["silt", "How wide is the crack? Measure it, Rory, so the bridge is long enough."]] },
  // ---------------------------------------------------------------- Undertow's Dome
  dom2: { p: "beads", lv: 4, title: "THE STOLEN SEAS",
    say: [["pip", "She strung the pearls from every sea into a necklace. They go in a pattern, with gaps."], ["pip", "Which pearl goes in the gap, Rory?"]] },
  dom3: { p: "map", lv: 4, title: "THE DOME SEA MAP",
    say: [["torpedo", "I have a map of the dome sea. The Engine is at the end of it."], ["pip", "Start at the square it says, Rory."]] },
  dom6: { p: "cipher", lv: 4, word: "HOME", title: "THE GATE CODE",
    say: [["undertow", "All right. The gate code is in my own symbols. Here is the key."], ["pip", "Last code, Rory. Open the gates and send the sea home."]] },
};
