// Deep Red's clues (clues.js): the missions that end with a puzzle for Rory to crack.
// p is the kind of puzzle, lv its level (1 is the gentlest), say the lines before it,
// after the line once it's solved. Every place has four or five puzzles out of six.
export const THEME = {
  things: ["Drips", "Tide Pearls", "pumps", "crates"],
  boxes: ["crates", "boats", "nets"],
  words: ["SEA", "TIDE", "PEARL", "DRIP", "PUMP", "DEEP"],
  names: ["Max", "Ivy", "Sam", "Nell", "Otto", "Ruby", "Jay", "Mo", "Lena", "Finn"],
};

export const CLUES = {
  // ================================================================ ACT ONE
  // ---------------------------------------------------------------- the Sub Pen
  pen2: { p: "count", lv: 1, title: "EYES OPEN",
    say: [["pip", "Good swimming! A spy has to notice things, too. Here's a picture of the pool floor."], ["pip", "Count the ones it asks for, Rory."]] },
  pen4: { p: "suspect", lv: 1, title: "THE TRAINING SPY",
    say: [["pip", "Last test. Somebody here has been sending secrets to the Drips."], ["pip", "Three suspects. Read the clues and pick out the spy."]],
    after: [["frost", "That was me, in a disguise. Well spotted, Agent."]] },
  pen5: { p: "sum", lv: 1, title: "THE NARWHAL HATCH",
    say: [["frost", "The Narwhal's hatch has a sum lock. Every POLARIS agent can open it."], ["pip", "Add them up, Rory."]] },
  // ---------------------------------------------------------------- Porthcarrow
  cor2: { p: "map", lv: 1, title: "THE SMUGGLERS' MAP",
    say: [["morwenna", "Gran's old smugglers' map! It shows the way through the cave."], ["pip", "Follow the steps, Rory. Where does it lead?"]] },
  cor3: { p: "clock", lv: 1, title: "THE KEEPER'S LOG",
    say: [["morwenna", "The lighthouse keeper writes down when the lamp goes funny. It's the same time every night."], ["pip", "Which clock says it, Rory?"]],
    after: [["rory", "That's when the Drips switch their pump on."]] },
  cor5: { p: "cipher", lv: 1, word: "PUMP", title: "THE LABEL",
    say: [["rory", "There's a label on the machine. It's in number code."], ["pip", "A is 1, B is 2. What does it say?"]] },
  // ---------------------------------------------------------------- Bay of Fundy
  fun1: { p: "scale", lv: 1, title: "THE FISH SCALE",
    say: [["emile", "These pearls are heavy! My dad's fish scale can weigh them."], ["pip", "Work out what the box weighs, Rory."]] },
  fun3: { p: "count", lv: 1, title: "THE PUMP PLAN",
    say: [["emile", "The Drips dropped their pump plan in the mud. It's all shapes!"], ["pip", "Count the ones it asks for, and we'll know how many pumps they planted."]] },
  fun6: { p: "order", lv: 1, title: "THE WEIR STONES",
    say: [["emile", "The weir stones are numbered. They have to go back in order."], ["pip", "Smallest first, Rory."]] },
  // ---------------------------------------------------------------- Panama Canal
  pan2: { p: "times", lv: 1, title: "THE SHIP'S LIST",
    say: [["valeria", "Every container on the ship holds the same number of pearls. The ship's list has the sums."], ["pip", "Times tables, Rory. How many pearls altogether?"]] },
  pan3: { p: "clock", lv: 1, title: "THE VALVE LOG",
    say: [["valeria", "The desk writes down when the valves open. Always at the same time."], ["pip", "Which clock is it, Rory?"]] },
  pan6: { p: "map", lv: 1, title: "BOLT'S MAP",
    say: [["bolt", "I can see where the Drips are hiding. I drew a map. It is a good map."], ["pip", "Follow BOLT's steps, Rory."]] },
  // ---------------------------------------------------------------- Galápagos Islands
  gal1: { p: "story", lv: 1, things: "baby turtles", boxes: "nests", title: "THE RANGER'S COUNT",
    say: [["mateo", "The rangers need to know how many baby turtles reached the sea. Can you work it out?"]],
    after: [["mateo", "Every one of them. Safe in the water."]] },
  gal3: { p: "minus", lv: 1, title: "THE MISSING PEARLS",
    say: [["mateo", "The sea lions had lots of pearls. Some of them are still missing."], ["pip", "Take away, Rory. How many are still out there?"]] },
  gal6: { p: "suspect", lv: 1, title: "THE CAPTAIN",
    say: [["mateo", "Three boats were here when the Drips dropped that pump. One of the captains is working for them!"], ["pip", "Read the clues, Rory."]] },
  // ---------------------------------------------------------------- Big Island
  haw1: { p: "next", lv: 1, title: "THE SURF BUOYS",
    say: [["kai", "The surf buoys are numbered in a pattern. The Drips took some away!"], ["pip", "What comes next, Rory?"]] },
  haw2: { p: "coins", lv: 1, title: "THE HEAT GLOVES",
    say: [["kai", "The ranger will lend us heat gloves for the lava tube. But there's a fee."], ["pip", "Pay exactly, Rory."]],
    after: [["kai", "Gloves! Now we can go into the lava tube."]] },
  haw3: { p: "cipher", lv: 2, word: "DRIP", title: "THE MACHINE",
    say: [["rory", "There's writing on the machine. Number code again."], ["pip", "Crack it, Rory."]] },
  haw4: { p: "count", lv: 2, title: "THE REEF CHART",
    say: [["kai", "My reef chart marks everything the Drips left behind."], ["pip", "Count the ones it asks for, Rory."]] },
  // ---------------------------------------------------------------- Great Barrier Reef
  reef1: { p: "sum", lv: 2, title: "THE DIVE COMPUTER",
    say: [["ruby", "My dive computer's locked! The Drips changed the code into sums."], ["pip", "Add them up, Rory."]] },
  reef3: { p: "map", lv: 2, title: "THE SONAR MAP",
    say: [["torpedo", "The sonar made a map of the pipe. It is very twisty."], ["pip", "Follow the steps, Rory. Where does it go?"]] },
  reef4: { p: "scale", lv: 2, title: "THE BOULDERS",
    say: [["torpedo", "The boulders must be heavy enough to block the pipe. My claw has a scale!"], ["pip", "Work out what the box weighs, Rory."]] },
  reef6: { p: "story", lv: 2, things: "clownfish", boxes: "anemones", title: "THE CLOWNFISH COUNT",
    say: [["ruby", "Let's make sure every clownfish is home. Help me work it out."]] },
  // ---------------------------------------------------------------- Hong Kong
  hk1: { p: "coins", lv: 2, title: "THE HARBOUR MAP",
    say: [["ming", "Grandpa's friend sells harbour maps. We need one to find the ship."], ["pip", "Pay exactly, Rory."]] },
  hk2: { p: "order", lv: 2, title: "THE CAPTAIN'S BOX",
    say: [["rory", "The captain's log is in a box with a number lock."], ["pip", "Put the numbers in order, Rory."]] },
  hk5: { p: "suspect", lv: 2, title: "THE TOWER LOBBY",
    say: [["ming", "Four people in the tower lobby. One of them let the Drip up onto the roof!"], ["pip", "Read the clues, Rory."]] },
  // ---------------------------------------------------------------- The Maldives
  mal1: { p: "map", lv: 2, title: "THE NEW SANDBANKS",
    say: [["aisha", "The sandbanks are new, so they aren't on any map. I drew one."], ["pip", "Follow the steps to the biggest pump, Rory."]] },
  mal3: { p: "times", lv: 2, title: "THE PUMP'S SUMS",
    say: [["aisha", "The pump fills the same number of pearls every hour. The sums are on its side."], ["pip", "Times tables, Rory. How many has it taken?"]] },
  mal4: { p: "clock", lv: 2, title: "THE SEAPLANE",
    say: [["aisha", "The Drips' TV guide! Their seaplane leaves straight after the programme."], ["pip", "Which clock says the time, Rory?"]],
    after: [["aisha", "Then we can still catch it!"]] },
  // ---------------------------------------------------------------- The Bermuda Triangle
  ber1: { p: "sum", lv: 2, title: "THE MAIN HATCH",
    say: [["nia", "The main hatch has a sum lock. Undertow loves her locks."], ["pip", "Add them up, Rory. Quickly!"]] },
  ber2: { p: "cipher", lv: 2, word: "UNDER", title: "THE CONTROL PANEL",
    say: [["rory", "There's a message on the control panel. Number code."], ["pip", "Crack it, Rory!"]] },
  ber4: { p: "next", lv: 2, title: "THE MARKER NUMBERS",
    say: [["torpedo", "The markers pinged back numbers. They make a pattern!"], ["pip", "What comes next, Rory?"]] },

  // ================================================================ ACT TWO
  // ---------------------------------------------------------------- The Sunlight Zone
  sun1: { p: "count", lv: 2, title: "THE SUIT SCREEN",
    say: [["lani", "The suit's screen shows everything on the wreck. Count the ones it asks for, Rory."]] },
  sun3: { p: "story", lv: 2, things: "pipe sections", boxes: "sleds", title: "THE PIPE REPORT",
    say: [["lani", "The Drips were laying pipe along the sea bed. How much? Work it out, Rory."]] },
  sun5: { p: "suspect", lv: 2, title: "THE MOLE",
    say: [["rory", "Photos of Undertow's crew. And one of them still works at POLARIS!"], ["pip", "Read the clues, Rory. Who's the spy?"]],
    after: [["frost", "I'll have them picked up at once. Good work, Agent."]] },
  sun6: { p: "map", lv: 2, title: "THE DRIP SUB'S TRAIL",
    say: [["torpedo", "I have made a map of the Drip sub's trail."], ["pip", "Follow the steps, Rory."]] },
  // ---------------------------------------------------------------- The Kelp Forest
  kel1: { p: "next", lv: 2, title: "THE KELP POSTS",
    say: [["rosa", "The kelp posts are numbered in a pattern. Some of them have washed away."], ["pip", "What comes next, Rory?"]] },
  kel2: { p: "times", lv: 2, title: "THE OTTER NETS",
    say: [["rosa", "Every net had the same number of otters caught in it. How many did TORPEDO save?"], ["pip", "Times tables, Rory."]] },
  kel3: { p: "cipher", lv: 2, word: "LINER", title: "THE DROPPED NOTE",
    say: [["torpedo", "The Drip sub dropped a note! It is in number code."], ["pip", "Crack it, Rory."]] },
  kel6: { p: "clock", lv: 2, title: "OTTER TIME",
    say: [["rosa", "The otter mums always come back at the same time. It's on my chart."], ["pip", "Which clock is it, Rory?"]] },
  // ---------------------------------------------------------------- The Sunken Liner
  lin2: { p: "sum", lv: 2, title: "THE STAIRCASE GATE",
    say: [["barnaby", "The grand staircase has a locked gate. The code is a sum."], ["pip", "Add them up, Rory."]] },
  lin3: { p: "suspect", lv: 3, title: "THE BALLROOM PHOTO",
    say: [["barnaby", "An old photo from the ballroom. Five passengers, and one of them was a spy, even back then!"], ["pip", "Read the clues, Rory. Some of them say NOT."]] },
  lin5: { p: "order", lv: 3, title: "THE CAPTAIN'S SAFE",
    say: [["barnaby", "The captain's safe! It still has its old number lock."], ["pip", "Put the numbers in order, Rory."]] },
  // ---------------------------------------------------------------- The Twilight Zone
  twi1: { p: "next", lv: 3, title: "THE PIPE PLATES",
    say: [["hiro", "The pipe has number plates on it, in a pattern."], ["pip", "What comes next, Rory?"]] },
  twi2: { p: "count", lv: 2, title: "HAPPY LANTERNFISH",
    say: [["hiro", "Lanternfish glow in shapes when they're happy. Count the ones it asks for!"]] },
  twi3: { p: "minus", lv: 3, title: "THE DEPTH GAUGE",
    say: [["hiro", "Check my depth gauge. Work out how far we've come down."], ["pip", "Take away, Rory."]] },
  // ---------------------------------------------------------------- The Midnight Zone
  mid1: { p: "count", lv: 3, title: "GLIM'S RECORDS",
    say: [["glim", "I record everything that glows. Can you count the ones on my screen?"]] },
  mid3: { p: "story", lv: 3, things: "Drips", boxes: "teams", title: "GLIM'S REPORT",
    say: [["glim", "I have to report how many Drips we bubbled. Help me work it out!"]] },
  mid6: { p: "scale", lv: 3, title: "THE BATTERY PACKS",
    say: [["torpedo", "To charge Glim, the battery packs must balance."], ["pip", "Work out what one box weighs, Rory."]] },
  // ---------------------------------------------------------------- The Hydrothermal Vents
  ven1: { p: "next", lv: 3, title: "THE CHIMNEY SENSOR",
    say: [["ama", "The chimney temperatures go up in a pattern. My sensor lost the last one."], ["pip", "What comes next, Rory?"]] },
  ven2: { p: "map", lv: 3, title: "THE WORM FOREST MAP",
    say: [["ama", "Here's my map of the worm forest. The lab is at the end of the steps."], ["pip", "Follow the steps, Rory."]] },
  ven5: { p: "times", lv: 3, title: "THE LOST READINGS",
    say: [["ama", "Each sensor takes the same number of readings. Work out how many we lost."], ["pip", "Times tables, Rory."]] },
  // ---------------------------------------------------------------- The Glass Station
  gla2: { p: "suspect", lv: 3, title: "WHO'S THE SPY?",
    say: [["pip", "One of the scientists up here is on our side. But one of these is Undertow's spy!"], ["pip", "Read the clues, Rory, and keep away from the spy."]] },
  gla5: { p: "sum", lv: 3, title: "THE MOON POOL DOOR",
    say: [["silt", "The moon pool door! It's a sum lock. Quickly, Rory!"]] },
  // ---------------------------------------------------------------- The Mariana Trench
  mar4: { p: "cipher", lv: 3, word: "SPACE", title: "UNDERTOW'S LOGBOOK",
    say: [["rory", "Her logbook's written in symbol code!"], ["silt", "She always did love a code. Use the key, Rory."]] },
  mar5: { p: "clock", lv: 3, title: "PUMPING TIME",
    say: [["silt", "The Engine pumps at the same time every day. The markers show it."], ["pip", "Which clock is it, Rory?"]] },
  // ---------------------------------------------------------------- The Tidal Engine
  eng2: { p: "story", lv: 3, things: "Drips", boxes: "squads", title: "THE DRIP ARMY",
    say: [["glim", "That was the whole army! How many Drips? Work it out for the report."]] },
  eng5: { p: "map", lv: 3, title: "THE LIFT SHAFT MAP",
    say: [["torpedo", "The pod is heading for the elevator. I have mapped the way."], ["pip", "Follow the steps, Rory. Where does it come out?"]] },
  eng6: { p: "next", lv: 3, title: "THE FLOOR NUMBERS",
    say: [["silt", "The floors of the shaft are numbered in a pattern. Some are missing."], ["pip", "What comes next, Rory?"]] },

  // ================================================================ ACT THREE
  // ---------------------------------------------------------------- The Sea-Launch Platform
  lau1: { p: "times", lv: 3, title: "THE LAST CHECK",
    say: [["vega", "Last pre-flight check. Times tables, Agent. We don't launch until they're all right."]] },
  lau3: { p: "story", lv: 3, things: "spare socks", boxes: "crates", title: "THE SUPPLY LIST",
    say: [["vega", "We need to check the supply list. Can you work it out?"]] },
  lau4: { p: "suspect", lv: 3, title: "THE RIG CREW",
    say: [["vega", "One of the rig crew let the Drips on board. Five people were on shift."], ["pip", "Read the clues, Rory. Some of them say NOT."]] },
  // ---------------------------------------------------------------- The Space Elevator
  ele1: { p: "order", lv: 3, title: "THE CONTROL ROOM",
    say: [["otis", "The control room has a number lock. Undertow set it herself."], ["pip", "Put them in order, Rory."]] },
  ele2: { p: "coins", lv: 3, title: "A TICKET UP",
    say: [["otis", "The climber needs a ticket. Even for spies. Rules are rules."], ["pip", "Pay exactly, Rory."]] },
  ele4: { p: "scale", lv: 3, title: "THE CLIMBER'S LOAD",
    say: [["otis", "The climber's load has to balance before it can go up."], ["pip", "Work out what one box weighs, Rory."]] },
  // ---------------------------------------------------------------- The Orbital Dock
  doc1: { p: "sum", lv: 4, title: "THE AIRLOCK CODE",
    say: [["juno", "The airlock needs a code to let you back in. Three sums!"]] },
  doc2: { p: "count", lv: 3, title: "THE CARGO LIST",
    say: [["juno", "Let's check the cargo. Count the ones it asks for."]] },
  doc6: { p: "clock", lv: 3, title: "DEPARTURE TIME",
    say: [["juno", "Her ship leaves at the time on the board. Which clock is it?"], ["pip", "Then we'll know how long you've got to hide."]] },
  // ---------------------------------------------------------------- Phobos
  pho1: { p: "next", lv: 3, title: "THE BOULDER NUMBERS",
    say: [["tycho", "The boulders are numbered in a pattern. Some of the numbers rubbed off."], ["pip", "What comes next, Rory?"]] },
  pho3: { p: "story", lv: 3, things: "mining bots", boxes: "pens", title: "THE BOT COUNT",
    say: [["tycho", "How many bots are home? Work it out for me, Agent."]] },
  pho6: { p: "minus", lv: 3, title: "THE BRICK PILE",
    say: [["tycho", "Her ship had a pile of ice bricks. Work out how many she's got left."]] },
  // ---------------------------------------------------------------- Jezero Crater
  jez1: { p: "map", lv: 3, title: "THE ROVER MAP",
    say: [["amani", "Here's the rover map. Undertow's ship landed somewhere in this crater."], ["pip", "Follow the steps, Rory."]] },
  jez3: { p: "order", lv: 3, title: "THE SAMPLE BOX",
    say: [["amani", "The samples go in the box in order. Smallest number first."]] },
  jez5: { p: "times", lv: 3, title: "THE LITTLE ROVERS",
    say: [["amani", "Each little rover carries the same number of samples. How many altogether?"], ["pip", "Times tables, Rory."]] },
  // ---------------------------------------------------------------- Valles Marineris
  val2: { p: "scale", lv: 4, title: "THE HEAVY VALVE",
    say: [["lucia", "The pipe valves are all different weights. The heavy ones are the real ones."], ["pip", "Work out what one box weighs, Rory."]] },
  val5: { p: "map", lv: 4, title: "THE CANYON MAP",
    say: [["lucia", "The helicopter's camera made a map of the canyon."], ["pip", "Start at the square it says, Rory. Where's the pump station?"]] },
  val6: { p: "cipher", lv: 4, word: "NORTH", title: "HER PLANS",
    say: [["rory", "Her plans! In symbol code again."], ["pip", "Use the key, Rory."]] },
  // ---------------------------------------------------------------- The Dust Storm
  sto2: { p: "next", lv: 4, title: "THE PATH BEACONS",
    say: [["sol", "The beacons are numbered in a pattern, all the way to the station."], ["pip", "What comes next, Rory?"]] },
  sto3: { p: "story", lv: 4, things: "Drips", boxes: "tents", title: "THE STORM REPORT",
    say: [["sol", "How many Drips did we catch? Work it out, Rory."]] },
  sto4: { p: "clock", lv: 4, title: "WHEN THE STORM STOPS",
    say: [["sol", "The storm stops at the time on my weather screen. Which clock is it?"]] },
  // ---------------------------------------------------------------- Olympus Mons
  oly1: { p: "times", lv: 4, title: "THE ROUTE MARKERS",
    say: [["hana", "The climbing route has sums on the markers. Times tables all the way up!"]] },
  oly2: { p: "suspect", lv: 4, title: "THE CLIMBERS' PHOTO",
    say: [["hana", "Six people in the climbers' photo, and one of them is Undertow's lookout."], ["pip", "Read the clues, Rory. Watch out for NOT."]] },
  oly4: { p: "minus", lv: 4, title: "THE PATH",
    say: [["hana", "How many rocks are still on the path? Take away, Agent."]] },
  // ---------------------------------------------------------------- The Polar Cap
  pol1: { p: "count", lv: 4, title: "THE TRACKERS",
    say: [["silt", "The trackers show which towers she's melting. Count the ones it asks for."]] },
  pol3: { p: "sum", lv: 4, title: "THE MELT SWITCH",
    say: [["silt", "The melt switch has a sum lock. Three sums, Rory."]] },
  pol5: { p: "scale", lv: 4, title: "THE BRICK BRIDGE",
    say: [["silt", "The bridge has to balance, or it'll crack. Work out what one box weighs."]] },
  // ---------------------------------------------------------------- Undertow's Dome
  dom2: { p: "story", lv: 4, things: "Tide Pearls", boxes: "nets", title: "EVERY PEARL",
    say: [["pip", "Every pearl has to go home. How many are there? Work it out, Rory."]] },
  dom3: { p: "map", lv: 4, title: "THE DOME SEA MAP",
    say: [["torpedo", "I have a map of the dome sea. The Engine is at the end of it."], ["pip", "Start at the square it says, Rory."]] },
  dom6: { p: "cipher", lv: 4, word: "HOME", title: "THE GATE CODE",
    say: [["undertow", "All right. The gate code is in my own symbols. Here is the key."], ["pip", "Last code, Rory. Open the gates and send the sea home."]] },

  // ---------------------------------------------------------------- the Ice Trench (Act Two)
  ice1: { p: "next", lv: 4, title: "THE AIR HOLES",
    say: [["nuka", "The air holes are numbered in a pattern. Find the next one!"]] },
  ice2: { p: "order", lv: 4, title: "THE CONTROL ROOM DOOR",
    say: [["silt", "The control room door has a number lock."], ["pip", "In order, Rory. Watch which way it asks for."]] },
  ice6: { p: "story", lv: 4, things: "narwhals", boxes: "pods", title: "THE NARWHAL COUNT",
    say: [["nuka", "How many narwhals did we free? Work it out, Rory."]] },
};
