// Agent Rory: Deep Red — the cast, the acts, the places and every mission's
// lines. Captain Undertow is draining the sea; Rory, BOLT and TORPEDO the little
// submarine follow the stolen water from the coasts to the deep, and then to Mars.

import { CHARS2, ACT2 } from "./story2.js";
import { CHARS3, ACT3 } from "./story3.js";

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS = {
  rory:    { name: "Rory", voice: V("m", "en-GB", 1.15, 1.05), look: { skin: 0xf3cfae, hair: 0x6b4423, eyes: 0x3b5f8a, coat: 0x16324f, trousers: 0x1a1f2a, shirt: 0xf4f6fa, tie: 0x0e1a2c, kid: true, earpiece: true, hairStyle: "rory" } },
  bolt:    { name: "BOLT", side: "bolt", robot: "bolt", voice: V("m", "en-GB", 1.6, 1.15), bg: "#0e3050" },
  torpedo: { name: "TORPEDO", side: "bolt", craft: "sub", voice: V("m", "en-GB", 1.3, 1.1), bg: "#0a3a5a" },
  frost:   { name: "Admiral Frost", voice: V("m", "en-GB", 0.7, 0.92), look: { skin: 0xe8c8a8, hair: 0xe8e8e8, coat: 0x1a2440, trousers: 0x1a2440, shirt: 0xf0f0f0, tie: 0x2a4a8a, moustache: 0xe8e8e8, hairStyle: "short", hat: "captain", hatColor: 0x1a2440 } },
  pip:     { name: "Pip", voice: V("f", "en-GB", 1.25, 1.05), look: { skin: 0xf0c8a0, hair: 0xd06a2a, coat: 0x2a8a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", glasses: 0x1a1a1a } },
  undertow:{ name: "Captain Undertow", side: "villain", voice: V("f", "en-GB", 0.9, 0.92), look: { skin: 0xe8d0c0, hair: 0xb8c8d8, coat: 0x0e2a4a, trousers: 0x0e2a4a, shirt: 0x2ad0c0, tie: 0xd8b04a, hairStyle: "bun", hat: "captain", hatColor: 0xf4f4f8, stern: true, belt: 0xd8b04a } },
  drip:    { name: "Drip", side: "villain", robot: "drip", voice: V("m", "en-GB", 1.5, 1.15), bg: "#0a2a3a" },
  morwenna:{ name: "Morwenna", voice: V("f", "en-GB", 1.2, 1.0), look: { skin: 0xf4d0b8, hair: 0x2a1a10, coat: 0xe8c020, trousers: 0x2a3a5a, kid: true, hairStyle: "long" } },
  emile:   { name: "Émile", voice: V("m", "fr-CA", 1.2, 1.0), look: { skin: 0xf0c8a8, hair: 0x6a3a1a, coat: 0xd83a2a, trousers: 0x2a2a3a, kid: true, hairStyle: "short", hat: "beanie", hatColor: 0x2a6ad8 } },
  valeria: { name: "Valeria", voice: V("f", "es-US", 1.2, 1.0), look: { skin: 0xc89060, hair: 0x14100c, coat: 0xf4f4f8, trousers: 0x2a4a8a, kid: true, hairStyle: "ponytail", hat: "cap", hatColor: 0x2a4a8a } },
  mateo:   { name: "Mateo", voice: V("m", "es-US", 1.2, 1.0), look: { skin: 0xb88050, hair: 0x14100c, coat: 0x6a8a3a, trousers: 0xd8c8a0, kid: true, hairStyle: "curly", hat: "sunhat", hatColor: 0xd8c898 } },
  kai:     { name: "Kai", voice: V("m", "en-US", 1.15, 1.05), look: { skin: 0xa8784e, hair: 0x1a1410, coat: 0x2ab8d8, trousers: 0xf0c040, kid: true, hairStyle: "spiky" } },
  ruby:    { name: "Ruby", voice: V("f", "en-AU", 1.2, 1.05), look: { skin: 0xf0c8a0, hair: 0xc84a2a, coat: 0x2a8ad8, trousers: 0x1a2a3a, kid: true, hairStyle: "pigtails", hat: "cap", hatColor: 0xe8e8e8 } },
  ming:    { name: "Ming", voice: V("m", "zh-HK", 1.2, 1.0), look: { skin: 0xf0d4b4, hair: 0x14141a, coat: 0xd82a2a, trousers: 0x1a1a24, kid: true, hairStyle: "short" } },
  aisha:   { name: "Aisha", voice: V("f", "en-IN", 1.2, 1.0), look: { skin: 0x9a6a44, hair: 0x14100c, coat: 0xf4d020, trousers: 0x2a8a8a, kid: true, hairStyle: "long" } },
  nia:     { name: "Nia", voice: V("f", "en-US", 1.15, 1.0), look: { skin: 0x6a4028, hair: 0x14100c, coat: 0xe86a2a, trousers: 0x1a2a4a, kid: true, hairStyle: "curly", hat: "cap", hatColor: 0x1a2a4a } },
  ...CHARS2,
  ...CHARS3,
};

// Mission kinds (missions.js, missions2.js, missions3.js). From Zero Gravity: cells (Tide
// Pearls here), roundup, stack, lasers, drone, chase, stealth, boss, circuit, codes. New: dive,
// subrings, boatchase, subchase, sonar, tide, salvage, escort, morse, surf. lv is the difficulty.
export const CHAPTERS = [
  { n: 1, title: "The Sea Is Going Down", blurb: "Harbours are drying up all over the world. Somebody is stealing the sea." },
  { n: 2, title: "Into the Abyss", blurb: "The stolen water goes down, not away. Follow it to the bottom of the ocean." },
  { n: 3, title: "Red Planet", blurb: "The sea is on its way to Mars. So are you." },
];

// Act Two's places join as each is built (story2.js has them all)
export const READY = ["sunlight", "kelp", "liner", "twilight", "midnight", "vents", "glass", "ice", "mariana", "engine"];
// and Act Three's (story3.js), likewise
export const READY3 = ["launch", "elevator", "dock", "phobos", "jezero", "valles", "storm", "olympus", "polar", "dome"];
export const PLACES = [
  // ------------------------------------------------------------ 1. the sub pen
  { id: "pen", ch: 1, name: "POLARIS Sub Pen", country: "Scotland", flag: "sct", contact: "pip", lat: 57.1, lon: -5.6,
    arrive: [["frost", "Agent Rory. The sea is going down."], ["rory", "Going down where?"], ["frost", "That is the question. Harbours are drying out from Cornwall to Hong Kong. Boats are sitting on the mud."], ["pip", "So this mission is under the water. Rory, meet your new partner!"], ["torpedo", "Hello! I am TORPEDO. I am a submarine. I am yellow. I am very fast."], ["bolt", "I am BOLT. I am also very fast. On land."], ["torpedo", "Land is just the bottom of the sea with the water missing."], ["pip", "You two will get on brilliantly. Training first. Follow the beams of light!"]],
    leave: [["frost", "Training complete. The first harbour to dry out was in Cornwall. Porthcarrow. Go and find out why."], ["torpedo", "Cornwall! They have pasties. I cannot eat pasties. I will watch you eat pasties."]],
    missions: [
      { id: "pen1", kind: "puzzle", p: "beads", lv: 1, title: "Pearl School",
        intro: [["pip", "These glowing balls are Tide Pearls. Somebody is squeezing the tide into them, a little bit at a time."], ["pip", "Our spies found them on a necklace, in a pattern. Say the pattern out loud, then tap the pearl that's missing!"]],
        outro: [["rory", "They're cold. And they sort of slosh."], ["pip", "That's the sea inside. And they're strung in patterns, so somebody is organised. We need to find out who."]],
        intel: { title: "Tide Pearls", text: "Somebody is squeezing the sea into glowing Tide Pearls. That's why harbours are drying out." } },
      { id: "pen2", kind: "puzzle", p: "bonds", lv: 1, title: "First Dive",
        intro: [["pip", "Into the training pool, Rory. First rule of diving: fill your air tank before you go down."], ["pip", "Look how much air the tank has. How much more fills it right up?"], ["torpedo", "Or you could just be a submarine. I am just saying."]],
        outro: [["rory", "Full tank, and down I went. It's so quiet down there."], ["bolt", "I stayed dry. I watched. It was very good swimming."]],
        intel: { title: "Under the sea", text: "This mission happens under the water. A spy diver always fills the air tank before going down." } },
      { id: "pen3", kind: "puzzle", p: "numberline", lv: 1, who: "TORPEDO", title: "TORPEDO's Test Drive",
        intro: [["torpedo", "Climb in, Rory! You steer. I do the engine noises."], ["pip", "The depth line shows how far down TORPEDO is. Read where he's going and tap that spot on the line."]],
        outro: [["torpedo", "Wheee! Down and up and down again. You are a natural. BOLT, did you see?"], ["bolt", "I saw. It was adequate."]],
        intel: { title: "TORPEDO", text: "TORPEDO is a yellow robot submarine. He can carry Rory deep down, where a diver on their own can't go." } },
      { id: "pen4", kind: "roundup", lv: 1, title: "Practice Drips", n: 4, time: 90,
        intro: [["pip", "Whoever is stealing the sea has little diving robots. Our spies call them Drips."], ["pip", "These are my practice ones. Press USE near a Drip and your watch pops it in a bubble!"]],
        outro: [["bolt", "The practice Drips say: blub."], ["pip", "That's all real Drips say too. It's very hard to interrogate them."]],
        intel: { title: "Drips", text: "The sea thief's diving robots are called Drips. A bubble from Rory's watch pops them away. All they ever say is blub." } },
      { id: "pen5", kind: "puzzle", p: "sides", lv: 1, thing: "hatch", title: "Load the Narwhal",
        intro: [["frost", "The submarine Narwhal is our base for this mission. It needs its supplies."], ["pip", "Every crate goes in through a hatch with its own shape. Count the sides, and tap the hatch I ask for."]],
        outro: [["torpedo", "All loaded! One crate is snacks. For you. Not for me. I run on batteries."], ["frost", "Good. The first harbour to dry out was Porthcarrow, in Cornwall. The Narwhal sails tonight."]],
        intel: { title: "First stop: Cornwall", text: "The first harbour to dry out was Porthcarrow, in Cornwall. The Narwhal is sailing there." } },
    ] },
  // ------------------------------------------------------------ 2. Cornwall
  { id: "cornwall", ch: 1, name: "Porthcarrow", country: "Cornwall", flag: "eng", contact: "morwenna", lat: 50.1, lon: -5.5,
    arrive: [["morwenna", "You must be Agent Rory! I'm Morwenna. My gran keeps the lighthouse."], ["rory", "Where's the sea?"], ["morwenna", "That's what everyone's asking. Yesterday the boats were floating. This morning they were sitting on the mud."], ["torpedo", "I do not like mud. Mud is sea that has given up."], ["morwenna", "Gran saw lights in the smugglers' cave last night. Little round lights. Blowing bubbles."], ["pip", "Drips! Start in the harbour, Rory."]],
    leave: [["morwenna", "The tide's coming back in! Look at the boats bob!"], ["frost", "The pump was stamped with a maker's mark: a wave, and the letter U. And its logbook says the next stop is the Bay of Fundy, in Canada."], ["torpedo", "Canada has the biggest tides in the world. Had. Has. I hope has."]],
    missions: [
      { id: "cor1", kind: "puzzle", p: "depth", lv: 1, water: "The harbour", title: "Harbour on the Mud",
        intro: [["morwenna", "Our harbour's on the mud! Gran checks the water every morning, and today it's nearly gone."], ["pip", "Read the depth gauge, Rory. Take away what the Drips pumped out. How deep is it now?"]],
        outro: [["rory", "Hardly any water left. And look, footprints in the mud. Little round ones."], ["morwenna", "Drip prints! They go towards the cave."]],
        intel: { title: "Drip prints", text: "Little round Drip footprints lead from the harbour to the smugglers' cave round the point." } },
      { id: "cor2", kind: "puzzle", p: "map", lv: 1, title: "Smugglers' Cove",
        intro: [["morwenna", "The cave is round the point. Two Drips with lanterns are guarding it."], ["pip", "I've drawn a sneaky path behind the rocks on the spy map. Follow the arrows from the star and tap where you end up."]],
        outro: [["rory", "I'm in. There's a pipe going down into the water. It's humming."], ["pip", "A pump! Something is pumping the sea away from here."], ["morwenna", "And look out there. A boat with no lights, going out to sea. Smugglers? Or Drips?"]],
        intel: { title: "The humming pipe", text: "A pump in the cave is sucking the sea out of the harbour. A boat with no lights is waiting out at sea." } },
      { id: "cor4", kind: "morse", lv: 1, title: "Lamp Signals", time: 150,
        intro: [["morwenna", "Look! Somebody on that boat is flashing a lamp. Long and short flashes."], ["pip", "That's Morse code. Each letter is a pattern of flashes. Use the chart and work out the message!"]],
        outro: [["rory", "It says: PUMP ONE FULL. SEND TO FUNDY."], ["pip", "Somebody's sending the sea away. Let's switch off that pump first."]],
        intel: { title: "PUMP ONE FULL", text: "The boat's lamp flashed: PUMP ONE FULL. SEND TO FUNDY. Somebody is sending the sea away." } },
      { id: "cor5", kind: "puzzle", p: "bonds", lv: 2, title: "The Sea Cave",
        intro: [["pip", "The pump's switch is at the bottom of the flooded part of the cave. That's a long dive."], ["torpedo", "It is too narrow for me. I will wait here and be brave."], ["pip", "Top up your air tank first, Rory. How much more does it need to be full?"]],
        outro: [["rory", "Pump off! The water's stopped going down the pipe."], ["undertow", "Who switched off my pump?"], ["rory", "Who said that?"], ["undertow", "Captain Undertow. Remember the name, little diver. The tide is turning."]],
        intel: { title: "Captain Undertow", text: "The sea thief is called Captain Undertow. The pumps belong to her, and she says the tide is turning." } },
      { id: "cor6", kind: "boatchase", lv: 1, title: "Smugglers' Chase", n: 3, time: 150,
        intro: [["morwenna", "That boat with no lights is getting away! It's full of pearls!"], ["pip", "Take the jet-ski. Catch up and bump it three times!"]],
        outro: [["rory", "Got it! The Drips jumped overboard. Blub, blub, blub."], ["morwenna", "And the pearls are going back into the sea. Look, the tide's coming in!"]],
        intel: { title: "Next stop: Fundy", text: "Undertow's pump has her mark on it: a wave and the letter U. Its logbook says the next stop is the Bay of Fundy, in Canada." } },
    ] },
  // ------------------------------------------------------------ 3. Bay of Fundy
  { id: "fundy", ch: 1, name: "Bay of Fundy", country: "Canada", flag: "ca", contact: "emile", lat: 45.8, lon: -64.6,
    arrive: [["emile", "Bonjour, Agent Rory! I'm Émile. Welcome to the Bay of Fundy."], ["emile", "Twice a day the tide here goes up higher than a house. Or it did."], ["rory", "Those rocks look like giant flowerpots."], ["emile", "The Flowerpot Rocks. The sea carved them. Now it's gone and they look lonely."], ["torpedo", "I know how they feel. I have been out of the water for eleven minutes."], ["pip", "Captain Undertow's logbook said Fundy. Let's find her pump."]],
    leave: [["emile", "Here comes the tide! It's racing in. Merci, Rory, merci, TORPEDO!"], ["frost", "Undertow's boat got away, heading south. The tide gauge caught its radio: the Panama Canal."], ["bolt", "A canal is a river that went to school."]],
    missions: [
      { id: "fun2", kind: "tide", lv: 1, title: "The Tide Mill", time: 180,
        intro: [["emile", "The old mill has sluice gates. When the pond fills, the wheel turns and powers the tide gauge."], ["pip", "Open and shut the gates to get the water up to the line in the mill pond."]],
        outro: [["emile", "The wheel's turning! The gauge is waking up."], ["pip", "It says the water is being pumped out of the bay from somewhere on the mudflats."]],
        intel: { title: "Pumped from the mud", text: "The tide gauge says the bay's water is being pumped out from somewhere on the mudflats." } },
      { id: "fun3", kind: "puzzle", p: "tally", lv: 2, rows: [["Drips","#7fe3ff"],["pumps","#ffd166"],["holes","#ff8ac8"]], title: "Mudflat Drips",
        intro: [["emile", "There they are! Drips, digging holes in the mudflats. They're planting pumps!"], ["pip", "Émile kept a tally of everything out on the mud. Count the marks, Rory. Each gate of five is five."]],
        outro: [["bolt", "We bubbled every Drip. They are floating away towards the sea. There is no sea."], ["emile", "They'll just float for a while then. But the tide gauge has gone dark. We need it to find the big pump."]],
        intel: { title: "Pumps in the mud", text: "The Drips planted little pumps all over the mudflats. Somewhere there's a big one doing most of the work." } },
      { id: "fun4", kind: "circuit", lv: 2, title: "Wake the Tide Gauge", time: 180,
        intro: [["emile", "The gauge needs power to track the pumps. The wires got muddled up."], ["pip", "Turn the tiles so the power runs from the mill to the gauge."]],
        outro: [["pip", "It's picked up the big pump. It's on a barge just off the shore road!"], ["emile", "And somebody's driving away from the mill with the crank handle!"]],
        intel: { title: "The barge pump", text: "The big pump is on a barge just off the shore road. A Drip has driven off with its crank handle." } },
      { id: "fun5", kind: "chase", lv: 2, title: "Shore Road Chase", n: 3, time: 150,
        intro: [["emile", "A Drip in a pickup truck! It's got the crank for the barge pump."], ["pip", "Take the buggy. Three bumps and it'll drop it!"]],
        outro: [["rory", "Got the crank! Now let's get that barge."], ["torpedo", "Barges are just lazy boats."]],
        intel: { title: "The crank", text: "Rory got the crank handle back. With it, the barge pump can be switched off." } },
      { id: "fun6", kind: "puzzle", p: "pressure", lv: 2, title: "The Barge Pump",
        intro: [["emile", "We've got the crank! But the barge pump's switch is behind a pressure lock."], ["pip", "Add up the gauges, Rory. Get the number right and the lock pops open."]],
        outro: [["rory", "Crank in, switch off. Listen! The barge pump's stopped."], ["emile", "The bay is ready for its tide. Here it comes!"], ["pip", "But the barge radio is still crackling. Somebody's heading south."]],
        intel: { title: "South to Panama", text: "Undertow's boat got away, heading south. The barge radio caught where to: the Panama Canal." } },
    ] },
  // ------------------------------------------------------------ 4. Panama Canal
  { id: "panama", ch: 1, name: "Panama Canal", country: "Panama", flag: "pa", contact: "valeria", lat: 9.0, lon: -79.6,
    arrive: [["valeria", "¡Hola, Agent Rory! I'm Valeria. My dad is a canal pilot. He steers the big ships through."], ["rory", "Why is that ship stuck?"], ["valeria", "The locks are running dry. Every ship between the oceans is stuck."], ["torpedo", "I will push them. I am small but I am determined."], ["pip", "Undertow is up to something in the lock machinery. Let's get the ships moving."]],
    leave: [["valeria", "The ships are moving! Dad says gracias. He's never been so happy to be in a queue."], ["frost", "The barge you caught was carrying pearls to the Galápagos Islands. Out in the Pacific."], ["bolt", "The Galápagos have giant tortoises. I would like to race one. I think I would win. Just."]],
    missions: [
      { id: "pan1", kind: "tide", lv: 2, title: "Fill the Locks", time: 200,
        intro: [["valeria", "The locks are like steps for ships. Each chamber fills from the one above."], ["pip", "Open the valves in the right order to fill each chamber in turn."]],
        outro: [["valeria", "The ship's floating again! Look at it rise!"]],
        intel: { title: "Steps for ships", text: "The canal's locks are steps of water for ships. Somebody has been letting the water out, and the ships got stuck." } },
      { id: "pan2", kind: "puzzle", p: "cipher", lv: 1, word: "MINE", title: "Ship in the Lock",
        intro: [["valeria", "The Drips hid pearls on the cargo ship in the lock. Every crate has a label, but it's in code!"], ["pip", "Each symbol is a letter. Find it in the key, then tap the letters to spell the label."]],
        outro: [["rory", "It says MINE. And under it, a little wave and a U."], ["valeria", "Captain Undertow? She's labelling the sea? That's so rude."]],
        intel: { title: "MINE", text: "Undertow labels every pearl crate MINE. She thinks the sea belongs to her." } },
      { id: "pan3", kind: "puzzle", p: "chart", lv: 2, what: "barges", title: "The Control House",
        intro: [["valeria", "The Drips took over the lock control house. They ran off when they saw you coming!"], ["pip", "The control desk has a chart of how many barges filled up each night. Read the bars, Rory."]],
        outro: [["rory", "Barges every night, all filled from the lake. Somebody's draining it."], ["pip", "With valves under the lock gates. And Undertow likes to guard things with lasers."]],
        intel: { title: "Barges by night", text: "Every night the Drips open valves under the lock gates and drain the lake into barges." } },
      { id: "pan4", kind: "puzzle", p: "depth", lv: 2, water: "The lake", title: "Gate Machinery",
        intro: [["valeria", "The tunnel under the gates is full of red beams, but the valve wheel is just past them."], ["pip", "Before we shut it, read the lake gauge. Take away what the Drips pumped out. How deep is the lake now?"]],
        outro: [["rory", "Valves shut! The lake stays in the lake."], ["valeria", "A barge is racing away down the canal!"]],
        intel: { title: "Valves shut", text: "The valves are shut and the lake is safe. But one last barge full of pearls is escaping down the canal." } },
      { id: "pan5", kind: "boatchase", lv: 2, title: "Canal Chase", n: 3, time: 150,
        intro: [["valeria", "It's heading for the Pacific! Take my dad's speedboat!"], ["pip", "Three bumps. Mind the channel markers."]],
        outro: [["torpedo", "The barge has stopped. It says sorry. In bubbles."], ["valeria", "It's full of pearls! And a map of some islands."]],
        intel: { title: "A map of islands", text: "The barge was full of pearls, with a map of the Galápagos Islands, out in the Pacific Ocean." } },
    ] },
  // ------------------------------------------------------------ 5. Galápagos
  { id: "galapagos", ch: 1, name: "Galápagos Islands", country: "Ecuador", flag: "ec", contact: "mateo", lat: -0.7, lon: -90.3,
    arrive: [["mateo", "¡Bienvenido, Agent Rory! I'm Mateo. I help look after the giant tortoises."], ["rory", "That tortoise is enormous."], ["mateo", "That's Doña Rosa. She's a hundred and twenty years old. And she's worried."], ["torpedo", "Why is she worried?"], ["mateo", "The rock pools are drying up and the baby turtles can't reach the sea. And I've seen iguanas that go blub."], ["pip", "Drips in disguise! Let's help the babies first."]],
    leave: [["mateo", "The pools are full and the babies made it! Doña Rosa says thank you. Slowly."], ["frost", "The disguised Drips had orders for Hawaii. They're using the volcanoes for something. Hot water, perhaps."], ["torpedo", "Hot water? I am a submarine, not a teapot."]],
    missions: [
      { id: "gal1", kind: "puzzle", p: "map", lv: 1, title: "Baby Turtle Run",
        intro: [["mateo", "The baby turtles hatched, but the sea is too far away now. And there are crabs!"], ["pip", "I've marked a safe path on the spy map. Follow the arrows from the star, and tap where the babies reach the water."]],
        outro: [["mateo", "They're swimming! Little flippers everywhere!"], ["rory", "Mateo, why is that iguana blowing bubbles?"]],
        intel: { title: "Bubbly iguanas", text: "Some of the iguanas on the beach are blowing bubbles. Real iguanas sneeze salt. Drips blow bubbles." } },
      { id: "gal2", kind: "roundup", lv: 2, title: "Iguana or Drip?", n: 5, time: 150,
        intro: [["mateo", "Some of those marine iguanas are Drips in costumes."], ["pip", "Real iguanas sneeze salt. Drips blow bubbles. Bubble the fake ones!"]],
        outro: [["bolt", "The costumes were very good. I would like one."]],
        intel: { title: "Drips in disguise", text: "The bubbly iguanas were Drips in costumes. They had been hiding pearls up on the old lava fields." } },
      { id: "gal4", kind: "puzzle", p: "beads", lv: 2, title: "Lava Fields",
        intro: [["mateo", "The Drips left a line of pearls across the old lava fields. It's like a trail!"], ["pip", "The pearls go in a pattern. Find the missing one each time and we can follow the trail."]],
        outro: [["rory", "The trail stops here. At a radio mast that doesn't belong."], ["pip", "A Drip mast! It needs a code to switch off."]],
        intel: { title: "The Drip mast", text: "The pearl trail leads to a Drip radio mast on the lava fields. It's sending messages." } },
      { id: "gal5", kind: "codes", lv: 2, title: "The Drip Mast", time: 150,
        intro: [["pip", "The mast plays a tune before it unlocks. Watch the lights and play it back."]],
        outro: [["pip", "Mast off! Its last message went to a salvage boat in the bay."]],
        intel: { title: "The salvage boat", text: "The mast's last message went to a salvage boat in the bay. It's hiding parts of a pump." } },
      { id: "gal6", kind: "puzzle", p: "measure", lv: 2, thing: "pump part", title: "Raise the Pump",
        intro: [["torpedo", "My turn! The Drips dropped pump parts on the sea bed. I have grabbed them with my claw."], ["pip", "Measure each part with the ruler, Rory, so we know where it goes. Look where the end lines up."]],
        outro: [["torpedo", "I am a salvage submarine now. I have a new job title."], ["bolt", "I also have a job title. Mine is BOLT."], ["pip", "The biggest part has a delivery label. Hawaii."]],
        intel: { title: "Orders for Hawaii", text: "The pump parts were going to Hawaii. Undertow is using the volcanoes for something." } },
    ] },
  // ------------------------------------------------------------ 6. Hawaii
  { id: "hawaii", ch: 1, name: "Big Island", country: "Hawaii", flag: "us", contact: "kai", lat: 19.4, lon: -155.3,
    arrive: [["kai", "Aloha, Agent Rory! I'm Kai. I surf, mostly. And I help at the volcano centre."], ["rory", "Is that lava going into the sea?"], ["kai", "It's been doing that for thousands of years. It makes new land. But now there's less sea to meet it."], ["torpedo", "I will stay well away from the lava. I have a yellow paint job to think about."], ["pip", "Undertow's pumps are using the volcano's heat. Let's find them."]],
    leave: [["kai", "The waves are back! Look at those sets rolling in. Mahalo, Rory!"], ["frost", "The Drip Digger's memory shows a pipe on the Great Barrier Reef, in Australia. The biggest pump yet."], ["bolt", "The reef is alive. It is made of tiny animals. Billions. I cannot count that high. I tried."]],
    missions: [
      { id: "haw1", kind: "puzzle", p: "chart", lv: 2, what: "big waves", title: "Surf's Up",
        intro: [["kai", "Something's wrong with the surf. I write down the big waves every day, and there are fewer and fewer."], ["pip", "Read Kai's chart, Rory. Put your finger on the top of a bar and go across to the numbers."]],
        outro: [["kai", "You read that like a pro! Totally shredded it."], ["rory", "I don't know what that means but thank you."], ["kai", "Something along the lava coast is drinking the sea."]],
        intel: { title: "Shrinking waves", text: "Hawaii's waves get smaller every day. Something on the lava coast is pumping the sea away." } },
      { id: "haw2", kind: "puzzle", p: "measure", lv: 2, thing: "pipe", title: "Lava Coast",
        intro: [["kai", "Look! A pipe going into a tunnel in the black lava rock."], ["pip", "A bigger pipe means a bigger pump. Line the ruler up, Rory. How long is the pipe?"]],
        outro: [["kai", "That's an old lava tube. Like a cave the lava made."], ["pip", "And the pipe goes all the way in. So do a lot of lasers."]],
        intel: { title: "The lava tube", text: "A big pipe runs into an old lava tube, a cave the lava made. Undertow has filled it with lasers." } },
      { id: "haw3", kind: "puzzle", p: "cipher", lv: 3, word: "DIGGER", title: "The Lava Tube",
        intro: [["pip", "I've switched the lasers off. At the end of the tube there's a huge machine with a name plate."], ["kai", "Be careful, Rory. It's hot in there. And the name is in code!"], ["pip", "Use the key. Swap each symbol for its letter."]],
        outro: [["rory", "DIGGER. It says DRIP DIGGER. It's drilling into the rock!"], ["pip", "That sounds big. Where's its owner?"]],
        intel: { title: "The Drip Digger", text: "Undertow's Drip Digger drills through lava rock. It's at the end of the lava tube." } },
      { id: "haw5", kind: "puzzle", p: "numberline", lv: 3, who: "The Drip boat", place: "from the cliffs", further: "further out", title: "The Pearl Net",
        intro: [["kai", "A Drip boat is towing a pearl net along the cliffs!"], ["pip", "I'm tracking it on the number line. Tap where the Drip boat is, and the coastguard will cut its net."]],
        outro: [["kai", "Net cut! The pearls are sinking back where they belong."], ["undertow", "Enough! Drip Digger, show them what you can do."]],
        intel: { title: "Undertow is cross", text: "Undertow has sent her Drip Digger out of the lava tube to stop Rory." } },
      { id: "haw6", kind: "boss", lv: 1, title: "The Drip Digger", n: 3, time: 180,
        intro: [["undertow", "My Drip Digger drills through lava rock like butter. Imagine what it does to spies."], ["pip", "When it stomps, a ring of steam rolls out. JUMP over it! Then zap it from behind."]],
        outro: [["rory", "It's popped into a bubble!"], ["undertow", "Oh, very clever. You've stopped one little pump. My Engine is a hundred times bigger, and you'll never reach it."], ["torpedo", "Engine? What engine?"], ["pip", "I don't know. But I don't like the sound of it."]],
        intel: { title: "The Engine", text: "Undertow has an Engine a hundred times bigger than the Digger. The Digger's memory shows a pipe on the Great Barrier Reef." } },
    ] },
  // ------------------------------------------------------------ 7. Great Barrier Reef
  { id: "reef", ch: 1, name: "Great Barrier Reef", country: "Australia", flag: "au", contact: "ruby", lat: -18.3, lon: 147.7,
    arrive: [["ruby", "G'day, Rory! I'm Ruby. My mum studies the coral here."], ["ruby", "The reef's drying out at low tide, and low tide keeps getting lower."], ["rory", "It's beautiful. Look at all the colours."], ["ruby", "It's the biggest living thing in the world. And something is sucking the water off it."], ["torpedo", "This is what I was built for. Coral! Fish! Proper sea!"], ["pip", "The Digger pointed at a pipe on the outer reef. Suit up, Rory."]],
    leave: [["ruby", "The water's back over the reef! The coral's happy. The fish are happy. I'm happy!"], ["frost", "The pipe's records show a whole fleet of cargo ships in Hong Kong. Undertow is shipping pearls somewhere."], ["bolt", "Hong Kong at night has the best lights. I will match them."]],
    missions: [
      { id: "reef1", kind: "puzzle", p: "bonds", lv: 3, title: "The Reef Wall",
        intro: [["ruby", "The outer reef drops off like a cliff, down and down into the blue."], ["pip", "That's a deep dive, so you need a really full tank. How much more air fills it up?"]],
        outro: [["rory", "It goes down and down. And there's a pipe, in the canyon at the bottom!"], ["ruby", "It goes right into the dark."]],
        intel: { title: "The canyon pipe", text: "A giant pipe runs down a canyon in the reef wall, and into the dark." } },
      { id: "reef3", kind: "puzzle", p: "map", lv: 2, title: "Into the Pipe",
        intro: [["pip", "It's pitch black in the pipe. But TORPEDO's sonar can draw a map of it!"], ["torpedo", "Ping! There. A map. I am very clever."], ["pip", "Follow the arrows from the star, Rory, and tap where the Drips' markers lead."]],
        outro: [["rory", "The pipe opens out. There's a pump bigger than a house."], ["pip", "We need to block its intake."]],
        intel: { title: "The biggest pump", text: "Inside the pipe is a pump bigger than a house. Blocking its mouth will stop it." } },
      { id: "reef4", kind: "puzzle", p: "sides", lv: 2, thing: "boulder", title: "Block the Pipe",
        intro: [["torpedo", "Rocks! Big ones. I will carry them. You choose, I strain."], ["pip", "Only the right shape will plug the pipe. Count the sides, and tap the boulder I ask for."]],
        outro: [["rory", "Blocked! The water's stopped going down the pipe."], ["ruby", "Some Drips are still guarding the pump though."]],
        intel: { title: "Pipe blocked", text: "The big pump's mouth is plugged with boulders. Only its Drip guards are left." } },
      { id: "reef5", kind: "divers", lv: 3, title: "Drip Divers", n: 6, time: 150,
        intro: [["ruby", "The Drips are swimming round the pump."], ["pip", "Swim up close and zap them into bubbles. They're slippery underwater."]],
        outro: [["bolt", "Six bubbles floating up. It looks like a lemonade."]],
        intel: { title: "Guards popped", text: "The pump's Drip guards are bubbled. But the pump scared the reef fish out of their homes." } },
      { id: "reef6", kind: "puzzle", p: "tally", lv: 3, title: "Lost Clownfish",
        intro: [["ruby", "The pump scared the fish out of their homes. Mum's done a fish survey to see who's back."], ["pip", "Count the tally marks, Rory. Each gate of five is five. Then add them together."]],
        outro: [["ruby", "Everybody's home. Mum's going to be so pleased."], ["pip", "And I've found the pump's records. A whole fleet of cargo ships, in Hong Kong."]],
        intel: { title: "Ships in Hong Kong", text: "The reef pump's records show a fleet of cargo ships in Hong Kong. Undertow is shipping pearls somewhere." } },
    ] },
  // ------------------------------------------------------------ 8. Hong Kong
  { id: "hongkong", ch: 1, name: "Hong Kong", country: "China", flag: "hk", contact: "ming", lat: 22.3, lon: 114.2,
    arrive: [["ming", "Agent Rory! I'm Ming. My grandpa sails the last red-sail junk in the harbour."], ["rory", "The lights are amazing."], ["ming", "Every night at eight they do a light show. But tonight the harbour is half empty and the ferries are scraping the bottom."], ["torpedo", "I will scrape nothing. I am very careful."], ["pip", "Undertow's cargo ships are here. Let's find out where they're going."]],
    leave: [["ming", "The harbour's full again! Grandpa's junk is sailing tonight."], ["frost", "The cargo was going to the Maldives. Islands are popping up there where there was only sea."], ["torpedo", "New islands. Undertow is making land. I do not approve."]],
    missions: [
      { id: "hk1", kind: "puzzle", p: "tally", lv: 2, rows: [["pearls","#ffd166"],["Drips","#7fe3ff"],["crates","#ff8a1a"]], title: "Junk Hop",
        intro: [["ming", "Grandpa watches every junk in the harbour. He's kept a tally of all the funny things on board."], ["pip", "Count Grandpa's tally marks, Rory. Each gate of five is five."]],
        outro: [["ming", "Grandpa says it all goes to one ship. The big grey cargo ship."], ["rory", "Then that's where the pearls are."]],
        intel: { title: "The grey ship", text: "Drips are carrying pearls from the junks to one big grey cargo ship in the harbour." } },
      { id: "hk2", kind: "puzzle", p: "suspect", lv: 3, title: "Cargo Ship",
        intro: [["ming", "That's the ship. The containers are full of pearls."], ["pip", "One of the crew is Undertow's spy, and they have the captain's log. Read the clues and tap the spy, Rory."]],
        outro: [["rory", "Got it! The log is in code. Morse code."], ["pip", "There's a radio room on the bridge. Let's listen in."]],
        intel: { title: "The captain's log", text: "Undertow's spy on the cargo ship had the captain's log. It's written in Morse code." } },
      { id: "hk3", kind: "morse", lv: 2, title: "Radio Room", time: 180,
        intro: [["pip", "Undertow is sending a message. Listen to the beeps and match them to the chart."]],
        outro: [["rory", "It says: ALL PEARLS TO MALDIVES. THE ISLANDS ARE READY."], ["pip", "Islands made of pearls? What is she up to?"]],
        intel: { title: "All pearls to the Maldives", text: "Undertow's radio message said: ALL PEARLS TO MALDIVES. THE ISLANDS ARE READY." } },
      { id: "hk4", kind: "codes", lv: 3, title: "Container Lock", time: 150,
        intro: [["ming", "The biggest container has a lock that plays a tune."], ["pip", "Watch it light up, then play it back."]],
        outro: [["rory", "It's full of machinery. Parts of something huge. Stamped TIDAL ENGINE."], ["torpedo", "There is the engine. I still do not like the sound of it."]],
        intel: { title: "The Tidal Engine", text: "The biggest container is full of machine parts stamped TIDAL ENGINE. That's Undertow's Engine." } },
      { id: "hk6", kind: "boatchase", lv: 3, title: "Harbour Chase", n: 3, time: 180,
        intro: [["ming", "The cargo ship's launch is escaping with the engine plans!"], ["pip", "Chase it through the harbour. Mind the junks!"]],
        outro: [["rory", "Plans got! They show islands in the Maldives with pipes going down into the sea."], ["ming", "Good luck, Rory! Come back for the light show!"]],
        intel: { title: "Islands of pipes", text: "The stolen plans show new islands in the Maldives, with pipes going down into the sea." } },
    ] },
  // ------------------------------------------------------------ 9. Maldives
  { id: "maldives", ch: 1, name: "The Maldives", country: "Maldives", flag: "mv", contact: "aisha", lat: 4.2, lon: 73.5,
    arrive: [["aisha", "Welcome, Agent Rory! I'm Aisha. My mum flies the seaplanes between the islands."], ["rory", "Those islands look brand new."], ["aisha", "They are! They weren't there last week. The sea has gone down so far that sandbanks are poking out."], ["torpedo", "The lagoon is so shallow. I can feel my tummy on the sand."], ["pip", "Undertow said the islands were ready. Ready for what?"]],
    leave: [["aisha", "The sandbanks are going back under. That's how it should be!"], ["undertow", "Enough, Agent Rory. If you want your precious sea, come and get it. I'll be waiting in the Bermuda Triangle."], ["frost", "The Bermuda Triangle. Where ships go missing. Be careful, Rory."]],
    missions: [
      { id: "mal1", kind: "puzzle", p: "depth", lv: 3, water: "The lagoon", title: "New Islands",
        intro: [["aisha", "New sandbanks keep popping up in our lagoon. The water's going down and down!"], ["pip", "Read the lagoon gauge, Rory. Take away what the Drips pumped out. How deep is it now?"]],
        outro: [["rory", "The sandbanks are full of pipes. They're pumping the lagoon dry from underneath."], ["aisha", "The pipes have sluice gates. Maybe we can make them work backwards."]],
        intel: { title: "Pipes in the sand", text: "The new islands are full of pipes, pumping the lagoon dry from underneath." } },
      { id: "mal2", kind: "tide", lv: 3, title: "Lagoon Sluices", time: 220,
        intro: [["aisha", "The pipes have sluice gates. If we can open the right ones, the water flows back."], ["pip", "Get every lagoon up to its line. Some gates fill two at once!"]],
        outro: [["aisha", "The lagoon is filling! The fish are coming back in."]],
        intel: { title: "The lagoon fills", text: "The sluices are open and the lagoon is filling. But the Drips have hidden themselves in the water villas." } },
      { id: "mal4", kind: "puzzle", p: "suspect", lv: 3, title: "Villa Drips",
        intro: [["aisha", "The Drips are hiding in the water villas, and one of the guests is letting them in!"], ["pip", "Read the clues, Rory. Which guest is working for Undertow? Tap them."]],
        outro: [["rory", "Got you! And the Drips are in that villa."], ["bolt", "They were watching television. It was a programme about the sea. They were taking notes."], ["aisha", "There's a wire from the villa to a control box. For all the island pumps!"]],
        intel: { title: "The control box", text: "All the island pumps are wired to one control box. Cut its power and they all stop." } },
      { id: "mal5", kind: "circuit", lv: 3, title: "Island Pumps", time: 200,
        intro: [["pip", "All the island pumps are wired to one control box. Turn the tiles to cut the power."]],
        outro: [["pip", "Pumps off! But a seaplane is taking off with Undertow's maps!"]],
        intel: { title: "The seaplane", text: "The island pumps are off, but a Drip seaplane is trying to take off with Undertow's maps." } },
      { id: "mal6", kind: "boatchase", lv: 4, title: "Seaplane Taxi", n: 3, time: 150,
        intro: [["aisha", "It's still on the water! Catch it before it takes off!"], ["pip", "Bump its floats three times and it'll have to stop."]],
        outro: [["aisha", "It's stopped! The Drip pilot is waving a white flag. A very small one."], ["rory", "And here are the maps. Every pump she has leads to one place. The Bermuda Triangle."]],
        intel: { title: "The Bermuda Triangle", text: "Every one of Undertow's pumps leads to one place: the Bermuda Triangle." } },
    ] },
  // ------------------------------------------------------------ 10. Bermuda
  { id: "bermuda", ch: 1, name: "The Bermuda Triangle", country: "Atlantic Ocean", flag: "bm", contact: "nia", lat: 25.0, lon: -71.0,
    arrive: [["nia", "Agent Rory? I'm Nia, Bermuda Coast Guard cadet. The compasses have been spinning for a week."], ["rory", "What is that?"], ["nia", "That's Undertow's base. It floats. It's as big as a town."], ["torpedo", "It is also ugly. I am sorry, but it is."], ["undertow", "Welcome aboard, Agent Rory. Do wipe your flippers."], ["pip", "This is it, Rory. Find out what the Tidal Engine is, and stop it."]],
    leave: [["rory", "She's gone. The whole base is sinking after her!"], ["torpedo", "She is going down. Deep. Deeper than I have ever been."], ["frost", "Then that's where we follow. Get some rest, Agent Rory. Tomorrow, we go into the abyss."], ["pip", "End of Act One. Act Two: Into the Abyss is coming soon!"]],
    missions: [
      { id: "ber1", kind: "puzzle", p: "pressure", lv: 3, title: "Deck Patrol",
        intro: [["nia", "That's her base, right in the middle of the Triangle. The deck is crawling with Drip guards."], ["pip", "They're all looking the other way. Quick, the main hatch has a pressure lock. Add up the gauges!"]],
        outro: [["rory", "I'm in. It's a huge hall full of pipes."], ["pip", "And lasers. Lots of lasers."]],
        intel: { title: "The pump hall", text: "Under the main hatch is a huge hall full of pipes, guarded by lasers." } },
      { id: "ber2", kind: "puzzle", p: "beads", lv: 2, title: "Pump Hall",
        intro: [["pip", "The laser switch is a necklace of Tide Pearls. Find the missing pearl in the pattern and the beams go off."], ["torpedo", "I would help but I am a submarine and this is a corridor."]],
        outro: [["rory", "Beams off! There's a control room on the far side."]],
        intel: { title: "The control room", text: "Past the lasers is a control room with a panel that powers every pump in the world." } },
      { id: "ber3", kind: "circuit", lv: 4, title: "The Engine Room", time: 220,
        intro: [["pip", "This panel sends power to every pump in the world. Cut it!"]],
        outro: [["pip", "Pumps off, everywhere! Harbours are filling up all over the world!"], ["undertow", "You think this is my Engine? This is a pantry. My Engine is where you will never follow."], ["nia", "Look down through the floor! There's a submarine under the base."], ["rory", "It's shaped like a squid."]],
        intel: { title: "The squid sub", text: "Every pump is off. Undertow has a submarine shaped like a squid, waiting under her base." } },
      { id: "ber5", kind: "boss", lv: 2, title: "The Kraken", n: 4, time: 240,
        intro: [["undertow", "Meet my Kraken. It's a robot squid, and it's very cross."], ["pip", "Jump the rings, and zap its battery pack when it turns round. Four hits!"]],
        outro: [["undertow", "My Kraken! Very well. Keep your little harbours. The ocean is mine."], ["rory", "She's diving! The whole base is going under!"]],
        intel: { title: "Going under", text: "The Kraken is beaten. But Undertow is diving, and she's taking her whole base down with her." } },
      { id: "ber6", kind: "puzzle", p: "numberline", lv: 3, who: "Undertow's sub", title: "Follow Her Down",
        intro: [["torpedo", "In you get, Rory! We are not losing her now."], ["pip", "Watch the line. Tap where Undertow's sub is, so TORPEDO can follow it down through the sinking base."]],
        outro: [["torpedo", "She is gone. Down there. Where it is dark."], ["rory", "We'll find her, TORPEDO. Whatever the Tidal Engine is."]],
        intel: { title: "Into the abyss", text: "Undertow dived deeper than TORPEDO has ever been, down to her Tidal Engine in the abyss." } },
    ] },
  ...ACT2.filter(p => READY.includes(p.id)),
  ...ACT3.filter(p => READY3.includes(p.id)),
];

export const CREDITS = [
  ["Agent Rory: Deep Red", "A game for Rory"],
  ["Story, code and levels", "Written with Claude"],
  ["3D", "three.js, with bloom, SMAA and AgX tone mapping, and a sea of its own"],
  ["Physics", "Rapier: Rory, TORPEDO, the jet-ski and every tumbling crate"],
  ["Music and sound", "Tone.js synthesizers, played live"],
  ["BOLT and the Drips", "RobotExpressive by Tomás Laulhé (Quaternius), CC0"],
  ["Voices", "Kokoro-82M, an open neural voice model"],
  ["Coastlines", "Natural Earth, via world-atlas"],
  ["Starring", "Agent Rory, BOLT, TORPEDO, Pip, Admiral Frost, and Captain Undertow"],
];

export const ALL = PLACES.flatMap(p => p.missions.map(m => ({ ...m, place: p.id })));
export function placeOf(mid) { return PLACES.find(p => p.missions.some(m => m.id === mid)); }
