// Agent Rory: Deep Red, Act Two: Into the Abyss. Undertow dived from her sinking base, and
// the stolen water goes down, not away. Rory follows it in a diving suit and in TORPEDO, zone
// by zone, from the sunlit water to the bottom of the Mariana Trench, where the Tidal Engine
// is freezing the sea into bricks to send up a secret space elevator.

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS2 = {
  lani:    { name: "Dr Lani", voice: V("f", "en-US", 1.05, 1.0), look: { skin: 0xa8784e, hair: 0x1a1410, coat: 0x2ab8a8, trousers: 0x2a3a5a, shirt: 0xf4f4f0, hairStyle: "long" } },
  rosa:    { name: "Rosa", voice: V("f", "en-US", 1.2, 1.05), look: { skin: 0xd8a070, hair: 0x2a1a10, coat: 0xd8402a, trousers: 0x2a3a4a, kid: true, hairStyle: "ponytail", hat: "beanie", hatColor: 0x2a8a6a } },
  barnaby: { name: "Captain Barnaby", voice: V("m", "en-GB", 0.8, 0.9), look: { skin: 0xf0c8a8, hair: 0xe8e8e8, coat: 0x1a2a4a, trousers: 0x1a2a4a, shirt: 0xf0f0f0, moustache: 0xe8e8e8, hairStyle: "short", hat: "captain", hatColor: 0x1a2a4a } },
  hiro:    { name: "Dr Hiro", voice: V("m", "en-US", 1.0, 1.0), look: { skin: 0xf0d4b4, hair: 0x14141a, coat: 0xf08a1a, trousers: 0x2a2a3a, shirt: 0xf4f4f4, hairStyle: "short", glasses: 0x1a1a1a } },
  glim:    { name: "Glim", side: "bolt", critter: "glim", voice: V("f", "en-GB", 1.5, 1.1), bg: "#0a2a3a" },
  ama:     { name: "Dr Ama", voice: V("f", "en-GB", 1.0, 1.0), look: { skin: 0x6a4028, hair: 0x14100c, coat: 0xd8a020, trousers: 0x3a2a1a, shirt: 0xf0e8d8, hairStyle: "curly" } },
  silt:    { name: "Professor Silt", side: "villain", voice: V("m", "en-GB", 0.85, 0.9), look: { skin: 0xe8c8a8, hair: 0xd8d8d0, coat: 0x6a5a4a, trousers: 0x3a3228, shirt: 0xe8e0d0, tie: 0x2a6a4a, moustache: 0xd8d8d0, hairStyle: "bald", glasses: 0x6a5a3a } },
  nuka:    { name: "Nuka", voice: V("f", "en-US", 1.15, 1.0), look: { skin: 0xc89870, hair: 0x14100c, coat: 0xe8e8f0, trousers: 0x2a3a5a, kid: true, hairStyle: "long", hat: "beanie", hatColor: 0xd83a3a } },
  vega:    { name: "Commander Vega", voice: V("f", "en-US", 0.95, 0.95), look: { skin: 0xd8b090, hair: 0x2a1a10, coat: 0xf4f4f8, trousers: 0x2a3a5a, shirt: 0x2a6ad8, hairStyle: "bun" } },
};

export const ACT2 = [
  // ------------------------------------------------------------ 11. the sunlight zone
  { id: "sunlight", ch: 2, name: "The Sunlight Zone", country: "Atlantic Ocean", flag: "bm", contact: "lani", lat: 27.0, lon: -66.0, suit: "dive",
    arrive: [["frost", "Agent Rory. The Bermuda base has sunk, and Undertow went down with it."], ["pip", "You'll need this. A diving suit, with a fish-bowl helmet and ninety seconds of air!"], ["rory", "It's got flippers. I love it."], ["torpedo", "Finally. You will swim almost as well as me. Almost."], ["lani", "Welcome aboard the Albatross! I'm Dr Lani. I study everything that lives in the sunlit water."], ["lani", "And something strange is going on down there. Come and see."]],
    leave: [["lani", "The pipe runs west, along the sea bed. Towards the coast of California."], ["frost", "Then so do you, Agent Rory. There's a kelp forest in the way."], ["torpedo", "A forest. Under the sea. This I must see."]],
    missions: [
      { id: "sun1", kind: "dive", lv: 1, title: "First Dive in the Suit", n: 6, time: 150,
        intro: [["pip", "Try the suit! Swim down to the wreck and grab the Tide Pearls."], ["lani", "Your air lasts much longer in the suit. The bubble streams top it up too."]],
        outro: [["rory", "The suit's brilliant. I can breathe for ages!"], ["torpedo", "Show-off."]] },
      { id: "sun2", kind: "current", lv: 1, title: "The Warm Current", n: 5, time: 150,
        intro: [["lani", "See the streaks in the water? That's a warm current. The turtles ride it like a road."], ["pip", "Swim into it and let it carry you through the rings. Don't fight it!"]],
        outro: [["rory", "Wheee! That was faster than TORPEDO."], ["torpedo", "It was not. I was being polite."]] },
      { id: "sun3", kind: "divers", lv: 2, title: "Drips in the Blue", n: 6, time: 180,
        intro: [["lani", "Drip divers! They're laying a pipe along the sea bed."], ["pip", "Bubble them before they finish it!"]],
        outro: [["rory", "They were laying a pipe from the sunken base. It goes a long way."]] },
      { id: "sun4", kind: "subrings", lv: 2, title: "Manta Rings", time: 160,
        intro: [["torpedo", "My turn! In you get."], ["lani", "Careful of the mantas. They're gentle, and very big."], ["pip", "Drive through the rings, round the manta school."]],
        outro: [["torpedo", "A manta winked at me. I am almost sure of it."]] },
      { id: "sun5", kind: "sonar", lv: 2, title: "The Sunken Base", n: 5, time: 200,
        intro: [["pip", "The wreck is dark inside. Ping the sonar and find Undertow's markers."]],
        outro: [["rory", "Her markers all point the same way. West."], ["lani", "Along the pipe."]] },
      { id: "sun6", kind: "subchase", lv: 2, title: "Follow the Pipe", n: 6, time: 200,
        intro: [["torpedo", "A Drip sub is following the pipe. Let us follow the Drip sub!"], ["pip", "Stay close, through the rings it leaves behind."]],
        outro: [["torpedo", "It went into the kelp. I do not like kelp. It tickles."]] },
    ] },
  // ------------------------------------------------------------ 12. the kelp forest
  { id: "kelp", ch: 2, name: "The Kelp Forest", country: "California", flag: "us", contact: "rosa", lat: 36.6, lon: -121.9, suit: "dive",
    arrive: [["rosa", "Shh! You'll scare the otters. I'm Rosa. I look after them."], ["rory", "Why are they all hiding?"], ["rosa", "The Drips are cutting paths through the kelp, and putting nets across them."], ["torpedo", "The kelp is swaying. I feel seasick. Can a submarine be seasick?"]],
    leave: [["rosa", "The otters are safe, and the pipe goes out to sea. Towards a shipwreck."], ["pip", "Not just any shipwreck, Rory. The RMS Neptune. The biggest liner that ever sank."], ["rory", "Why would Undertow go there?"], ["frost", "That's what you're going to find out."]],
    missions: [
      { id: "kel1", kind: "dive", lv: 2, title: "The Canopy", n: 7, time: 180,
        intro: [["rosa", "There are pearls all up in the kelp, near the surface."], ["pip", "Swim up through the fronds and collect them."]],
        outro: [["rosa", "You swim like an otter! Well, nearly."]] },
      { id: "kel2", kind: "salvage", lv: 2, title: "Otter Nets", n: 4, time: 200,
        intro: [["rosa", "The Drips left nets all over the sea bed. The otters get tangled."], ["torpedo", "My claw can lift them! Bring them to the boat."]],
        outro: [["rosa", "Every net gone! Thank you, TORPEDO."], ["torpedo", "You are welcome. I am a hero."]] },
      { id: "kel3", kind: "subchase", lv: 2, title: "Kelp Chase", n: 7, time: 200,
        intro: [["pip", "A Drip sub, heading for the deep water!"], ["torpedo", "Through the kelp? It tickles! Fine. Fine!"]],
        outro: [["rory", "It dropped something. A picture of an old ship."]] },
      { id: "kel4", kind: "divers", lv: 2, title: "Net Cutters", n: 6, time: 180,
        intro: [["rosa", "More Drip divers, cutting the kelp to make room for the pipe."], ["pip", "Bubble every one of them."]],
        outro: [["rosa", "The kelp will grow back. It grows really fast."]] },
      { id: "kel5", kind: "sonar", lv: 3, title: "The Kelp Maze", n: 5, time: 220,
        intro: [["pip", "The kelp is so thick you can't see a thing. Use the sonar."], ["rosa", "The Drips hid their markers in the thickest part."]],
        outro: [["rory", "The markers point out to sea. Towards the wreck in the picture."]] },
      { id: "kel6", kind: "escort", lv: 2, title: "Otter Pup", n: 3, time: 180,
        intro: [["rosa", "Three pups got lost in all the fuss. Lead them back to their mums."], ["pip", "Swim slowly. They follow you like ducklings."]],
        outro: [["rosa", "All home! Look, they're holding hands."], ["torpedo", "That is the best thing I have ever seen."]] },
    ] },
  // ------------------------------------------------------------ 13. the sunken liner
  { id: "liner", ch: 2, name: "The Sunken Liner", country: "North Atlantic", flag: "gb", contact: "barnaby", lat: 42.0, lon: -48.0, suit: "dive",
    arrive: [["barnaby", "So you're the young agent. I'm Captain Barnaby. I sailed on the Neptune, sixty years ago."], ["rory", "Before she sank?"], ["barnaby", "Long before. There was a girl aboard who loved the sea more than anyone I ever met."], ["barnaby", "She'd sit on the deck all day, listening to the waves. Her name was Marina Undertow."], ["torpedo", "Undertow? The Undertow?"], ["barnaby", "The very same. Be careful in there. The old ship creaks."]],
    leave: [["rory", "Her logbook says the pipe goes down. Down into the dark, where the light runs out."], ["barnaby", "The Twilight Zone. Poor Marina. She always said nobody listened to the sea."], ["frost", "We're listening now. Go on, Agent Rory."]],
    missions: [
      { id: "lin1", kind: "airlock", lv: 1, title: "Into the Air Pocket", time: 180,
        intro: [["barnaby", "The front of the ship still has air in it. Get in through the old cargo door."], ["pip", "Close the outer door, pump the water out, then open the inner one. In that order!"]],
        outro: [["rory", "I'm in a room with air in it, at the bottom of the sea. That's so weird."]] },
      { id: "lin2", kind: "cells", lv: 3, title: "Deck by Deck", n: 8, time: 220,
        intro: [["pip", "Undertow's been here. There are pearls on every deck."], ["barnaby", "The grand staircase is still there. Mind the steps."]],
        outro: [["rory", "Someone's been living here! There's a camp bed and a lamp."]] },
      { id: "lin3", kind: "stealth", lv: 4, title: "The Ballroom", time: 200,
        intro: [["pip", "Drip guards in the ballroom. They're guarding something."], ["barnaby", "The ballroom. Marina used to dance there with her grandfather."]],
        outro: [["rory", "A little cabin, with pictures of the sea all over the walls."]] },
      { id: "lin4", kind: "valves", lv: 1, title: "The Engine Room", time: 200,
        intro: [["pip", "Undertow's pipe runs through the old engine room. The pressure's all wrong."], ["torpedo", "Turn the valves until every gauge is green. Then the pipe stops pumping."]],
        outro: [["pip", "All green! That pipe's stopped."], ["undertow", "Stop one pipe, Agent Rory, and I have a hundred more."]] },
      { id: "lin5", kind: "salvage", lv: 3, title: "The Captain's Safe", n: 3, time: 220,
        intro: [["barnaby", "The captain's safe fell through three decks when she sank. It's on the sea bed."], ["torpedo", "Lift it with my claw and bring it back to the ship."]],
        outro: [["rory", "Inside there's a logbook. It's Marina's."], ["barnaby", "She kept it all these years."]] },
      { id: "lin6", kind: "subchase", lv: 2, title: "She's Shifting!", n: 7, time: 200,
        intro: [["barnaby", "The ship's moving! She's sliding off the ledge!"], ["torpedo", "Everybody out! Follow the rings and don't stop!"]],
        outro: [["torpedo", "We made it. The Neptune is sleeping again."], ["barnaby", "Goodbye, old girl."]] },
    ] },
  // ------------------------------------------------------------ 14. the twilight zone
  { id: "twilight", ch: 2, name: "The Twilight Zone", country: "Pacific Ocean", flag: "jp", contact: "hiro", lat: 22.0, lon: -150.0, suit: "dive",
    arrive: [["hiro", "Hello! I'm Dr Hiro, and this is my deep submarine, the Kaiko."], ["torpedo", "It is very big. Is it friendly?"], ["hiro", "Very. We're two hundred metres down. The sunlight is almost gone."], ["rory", "It's all blue and dim, like the evening."], ["hiro", "That's why it's called the Twilight Zone. And everything here makes its own light."]],
    leave: [["hiro", "The pipe goes down a canyon. Into the Midnight Zone, where there's no light at all."], ["rory", "None?"], ["hiro", "Only what the animals make. Take your helmet lamp."], ["pip", "And TORPEDO's headlights. You're going to need them."]],
    missions: [
      { id: "twi1", kind: "sonar", lv: 3, title: "Where's the Pipe?", n: 6, time: 220,
        intro: [["hiro", "The pipe comes in here somewhere, but it's too dim to see."], ["pip", "Ping the sonar and find the markers along it."]],
        outro: [["rory", "Found it. It's huge, and it's humming."]] },
      { id: "twi2", kind: "escort", lv: 3, title: "Lanternfish", n: 4, time: 200,
        intro: [["hiro", "The pipe's noise has scared the lanternfish away from their shoal."], ["pip", "Lead them home. They glow, so you can see them."]],
        outro: [["hiro", "Listen. The shoal is singing again. Well, clicking."]] },
      { id: "twi3", kind: "current", lv: 2, title: "The Down-Current", n: 6, time: 180,
        intro: [["hiro", "There's a cold current running down the slope, along the pipe."], ["pip", "Ride it down through the rings!"]],
        outro: [["rory", "We're really deep now. My ears feel funny."], ["torpedo", "You do not have ears in that helmet. Well, you do. But still."]] },
      { id: "twi4", kind: "codes", lv: 3, title: "The Drip Beacon", time: 180,
        intro: [["pip", "A Drip beacon, flashing a code to someone. Crack it!"]],
        outro: [["pip", "It says: Tidal Engine. Mariana. Glass Station ready."], ["rory", "The Mariana Trench. The deepest place in the world."]] },
      { id: "twi5", kind: "subrings", lv: 3, title: "Rings in the Gloom", time: 180,
        intro: [["torpedo", "Headlights on! Through the rings, down the canyon."]],
        outro: [["torpedo", "I did not hit a single thing. Write that down."]] },
      { id: "twi6", kind: "valves", lv: 2, title: "The Pipe Junction", time: 200,
        intro: [["hiro", "Three pipes meet here. Balance the valves and they'll all stop."]],
        outro: [["hiro", "Silence! You did it."], ["undertow", "Clever. But the deeper you go, Agent Rory, the darker it gets."]] },
    ] },
  // ------------------------------------------------------------ 15. the midnight zone
  { id: "midnight", ch: 2, name: "The Midnight Zone", country: "Pacific Ocean", flag: "jp", contact: "glim", lat: 18.0, lon: -155.0, suit: "dive",
    arrive: [["rory", "It's pitch black. I can only see what my lamp shows."], ["torpedo", "And the lights. Look at all the little lights."], ["glim", "Hello! Hello! Are you real? Nobody's been down here for ages!"], ["rory", "Who said that?"], ["glim", "Me! Glim! POLARIS probe number nine. I got lost two years ago and nobody came to find me."], ["pip", "Probe nine! We thought you were gone forever!"]],
    leave: [["glim", "The pipe goes down to the vents. Where the sea floor is on fire. Well, hot."], ["pip", "Glim, you're coming home with us after this."], ["glim", "Really? Hooray! I'll light the way."]],
    missions: [
      { id: "mid1", kind: "dive", lv: 3, title: "Living Lights", n: 7, time: 200,
        intro: [["glim", "Everything that glows down here is alive. Except the pearls. They glow too!"], ["pip", "Find the pearls in the dark. Follow the lights."]],
        outro: [["glim", "You found them all! In the dark! You're good at this."]] },
      { id: "mid2", kind: "current", lv: 3, title: "The Jelly Drift", n: 6, time: 200,
        intro: [["glim", "The jellyfish drift on a current right through the canyon."], ["pip", "Ride it with them. Don't touch the jellies!"]],
        outro: [["rory", "Some of them were bigger than a bus!"], ["glim", "That's Gerald. He's very gentle."]] },
      { id: "mid3", kind: "divers", lv: 3, title: "Drips in the Dark", n: 6, time: 200,
        intro: [["glim", "Drips! They've got lamps on their heads. That's how you'll see them."]],
        outro: [["glim", "Bubbled! That was the most exciting thing that's happened to me in two years."]] },
      { id: "mid4", kind: "sonar", lv: 4, title: "The Canyon Map", n: 6, time: 240,
        intro: [["pip", "We need a map of the canyon. Ping and find the survey markers."]],
        outro: [["pip", "Got it. The pipe goes straight down to the hydrothermal vents."]] },
      { id: "mid5", kind: "morse", lv: 3, title: "A Message from Below", time: 200,
        intro: [["glim", "Someone's been flashing a lamp from far below. Every night. The same message."], ["pip", "Read the flashes, Rory."]],
        outro: [["rory", "It says: I think I have made a terrible mistake. Signed: S."], ["pip", "S? Who's S?"]] },
      { id: "mid6", kind: "escort", lv: 3, title: "Tow Glim Home", n: 1, time: 180,
        intro: [["glim", "My battery's nearly flat. Can you take me to TORPEDO? I'll follow you."], ["torpedo", "A little probe! I will charge you up. I have plenty of charge."]],
        outro: [["glim", "Charging! Oh, that's lovely. Thank you, TORPEDO."], ["torpedo", "You can sit in my glovebox. I have never used it."]] },
    ] },
  // ------------------------------------------------------------ 16. the hydrothermal vents
  { id: "vents", ch: 2, name: "The Hydrothermal Vents", country: "Pacific Ocean", flag: "ec", contact: "ama", lat: 0.8, lon: -86.2, suit: "dive",
    arrive: [["ama", "Welcome to the vents! I'm Dr Ama. I study the chimneys."], ["rory", "They're puffing black smoke!"], ["ama", "Hot water, full of minerals. Hotter than an oven. Don't swim through it!"], ["torpedo", "Giant worms! There are giant red worms!"], ["ama", "Tube worms. They're lovely. And Undertow is using the vents' heat to power her Engine."]],
    leave: [["ama", "The heat pipes go north-west, to a station made of glass."], ["glim", "The Glass Station! That's where the flashing comes from!"], ["pip", "Then that's where S is. Go carefully, Rory."]],
    missions: [
      { id: "ven1", kind: "dive", lv: 3, title: "Black Smokers", n: 7, time: 200,
        intro: [["ama", "Pearls are stuck to the chimneys. Collect them, but keep out of the hot water!"]],
        outro: [["ama", "Not a single burn. Well done!"]] },
      { id: "ven2", kind: "subrings", lv: 4, title: "The Tube-Worm Maze", time: 200,
        intro: [["torpedo", "Through the worm forest, gently. I do not want to tickle them."]],
        outro: [["ama", "The worms didn't even notice. That's how you drive a sub."]] },
      { id: "ven3", kind: "circuit", lv: 4, title: "The Pump House", time: 220,
        intro: [["pip", "Undertow's pump house runs on vent heat. Reroute the power and switch it off."]],
        outro: [["pip", "The pumps have stopped! The pipe to the Engine is running dry."]] },
      { id: "ven4", kind: "subchase", lv: 3, title: "Chimney Chase", n: 8, time: 220,
        intro: [["torpedo", "A Drip sub is getting away through the chimneys!"], ["ama", "Mind the smoke. It's very hot."]],
        outro: [["torpedo", "Caught its trail. It went towards the glass lights."]] },
      { id: "ven5", kind: "salvage", lv: 3, title: "The Sensor Sled", n: 3, time: 220,
        intro: [["ama", "The Drips knocked my sensors over. Can you bring them back to the lab?"]],
        outro: [["ama", "All three! Now I can watch the vents again."]] },
      { id: "ven6", kind: "valves", lv: 3, title: "The Heat Exchanger", time: 220,
        intro: [["pip", "This is where the vent heat goes into the Engine's pipes. Balance the valves to shut it off."]],
        outro: [["ama", "The chimneys are calm again."], ["undertow", "You're getting close, Agent Rory. Too close."]] },
    ] },
  // ------------------------------------------------------------ 17. the glass station
  { id: "glass", ch: 2, name: "The Glass Station", country: "Pacific Ocean", flag: "gu", contact: "silt", lat: 13.5, lon: 144.0, suit: "dive",
    arrive: [["rory", "A station made of glass domes, on the sea bed."], ["torpedo", "It is glowing. It is beautiful. It is also full of Drips."], ["glim", "The flashes came from that little dome, at the top."], ["pip", "Get inside, Rory. Find S."]],
    leave: [["silt", "The Engine is at the bottom of the Mariana Trench. I'll take you there myself."], ["frost", "Professor Silt. Welcome to POLARIS."], ["silt", "Thank you. I'm so sorry. I only wanted to help the sea."], ["rory", "You still can."]],
    missions: [
      { id: "gla1", kind: "airlock", lv: 2, title: "Airlock In", time: 200,
        intro: [["pip", "The station's airlock. Outer door, pumps, inner door. Don't mix them up!"]],
        outro: [["rory", "I'm in. It smells of coffee and seaweed."]] },
      { id: "gla2", kind: "stealth", lv: 5, title: "The Labs", time: 220,
        intro: [["pip", "Drip guards all through the labs. Sneak to the top dome."]],
        outro: [["silt", "Oh! A child? In a diving suit? How did you get in here?"]] },
      { id: "gla3", kind: "morse", lv: 4, title: "Silt's Signal", time: 200,
        intro: [["silt", "I'm Professor Silt. Undertow's watching me. I can only talk with the lamp. Read my flashes."]],
        outro: [["rory", "He says he built the Engine because she told him it would save the sea."], ["silt", "She said the sea was in danger. That we'd keep it safe."]] },
      { id: "gla4", kind: "codes", lv: 4, title: "The Plans", time: 200,
        intro: [["silt", "The Engine's plans are locked in her safe. Crack the code."]],
        outro: [["silt", "What? Ice bricks? A space elevator? To Mars?"], ["silt", "She never told me. She's not keeping the sea safe. She's taking it away!"]] },
      { id: "gla5", kind: "lasers", lv: 5, title: "The Security Wing", time: 200,
        intro: [["silt", "The alarms! She knows I've been talking to you. Get me out!"], ["pip", "Lasers across the corridor. Get Silt to the moon pool."]],
        outro: [["silt", "We're through. Oh, I haven't run like that in forty years."]] },
      { id: "gla6", kind: "subrings", lv: 4, title: "Out Through the Moon Pool", time: 200,
        intro: [["torpedo", "Everyone in! Professor, you can sit next to Glim."], ["glim", "Hello, Professor! I'll glow for you."], ["pip", "Out through the moon pool and away through the rings."]],
        outro: [["silt", "Thank you, Agent Rory. Now let's stop her. Together."]] },
    ] },
  // ------------------------------------------------------------ 18. the ice trench
  { id: "ice", ch: 2, name: "The Ice Trench", country: "Arctic Ocean", flag: "gl", contact: "nuka", lat: 84.0, lon: -30.0, suit: "dive",
    arrive: [["silt", "Before the Engine, the ice factory. Under the Arctic ice. That's where she makes the bricks."], ["nuka", "Hi! I'm Nuka. I dive under the ice with my dad. The narwhals are scared of the noise."], ["rory", "Narwhals? The ones with the long tusks?"], ["nuka", "The unicorns of the sea! The factory has trapped some of them."], ["torpedo", "It is very cold. My headlights are shivering."]],
    leave: [["nuka", "The narwhals are free! Look at them go!"], ["silt", "No more bricks. Now there's only the Engine itself."], ["frost", "The Mariana Trench, Agent Rory. This is it."]],
    missions: [
      { id: "ice1", kind: "dive", lv: 4, title: "Under the Pack Ice", n: 7, time: 220,
        intro: [["nuka", "There's no surface here, just ice. Breathe at the air holes and bubble streams."], ["pip", "Collect the pearls, and watch your air!"]],
        outro: [["nuka", "You'd make a great ice diver."]] },
      { id: "ice2", kind: "stealth", lv: 5, title: "The Brick Factory", time: 220,
        intro: [["silt", "The factory floor. Drip guards everywhere. Get to the control room."]],
        outro: [["rory", "Millions of ice bricks. All the sea she's stolen."]] },
      { id: "ice3", kind: "lasers", lv: 5, title: "The Conveyor", time: 200,
        intro: [["pip", "Lasers over the conveyor belts. Jump the beams!"]],
        outro: [["rory", "Made it to the freezer controls."]] },
      { id: "ice4", kind: "circuit", lv: 5, title: "Stop the Freezer", time: 220,
        intro: [["silt", "I designed this freezer. Cut the power here, and here, and it stops."]],
        outro: [["silt", "The freezer's off! The bricks will melt back into the sea."]] },
      { id: "ice5", kind: "subchase", lv: 4, title: "The Ice-Tunnel Chase", n: 8, time: 220,
        intro: [["torpedo", "A Drip sub with the last load of bricks! Through the ice tunnels!"]],
        outro: [["torpedo", "It dropped the bricks. The sea gets them back."]] },
      { id: "ice6", kind: "salvage", lv: 4, title: "Free the Narwhals", n: 4, time: 220,
        intro: [["nuka", "The narwhals are trapped behind ice blocks. Lift them out of the way!"]],
        outro: [["nuka", "They're singing! Can you hear them?"], ["glim", "I recorded it. I'm keeping it forever."]] },
    ] },
  // ------------------------------------------------------------ 19. the mariana trench
  { id: "mariana", ch: 2, name: "The Mariana Trench", country: "Pacific Ocean", flag: "gu", contact: "silt", lat: 11.35, lon: 142.2, suit: "dive",
    arrive: [["silt", "The deepest place on Earth. Eleven kilometres down."], ["rory", "It's like looking into space."], ["torpedo", "My hull is creaking. That is normal. Probably."], ["silt", "Undertow's pressure doors are the only way down. I'll help you through them."]],
    leave: [["silt", "The Engine is below us. The biggest machine ever built under the sea."], ["undertow", "Come down, then, Agent Rory. Come and see what I've made."], ["frost", "All POLARIS agents, stand by. Rory's going in."]],
    missions: [
      { id: "mar1", kind: "airlock", lv: 3, title: "The Pressure Door", time: 220,
        intro: [["silt", "The first pressure door. The order matters. Get it wrong and the door won't budge."]],
        outro: [["silt", "Perfect. Only three thousand metres to go."]] },
      { id: "mar2", kind: "current", lv: 4, title: "Down the Trench", n: 7, time: 220,
        intro: [["silt", "The Engine pulls a current down the trench wall. Ride it!"]],
        outro: [["rory", "So deep. And it's all still alive down here."], ["glim", "It always is."]] },
      { id: "mar3", kind: "valves", lv: 4, title: "The Great Pipe", time: 220,
        intro: [["silt", "Every pipe from every ocean joins here. Balance it and the whole network slows down."]],
        outro: [["pip", "Harbours are filling up again all over the world!"]] },
      { id: "mar4", kind: "salvage", lv: 4, title: "Undertow's Logbook", n: 3, time: 220,
        intro: [["silt", "Her supply sled crashed on the trench floor. Her new logbook's in it."]],
        outro: [["rory", "It says: the cargo pod goes up the space elevator tomorrow. To Mars."], ["silt", "A space elevator. She really did it."]] },
      { id: "mar5", kind: "sonar", lv: 5, title: "The Deepest Place", n: 6, time: 240,
        intro: [["pip", "The Engine's entrance is hidden. Ping and find her markers."]],
        outro: [["rory", "There. A door the size of a church."]] },
      { id: "mar6", kind: "codes", lv: 5, title: "The Last Door", time: 220,
        intro: [["silt", "The last door. Her code. I think I know how she thinks. Let's try."]],
        outro: [["silt", "It's opening. Good luck, Agent Rory."], ["undertow", "Welcome to the Tidal Engine."]] },
    ] },
  // ------------------------------------------------------------ 20. the tidal engine
  { id: "engine", ch: 2, name: "The Tidal Engine", country: "Pacific Ocean", flag: "gu", contact: "silt", lat: 11.37, lon: 142.6, suit: "dive",
    arrive: [["rory", "It's enormous. Pipes, pumps and a great glowing heart."], ["undertow", "Beautiful, isn't it? Every sea in the world, flowing into my Engine."], ["undertow", "Frozen, packed and sent to Mars, where nobody will ever pollute it again."], ["rory", "But people need the sea! The fish, the turtles, the otters. Everybody."], ["undertow", "People never listened to the sea. I did."], ["silt", "Marina, please. This isn't the way."]],
    leave: [["undertow", "The tide is turning, Agent Rory. Up there, not down here."], ["rory", "She's in the cargo pod! Going up the space elevator!"], ["pip", "But the Engine's stopped! Rory, look. The water's flowing back!"], ["frost", "Harbours are filling all over the world. Well done, Agent Rory. Well done indeed."], ["frost", "Pip, get me Commander Vega. We're going to Mars."], ["vega", "Commander Vega here. I've been waiting for this call."], ["pip", "End of Act Two. Act Three: Red Planet is coming soon!"]],
    missions: [
      { id: "eng1", kind: "valves", lv: 5, title: "The Intake Valves", time: 240,
        intro: [["silt", "The intake valves. Balance them all and the Engine can't drink any more sea."]],
        outro: [["undertow", "My intakes! Drips! Stop that child!"]] },
      { id: "eng2", kind: "divers", lv: 5, title: "The Drip Army", n: 8, time: 240,
        intro: [["glim", "That's a lot of Drips. That's all the Drips!"], ["pip", "Bubble them all, Rory!"]],
        outro: [["rory", "Every last one."], ["torpedo", "They are very bubbly now."]] },
      { id: "eng3", kind: "circuit", lv: 5, title: "The Engine's Heart", time: 240,
        intro: [["silt", "The heart of the Engine. Cut the power to it. I'll talk you through it."]],
        outro: [["silt", "It's stopping! The Engine is stopping!"], ["undertow", "Then meet my Kraken. The new one. The bigger one."]] },
      { id: "eng4", kind: "boss", lv: 3, title: "Kraken Mark Two", n: 5, time: 260,
        intro: [["torpedo", "It is the Kraken again. It has more arms this time."], ["pip", "Same trick! Jump the rings and zap its battery pack. Five hits this time."]],
        outro: [["undertow", "Enough! If I can't have the Engine, I'll take what I've already got."]] },
      { id: "eng5", kind: "subchase", lv: 5, title: "The Cargo Pod", n: 9, time: 240,
        intro: [["rory", "She's in a cargo pod full of ice bricks, heading for the elevator!"], ["torpedo", "Hold on to something, everybody!"]],
        outro: [["torpedo", "We are too late. She is at the lift."]] },
      { id: "eng6", kind: "subrings", lv: 5, title: "Up the Lift Shaft", time: 220,
        intro: [["silt", "The elevator goes up through the sea. Follow her as far as you can!"]],
        outro: [["rory", "She's out of the water. Going up and up, into the sky."], ["undertow", "Goodbye, Agent Rory. Look for me on Mars."]] },
    ] },
];
