// Agent Rory: Deep Red, Act Three: Red Planet. Undertow's cargo pod of frozen sea has gone up
// the space elevator. Rory follows it up the ribbon, across to Mars by way of Phobos, and down
// to the dome where she has built a new sea of her own, to turn the Tidal Engine round and send
// the sea home as rain.

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS3 = {
  otis:  { name: "Otis", voice: V("m", "en-US", 0.95, 0.95), look: { skin: 0x8a5a3a, hair: 0x1a1410, coat: 0xf08a1a, trousers: 0x2a3a4a, shirt: 0xf0f0f0, hairStyle: "short", glasses: 0x1a1a1a, moustache: 0x1a1410 } },
  juno:  { name: "Juno", voice: V("f", "en-GB", 1.05, 1.0), look: { skin: 0xf0d0b8, hair: 0x2a1a10, coat: 0x2a6ad8, trousers: 0x2a2a3a, shirt: 0xf4f4f8, hairStyle: "bun" } },
  tycho: { name: "Tycho", voice: V("m", "en-US", 1.2, 1.05), look: { skin: 0xd8b090, hair: 0xd8a040, coat: 0x8a8a9a, trousers: 0x3a3a4a, kid: true, hairStyle: "spiky" } },
  amani: { name: "Dr Amani", voice: V("f", "en-GB", 1.0, 1.0), look: { skin: 0x6a4028, hair: 0x14100c, coat: 0xe8e8f0, trousers: 0x3a2a2a, shirt: 0xd83a2a, hairStyle: "curly", glasses: 0x6a3a1a } },
  lucia: { name: "Lucía", voice: V("f", "es-US", 1.15, 1.0), look: { skin: 0xc89060, hair: 0x2a1a10, coat: 0xd86a2a, trousers: 0x3a2a1a, kid: true, hairStyle: "ponytail", hat: "cap", hatColor: 0xd8c898 } },
  sol:   { name: "Sol", voice: V("m", "en-AU", 1.1, 1.05), look: { skin: 0xf0c8a0, hair: 0xe8d8a0, coat: 0x2ab8a8, trousers: 0xf0c040, kid: true, hairStyle: "spiky", glasses: 0x1a1a1a } },
  hana:  { name: "Hana", voice: V("f", "en-US", 1.1, 1.0), look: { skin: 0xf0d4b4, hair: 0x14141a, coat: 0x8a3ad8, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", hat: "beanie", hatColor: 0xffd166 } },
};

export const ACT3 = [
  // ------------------------------------------------------------ 21. the sea-launch platform
  { id: "launch", ch: 3, name: "The Sea-Launch Platform", country: "Pacific Ocean", flag: "zz", contact: "vega", lat: 0.5, lon: -154.0,
    arrive: [["frost", "Agent Rory. Undertow's cargo pod went up her space elevator last night. Full of frozen sea."], ["vega", "Commander Vega, POLARIS space. Welcome to the Sea-Launch Platform."], ["vega", "My rocket can follow her. But somebody has been messing with it."], ["rory", "Drips?"], ["vega", "Drips. Dozens of them. They swam over from her elevator."], ["torpedo", "I am coming too. I do not know how yet. But I am coming."]],
    leave: [["vega", "The rocket's ready. But it can only carry the supplies, not passengers."], ["pip", "Then Rory goes up the elevator! She'll never expect that."], ["rory", "Up a ribbon into space. Easy."], ["bolt", "I will hold your hand. It is not because I am scared."]],
    missions: [
      { id: "lau1", kind: "cells", lv: 2, title: "Pre-Flight Checks", n: 7, time: 180,
        intro: [["vega", "Every system on the rig has a check light. The Drips switched them off."], ["pip", "Find the glowing cells and switch everything back on."]],
        outro: [["vega", "All green. Nice work, Agent."], ["rory", "What does this big red one do?"], ["vega", "Please don't touch that."]] },
      { id: "lau2", kind: "boatchase", lv: 2, title: "Fuel Thieves", n: 3, time: 200,
        intro: [["pip", "A Drip boat just took a rocket fuel pod!"], ["vega", "Grab a jet-ski. Bump them three times and they'll drop it."]],
        outro: [["rory", "Fuel pod back! And a very wet Drip."], ["torpedo", "Jet-skis. Always showing off on top of the water."]] },
      { id: "lau3", kind: "stack", lv: 2, title: "The Supply Pod", time: 200,
        intro: [["vega", "The supplies for Mars go on the lift pad. Stack the crates on the ring."]],
        outro: [["vega", "Food, water, spare socks. We're ready for a long trip."]] },
      { id: "lau4", kind: "roundup", lv: 2, title: "Drips on Deck", n: 6, time: 180,
        intro: [["pip", "There are still Drips hiding all over the deck!"], ["vega", "Herd them into the cage. Gently. They wobble."]],
        outro: [["rory", "Six Drips in a cage. They're blowing bubbles at me."], ["pip", "That means they're sorry. I think."]] },
      { id: "lau5", kind: "circuit", lv: 3, title: "Launch Control", time: 200,
        intro: [["vega", "They crossed the wires in launch control. Nothing talks to the rocket."], ["pip", "Turn the tiles to join the power back up."]],
        outro: [["vega", "Launch control is online. Now for the countdown."]] },
      { id: "lau6", kind: "codes", lv: 3, title: "The Countdown", time: 200,
        intro: [["vega", "The launch code is locked. The Drips changed it."], ["pip", "They left clues in their bubbles. Crack the code!"]],
        outro: [["vega", "Three, two, one... lift off!"], ["rory", "Wow. Look at it go."], ["vega", "And now, Agent Rory, you have an elevator to catch."]] },
    ] },
  // ------------------------------------------------------------ 22. the space elevator
  { id: "elevator", ch: 3, name: "The Space Elevator", country: "Pacific Ocean", flag: "zz", contact: "otis", lat: 0.0, lon: -150.0,
    arrive: [["rory", "Whoa. It just goes up and up and up."], ["otis", "Thirty-six thousand kilometres of ribbon. I built the climbers that ride it."], ["otis", "I'm Otis. Undertow told me it was for a space hotel. A hotel!"], ["otis", "Now her Drips have locked me out of my own station."], ["pip", "Then we'll get you back in."]],
    leave: [["otis", "You beat her climber! Nobody has ever gone up the ribbon that fast."], ["rory", "My ears are still popping."], ["pip", "The top of the elevator is the Orbital Dock. Undertow's Mars ship is waiting there."]],
    missions: [
      { id: "ele1", kind: "stealth", lv: 3, title: "The Anchor Station", time: 220,
        intro: [["otis", "The anchor station's full of Drip guards with searchlights."], ["pip", "Sneak through to the control room. Stay out of the light!"]],
        outro: [["otis", "My control room! I missed it so much."]] },
      { id: "ele2", kind: "lasers", lv: 4, title: "The Climber Bay", time: 200,
        intro: [["otis", "The climber bay is behind a laser fence. Undertow's idea, not mine."], ["pip", "Jump the low beams, and wait for the others."]],
        outro: [["rory", "Through! Is that the climber? It's tiny."], ["otis", "It's cosy."]] },
      { id: "ele3", kind: "valves", lv: 3, title: "Cool the Motors", time: 200,
        intro: [["otis", "The climber motors get very hot. The coolant valves are all wrong."], ["pip", "Turn the wheels until every gauge is in the green."]],
        outro: [["otis", "Nice and cool. She'll climb like a rocket now."]] },
      { id: "ele4", kind: "cells", lv: 3, title: "The Maintenance Tower", n: 7, time: 200,
        intro: [["otis", "The power cells for the climber are up the maintenance tower."], ["pip", "Climb up and grab them all. Don't look down!"]],
        outro: [["rory", "I looked down."], ["bolt", "I also looked down. I did not like it."]] },
      { id: "ele5", kind: "morse", lv: 3, title: "Otis's Message", time: 180,
        intro: [["otis", "I rigged the top of the ribbon to flash a message. Read it for me?"], ["pip", "Watch the flashes. Short and long. Tap in the letters."]],
        outro: [["otis", "RACE. That's from my friend at the dock. Undertow's climber is on its way up!"]] },
      { id: "ele6", kind: "climb", lv: 3, title: "Race Up the Ribbon", n: 5, time: 200,
        intro: [["otis", "Her climber has a head start. But mine is faster, if you use the boosts."], ["pip", "Steer round the ribbon. Dodge the space junk and grab the boost cells!"]],
        outro: [["rory", "We got here first!"], ["torpedo", "Rory! Rory, can you hear me? I am in the supply rocket. In a box. It is very dark."]] },
    ] },
  // ------------------------------------------------------------ 23. the orbital dock
  { id: "dock", ch: 3, name: "The Orbital Dock", country: "Orbit", flag: "zz", contact: "juno", lat: 0.0, lon: -150.0, orbit: true, suit: "space",
    arrive: [["juno", "Welcome to the top of the world! I'm Juno. I run the dock."], ["juno", "Everything floats up here, so hold on to something."], ["pip", "Hold JUMP to fire your jetpack, Rory. Let go to drift."], ["bolt", "I am floating. I did not agree to this."], ["juno", "And that big ugly ship at the end? That's Undertow's. It's loading her ice for Mars."]],
    leave: [["juno", "Her ship's leaving, and you're on it! Good luck, Agent Rory."], ["vega", "I'm right behind you in the supply rocket. With a very grumpy submarine."], ["torpedo", "I am not grumpy. I am just in a box."]],
    missions: [
      { id: "doc1", kind: "cells", lv: 3, title: "Spacewalk", n: 7, time: 200,
        intro: [["juno", "The dock's power cells floated away when her ship bumped us."], ["pip", "Jetpack out and bring them back. Mind the solar panels!"]],
        outro: [["rory", "Spacewalking is the best thing ever."], ["bolt", "Spacewalking is the worst thing ever."]] },
      { id: "doc2", kind: "tractor", lv: 3, title: "Drifting Cargo", n: 6, time: 200,
        intro: [["juno", "Crates are drifting all over the place. Use the tractor beam."], ["pip", "Pull them into the cargo bay, one at a time."]],
        outro: [["juno", "All tidy! Well, tidy for space."]] },
      { id: "doc3", kind: "airlock", lv: 3, title: "Into the Dock", time: 200,
        intro: [["juno", "The dock has air inside, and space outside. The airlock keeps it that way."], ["pip", "Outer door, pump the air in, then the inner door. In that order!"]],
        outro: [["rory", "Air! I can hear things again."]] },
      { id: "doc4", kind: "starmap", lv: 2, title: "The Way to Mars", n: 3, time: 180,
        intro: [["juno", "Undertow wiped the dock's star charts. We need to plot the course to Mars by hand."], ["pip", "Join the stars to make the pictures. Each one points the way."]],
        outro: [["juno", "Course plotted! Mars, here we come."]] },
      { id: "doc5", kind: "drone", lv: 3, title: "The Docking Rings", n: 6, time: 180,
        intro: [["juno", "Fly the dock's little camera drone through the rings. We need to see her ship."], ["pip", "Gently. There's no brakes in space."]],
        outro: [["rory", "Her ship's full of ice bricks. Hundreds of them."], ["juno", "Enough to fill a sea."]] },
      { id: "doc6", kind: "stealth", lv: 4, title: "Stowaway", time: 220,
        intro: [["pip", "Her ship leaves soon. Sneak aboard through the cargo hold!"], ["juno", "Her Drips are guarding it. Stay out of their lights."]],
        outro: [["rory", "I'm in. Hiding behind a crate of frozen sea."], ["undertow", "All aboard. Next stop, Mars. My beautiful new ocean is waiting."]] },
    ] },
  // ------------------------------------------------------------ 24. phobos
  { id: "phobos", ch: 3, name: "Phobos", country: "Mars orbit", flag: "zz", contact: "tycho", mars: "phobos", lat: 0, lon: 0, suit: "space", gravity: 0.06,
    arrive: [["rory", "Her ship's stopped at a little moon. It looks like a potato."], ["tycho", "Hey! That's my home you're talking about. I'm Tycho. I was born on Phobos."], ["tycho", "Be careful. There's hardly any gravity here. Jump too hard and you'll float off."], ["bolt", "I am holding on to the ground with all my fingers."]],
    leave: [["tycho", "Her ship's gone down to Mars. Your friends just landed next to it."], ["vega", "Jump in, Agent Rory. We're going down to Jezero Crater."], ["torpedo", "I am out of the box! Mars smells funny."], ["pip", "You can't smell anything, TORPEDO. You're a submarine."]],
    missions: [
      { id: "pho1", kind: "cells", lv: 3, title: "Boulder Hopping", n: 8, time: 200,
        intro: [["tycho", "The station's cells are on top of the big boulders."], ["pip", "Tiny jumps, Rory. Tiny!"]],
        outro: [["rory", "I jumped over a boulder the size of a house."], ["tycho", "Show-off."]] },
      { id: "pho2", kind: "drive", lv: 3, title: "Across the Crater", n: 8, time: 220,
        intro: [["tycho", "Take my buggy across Stickney Crater. Drive over the glowing cells."], ["pip", "Slowly! The wheels hardly touch the ground here."]],
        outro: [["tycho", "You only left the ground eleven times. That's a record."]] },
      { id: "pho3", kind: "roundup", lv: 3, title: "Runaway Mining Bots", n: 6, time: 200,
        intro: [["tycho", "The mining bots got scared of Undertow's ship and ran off."], ["pip", "Herd them back into their pen."]],
        outro: [["tycho", "They're home. They like you. That's a happy beep."]] },
      { id: "pho4", kind: "circuit", lv: 3, title: "The Station Lights", time: 200,
        intro: [["tycho", "Her ship knocked out the station's lights. Can you fix the wiring?"]],
        outro: [["tycho", "Lights on! Thanks, Agent Rory."]] },
      { id: "pho5", kind: "starmap", lv: 3, title: "Find Mars", n: 3, time: 200,
        intro: [["tycho", "From Phobos you can see every star. I'll show you how I find my way."], ["pip", "Join them up. The last one points straight at Mars."]],
        outro: [["rory", "There it is. Big and red."], ["tycho", "Home sweet neighbour."]] },
      { id: "pho6", kind: "stack", lv: 3, title: "Dropped Bricks", time: 200,
        intro: [["tycho", "Her ship dropped some ice bricks when it landed. They're floating about."], ["pip", "Stack them on the ring before they drift off into space."]],
        outro: [["tycho", "Real sea, frozen into bricks. It's so weird."], ["rory", "It belongs back on Earth. We're taking it home."]] },
    ] },
  // ------------------------------------------------------------ 25. jezero crater
  { id: "jezero", ch: 3, name: "Jezero Crater", country: "Mars", flag: "zz", contact: "amani", mars: true, lat: 18.4, lon: 77.7, suit: "mars", gravity: 0.38,
    arrive: [["vega", "Welcome to Mars, Agent Rory. Mind the first step. It's a big one."], ["rory", "I'm on Mars. I'm actually on Mars!"], ["amani", "And I'm Dr Amani. I run the rovers here in Jezero Crater."], ["amani", "This crater was a lake, once. Billions of years ago. Mars had water."], ["pip", "And Undertow wants to give it water again. Ours."]],
    leave: [["amani", "Her map shows a pipe running up the great canyon. The Valles Marineris."], ["vega", "The rover will get you there. Hold on to your helmet."], ["bolt", "I have glued mine on."]],
    missions: [
      { id: "jez1", kind: "drive", lv: 2, title: "First Drive on Mars", n: 8, time: 220,
        intro: [["amani", "Take the big rover for a spin. Drive over the glowing sample spots."], ["pip", "Gently round the rocks. It's a long walk home."]],
        outro: [["amani", "Beautiful driving. The rover's never been happier."]] },
      { id: "jez2", kind: "drone", lv: 2, title: "The Little Helicopter", n: 6, time: 180,
        intro: [["amani", "This is our helicopter. The air is so thin that its blades spin really fast."], ["pip", "Fly it through the rings round the crater rim."]],
        outro: [["rory", "It flew! On Mars!"], ["amani", "Every time it flies, I cheer. Every single time."]] },
      { id: "jez3", kind: "cells", lv: 3, title: "The River Delta", n: 8, time: 200,
        intro: [["amani", "There are rock samples all over the old river delta. Collect them for me."], ["pip", "Big floaty jumps, Rory. Mars gravity is only a third of Earth's."]],
        outro: [["amani", "These rocks were once at the bottom of a river. Isn't that wonderful?"]] },
      { id: "jez4", kind: "greenhouse", lv: 2, title: "The Greenhouse", n: 4, time: 200,
        intro: [["amani", "We grow our own food in the greenhouse. The plants need you."], ["pip", "Each bed needs water and light at the right time. Watch them closely!"]],
        outro: [["amani", "Tomatoes on Mars! Would you like one?"], ["rory", "Through my helmet? Maybe later."]] },
      { id: "jez5", kind: "escort", lv: 3, title: "Lost Mini-Rovers", n: 3, time: 200,
        intro: [["amani", "Three of my little rovers got lost chasing Undertow's ship."], ["pip", "Lead them back to the rover garage. They'll follow you."]],
        outro: [["amani", "All home safe. They're charging their batteries. That means they're happy."]] },
      { id: "jez6", kind: "codes", lv: 3, title: "Undertow's Map", time: 200,
        intro: [["pip", "One of her Drips dropped a locked map case."], ["amani", "Can you open it? The code is in the pictures."]],
        outro: [["rory", "It's a map of her pipe. It runs up the Valles Marineris to the north pole!"]] },
    ] },
  // ------------------------------------------------------------ 26. valles marineris
  { id: "valles", ch: 3, name: "Valles Marineris", country: "Mars", flag: "zz", contact: "lucia", mars: true, lat: -13.9, lon: -59.2, suit: "mars", gravity: 0.38,
    arrive: [["lucia", "Hola! I'm Lucía. I guide people through the canyon."], ["lucia", "It's four thousand kilometres long. On Earth it would stretch right across America!"], ["rory", "And there's a pipe running along the bottom."], ["lucia", "It appeared last week. Nobody asked me."]],
    leave: [["lucia", "The pipe goes north, into the dust storm. Nobody goes into the storm."], ["pip", "Except Agent Rory."], ["lucia", "Then take my friend Sol. He races sand yachts through storms for fun."]],
    missions: [
      { id: "val1", kind: "chase", lv: 3, title: "The Rim Chase", n: 3, time: 220,
        intro: [["lucia", "A Drip rover is driving along the rim with a bag of pipe parts!"], ["pip", "Chase it in the rover and bump it three times."]],
        outro: [["rory", "Got the parts! And the Drip is sulking."]] },
      { id: "val2", kind: "cells", lv: 4, title: "Down the Canyon", n: 8, time: 220,
        intro: [["lucia", "The pipe's valves are down on the ledges. Jump down carefully."], ["pip", "Mars gravity is your friend. Big floaty jumps!"]],
        outro: [["lucia", "You jump like a Martian."]] },
      { id: "val3", kind: "lasers", lv: 4, title: "Pipeline Lasers", time: 200,
        intro: [["lucia", "She's put lasers along the pipeline to keep people away."], ["pip", "Jump the low beams, and wait for the sweeping ones."]],
        outro: [["rory", "Through the lasers. Now for the valves."]] },
      { id: "val4", kind: "valves", lv: 4, title: "Pipeline Valves", time: 200,
        intro: [["pip", "If we slow the pipe down, she'll get less water. Turn the valves!"], ["lucia", "Every gauge in the green, and nothing bursts."]],
        outro: [["lucia", "The pipe's slowed right down. That'll annoy her."]] },
      { id: "val5", kind: "drone", lv: 3, title: "Canyon Rings", n: 6, time: 180,
        intro: [["lucia", "Take the helicopter down the canyon. There's a pump station somewhere."], ["pip", "Through the rings, round the cliffs."]],
        outro: [["rory", "Found it! A pump station, halfway down the cliff."]] },
      { id: "val6", kind: "stealth", lv: 4, title: "The Pump Station", time: 220,
        intro: [["pip", "Drip guards all over the pump station. Sneak in and find her plans."]],
        outro: [["rory", "The plans say the ice is at the north pole. And her dome is next to it."], ["undertow", "Clever little agent. But the storm will stop you. My storm."]] },
    ] },
  // ------------------------------------------------------------ 27. the dust storm
  { id: "storm", ch: 3, name: "The Dust Storm", country: "Mars", flag: "zz", contact: "sol", mars: true, lat: 46.7, lon: 117.5, suit: "mars", gravity: 0.38,
    arrive: [["sol", "G'day! I'm Sol. Welcome to the biggest dust storm on Mars!"], ["rory", "I can't see a thing."], ["sol", "That's the fun part. My sand yacht sails on the wind."], ["pip", "Undertow is making this storm, Rory. With giant fans. To hide her dome."]],
    leave: [["sol", "The storm's dying down! Look, you can see the sun."], ["rory", "And a mountain. A really, really big mountain."], ["sol", "Olympus Mons. The biggest volcano in the solar system. Her radio is on top."]],
    missions: [
      { id: "sto1", kind: "chase", lv: 3, title: "Storm Chase", n: 3, time: 240,
        intro: [["sol", "A Drip yacht is sailing off with a storm fan! Hop in mine."], ["pip", "Bump it three times. The wind is on your side."]],
        outro: [["sol", "Beautiful sailing! You're a natural."]] },
      { id: "sto2", kind: "cells", lv: 3, title: "Beacons in the Dust", n: 7, time: 200,
        intro: [["sol", "The storm has buried the path beacons. Find them, and we can find our way."], ["pip", "Look for the glow through the dust."]],
        outro: [["sol", "Path's lit! Now nobody gets lost."]] },
      { id: "sto3", kind: "roundup", lv: 3, title: "Blown-Away Drips", n: 6, time: 200,
        intro: [["sol", "Even her Drips got blown away. They're rolling about everywhere."], ["pip", "Round them up. They'll be glad to get out of the wind."]],
        outro: [["rory", "They're blowing dusty bubbles. That's new."]] },
      { id: "sto4", kind: "stack", lv: 3, title: "The Storm Shelter", time: 200,
        intro: [["sol", "We need a shelter from the wind. Stack the blocks on the ring."]],
        outro: [["sol", "Cosy! Well, cosy for a storm."]] },
      { id: "sto5", kind: "circuit", lv: 4, title: "The Weather Station", time: 200,
        intro: [["pip", "The weather station controls her storm fans. Rewire it and switch them off!"]],
        outro: [["sol", "The fans are slowing down. The storm's going to blow itself out."]] },
      { id: "sto6", kind: "morse", lv: 4, title: "Signals in the Storm", time: 200,
        intro: [["pip", "Her Drips are flashing signals to each other through the dust."], ["sol", "Can you read them? Short and long flashes."]],
        outro: [["rory", "SUMMIT. They're heading for the top of Olympus Mons!"]] },
    ] },
  // ------------------------------------------------------------ 28. olympus mons
  { id: "olympus", ch: 3, name: "Olympus Mons", country: "Mars", flag: "zz", contact: "hana", mars: true, lat: 18.65, lon: -133.8, suit: "mars", gravity: 0.38, jetpack: true,
    arrive: [["hana", "Hi! I'm Hana. I'm climbing to the top. It's twenty-two kilometres high!"], ["rory", "That's two and a half Mount Everests."], ["hana", "So I brought a jetpack. And one for you!"], ["pip", "Hold JUMP to fly, Rory. The jetpack works here, the air is so thin."]],
    leave: [["hana", "We did it! The top of the tallest volcano in the solar system!"], ["rory", "And her radio says the ice is at the north pole. Silt is waiting there."], ["hana", "Race you there!"]],
    missions: [
      { id: "oly1", kind: "cells", lv: 4, title: "The Great Climb", n: 8, time: 220,
        intro: [["hana", "The climbing route is marked with cells. Fly up and grab them!"], ["pip", "Short bursts on the jetpack. Save some fuel for the top."]],
        outro: [["hana", "You fly like a bird. A bird in a spacesuit."]] },
      { id: "oly2", kind: "lasers", lv: 4, title: "The Caldera Gate", time: 200,
        intro: [["hana", "Her Drips have fenced off the crater at the top. With lasers, of course."], ["pip", "Keep low. The net overhead stops the jetpack."]],
        outro: [["rory", "Through the gate. There's a radio mast in the middle."]] },
      { id: "oly3", kind: "codes", lv: 4, title: "The Summit Radio", time: 200,
        intro: [["pip", "Her radio is locked. Crack the code and we can hear her messages."]],
        outro: [["undertow", "Ice towers, ready. Dome, full. Engine, running. The tide is turning."], ["rory", "The ice towers are at the north pole!"]] },
      { id: "oly4", kind: "tractor", lv: 4, title: "Falling Rocks", n: 6, time: 200,
        intro: [["hana", "Rocks keep rolling down onto the path! Clear them with the tractor beam."], ["pip", "Pull them into the crater, away from the path."]],
        outro: [["hana", "Path's clear. Thanks, Rory!"]] },
      { id: "oly5", kind: "greenhouse", lv: 4, title: "The High Greenhouse", n: 5, time: 220,
        intro: [["hana", "There's a greenhouse up here for climbers. The plants are thirsty."], ["pip", "Water and light, at the right time. There are more beds this time!"]],
        outro: [["hana", "Strawberries at the top of a volcano. Best snack ever."]] },
      { id: "oly6", kind: "boss", lv: 3, title: "The Dust Kraken", n: 5, time: 260,
        intro: [["undertow", "You found my radio. Then meet my Dust Kraken!"], ["pip", "Jump its rings, and zap the battery pack on its back. Five hits!"]],
        outro: [["undertow", "My beautiful Kraken! Very well. Come to the pole, little agent. See what I've made."], ["rory", "We're coming, Undertow."]] },
    ] },
  // ------------------------------------------------------------ 29. the polar cap
  { id: "polar", ch: 3, name: "The Polar Cap", country: "Mars", flag: "zz", contact: "silt", mars: true, lat: 85.0, lon: 0.0, suit: "mars", gravity: 0.38,
    arrive: [["silt", "Rory! Over here! It's Professor Silt. POLARIS flew me up to help."], ["rory", "Professor! What is all this?"], ["silt", "The stolen sea. Frozen into bricks and stacked into towers. Miles of them."], ["silt", "She's melting them into her dome, one tower at a time."]],
    leave: [["silt", "We've stopped the melting. But the Engine is in her dome, and the dome is full of sea."], ["torpedo", "A sea? On Mars? Did somebody say SEA?"], ["vega", "TORPEDO's coming with you, Rory. This one's a dive."]],
    missions: [
      { id: "pol1", kind: "cells", lv: 4, title: "The Ice-Brick Towers", n: 8, time: 220,
        intro: [["silt", "Each tower has a tracker cell on top. Collect them, and we'll know which towers she's melting."], ["pip", "Jump from tower to tower. Don't slip!"]],
        outro: [["silt", "Every tower tracked. Clever you."]] },
      { id: "pol2", kind: "drive", lv: 4, title: "Rover on the Ice", n: 8, time: 220,
        intro: [["silt", "Drive the ice rover over the sensor spots. It's very slippery."], ["pip", "Gently on the steering!"]],
        outro: [["rory", "I only spun round four times."], ["silt", "Five. I was counting."]] },
      { id: "pol3", kind: "stealth", lv: 5, title: "The Brick Yard", time: 240,
        intro: [["silt", "The brick yard is full of Drip guards. The melt switch is on the far side."], ["pip", "Sneak through. Stay out of the searchlights!"]],
        outro: [["rory", "At the melt switch. It's wired up like a puzzle."]] },
      { id: "pol4", kind: "circuit", lv: 5, title: "The Melt Switch", time: 220,
        intro: [["silt", "Rewire the switch and the towers stop melting. Carefully!"]],
        outro: [["silt", "The melting has stopped! The rest of the sea stays safe in its bricks."]] },
      { id: "pol5", kind: "stack", lv: 4, title: "The Brick Bridge", time: 220,
        intro: [["silt", "There's a crack in the ice between us and the dome. We'll need a bridge."], ["pip", "Stack the ice bricks on the ring."]],
        outro: [["silt", "A bridge made of frozen sea. Now I've seen everything."]] },
      { id: "pol6", kind: "starmap", lv: 4, title: "Silt's Star Chart", n: 4, time: 220,
        intro: [["silt", "I kept a star chart of the way to her dome. The Drips scrambled it."], ["pip", "Join the stars again. There are four pictures this time."]],
        outro: [["silt", "The dome is just over the ridge. Good luck, Rory. Bring the sea home."]] },
    ] },
  // ------------------------------------------------------------ 30. undertow's dome
  { id: "dome", ch: 3, name: "Undertow's Dome", country: "Mars", flag: "zz", contact: "vega", mars: true, lat: 75.0, lon: 30.0, suit: "dive", gravity: 0.38,
    arrive: [["rory", "It's a sea. A whole sea, under a glass dome. On Mars."], ["undertow", "Beautiful, isn't it? A sea nobody can ruin. A sea that is only mine."], ["torpedo", "It is very nice water. But it is not yours."], ["vega", "The Tidal Engine is at the bottom, Rory. Turn it round, and the sea goes home."]],
    leave: [["undertow", "My sea. It's going."], ["rory", "It's going home. Where people need it."], ["undertow", "Nobody ever listened to the sea but me."], ["frost", "Then come and work for POLARIS, Captain. We could use someone who listens."], ["undertow", "I... would like that."], ["pip", "And on Earth, it's raining! It's raining on every harbour in the world!"]],
    missions: [
      { id: "dom1", kind: "airlock", lv: 4, title: "Into the Dome", time: 220,
        intro: [["vega", "The dome is full of air and water. The airlock is the only way in."], ["pip", "Outer door, then the pump, then the inner door. You know the drill."]],
        outro: [["rory", "In. It's warm, and it smells like the seaside."]] },
      { id: "dom2", kind: "dive", lv: 4, title: "The Dome Sea", n: 7, time: 220,
        intro: [["pip", "She's filled the dome sea with Tide Pearls from all over Earth."], ["torpedo", "Dive in, Rory. Bring them back."]],
        outro: [["rory", "Swimming on Mars. Nobody's ever done that before."]] },
      { id: "dom3", kind: "subrings", lv: 4, title: "TORPEDO on Mars", time: 200,
        intro: [["torpedo", "My turn. My sea. Well, Earth's sea. In you get!"], ["pip", "Drive through the rings, down to the Engine."]],
        outro: [["torpedo", "The first submarine on Mars. Write that down, somebody."]] },
      { id: "dom4", kind: "valves", lv: 5, title: "Turn the Engine Round", time: 240,
        intro: [["vega", "The Engine's valves decide which way the water goes. Turn every one."], ["pip", "Every gauge in the green, and the Engine runs backwards."]],
        outro: [["undertow", "What have you done to my Engine?"], ["rory", "Turned it round. The sea's going home."]] },
      { id: "dom5", kind: "boss", lv: 4, title: "Undertow's Last Stand", n: 5, time: 260,
        intro: [["undertow", "You will not take my sea! Kraken, one last time!"], ["pip", "Jump the rings and zap the battery pack. Five hits, Rory!"]],
        outro: [["undertow", "Stop. Please. I don't want to fight any more."], ["rory", "Then help us send it home."]] },
      { id: "dom6", kind: "current", lv: 3, title: "The Sea Goes Home", time: 200,
        intro: [["undertow", "The Engine is pushing the water up the pipe. Ride the current, and open the gates on the way."], ["pip", "Through every ring, Rory. This is it!"]],
        outro: [["rory", "The sea's pouring up into the sky. All of it."], ["torpedo", "Goodbye, sea. See you at home."]] },
    ] },
];
