// Agent Rory: Deep Red — the cast, the acts, the places and every mission's
// lines. Captain Undertow is draining the sea; Rory, BOLT and TORPEDO the little
// submarine follow the stolen water from the coasts to the deep, and then to Mars.

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS = {
  rory:    { name: "Rory", voice: V("m", "en-GB", 1.15, 1.05), look: { skin: 0xf3cfae, hair: 0x6b4423, eyes: 0x3b5f8a, coat: 0x16324f, trousers: 0x1a1f2a, shirt: 0xf4f6fa, tie: 0x0e1a2c, kid: true, earpiece: true, hairStyle: "rory" } },
  bolt:    { name: "BOLT", side: "bolt", robot: "bolt", voice: V("m", "en-GB", 1.6, 1.15), bg: "#0e3050" },
  torpedo: { name: "TORPEDO", side: "bolt", craft: "sub", voice: V("m", "en-GB", 1.3, 1.1), bg: "#0a3a5a" },
  frost:   { name: "Admiral Frost", voice: V("m", "en-GB", 0.7, 0.92), look: { skin: 0xe8c8a8, hair: 0xe8e8e8, coat: 0x1a2440, trousers: 0x1a2440, shirt: 0xf0f0f0, tie: 0x2a4a8a, moustache: 0xe8e8e8, hairStyle: "short", hat: "captain", hatColor: 0x1a2440 } },
  pip:     { name: "Pip", voice: V("f", "en-GB", 1.25, 1.05), look: { skin: 0xf0c8a0, hair: 0xd06a2a, coat: 0x2a8a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", glasses: 0x1a1a1a } },
  undertow:{ name: "Captain Undertow", side: "villain", voice: V("f", "en-GB", 0.9, 0.92), look: { skin: 0xe8d0c0, hair: 0xb8c8d8, coat: 0x0e2a4a, trousers: 0x0e2a4a, shirt: 0x2ad0c0, tie: 0xd8b04a, hairStyle: "bun", hat: "captain", hatColor: 0xf4f4f8, stern: true, belt: 0xd8b04a } },
  drip:    { name: "Drip", side: "villain", robot: "drip", voice: V("m", "en-GB", 1.5, 1.15), bg: "#0a2a3a" },
  morwenna:{ name: "Morwenna", voice: V("f", "en-GB", 1.2, 1.0), look: { skin: 0xf4d0b8, hair: 0x2a1a10, coat: 0xe8c020, trousers: 0x2a3a5a, kid: true, hairStyle: "long" } },
  emile:   { name: "Émile", voice: V("m", "fr-CA", 1.2, 1.0), look: { skin: 0xf0c8a8, hair: 0x6a3a1a, coat: 0xd83a2a, trousers: 0x2a2a3a, kid: true, hairStyle: "short", hat: "beanie", hatColor: 0x2a6ad8 } },
  valeria: { name: "Valeria", voice: V("f", "es-US", 1.2, 1.0), look: { skin: 0xc89060, hair: 0x14100c, coat: 0xf4f4f8, trousers: 0x2a4a8a, kid: true, hairStyle: "ponytail", hat: "cap", hatColor: 0x2a4a8a } },
  mateo:   { name: "Mateo", voice: V("m", "es-US", 1.2, 1.0), look: { skin: 0xb88050, hair: 0x14100c, coat: 0x6a8a3a, trousers: 0xd8c8a0, kid: true, hairStyle: "curly", hat: "sunhat", hatColor: 0xd8c898 } },
  kai:     { name: "Kai", voice: V("m", "en-US", 1.15, 1.05), look: { skin: 0xa8784e, hair: 0x1a1410, coat: 0x2ab8d8, trousers: 0xf0c040, kid: true, hairStyle: "spiky" } },
  ruby:    { name: "Ruby", voice: V("f", "en-AU", 1.2, 1.05), look: { skin: 0xf0c8a0, hair: 0xc84a2a, coat: 0x2a8ad8, trousers: 0x1a2a3a, kid: true, hairStyle: "pigtails", hat: "cap", hatColor: 0xe8e8e8 } },
  ming:    { name: "Ming", voice: V("m", "zh-HK", 1.2, 1.0), look: { skin: 0xf0d4b4, hair: 0x14141a, coat: 0xd82a2a, trousers: 0x1a1a24, kid: true, hairStyle: "short" } },
  aisha:   { name: "Aisha", voice: V("f", "en-IN", 1.2, 1.0), look: { skin: 0x9a6a44, hair: 0x14100c, coat: 0xf4d020, trousers: 0x2a8a8a, kid: true, hairStyle: "long" } },
  nia:     { name: "Nia", voice: V("f", "en-US", 1.15, 1.0), look: { skin: 0x6a4028, hair: 0x14100c, coat: 0xe86a2a, trousers: 0x1a2a4a, kid: true, hairStyle: "curly", hat: "cap", hatColor: 0x1a2a4a } },
};

// Mission kinds (missions.js, missions2.js, missions3.js). From Zero Gravity: cells (Tide
// Pearls here), roundup, stack, lasers, drone, chase, stealth, boss, circuit, codes. New: dive,
// subrings, boatchase, subchase, sonar, tide, salvage, escort, morse, surf. lv is the difficulty.
export const CHAPTERS = [
  { n: 1, title: "The Sea Is Going Down", blurb: "Harbours are drying up all over the world. Somebody is stealing the sea." },
  { n: 2, title: "Into the Abyss", blurb: "The stolen water goes down, not away. Follow it to the bottom of the ocean." },
  { n: 3, title: "Red Planet", blurb: "The sea is on its way to Mars. So are you." },
];

export const PLACES = [
  // ------------------------------------------------------------ 1. the sub pen
  { id: "pen", ch: 1, name: "POLARIS Sub Pen", country: "Scotland", flag: "sct", contact: "pip", lat: 57.1, lon: -5.6,
    arrive: [["frost", "Agent Rory. The sea is going down."], ["rory", "Going down where?"], ["frost", "That is the question. Harbours are drying out from Cornwall to Hong Kong. Boats are sitting on the mud."], ["pip", "So this mission is under the water. Rory, meet your new partner!"], ["torpedo", "Hello! I am TORPEDO. I am a submarine. I am yellow. I am very fast."], ["bolt", "I am BOLT. I am also very fast. On land."], ["torpedo", "Land is just the bottom of the sea with the water missing."], ["pip", "You two will get on brilliantly. Training first. Follow the beams of light!"]],
    leave: [["frost", "Training complete. The first harbour to dry out was in Cornwall. Porthcarrow. Go and find out why."], ["torpedo", "Cornwall! They have pasties. I cannot eat pasties. I will watch you eat pasties."]],
    missions: [
      { id: "pen1", kind: "cells", lv: 1, title: "Pearl School", n: 6, time: 90,
        intro: [["pip", "These glowing balls are Tide Pearls. Somebody is squeezing the tide into them, a little bit at a time."], ["pip", "Grab all six! Run into them, and jump for the high ones."]],
        outro: [["rory", "They're cold. And they sort of slosh."], ["pip", "That's the sea inside. We need to find out who's making them."]] },
      { id: "pen2", kind: "dive", lv: 1, title: "First Dive", n: 5, time: 150,
        intro: [["pip", "Into the training pool, Rory. The bubbles at the top of the screen are your air."], ["pip", "Hold DIVE to swim down, and JUMP to swim up. The bubble streams give you more air."], ["torpedo", "Or you could just be a submarine. I am just saying."]],
        outro: [["rory", "That was brilliant. It's so quiet down there."], ["bolt", "I stayed dry. I watched. It was very good swimming."]] },
      { id: "pen3", kind: "subrings", lv: 1, title: "TORPEDO's Test Drive", time: 150,
        intro: [["torpedo", "Climb in, Rory! You steer. I do the engine noises."], ["pip", "Push the stick where you want to go. JUMP takes you up, DIVE takes you down. Through all the rings!"]],
        outro: [["torpedo", "Wheee! You are a natural. BOLT, did you see?"], ["bolt", "I saw. It was adequate."]] },
      { id: "pen4", kind: "roundup", lv: 1, title: "Practice Drips", n: 4, time: 90,
        intro: [["pip", "Whoever is stealing the sea has little diving robots. Our spies call them Drips."], ["pip", "These are my practice ones. Press USE near a Drip and your watch pops it in a bubble!"]],
        outro: [["bolt", "The practice Drips say: blub."], ["pip", "That's all real Drips say too. It's very hard to interrogate them."]] },
      { id: "pen5", kind: "stack", lv: 1, title: "Load the Narwhal", n: 3, time: 120,
        intro: [["frost", "The submarine Narwhal is our base for this mission. It needs its supplies."], ["pip", "Your watch has a tractor beam. GRAB a crate, carry it onto the glowing pad and DROP it."]],
        outro: [["torpedo", "Three crates! One of them is snacks. For you. Not for me. I run on batteries."]] },
    ] },
  // ------------------------------------------------------------ 2. Cornwall
  { id: "cornwall", ch: 1, name: "Porthcarrow", country: "Cornwall", flag: "eng", contact: "morwenna", lat: 50.1, lon: -5.5,
    arrive: [["morwenna", "You must be Agent Rory! I'm Morwenna. My gran keeps the lighthouse."], ["rory", "Where's the sea?"], ["morwenna", "That's what everyone's asking. Yesterday the boats were floating. This morning they were sitting on the mud."], ["torpedo", "I do not like mud. Mud is sea that has given up."], ["morwenna", "Gran saw lights in the smugglers' cave last night. Little round lights. Blowing bubbles."], ["pip", "Drips! Start in the harbour, Rory."]],
    leave: [["morwenna", "The tide's coming back in! Look at the boats bob!"], ["frost", "The pump was stamped with a maker's mark: a wave, and the letter U. And its logbook says the next stop is the Bay of Fundy, in Canada."], ["torpedo", "Canada has the biggest tides in the world. Had. Has. I hope has."]],
    missions: [
      { id: "cor1", kind: "cells", lv: 2, title: "Harbour on the Mud", n: 8, time: 150,
        intro: [["morwenna", "There are pearls all over the harbour. On the boats, on the walls, everywhere."], ["pip", "Climb on the boats and jump between them. Mind the mud, it's sticky!"]],
        outro: [["rory", "Eight pearls. And footprints. Little round ones."], ["morwenna", "Drip prints! They go towards the cave."]] },
      { id: "cor2", kind: "stealth", lv: 1, title: "Smugglers' Cove", time: 150,
        intro: [["morwenna", "The cave is round the point. Two Drips with lanterns are guarding it."], ["pip", "Stay out of their yellow light. Sneak behind the rocks to the cave mouth."]],
        outro: [["rory", "I'm in. There's a pipe going down into the water. It's humming."], ["pip", "A pump! Something is pumping the sea away from here."]] },
      { id: "cor3", kind: "cells", lv: 2, title: "Lighthouse Climb", n: 7, time: 180,
        intro: [["morwenna", "Gran says the lighthouse lamp has gone funny. It's flashing pearls instead of light."], ["pip", "The stairs wind round and round inside. Collect the pearls all the way to the top."]],
        outro: [["rory", "From up here I can see the whole cove. And a boat with no lights, going out to sea."], ["morwenna", "Smugglers? Or Drips?"]] },
      { id: "cor4", kind: "morse", lv: 1, title: "Lamp Signals", time: 150,
        intro: [["morwenna", "Look! Somebody on that boat is flashing a lamp. Long and short flashes."], ["pip", "That's Morse code. Each letter is a pattern of flashes. Use the chart and work out the message!"]],
        outro: [["rory", "It says: PUMP ONE FULL. SEND TO FUNDY."], ["pip", "Somebody's sending the sea away. Let's switch off that pump first."]] },
      { id: "cor5", kind: "dive", lv: 2, title: "The Sea Cave", n: 6, time: 180,
        intro: [["pip", "The pump is at the bottom of the flooded part of the cave. Dive in and follow the pearls down."], ["torpedo", "It is too narrow for me. I will wait here and be brave."], ["pip", "Watch your air. There's a bubble stream halfway down."]],
        outro: [["rory", "Pump off! The water's stopped going down the pipe."], ["undertow", "Who switched off my pump?"], ["rory", "Who said that?"], ["undertow", "Captain Undertow. Remember the name, little diver. The tide is turning."]] },
      { id: "cor6", kind: "boatchase", lv: 1, title: "Smugglers' Chase", n: 3, time: 150,
        intro: [["morwenna", "That boat with no lights is getting away! It's full of pearls!"], ["pip", "Take the jet-ski. Catch up and bump it three times!"]],
        outro: [["rory", "Got it! The Drips jumped overboard. Blub, blub, blub."], ["morwenna", "And the pearls are going back into the sea. Look, the tide's coming in!"]] },
    ] },
  // ------------------------------------------------------------ 3. Bay of Fundy
  { id: "fundy", ch: 1, name: "Bay of Fundy", country: "Canada", flag: "ca", contact: "emile", lat: 45.8, lon: -64.6,
    arrive: [["emile", "Bonjour, Agent Rory! I'm Émile. Welcome to the Bay of Fundy."], ["emile", "Twice a day the tide here goes up higher than a house. Or it did."], ["rory", "Those rocks look like giant flowerpots."], ["emile", "The Flowerpot Rocks. The sea carved them. Now it's gone and they look lonely."], ["torpedo", "I know how they feel. I have been out of the water for eleven minutes."], ["pip", "Captain Undertow's logbook said Fundy. Let's find her pump."]],
    leave: [["emile", "Here comes the tide! It's racing in. Merci, Rory, merci, TORPEDO!"], ["frost", "Undertow's boat got away, heading south. The tide gauge caught its radio: the Panama Canal."], ["bolt", "A canal is a river that went to school."]],
    missions: [
      { id: "fun1", kind: "cells", lv: 2, title: "Flowerpot Rocks", n: 8, time: 180,
        intro: [["emile", "The Drips have hidden pearls on top of the Flowerpot Rocks."], ["pip", "Use the bounce pads to get up there. Hop from rock to rock!"]],
        outro: [["rory", "Eight! These pearls are heavy. Full of tide."], ["emile", "We need to put the tide back in the bay. Maybe the old tide mill can help."]] },
      { id: "fun2", kind: "tide", lv: 1, title: "The Tide Mill", time: 180,
        intro: [["emile", "The old mill has sluice gates. When the pond fills, the wheel turns and powers the tide gauge."], ["pip", "Open and shut the gates to get the water up to the line in the mill pond."]],
        outro: [["emile", "The wheel's turning! The gauge is waking up."], ["pip", "It says the water is being pumped out of the bay from somewhere on the mudflats."]] },
      { id: "fun3", kind: "roundup", lv: 2, title: "Mudflat Drips", n: 5, time: 120,
        intro: [["emile", "There they are! Drips, digging holes in the mudflats."], ["pip", "They're planting pumps! Bubble them all before they finish."]],
        outro: [["bolt", "Five Drips in bubbles. They are floating away towards the sea. There is no sea."], ["emile", "They'll just float for a while then."]] },
      { id: "fun4", kind: "circuit", lv: 2, title: "Wake the Tide Gauge", time: 180,
        intro: [["emile", "The gauge needs power to track the pumps. The wires got muddled up."], ["pip", "Turn the tiles so the power runs from the mill to the gauge."]],
        outro: [["pip", "It's picked up the big pump. It's on a barge just off the shore road!"], ["emile", "And somebody's driving away from the mill with the crank handle!"]] },
      { id: "fun5", kind: "chase", lv: 2, title: "Shore Road Chase", n: 3, time: 150,
        intro: [["emile", "A Drip in a pickup truck! It's got the crank for the barge pump."], ["pip", "Take the buggy. Three bumps and it'll drop it!"]],
        outro: [["rory", "Got the crank! Now let's get that barge."], ["torpedo", "Barges are just lazy boats."]] },
      { id: "fun6", kind: "stack", lv: 2, title: "Fix the Fish Weir", n: 4, time: 180,
        intro: [["emile", "When the tide comes back it'll need somewhere to go. The old fish weir is knocked over."], ["pip", "Carry the stones back onto the glowing spots with your tractor beam."]],
        outro: [["emile", "Perfect! Now the bay is ready for its tide."], ["rory", "And the barge pump is switched off. Listen!"]] },
    ] },
  // ------------------------------------------------------------ 4. Panama Canal
  { id: "panama", ch: 1, name: "Panama Canal", country: "Panama", flag: "pa", contact: "valeria", lat: 9.0, lon: -79.6,
    arrive: [["valeria", "¡Hola, Agent Rory! I'm Valeria. My dad is a canal pilot. He steers the big ships through."], ["rory", "Why is that ship stuck?"], ["valeria", "The locks are running dry. Every ship between the oceans is stuck."], ["torpedo", "I will push them. I am small but I am determined."], ["pip", "Undertow is up to something in the lock machinery. Let's get the ships moving."]],
    leave: [["valeria", "The ships are moving! Dad says gracias. He's never been so happy to be in a queue."], ["frost", "The barge you caught was carrying pearls to the Galápagos Islands. Out in the Pacific."], ["bolt", "The Galápagos have giant tortoises. I would like to race one. I think I would win. Just."]],
    missions: [
      { id: "pan1", kind: "tide", lv: 2, title: "Fill the Locks", time: 200,
        intro: [["valeria", "The locks are like steps for ships. Each chamber fills from the one above."], ["pip", "Open the valves in the right order to fill each chamber in turn."]],
        outro: [["valeria", "The ship's floating again! Look at it rise!"]] },
      { id: "pan2", kind: "cells", lv: 3, title: "Ship in the Lock", n: 8, time: 200,
        intro: [["valeria", "The Drips hid pearls on the cargo ship. It's rising in the lock right now!"], ["pip", "Jump across onto its deck and climb up the containers."]],
        outro: [["rory", "One of these pearls has a label. PROPERTY OF CAPTAIN UNDERTOW."], ["valeria", "She's labelling the sea? That's so rude."]] },
      { id: "pan3", kind: "stealth", lv: 2, title: "The Control House", time: 180,
        intro: [["valeria", "Drips have taken over the lock control house."], ["pip", "Sneak past their searchlights and get to the control desk."]],
        outro: [["rory", "The desk shows valves being opened at night. Draining the lake into barges."], ["pip", "The valves are under the lock gates. That means lasers, probably."]] },
      { id: "pan4", kind: "lasers", lv: 2, title: "Gate Machinery", time: 150,
        intro: [["valeria", "The tunnel under the gates is full of red beams now."], ["pip", "Jump the low ones, wait for the moving ones to pass. You know how."]],
        outro: [["rory", "Valves shut! The lake stays in the lake."], ["valeria", "A barge is racing away down the canal!"]] },
      { id: "pan5", kind: "boatchase", lv: 2, title: "Canal Chase", n: 3, time: 150,
        intro: [["valeria", "It's heading for the Pacific! Take my dad's speedboat!"], ["pip", "Three bumps. Mind the channel markers."]],
        outro: [["torpedo", "The barge has stopped. It says sorry. In bubbles."], ["valeria", "It's full of pearls! And a map of some islands."]] },
      { id: "pan6", kind: "drone", lv: 2, title: "Over the Rainforest", time: 150,
        intro: [["pip", "BOLT, fly up over the rainforest and look for more Drips from the air."], ["bolt", "Rocket feet: go. Rocket feet: going."]],
        outro: [["bolt", "I see toucans. I see monkeys. I see a Drip on a raft going towards the sea. It is very slow."], ["pip", "Following it is easy then. Next stop, the Galápagos!"]] },
    ] },
  // ------------------------------------------------------------ 5. Galápagos
  { id: "galapagos", ch: 1, name: "Galápagos Islands", country: "Ecuador", flag: "ec", contact: "mateo", lat: -0.7, lon: -90.3,
    arrive: [["mateo", "¡Bienvenido, Agent Rory! I'm Mateo. I help look after the giant tortoises."], ["rory", "That tortoise is enormous."], ["mateo", "That's Doña Rosa. She's a hundred and twenty years old. And she's worried."], ["torpedo", "Why is she worried?"], ["mateo", "The rock pools are drying up and the baby turtles can't reach the sea. And I've seen iguanas that go blub."], ["pip", "Drips in disguise! Let's help the babies first."]],
    leave: [["mateo", "The pools are full and the babies made it! Doña Rosa says thank you. Slowly."], ["frost", "The disguised Drips had orders for Hawaii. They're using the volcanoes for something. Hot water, perhaps."], ["torpedo", "Hot water? I am a submarine, not a teapot."]],
    missions: [
      { id: "gal1", kind: "escort", lv: 1, title: "Baby Turtle Run", n: 4, time: 180,
        intro: [["mateo", "The baby turtles hatched but the sea is too far away now."], ["pip", "Walk in front of a baby and it'll follow you. Lead all four down to the water. Watch out for the crabs!"]],
        outro: [["mateo", "They're swimming! Little flippers everywhere!"]] },
      { id: "gal2", kind: "roundup", lv: 2, title: "Iguana or Drip?", n: 5, time: 150,
        intro: [["mateo", "Some of those marine iguanas are Drips in costumes."], ["pip", "Real iguanas sneeze salt. Drips blow bubbles. Bubble the fake ones!"]],
        outro: [["bolt", "The costumes were very good. I would like one."]] },
      { id: "gal3", kind: "dive", lv: 2, title: "Sea Lion Swim", n: 7, time: 180,
        intro: [["mateo", "The sea lions have been playing with pearls in the bay. They think they're toys."], ["pip", "Dive in and collect them. The sea lions are friendly. Very friendly."]],
        outro: [["rory", "A sea lion just kissed my helmet."], ["torpedo", "That is how they say thank you. Or hello. Or I think you are a fish."]] },
      { id: "gal4", kind: "cells", lv: 3, title: "Lava Fields", n: 8, time: 180,
        intro: [["mateo", "The rest of the pearls are up on the old lava fields. It's a scramble."], ["pip", "Jump from rock to rock, and use the steam vents to bounce up high."]],
        outro: [["rory", "That's all of them. And there's a radio mast up here that doesn't belong."], ["pip", "A Drip mast! It needs a code to switch off."]] },
      { id: "gal5", kind: "codes", lv: 2, title: "The Drip Mast", time: 150,
        intro: [["pip", "The mast plays a tune before it unlocks. Watch the lights and play it back."]],
        outro: [["pip", "Mast off! Its last message went to a salvage boat in the bay."]] },
      { id: "gal6", kind: "salvage", lv: 1, title: "Raise the Pump", n: 3, time: 200,
        intro: [["torpedo", "My turn! The Drips dropped the parts of a pump on the sea bed."], ["pip", "TORPEDO has a claw. Drive over a part, press USE to grab it, and carry it up to the barge's glowing ring."]],
        outro: [["torpedo", "I am a salvage submarine now. I have a new job title."], ["bolt", "I also have a job title. Mine is BOLT."]] },
    ] },
  // ------------------------------------------------------------ 6. Hawaii
  { id: "hawaii", ch: 1, name: "Big Island", country: "Hawaii", flag: "us", contact: "kai", lat: 19.4, lon: -155.3,
    arrive: [["kai", "Aloha, Agent Rory! I'm Kai. I surf, mostly. And I help at the volcano centre."], ["rory", "Is that lava going into the sea?"], ["kai", "It's been doing that for thousands of years. It makes new land. But now there's less sea to meet it."], ["torpedo", "I will stay well away from the lava. I have a yellow paint job to think about."], ["pip", "Undertow's pumps are using the volcano's heat. Let's find them."]],
    leave: [["kai", "The waves are back! Look at those sets rolling in. Mahalo, Rory!"], ["frost", "The Drip Digger's memory shows a pipe on the Great Barrier Reef, in Australia. The biggest pump yet."], ["bolt", "The reef is alive. It is made of tiny animals. Billions. I cannot count that high. I tried."]],
    missions: [
      { id: "haw1", kind: "surf", lv: 1, title: "Surf's Up", n: 10, time: 120,
        intro: [["kai", "Pearls are floating on the waves out past the reef. Surf's the fastest way to them!"], ["pip", "Steer the board along the wave and grab the pearls."]],
        outro: [["kai", "You're a natural! Totally shredded it."], ["rory", "I don't know what that means but thank you."]] },
      { id: "haw2", kind: "cells", lv: 3, title: "Lava Coast", n: 8, time: 180,
        intro: [["kai", "The pearls are on the black lava rocks along the coast. Some of them are still warm."], ["pip", "Bounce on the steam vents to get high. And don't touch the glowing lava!"]],
        outro: [["rory", "There's a tunnel in the rock with a pipe going in."], ["kai", "That's an old lava tube. Like a cave the lava made."]] },
      { id: "haw3", kind: "lasers", lv: 3, title: "The Lava Tube", time: 150,
        intro: [["pip", "Undertow's put lasers in the lava tube. Beams and more beams."], ["kai", "Be careful, Rory. It's hot in there too."]],
        outro: [["rory", "The pipe ends in a machine with a drill. It says DRIP DIGGER on it."], ["pip", "That sounds big."]] },
      { id: "haw4", kind: "dive", lv: 3, title: "Turtle Reef", n: 7, time: 180,
        intro: [["kai", "The green sea turtles are hiding at the reef. They say there's pearls everywhere down there."], ["pip", "Dive in! There are bubble streams on the reef."]],
        outro: [["rory", "The turtles let me swim with them."], ["kai", "They like you. They're good judges of people."]] },
      { id: "haw5", kind: "boatchase", lv: 3, title: "Cliff Chase", n: 3, time: 150,
        intro: [["kai", "A Drip boat is towing a pearl net along the cliffs! Take my jet-ski!"], ["pip", "Watch out for the rocks at the bottom of the cliffs."]],
        outro: [["kai", "Net cut! The pearls are sinking back where they belong."], ["undertow", "Enough! Drip Digger, show them what you can do."]] },
      { id: "haw6", kind: "boss", lv: 1, title: "The Drip Digger", n: 3, time: 180,
        intro: [["undertow", "My Drip Digger drills through lava rock like butter. Imagine what it does to spies."], ["pip", "When it stomps, a ring of steam rolls out. JUMP over it! Then zap it from behind."]],
        outro: [["rory", "It's popped into a bubble!"], ["undertow", "Oh, very clever. You've stopped one little pump. My Engine is a hundred times bigger, and you'll never reach it."], ["torpedo", "Engine? What engine?"], ["pip", "I don't know. But I don't like the sound of it."]] },
    ] },
  // ------------------------------------------------------------ 7. Great Barrier Reef
  { id: "reef", ch: 1, name: "Great Barrier Reef", country: "Australia", flag: "au", contact: "ruby", lat: -18.3, lon: 147.7,
    arrive: [["ruby", "G'day, Rory! I'm Ruby. My mum studies the coral here."], ["ruby", "The reef's drying out at low tide, and low tide keeps getting lower."], ["rory", "It's beautiful. Look at all the colours."], ["ruby", "It's the biggest living thing in the world. And something is sucking the water off it."], ["torpedo", "This is what I was built for. Coral! Fish! Proper sea!"], ["pip", "The Digger pointed at a pipe on the outer reef. Suit up, Rory."]],
    leave: [["ruby", "The water's back over the reef! The coral's happy. The fish are happy. I'm happy!"], ["frost", "The pipe's records show a whole fleet of cargo ships in Hong Kong. Undertow is shipping pearls somewhere."], ["bolt", "Hong Kong at night has the best lights. I will match them."]],
    missions: [
      { id: "reef1", kind: "dive", lv: 3, title: "The Reef Wall", n: 8, time: 210,
        intro: [["ruby", "The outer reef drops off like a cliff. The pearls are all down the wall."], ["pip", "It's deep. Use the bubble streams on the way down."]],
        outro: [["rory", "It goes down and down into the blue."], ["ruby", "There's the pipe! In the canyon."]] },
      { id: "reef2", kind: "subrings", lv: 2, title: "Coral Canyon", time: 180,
        intro: [["torpedo", "Climb in, Rory. The canyons are twisty. I have excellent turning."], ["pip", "Follow the rings through the coral to the pipe."]],
        outro: [["torpedo", "Not one scratch on the coral. Not one scratch on me."], ["rory", "The pipe goes into the dark."]] },
      { id: "reef3", kind: "sonar", lv: 1, title: "Into the Pipe", n: 5, time: 200,
        intro: [["pip", "It's pitch black in there. TORPEDO has sonar!"], ["torpedo", "Press USE to ping. I will make a noise and the walls will light up for a moment."], ["pip", "Find the five markers the Drips left inside."]],
        outro: [["rory", "The pipe opens out. There's a pump bigger than a house."], ["pip", "We need to block its intake."]] },
      { id: "reef4", kind: "salvage", lv: 2, title: "Block the Pipe", n: 4, time: 200,
        intro: [["torpedo", "Rocks! Big ones. I will carry them. You steer, I strain."], ["pip", "Drop four boulders into the pipe's mouth, on the glowing ring."]],
        outro: [["rory", "Blocked! The water's stopped going down the pipe."], ["ruby", "Some Drips are still guarding the pump though."]] },
      { id: "reef5", kind: "roundup", lv: 3, title: "Drip Divers", n: 6, time: 150,
        intro: [["ruby", "The Drips are swimming round the pump."], ["pip", "Swim up close and zap them into bubbles. They're slippery underwater."]],
        outro: [["bolt", "Six bubbles floating up. It looks like a lemonade."]] },
      { id: "reef6", kind: "escort", lv: 2, title: "Lost Clownfish", n: 3, time: 180,
        intro: [["ruby", "The pump scared the clownfish out of their anemones. They're lost!"], ["pip", "Swim near one and it'll follow you. Lead each one home to its anemone."]],
        outro: [["ruby", "Everybody's home. Mum's going to be so pleased."]] },
    ] },
  // ------------------------------------------------------------ 8. Hong Kong
  { id: "hongkong", ch: 1, name: "Hong Kong", country: "China", flag: "hk", contact: "ming", lat: 22.3, lon: 114.2,
    arrive: [["ming", "Agent Rory! I'm Ming. My grandpa sails the last red-sail junk in the harbour."], ["rory", "The lights are amazing."], ["ming", "Every night at eight they do a light show. But tonight the harbour is half empty and the ferries are scraping the bottom."], ["torpedo", "I will scrape nothing. I am very careful."], ["pip", "Undertow's cargo ships are here. Let's find out where they're going."]],
    leave: [["ming", "The harbour's full again! Grandpa's junk is sailing tonight."], ["frost", "The cargo was going to the Maldives. Islands are popping up there where there was only sea."], ["torpedo", "New islands. Undertow is making land. I do not approve."]],
    missions: [
      { id: "hk1", kind: "cells", lv: 3, title: "Junk Hop", n: 8, time: 240,
        intro: [["ming", "The Drips have hidden pearls on the junks sailing round the harbour!"], ["pip", "Jump aboard as they pass the pier, and hop off when you've got them."]],
        outro: [["ming", "Grandpa says you jump like a harbour cat."], ["rory", "Thank you. I think."]] },
      { id: "hk2", kind: "stealth", lv: 3, title: "Cargo Ship", time: 200,
        intro: [["ming", "That's the ship. The containers are full of pearls."], ["pip", "Sneak along the deck past the searchlights and find the captain's log."]],
        outro: [["rory", "Got it! The log is in code. Morse code."], ["pip", "There's a radio room on the bridge. Let's listen in."]] },
      { id: "hk3", kind: "morse", lv: 2, title: "Radio Room", time: 180,
        intro: [["pip", "Undertow is sending a message. Listen to the beeps and match them to the chart."]],
        outro: [["rory", "It says: ALL PEARLS TO MALDIVES. THE ISLANDS ARE READY."], ["pip", "Islands made of pearls? What is she up to?"]] },
      { id: "hk4", kind: "codes", lv: 3, title: "Container Lock", time: 150,
        intro: [["ming", "The biggest container has a lock that plays a tune."], ["pip", "Watch it light up, then play it back."]],
        outro: [["rory", "It's full of machinery. Parts of something huge. Stamped TIDAL ENGINE."], ["torpedo", "There is the engine. I still do not like the sound of it."]] },
      { id: "hk5", kind: "drone", lv: 3, title: "Skyline Flight", time: 180,
        intro: [["ming", "A Drip is signalling from the top of a skyscraper!"], ["pip", "BOLT, fly up through the rings between the towers and stop it."]],
        outro: [["bolt", "The Drip was flashing a torch. I asked it to stop. It stopped. It said blub."]] },
      { id: "hk6", kind: "boatchase", lv: 3, title: "Harbour Chase", n: 3, time: 180,
        intro: [["ming", "The cargo ship's launch is escaping with the engine plans!"], ["pip", "Chase it through the harbour. Mind the junks!"]],
        outro: [["rory", "Plans got! They show islands in the Maldives with pipes going down into the sea."], ["ming", "Good luck, Rory! Come back for the light show!"]] },
    ] },
  // ------------------------------------------------------------ 9. Maldives
  { id: "maldives", ch: 1, name: "The Maldives", country: "Maldives", flag: "mv", contact: "aisha", lat: 4.2, lon: 73.5,
    arrive: [["aisha", "Welcome, Agent Rory! I'm Aisha. My mum flies the seaplanes between the islands."], ["rory", "Those islands look brand new."], ["aisha", "They are! They weren't there last week. The sea has gone down so far that sandbanks are poking out."], ["torpedo", "The lagoon is so shallow. I can feel my tummy on the sand."], ["pip", "Undertow said the islands were ready. Ready for what?"]],
    leave: [["aisha", "The sandbanks are going back under. That's how it should be!"], ["undertow", "Enough, Agent Rory. If you want your precious sea, come and get it. I'll be waiting in the Bermuda Triangle."], ["frost", "The Bermuda Triangle. Where ships go missing. Be careful, Rory."]],
    missions: [
      { id: "mal1", kind: "cells", lv: 3, title: "New Islands", n: 8, time: 200,
        intro: [["aisha", "There are pearls on all the new sandbanks."], ["pip", "Swim or jump between them. Some of the water is deep in the channels!"]],
        outro: [["rory", "The sandbanks are full of pipes. They're pumping the lagoon dry from underneath."]] },
      { id: "mal2", kind: "tide", lv: 3, title: "Lagoon Sluices", time: 220,
        intro: [["aisha", "The pipes have sluice gates. If we can open the right ones, the water flows back."], ["pip", "Get every lagoon up to its line. Some gates fill two at once!"]],
        outro: [["aisha", "The lagoon is filling! The fish are coming back in."]] },
      { id: "mal3", kind: "dive", lv: 4, title: "Manta Point", n: 8, time: 240,
        intro: [["aisha", "The manta rays are gathering at the cleaning station. There's a pump right in the middle."], ["pip", "Dive down and collect the pearls round it. The mantas won't hurt you. They're gentle giants."]],
        outro: [["rory", "A manta ray just flew right over me. It was like a spaceship."]] },
      { id: "mal4", kind: "roundup", lv: 3, title: "Villa Drips", n: 6, time: 150,
        intro: [["aisha", "The Drips are hiding in the water villas!"], ["pip", "Run along the jetties and bubble them."]],
        outro: [["bolt", "They were watching television. It was a programme about the sea. They were taking notes."]] },
      { id: "mal5", kind: "circuit", lv: 3, title: "Island Pumps", time: 200,
        intro: [["pip", "All the island pumps are wired to one control box. Turn the tiles to cut the power."]],
        outro: [["pip", "Pumps off! But a seaplane is taking off with Undertow's maps!"]] },
      { id: "mal6", kind: "boatchase", lv: 4, title: "Seaplane Taxi", n: 3, time: 150,
        intro: [["aisha", "It's still on the water! Catch it before it takes off!"], ["pip", "Bump its floats three times and it'll have to stop."]],
        outro: [["aisha", "It's stopped! The Drip pilot is waving a white flag. A very small one."], ["rory", "And here are the maps. Every pump she has leads to one place. The Bermuda Triangle."]] },
    ] },
  // ------------------------------------------------------------ 10. Bermuda
  { id: "bermuda", ch: 1, name: "The Bermuda Triangle", country: "Atlantic Ocean", flag: "bm", contact: "nia", lat: 25.0, lon: -71.0,
    arrive: [["nia", "Agent Rory? I'm Nia, Bermuda Coast Guard cadet. The compasses have been spinning for a week."], ["rory", "What is that?"], ["nia", "That's Undertow's base. It floats. It's as big as a town."], ["torpedo", "It is also ugly. I am sorry, but it is."], ["undertow", "Welcome aboard, Agent Rory. Do wipe your flippers."], ["pip", "This is it, Rory. Find out what the Tidal Engine is, and stop it."]],
    leave: [["rory", "She's gone. The whole base is sinking after her!"], ["torpedo", "She is going down. Deep. Deeper than I have ever been."], ["frost", "Then that's where we follow. Get some rest, Agent Rory. Tomorrow, we go into the abyss."], ["pip", "End of Act One. Act Two: Into the Abyss is coming soon!"]],
    missions: [
      { id: "ber1", kind: "stealth", lv: 4, title: "Deck Patrol", time: 200,
        intro: [["nia", "The deck is crawling with Drip guards."], ["pip", "Sneak past the searchlights to the main hatch."]],
        outro: [["rory", "I'm in. It's a huge hall full of pipes."]] },
      { id: "ber2", kind: "lasers", lv: 4, title: "Pump Hall", time: 180,
        intro: [["pip", "Lasers everywhere. Undertow doesn't want you in the pump hall."], ["torpedo", "I would help but I am a submarine and this is a corridor."]],
        outro: [["rory", "Past them! There's a control room on the far side."]] },
      { id: "ber3", kind: "circuit", lv: 4, title: "The Engine Room", time: 220,
        intro: [["pip", "This panel sends power to every pump in the world. Cut it!"]],
        outro: [["pip", "Pumps off, everywhere! Harbours are filling up all over the world!"], ["undertow", "You think this is my Engine? This is a pantry. My Engine is where you will never follow."]] },
      { id: "ber4", kind: "sonar", lv: 2, title: "Compass Chaos", n: 6, time: 220,
        intro: [["nia", "The compasses are useless and the fog's too thick to see."], ["torpedo", "Sonar! Ping with USE and follow the markers under the base."]],
        outro: [["rory", "There's her submarine, under the base. It's shaped like a squid."]] },
      { id: "ber5", kind: "boss", lv: 2, title: "The Kraken", n: 4, time: 240,
        intro: [["undertow", "Meet my Kraken. It's a robot squid, and it's very cross."], ["pip", "Jump the rings, and zap its battery pack when it turns round. Four hits!"]],
        outro: [["undertow", "My Kraken! Very well. Keep your little harbours. The ocean is mine."], ["rory", "She's diving! The whole base is going under!"]] },
      { id: "ber6", kind: "subchase", lv: 1, title: "Follow Her Down", n: 6, time: 200,
        intro: [["torpedo", "In you get, Rory! We are not losing her now."], ["pip", "Follow her submarine down through the sinking base. Stay close, through the rings she leaves behind!"]],
        outro: [["torpedo", "She is gone. Down there. Where it is dark."], ["rory", "We'll find her, TORPEDO. Whatever the Tidal Engine is."]] },
    ] },
];

export const CREDITS = [
  ["Agent Rory: Deep Red", "A game for Rory"],
  ["Story, code and levels", "Written with Claude"],
  ["3D", "three.js, with bloom, SMAA and AgX tone mapping, and a sea of its own"],
  ["Physics", "Rapier: Rory, TORPEDO, the jet-ski and every tumbling crate"],
  ["Music and sound", "Tone.js synthesizers, played live"],
  ["BOLT and the Drips", "RobotExpressive by Tomás Laulhé (Quaternius), CC0"],
  ["Voices", "Kokoro-82M, an open neural voice model"],
  ["Coastlines", "Natural Earth, via world-atlas"],
  ["Starring", "Agent Rory, BOLT, TORPEDO, Pip, Admiral Frost, and Captain Undertow"],
];

export const ALL = PLACES.flatMap(p => p.missions.map(m => ({ ...m, place: p.id })));
export function placeOf(mid) { return PLACES.find(p => p.missions.some(m => m.id === mid)); }
