// Agent Rory: Deep Red — the cast, the acts, the places and every mission's
// lines. Captain Undertow is draining the sea; Rory, BOLT and TORPEDO get it back.

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS = {
  rory:     { name: "Rory", voice: V("m", "en-GB", 1.15, 1.05), look: { skin: 0xf3cfae, hair: 0x6b4423, eyes: 0x3b5f8a, coat: 0x16324f, trousers: 0x1a1f2a, shirt: 0xf4f6fa, tie: 0x0e1a2c, kid: true, earpiece: true, hairStyle: "rory" } },
  bolt:     { name: "BOLT", side: "bolt", robot: "bolt", voice: V("m", "en-GB", 1.6, 1.15), bg: "#0e3050" },
  torpedo:  { name: "TORPEDO", side: "bolt", robot: "torpedo", voice: V("f", "en-GB", 1.45, 1.1), bg: "#1a3a10" },
  frost:    { name: "Admiral Frost", voice: V("m", "en-GB", 0.7, 0.92), look: { skin: 0xe8c8a8, hair: 0xe8e8e8, coat: 0x1a2440, trousers: 0x1a2440, shirt: 0xf0f0f0, tie: 0x2a4a8a, moustache: 0xe8e8e8, hairStyle: "short" } },
  pip:      { name: "Pip", voice: V("f", "en-GB", 1.25, 1.05), look: { skin: 0xf0c8a0, hair: 0xd06a2a, coat: 0x2a8a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", glasses: 0x1a1a1a } },
  undertow: { name: "Captain Undertow", side: "villain", voice: V("f", "en-GB", 0.85, 0.92), look: { skin: 0xe0c0b0, hair: 0x1a1a2a, coat: 0x8a1a2a, trousers: 0x1a1a24, shirt: 0xf0e8d8, tie: 0xd8a040, hairStyle: "long", hat: "cap", hatColor: 0x8a1a2a, stern: true } },
  drip:     { name: "Drip", side: "villain", robot: "drip", voice: V("m", "en-GB", 1.7, 1.2), bg: "#0a2a3a" },
  silt:     { name: "Professor Silt", side: "villain", voice: V("m", "en-GB", 0.8, 0.9), look: { skin: 0xe8d0b8, hair: 0xd8d8d0, coat: 0xd8c8a0, trousers: 0x5a4a3a, shirt: 0xf4f4f0, tie: 0x6a3a2a, beard: 0xd8d8d0, glasses: 0x3a2a1a, hairStyle: "bald" } },
  morwenna: { name: "Morwenna", voice: V("f", "en-GB", 0.95, 0.95), look: { skin: 0xf0d0b8, hair: 0xd8d8d8, coat: 0xf0d040, trousers: 0x2a3a4a, shirt: 0xf4f4f4, hairStyle: "bun", hat: "straw" } },
  maddie:   { name: "Maddie", voice: V("f", "en-CA", 1.2, 1.05), look: { skin: 0xf0c8a8, hair: 0xa84a2a, coat: 0xd82a2a, trousers: 0x2a3a5a, kid: true, hairStyle: "ponytail", hat: "cap", hatColor: 0x2a2a2a } },
  mateo:    { name: "Mateo", voice: V("m", "es-MX", 1.2, 1.05), look: { skin: 0xc09060, hair: 0x1a1010, coat: 0x2a8ad8, trousers: 0xf0e8d0, kid: true, hairStyle: "short", hat: "hardhat", hatColor: 0xffc020 } },
  isabela:  { name: "Isabela", voice: V("f", "es-ES", 1.2, 1.0), look: { skin: 0xc8946a, hair: 0x2a1a10, coat: 0x3a9a4a, trousers: 0xe8e0c8, kid: true, hairStyle: "long" } },
  kai:      { name: "Kai", voice: V("m", "en-US", 1.2, 1.05), look: { skin: 0xc89a70, hair: 0x14100c, coat: 0xff8a2a, trousers: 0x2a8ad8, kid: true, hairStyle: "spiky" } },
  tilly:    { name: "Tilly", voice: V("f", "en-AU", 1.2, 1.05), look: { skin: 0xf0c8a0, hair: 0xe8c860, coat: 0x2ad0d0, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", hat: "cap", hatColor: 0xffffff } },
  wing:     { name: "Wing", voice: V("m", "zh-HK", 1.2, 1.05), look: { skin: 0xf0d4b4, hair: 0x14141a, coat: 0xd82a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "short" } },
  aisha:    { name: "Aisha", voice: V("f", "en-IN", 1.2, 1.0), look: { skin: 0xb07a50, hair: 0x14100c, coat: 0xf0d040, trousers: 0x2a6ad8, kid: true, hairStyle: "bun" } },
};

// Mission kinds (see missions.js): cells, roundup, stack, tractor, drone, lasers,
// chase, stealth, boss, circuit, codes, drive, and Deep Red's own: dive, sub,
// boat, tide, valves, morse. lv is the difficulty (1-4). Each place has its own
// level file in levels/.
export const CHAPTERS = [
  { n: 1, title: "The Sea Is Going Down", blurb: "Harbours are draining and the tide has stopped. Somebody is stealing the sea." },
  { n: 2, title: "Into the Abyss", blurb: "Undertow's Tidal Engine is on the deepest floor of the ocean." },
  { n: 3, title: "Red Planet", blurb: "The stolen sea is on its way to Mars. So is Rory." },
];

export const PLACES = [
  { id: "narwhal", ch: 1, name: "The Narwhal", country: "Scotland", flag: "sct", contact: "pip", lat: 57.0, lon: -6.2, sea: true,
    arrive: [["frost", "Agent Rory. The sea is going down."], ["frost", "Harbours are draining. Boats are sitting on mud. And in Canada the tide has simply stopped coming in."], ["pip", "So we're taking the Narwhal to sea. And I've built you a partner for the water. Rory, meet TORPEDO."], ["torpedo", "Hello! I'm a submarine. A small one. The best one."], ["bolt", "I am also here. I am waterproof now. Mostly."], ["torpedo", "Mostly?"], ["bolt", "Mostly."], ["pip", "Training first. Follow the glowing beacons!"]],
    leave: [["frost", "Good work. Now, the first harbour to go dry was a fishing village in Cornwall. The Narwhal will take you."]],
    missions: [
      { id: "nw1", kind: "cells", lv: 1, title: "Crystal School", at: [0, -8], n: 6, time: 90,
        intro: [["pip", "These blue crystals are Tide Crystals. Undertow's machines freeze seawater into them."], ["pip", "Run into them to collect them. Jump with the JUMP button. Grab all six on the dock!"]],
        outro: [["bolt", "Six crystals. I counted them. They are very cold."]] },
      { id: "nw2", kind: "dive", lv: 1, title: "First Dive", at: [10, 6], n: 6, time: 120, air: 40,
        intro: [["pip", "Now the sea. Walk in and you swim. Hold JUMP to go up, DIVE to go down, and the stick swims you along."], ["pip", "Watch the blue air bar! Come up for a breath when it runs low, or swim through a silver bubble to fill it."]],
        outro: [["rory", "It's so quiet down there."], ["torpedo", "Quiet? You should hear the whales. They never stop."]] },
      { id: "nw3", kind: "sub", lv: 1, title: "TORPEDO Time", at: [-14, 6], time: 150,
        intro: [["torpedo", "My turn! Hop in. The stick steers me, JUMP goes up, DIVE goes down."], ["torpedo", "Fly me through the rings under the pen. All of them. Please."]],
        outro: [["torpedo", "Every ring! You're a natural. I'm a natural too."], ["bolt", "I watched from the dock. I did not get wet."]] },
      { id: "nw4", kind: "roundup", lv: 1, title: "Practice Drips", at: [12, -14], n: 4, time: 90,
        intro: [["pip", "Undertow's robots are called Drips. Round, wobbly, and terrible at hide and seek. These are my practice ones."], ["pip", "Your watch fires a bubble. Press USE near a Drip and off it floats!"]],
        outro: [["bolt", "They blow bubbles when they are nervous. They were very nervous."]] },
      { id: "nw5", kind: "tide", lv: 1, title: "Lock School", at: [-8, -14],
        intro: [["pip", "Last one. Undertow's pumps are worked by sluice gates. Tap a gate and the water in the basins beside it moves."], ["pip", "Get every basin up to its target line."]],
        outro: [["frost", "Training complete. Cornwall, Agent Rory. The tide is turning, and not the right way."]] },
    ] },
  { id: "cornwall", ch: 1, name: "Smugglers' Cove", country: "Cornwall", flag: "gb", contact: "morwenna", lat: 50.1, lon: -5.5, sea: true,
    arrive: [["morwenna", "Agent Rory! I'm Morwenna, I keep the lighthouse. Look at the harbour."], ["rory", "The boats are lying on their sides in the mud."], ["morwenna", "The sea went out on Tuesday and never came back. And at night there's a humming from the old smugglers' cave."], ["bolt", "I do not like humming. Unless it is me."], ["pip", "A pump, Rory. Undertow has a pump in that cave. Find it."]],
    leave: [["morwenna", "Look! The water's creeping back over the mud. Thank you, Rory. Thank you, all of you."], ["frost", "That pump was a small one, Agent Rory. The big trouble is in Canada. The Bay of Fundy has the highest tides in the world, and they've stopped."]],
    missions: [
      { id: "cw1", kind: "cells", lv: 2, title: "Harbour Mud", at: [6, -18], n: 8, time: 150,
        intro: [["morwenna", "Crystals everywhere the water used to be. On the mud, on the boats, on the harbour wall."], ["pip", "Climb the leaning boats and jump between them. Eight crystals!"]],
        outro: [["rory", "They were humming too. Like they wanted to go to the cave."], ["morwenna", "Everything round here wants to go to that cave."]] },
      { id: "cw2", kind: "stealth", lv: 1, title: "Cave Watch", at: [-22, -6],
        intro: [["morwenna", "The cave mouth is up the beach. Two Drips with lamps walk round the rocks in front of it."], ["pip", "Keep behind the rocks and out of the yellow light. The cave key is in the silver case at the back."]],
        outro: [["rory", "Got the key! The Drips didn't see a thing."], ["bolt", "One of them looked straight at me. I stood very still. I am good at that."]] },
      { id: "cw3", kind: "lasers", lv: 1, title: "The Pump Room", at: [-40, -20], time: 120,
        intro: [["morwenna", "The pump's inside, past the old smugglers' tunnel. Undertow's filled it with lasers."], ["pip", "Jump the low beams, wait for the moving ones. Same as ever."]],
        outro: [["rory", "The pump! It's got a pipe going straight out to sea, and it's full of crystals."], ["undertow", "Well, well. A little agent in my cave. I'm Captain Undertow, and I'm taking the sea somewhere it'll be appreciated."], ["rory", "The sea belongs here!"], ["undertow", "The sea belongs to whoever listens to it. Drips! Keep him busy."]] },
      { id: "cw4", kind: "circuit", lv: 1, title: "Switch It Off", at: [-42, -32],
        intro: [["pip", "The pump's power box is by the pipe. Turn the tiles till the power runs to the OFF switch."]],
        outro: [["rory", "It's stopped! The pipe's gone quiet."], ["morwenna", "And the sea's coming back into the cove! Listen!"], ["undertow", "One pump, Agent Rory. I have dozens. Drip, take the boat and bring me the crystals."]] },
      { id: "cw5", kind: "boat", lv: 1, title: "Cove Chase", at: [8, -24], n: 3, time: 150,
        intro: [["morwenna", "A Drip's getting away round the cove in a motorboat, with a sack of crystals!"], ["pip", "Take the jet ski. Steer with the stick, JUMP for a boost. Bump it three times!"]],
        outro: [["rory", "Got the crystals back!"], ["torpedo", "Did you see me? I was cheering. Underwater. It's harder than it looks."]] },
      { id: "cw6", kind: "morse", lv: 1, title: "Lighthouse Signal", at: [22, -12],
        intro: [["morwenna", "There's a ship out there flashing at my lighthouse. It's Morse code. Dots and dashes."], ["pip", "The chart on the lamp shows the letters. Watch each flash and tap the letter it spells."]],
        outro: [["rory", "F, U, N, D, Y. Fundy! The ship's going to the Bay of Fundy."], ["frost", "Then so are you, Agent Rory. Full speed, Narwhal."]] },
    ] },
  { id: "fundy", ch: 1, name: "Bay of Fundy", country: "Canada", flag: "ca", contact: "maddie", lat: 45.6, lon: -64.6, sea: true,
    arrive: [["maddie", "Hi! I'm Maddie. My dad runs the tide gauge. It's been stuck on LOW for a week!"], ["rory", "Those rocks look like giant flowerpots."], ["maddie", "They are! Well, they're called that. Normally the sea comes up to their tops and back down again twice a day. The highest tides in the world."], ["bolt", "The sea has stopped doing its job. I will have a word."], ["pip", "Undertow's pump here is much bigger, Rory. It's in the old tide mill."]],
    leave: [["maddie", "The tide's coming in! It's coming in really fast! Run!"], ["rory", "That was the biggest wave I've ever seen."], ["frost", "The mill's papers say the crystals are shipped through the Panama Canal. And the canal's locks are running dry."]],
    missions: [
      { id: "fd1", kind: "cells", lv: 2, title: "Flowerpot Rocks", at: [10, 16], n: 8, time: 160,
        intro: [["maddie", "The crystals are on the flowerpot rocks, right up on top where the trees grow."], ["pip", "Bounce up on the pads and jump from rock to rock. The mud between them is fine to walk on. Eight!"]],
        outro: [["rory", "You can see the whole bay from up here. And it's all mud."], ["maddie", "It's supposed to be water. All of it."]] },
      { id: "fd2", kind: "valves", lv: 1, title: "The Tide Gauge", at: [-16, 13],
        intro: [["maddie", "Dad's tide gauge has pipes full of valves. Undertow's Drips turned them all wrong."], ["pip", "Tap a valve to turn it. Every gauge needs to sit in the green."]],
        outro: [["maddie", "It's reading properly! And it says the water's all going... into the mill."]] },
      { id: "fd3", kind: "roundup", lv: 2, title: "Mudflat Drips", at: [-6, -18], n: 5, time: 120,
        intro: [["maddie", "Drips! On the mudflats! They're picking up clams!"], ["pip", "These ones run. Corner them against the rocks and ZAP."]],
        outro: [["bolt", "They ran in circles. Round ones. Because they are round."], ["maddie", "One of them dropped a gate key. For the mill."]] },
      { id: "fd4", kind: "dive", lv: 2, title: "The Tide Pool", at: [32, -4], n: 7, time: 150, air: 40,
        intro: [["maddie", "The one place with water left is the big tide pool under the cliff. There are crystals right at the bottom."], ["pip", "Watch your air, Rory. Come up when the bar goes red, and use the bubbles!"]],
        outro: [["rory", "There were starfish down there. And a lobster. He waved."], ["torpedo", "Lobsters don't wave. He was warning you about the mill."]] },
      { id: "fd5", kind: "tide", lv: 2, title: "Tide Mill Sluices", at: [-26, -4],
        intro: [["maddie", "The mill's got six sluice gates. Undertow rigged them so the water only ever goes one way. Out."], ["pip", "Set every basin to its line and the mill runs backwards. The water comes home."]],
        outro: [["rory", "It's turning! The wheel's going the other way!"], ["undertow", "My mill! Do you know how long it took to get that wheel to run backwards? Drip, the jet boat. Go, go, go!"]] },
      { id: "fd6", kind: "boat", lv: 1, title: "Tidal Bore", at: [10, 20], n: 3, time: 150,
        intro: [["maddie", "The tide's coming back all at once, in one big wave. And a Drip's riding it up the river in a jet boat!"], ["pip", "Take the other jet boat and bump it three times before it reaches the sea!"]],
        outro: [["rory", "Caught it! On the biggest wave in the world."], ["bolt", "I was in the boat too. I was the ballast. I am proud of that."]] },
    ] },
  { id: "panama", ch: 1, name: "Panama Canal", country: "Panama", flag: "pa", contact: "mateo", lat: 9.1, lon: -79.7, sea: true,
    arrive: [["mateo", "Hola, Agent Rory! I'm Mateo. My mum's a canal pilot. She steers the big ships through the locks."], ["mateo", "Only now the locks won't fill. There's a ship stuck in the middle with nowhere to go."], ["rory", "That's the ship from Cornwall! The one that was flashing."], ["bolt", "It is very big. I would like to stand on it."], ["pip", "That ship is carrying Undertow's crystals, Rory. Get aboard."]],
    leave: [["mateo", "The locks are filling! Mum says the ship can go through. Gracias, Rory!"], ["frost", "The ship's manifest lists a stop we didn't expect: the Galápagos Islands. Undertow is hiding something there."]],
    missions: [
      { id: "pn1", kind: "codes", lv: 2, title: "Lock Codes", at: [9, 20],
        intro: [["mateo", "The lock gates have a code lock. It plays a tune and you play it back."], ["pip", "Listen, then tap. It gets longer every time."]],
        outro: [["mateo", "The gates are moving! Slowly. Very slowly."]] },
      { id: "pn2", kind: "cells", lv: 2, title: "Ride the Ship", at: [9, 4], n: 8, time: 240,
        intro: [["pip", "The ship goes up through the locks and back. The crystals are riding on its deck!"], ["mateo", "Jump on from the lock wall as it goes past. And mind the gates!"]],
        outro: [["rory", "These crystals are labelled. GALÁPAGOS. Then something crossed out."], ["torpedo", "I can read it. It says BERMUDA. Somebody didn't want us to know that."]] },
      { id: "pn3", kind: "stack", lv: 2, title: "Gate Repair", at: [24, 16], n: 4, time: 180,
        intro: [["mateo", "The Drips knocked the counterweights off the big gate. Without them it won't shut."], ["pip", "GRAB the blocks and stack four on the green pad by the gate."]],
        outro: [["mateo", "It shuts! Mum's going to be so pleased."], ["bolt", "I would like a mum."]] },
      { id: "pn4", kind: "stealth", lv: 2, title: "Control Tower", at: [-18, -20],
        intro: [["mateo", "The lock controls are in the tower. Undertow's Drips patrol the yard round it with lamps."], ["pip", "Crates to hide behind, gaps to sneak through. The control key is in the case by the tower door."]],
        outro: [["rory", "The controls! Somebody's set the locks to drain out to sea."], ["undertow", "Agent Rory. Still here? The Pacific is that way. Drips, the jeep!"]] },
      { id: "pn5", kind: "chase", lv: 2, title: "Canal Road", at: [24, -36], n: 3, time: 150,
        intro: [["mateo", "A Drip's got the drain key and it's off down the canal road in a jeep!"], ["pip", "Take the other jeep. Round the road and bump it three times!"]],
        outro: [["rory", "Got the key! Now we can put the water back."]] },
      { id: "pn6", kind: "valves", lv: 2, title: "Fill the Locks", at: [9, -8],
        intro: [["mateo", "Last thing. The valves that fill the locks. Get every gauge in the green and the water comes in."]],
        outro: [["mateo", "The locks are filling! Look at the water rise!"], ["frost", "Well done, Agent Rory. Galápagos next. Mind the tortoises."]] },
    ] },
  { id: "galapagos", ch: 1, name: "Galápagos", country: "Ecuador", flag: "ec", contact: "isabela", lat: -0.7, lon: -90.3, sea: true,
    arrive: [["isabela", "Agent Rory! Welcome to the islands. I'm Isabela, my mum's a ranger here."], ["isabela", "Mind where you step. Tortoises. Iguanas. Boobies with blue feet. And now robots."], ["rory", "Robots?"], ["isabela", "Round ones. They've been hiding in the tortoise field. The tortoises don't mind. The tortoises don't mind anything."], ["bolt", "I would like to be a tortoise. For one day."], ["pip", "Undertow's ship unloaded something here, Rory. Find out what."]],
    leave: [["isabela", "The lagoon's filling up and the iguanas are swimming again. Gracias, Rory!"], ["frost", "The Drips' orders came from Hawaii. Undertow's got a pump under a volcano there, where the lava meets the sea."]],
    missions: [
      { id: "gp1", kind: "roundup", lv: 3, title: "Hide and Seek", at: [-10, -12], n: 6, time: 130,
        intro: [["isabela", "The Drips are hiding among the tortoises. It doesn't work. Tortoises don't wobble."], ["pip", "Six of them. They'll run when you get close, so corner them."]],
        outro: [["bolt", "The tortoises watched the whole thing. Very slowly."], ["isabela", "One Drip dropped a box. It's got a picture of the lagoon on it. And a big X."]] },
      { id: "gp2", kind: "dive", lv: 2, title: "Iguana Lagoon", at: [26, -2], n: 7, time: 160, air: 45,
        intro: [["isabela", "The marine iguanas dive in the lagoon for seaweed. Now there are crystals down there too."], ["pip", "Swim down for them. The iguanas won't mind. Watch your air!"]],
        outro: [["rory", "An iguana swam right past my nose."], ["torpedo", "He was showing off. They do that."]] },
      { id: "gp3", kind: "sub", lv: 2, title: "The Reef Tunnel", at: [40, -6], time: 170,
        intro: [["torpedo", "There's a tunnel through the reef. Undertow's pipe goes down it. Rings all the way. Hop in!"], ["pip", "Up and down as well as round, Rory. Take it steady."]],
        outro: [["torpedo", "The pipe comes out at a pump under the lava field."], ["isabela", "The lava field? Nobody goes on the lava field. It's all cracks."]] },
      { id: "gp4", kind: "tractor", lv: 2, title: "Loose Boats", at: [-30, -6], n: 6,
        intro: [["isabela", "The pump's pulling the water out from under the boats and they're tipping over!"], ["pip", "Get close to anything with a pink ring under it and press PIN. Your watch will hold it down."]],
        outro: [["isabela", "Boats saved! You're a hero. A small one."], ["bolt", "I am also a small hero."]] },
      { id: "gp5", kind: "drive", lv: 2, title: "Lava Buggy", at: [-8, -32], n: 8, time: 240,
        intro: [["isabela", "The ranger buggy can cross the lava field. Crystals have spilled from the pump all over it."], ["pip", "Drive over every one. It's bumpy, so go easy on the cracks."]],
        outro: [["rory", "Best. Drive. Ever."], ["bolt", "I was not in the buggy. I watched. A tortoise watched too."]] },
      { id: "gp6", kind: "morse", lv: 2, title: "Station Radio", at: [-24, -20],
        intro: [["isabela", "The station radio keeps picking up flashes from a ship. More Morse."], ["pip", "Same as the lighthouse, Rory. Watch, then tap the letters."]],
        outro: [["rory", "H, A, W, A, I, I. Hawaii!"], ["undertow", "Oh, very good, Agent Rory. Yes, Hawaii. Come and see what I've done with the volcano."]] },
    ] },
  { id: "hawaii", ch: 1, name: "Hawaii", country: "USA", flag: "us", contact: "kai", lat: 19.4, lon: -155.0, sea: true,
    arrive: [["kai", "Aloha, Agent Rory! I'm Kai. Surf's up. Well, it was, till the sea started going down."], ["kai", "See where the lava runs into the sea? There's steam coming out of the rocks that isn't lava steam. It's a machine."], ["rory", "Undertow's pump."], ["bolt", "Lava is very hot. I will stay near the sea. Which is also going away. This is a difficult island."], ["pip", "There's a lava tube under the cliffs, Rory. That's where the pump is."]],
    leave: [["kai", "The waves are back! Look at that set coming in! Mahalo, Rory!"], ["frost", "Agent Rory, the pump here was draining the Great Barrier Reef by pipe. Australia. TORPEDO will be busy."]],
    missions: [
      { id: "hw1", kind: "boat", lv: 2, title: "Jet-Ski Chase", at: [10, 24], n: 3, time: 150,
        intro: [["kai", "A Drip's stolen my jet ski! There it goes, round the cliffs!"], ["pip", "Take the other one. Bump it three times and it'll give up!"]],
        outro: [["kai", "My jet ski! Thanks, Rory. It's got a dent. I like the dent."]] },
      { id: "hw2", kind: "cells", lv: 3, title: "Lava Steps", at: [-24, 10], n: 8, time: 170,
        intro: [["kai", "The crystals are up the old lava terraces. Each step's a big jump, and there are pads on the way up."], ["pip", "All the way to the top. The last ones are high, so bounce!"]],
        outro: [["rory", "From the top you can see the steam coming out of the cliff."], ["kai", "That's the lava tube. Don't go in the wet way. Go in the dry way."]] },
      { id: "hw3", kind: "dive", lv: 3, title: "Turtle Reef", at: [34, 6], n: 8, time: 170, air: 45, sonar: true,
        intro: [["kai", "The turtles feed on the reef past the point. The water's gone cloudy from the pump, you can hardly see."], ["pip", "Use the sonar on your watch. Press PING and everything near you lights up for a moment. Then swim for it!"]],
        outro: [["rory", "The turtles swim through the cloudy bit like it's nothing."], ["torpedo", "Turtles have sonar in their hearts. That's not true. But it should be."]] },
      { id: "hw4", kind: "lasers", lv: 2, title: "The Lava Tube", at: [-40, 16], time: 130,
        intro: [["kai", "The lava tube's dry on this side. Undertow's put lasers all the way down it."], ["pip", "Faster than Cornwall. Watch the pattern, then go."]],
        outro: [["rory", "Through! There's the pump. It's sitting right on the lava."], ["undertow", "Careful, Agent Rory. Warm feet? That's the volcano. It does what I tell it. Drips, the beach!"]] },
      { id: "hw5", kind: "roundup", lv: 3, title: "Beach Drips", at: [14, 30], n: 6, time: 130,
        intro: [["kai", "Drips on the beach! They're burying crystals in the sand!"], ["pip", "Six of them. Chase them into the water's edge and ZAP."]],
        outro: [["bolt", "They ran into the sea. The sea is not there. They were confused."]] },
      { id: "hw6", kind: "circuit", lv: 3, title: "Volcano Pump", at: [-46, 16],
        intro: [["pip", "The pump's power box. Connect the power to the off switch and the volcano can go back to being a volcano."]],
        outro: [["rory", "Off! The steam's stopping."], ["kai", "And the sea's coming back up the beach! Surf's up!"], ["undertow", "Three pumps, Agent Rory. Three. The tide is turning, and you cannot stop a tide."]] },
    ] },
  { id: "reef", ch: 1, name: "The Great Barrier Reef", country: "Australia", flag: "au", contact: "tilly", lat: -16.9, lon: 146.0, sea: true,
    arrive: [["tilly", "G'day, Agent Rory! I'm Tilly. This is Mum's research pontoon. Everything below us is coral."], ["tilly", "And it's draining. There's a pipe on the bottom sucking the whole reef out to sea."], ["rory", "Then I'm going down."], ["bolt", "I will guard the pontoon. From the top. Where it is dry."], ["torpedo", "Finally! A whole mission in the water!"]],
    leave: [["tilly", "The reef's full again! The clownfish are back in their anemones! Thanks, Rory!"], ["frost", "The pipe's cargo was going to Hong Kong, Agent Rory. Undertow's ships are in the harbour there."]],
    missions: [
      { id: "rf1", kind: "dive", lv: 3, title: "Coral Garden", at: [8, 10], n: 8, time: 180, air: 45,
        intro: [["tilly", "The crystals are all over the coral garden. Some are deep, right down by the bommies."], ["pip", "Use every bubble you find. Eight crystals, then up for air!"]],
        outro: [["rory", "A clownfish bit my finger."], ["tilly", "They do that. It means they like you."]] },
      { id: "rf2", kind: "dive", lv: 3, title: "Murky Water", at: [-12, 8], n: 8, time: 180, air: 45, sonar: true,
        intro: [["tilly", "Past the wall the pump's stirred up all the sand. You can't see your own flippers."], ["pip", "PING with the sonar, then swim to what lights up. Keep pinging!"]],
        outro: [["torpedo", "See? Sonar. Turtles have it in their hearts."], ["bolt", "That is still not true."]] },
      { id: "rf3", kind: "sub", lv: 3, title: "The Drain Pipe", at: [-6, -10], time: 190,
        intro: [["torpedo", "The drain pipe! It's big enough for me. Rings all the way down and out the other side."], ["pip", "It twists, Rory. Up and down and round. Take it steady."]],
        outro: [["torpedo", "Out the other end! And the pipe goes on to a ship. A big one."], ["rory", "Undertow's ship."]] },
      { id: "rf4", kind: "salvage", lv: 2, title: "Lost Cargo", at: [6, -10], n: 3, time: 200,
        intro: [["tilly", "The pump sucked Mum's equipment cases off the pontoon. They're on the bottom."], ["torpedo", "I've got a claw! Fly me over a case and press GRAB. Bring it up to the ring under the pontoon and DROP it."]],
        outro: [["tilly", "All three! Mum's microscope is in one of those."], ["torpedo", "I'm a submarine and a crane. Put that on my file."]] },
      { id: "rf5", kind: "valves", lv: 3, title: "Pipe Pressure", at: [-12, -8],
        intro: [["tilly", "The pipe's pressure valves are on the pontoon. Set every gauge in the green and the pump can't pull."]],
        outro: [["tilly", "The pipe's gone slack! The water's staying put!"], ["undertow", "Drips! Get on that pontoon and get my valves back!"]] },
      { id: "rf6", kind: "roundup", lv: 3, title: "Pontoon Drips", at: [12, 2], n: 6, time: 130,
        intro: [["tilly", "Here they come, up the ladders! Six of them!"], ["pip", "Bubble them before they reach the valves!"]],
        outro: [["bolt", "They floated off over the reef. The fish were not impressed."], ["frost", "Hong Kong, Agent Rory. Time to find that ship."]] },
    ] },
  { id: "hongkong", ch: 1, name: "Hong Kong", country: "Hong Kong", flag: "hk", contact: "wing", lat: 22.3, lon: 114.2, sea: true,
    arrive: [["wing", "Agent Rory! I'm Wing. My grandpa sails a junk in the harbour. That's a boat with red sails."], ["wing", "Undertow's ships are tied up at the container quay. And the harbour's so low the ferries can't reach the piers."], ["rory", "Look at all the lights."], ["bolt", "There are more lights here than stars. I have counted both."], ["pip", "The ship from the reef is at the quay, Rory. Find out where it's going next."]],
    leave: [["wing", "The harbour's filling up! Grandpa's junk is floating again! Thanks, Rory!"], ["frost", "The ship's log has one more stop before Bermuda. The Maldives. And the islands there are appearing where there was only sea."]],
    missions: [
      { id: "hk1", kind: "stealth", lv: 3, title: "Container Yard", at: [20, 10],
        intro: [["wing", "The ship's papers are in the yard office. Three Drips walk the rows of containers with lamps."], ["pip", "Keep to the gaps. Wait for the lights to turn away, then go."]],
        outro: [["rory", "The papers! There's a map of the harbour with a rooftop circled."], ["wing", "That's the old market roof. The one with the neon sign."]] },
      { id: "hk2", kind: "cells", lv: 3, title: "Neon Rooftops", at: [-37, -16], n: 9, time: 190,
        intro: [["wing", "The crystals are up on the rooftops. Stairs up the side of the market, and the pads take you across."], ["pip", "Don't look down. Actually, look down a bit. So you don't fall."]],
        outro: [["rory", "You can see the whole harbour from up here. And Undertow's ship is lit up like a birthday cake."], ["wing", "Because they're loading it. Tonight."]] },
      { id: "hk3", kind: "codes", lv: 3, title: "Ship's Lock", at: [56, -6],
        intro: [["wing", "The ship's gangway has a code lock. Same kind as the canal."], ["pip", "Longer this time, Rory. Listen carefully."]],
        outro: [["rory", "I'm aboard. The hold's full of crystals. And a chart. Bermuda's circled in red."], ["undertow", "Reading my charts, Agent Rory? Rude. Drip, the junk. Take the chart and go!"]] },
      { id: "hk4", kind: "boat", lv: 3, title: "Junk Chase", at: [-6, -12], n: 3, time: 160,
        intro: [["wing", "A Drip's stolen Grandpa's junk! It's heading out through the harbour!"], ["pip", "Take the speedboat. Between the ships and round the ferries. Three bumps!"]],
        outro: [["wing", "Grandpa's junk! And the chart!"], ["bolt", "The red sails were very pretty. I nearly forgot to steer. I was not steering."]] },
      { id: "hk5", kind: "tractor", lv: 3, title: "Loose Containers", at: [10, -14], n: 6,
        intro: [["wing", "The pump's pulling the water out from under the quay and the containers are sliding!"], ["pip", "PIN them down before they go over the edge!"]],
        outro: [["wing", "Saved! There are noodles in that one. Very important noodles."]] },
      { id: "hk6", kind: "morse", lv: 3, title: "Harbour Lights", at: [-60, -6],
        intro: [["wing", "The ship's flashing at another ship, way out in the harbour. Morse again."], ["pip", "Faster this time. Watch and tap."]],
        outro: [["rory", "M, A, L, E. Malé. That's the Maldives!"], ["frost", "Then that's where we go. The islands are rising, Agent Rory. Be quick."]] },
    ] },
  { id: "maldives", ch: 1, name: "The Maldives", country: "Maldives", flag: "mv", contact: "aisha", lat: 4.2, lon: 73.5, sea: true,
    arrive: [["aisha", "Agent Rory! Welcome to the Maldives. I'm Aisha. Yesterday this was all sea. Today there's an island."], ["rory", "The sand's still wet."], ["aisha", "The lagoon's going down so fast the fish are getting stranded. Grandma's villa is on stilts and it's standing on dry sand!"], ["bolt", "An island appearing is the opposite of what usually happens. I have checked."], ["pip", "Undertow's seaplane has been landing on the lagoon at night. Find out why."]],
    leave: [["aisha", "The lagoon's full! The villas are back over the water! Thank you, Rory!"], ["frost", "The seaplane's flight log ends at one place, Agent Rory. The Bermuda Triangle. Undertow's base is there. This is it."]],
    missions: [
      { id: "md1", kind: "dive", lv: 3, title: "Atoll Crystals", at: [22, 8], n: 9, time: 190, air: 45,
        intro: [["aisha", "The crystals are all over the lagoon floor, round the coral heads."], ["pip", "Nine of them, Rory. Use the bubbles, and come up when you need to."]],
        outro: [["rory", "A manta ray went over me like a cloud."], ["torpedo", "Show-off. I can do that."]] },
      { id: "md2", kind: "stack", lv: 3, title: "Villa Repair", at: [-12, -2], n: 4, time: 180,
        intro: [["aisha", "The Drips pulled the stilts out from under Grandma's villa. They're scattered on the sand."], ["pip", "GRAB them and stack four on the pad under the villa."]],
        outro: [["aisha", "It's standing straight! Grandma says you can have a mango."], ["bolt", "I would like a mango. I cannot eat a mango."]] },
      { id: "md3", kind: "boat", lv: 3, title: "Seaplane Chase", at: [20, -14], n: 3, time: 160,
        intro: [["aisha", "The seaplane! It's taxiing across the lagoon with a load of crystals!"], ["pip", "It can't take off in water this shallow. Take the speedboat and bump it three times before it finds deep water!"]],
        outro: [["rory", "Got it! And its flight log."], ["bolt", "A plane that is also a boat. I respect that."]] },
      { id: "md4", kind: "tide", lv: 3, title: "Lagoon Sluices", at: [-18, -16],
        intro: [["aisha", "The reef has gates in it. Undertow built them to let the lagoon out. Six gates."], ["pip", "Set every basin to its line. It's a big one, Rory."]],
        outro: [["aisha", "The water's coming back over the reef! Look at it pour!"]] },
      { id: "md5", kind: "sub", lv: 3, title: "Reef Pass", at: [24, -20], time: 190,
        intro: [["torpedo", "The pass through the reef is full of Undertow's rings. Fly me through and we shut her pipe for good."], ["pip", "Deep, then up, then round the coral. Careful!"]],
        outro: [["torpedo", "Pipe shut! That's the last of them."], ["rory", "Then Bermuda's next."]] },
      { id: "md6", kind: "roundup", lv: 4, title: "Sandbank Drips", at: [-8, 32], n: 7, time: 140,
        intro: [["aisha", "Drips! All over the new sandbank! They're digging the crystals back up!"], ["pip", "Seven, and they're fast. Corner them, Rory!"]],
        outro: [["bolt", "They ran out of sandbank. Then they ran out of luck."], ["undertow", "Enough. Enough! Come to Bermuda, Agent Rory. Come and see my Engine. Nobody leaves."]] },
    ] },
  { id: "bermuda", ch: 1, name: "The Bermuda Triangle", country: "The Atlantic", flag: "zz", contact: null, lat: 26.0, lon: -66.0, sea: true,
    arrive: [["pip", "Rory, this is Undertow's floating base. Every compass on the Narwhal is spinning."], ["torpedo", "Mine's spinning too. I don't have a compass. It's still spinning."], ["frost", "The base is a ring of decks round a tower, Agent Rory. The crystals go down the middle. Get in, stop it, get out."], ["bolt", "Get in. Stop it. Get out. I have made a list."]],
    leave: [],
    missions: [
      { id: "bm1", kind: "lasers", lv: 4, title: "The Gangway", at: [-30, 56], time: 150,
        intro: [["pip", "The only way onto the base is the gangway, and it's a wall of lasers."], ["pip", "The fastest ones yet. Watch, wait, go."]],
        outro: [["rory", "I'm on the deck."], ["undertow", "Welcome aboard, Agent Rory. Mind the Drips. They've been told."]] },
      { id: "bm2", kind: "stealth", lv: 3, title: "Deck Patrol", at: [12, 24],
        intro: [["pip", "The tower door key is in a case at the far end of the deck. Three Drips with lamps."], ["pip", "Crates, pipes, corners. You know what to do."]],
        outro: [["rory", "Got the key!"], ["bolt", "I did not beep once. Beep. Sorry. That was after."]] },
      { id: "bm3", kind: "circuit", lv: 4, title: "Base Power", at: [6, -4],
        intro: [["pip", "The base's power box. Connect it to the tower lock and we're in."]],
        outro: [["rory", "The tower's open!"], ["undertow", "Fine. Fine! Come up, then. But first, my Drips would like a word underneath."]] },
      { id: "bm4", kind: "sub", lv: 4, title: "Under the Base", at: [-18, -32], time: 200,
        intro: [["torpedo", "The base floats on huge tanks. The pipes between them are full of rings. Through every one and the tanks flood!"], ["pip", "This is the big one, Rory. Steady."]],
        outro: [["torpedo", "The tanks are flooding! The base is going to sink!"], ["rory", "Not yet. Undertow's still in the tower."]] },
      { id: "bm5", kind: "dive", lv: 4, title: "The Dark Hull", at: [-8, -32], n: 8, time: 180, air: 40, sonar: true,
        intro: [["pip", "The Engine's key crystals are stuck to the hull under the base. It's pitch dark down there."], ["pip", "PING, swim, PING again. And watch your air, Rory!"]],
        outro: [["rory", "That's all of them. The Engine's key is dark."], ["undertow", "MY KEY! Right. That's it. Big Drip! Deal with him!"]] },
      { id: "bm6", kind: "boss", lv: 2, title: "The Big Drip", at: [0, 26], n: 4, event: "actEnd",
        intro: [["undertow", "Meet the Big Drip. The biggest, wobbliest robot I've ever built. Big Drip, sit on him. Wetly."], ["pip", "When it stomps, a ring rolls out across the deck. JUMP over it!"], ["pip", "After a stomp it's stuck for a moment. Run round behind it and ZAP the glowing tank on its back! Four hits!"]],
        outro: [["rory", "It's floating away in a bubble!"], ["undertow", "My Big Drip. Oh, you'll pay for that, Agent Rory. Not in money. In sea."], ["undertow", "This base was only the front door. The Tidal Engine is at the bottom of the ocean, and nothing you have can reach it. The tide is turning."], ["rory", "She's diving! She's going down with the base!"], ["torpedo", "Then we go down after her. All the way down."], ["frost", "Agent Rory. TORPEDO. BOLT. Act One is over. The abyss is next."]] },
    ] },
];

export const CREDITS = [
  ["Agent Rory: Deep Red", "A game for Rory"],
  ["Story, code and levels", "Written with Claude"],
  ["3D", "three.js, with bloom, SMAA and AgX tone mapping"],
  ["The sea", "Waves, caustics and light shafts in GLSL"],
  ["Physics", "Rapier: the character controller, the cars and every tumbling block"],
  ["Music and sound", "Tone.js synthesizers, played live"],
  ["BOLT and the Drips", "RobotExpressive by Tomás Laulhé (Quaternius), CC0"],
  ["Coastlines", "Natural Earth, via world-atlas"],
  ["Voices", "Your device's own speech voices"],
  ["Starring", "Agent Rory, BOLT, TORPEDO, Pip, Admiral Frost, and Captain Undertow"],
];

export const ALL = PLACES.flatMap(p => p.missions.map(m => ({ ...m, place: p.id })));
export function placeOf(mid) { return PLACES.find(p => p.missions.some(m => m.id === mid)); }
