// Agent Rory: Zero Gravity — the cast, the chapters, the places and every
// mission's lines. Professor Zero is stealing gravity; Rory and BOLT get it back.

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS = {
  rory:   { name: "Rory", voice: V("m", "en-GB", 1.15, 1.05), look: { skin: 0xf3cfae, hair: 0x6b4423, eyes: 0x3b5f8a, coat: 0x16324f, trousers: 0x1a1f2a, shirt: 0xf4f6fa, tie: 0x0e1a2c, kid: true, earpiece: true, hairStyle: "rory" } },
  bolt:   { name: "BOLT", side: "bolt", robot: "bolt", voice: V("m", "en-GB", 1.6, 1.15), bg: "#0e3050" },
  frost:  { name: "Admiral Frost", voice: V("m", "en-GB", 0.7, 0.92), look: { skin: 0xe8c8a8, hair: 0xe8e8e8, coat: 0x1a2440, trousers: 0x1a2440, shirt: 0xf0f0f0, tie: 0x2a4a8a, moustache: 0xe8e8e8, hairStyle: "short" } },
  pip:    { name: "Pip", voice: V("f", "en-GB", 1.25, 1.05), look: { skin: 0xf0c8a0, hair: 0xd06a2a, coat: 0x2a8a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", glasses: 0x1a1a1a } },
  zero:   { name: "Professor Zero", side: "villain", voice: V("m", "en-GB", 0.85, 0.95), look: { skin: 0xf0d8c8, hair: 0xf4f4f4, coat: 0xf4f4f8, trousers: 0x3a2a4a, shirt: 0x8a4ad8, tie: 0x2a1a3a, hairStyle: "curly", glasses: 0x8a4ad8, stern: true } },
  floater:{ name: "Floater", side: "villain", robot: "floater", voice: V("m", "en-GB", 0.6, 1.1), bg: "#2a1030" },
  yuki:   { name: "Yuki", voice: V("f", "ja-JP", 1.2, 1.0), look: { skin: 0xf0d0b0, hair: 0x14141a, coat: 0xe83a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "bun" } },
  amira:  { name: "Amira", voice: V("f", "ar-EG", 1.15, 0.95), look: { skin: 0xc08a60, hair: 0x1a1010, coat: 0xe8c86a, trousers: 0x3a3a4a, kid: true, hairStyle: "long" } },
  jack:   { name: "Jack", voice: V("m", "en-AU", 1.2, 1.05), look: { skin: 0xf0c8a0, hair: 0xe8c860, coat: 0x2aa8d8, trousers: 0xe8e0c8, kid: true, hairStyle: "spiky", hat: "cap", hatColor: 0xe83a3a } },
  lucas:  { name: "Lucas", voice: V("m", "pt-BR", 1.2, 1.05), look: { skin: 0xa8784e, hair: 0x1a1010, coat: 0xf4d020, trousers: 0x2a8a3a, kid: true, hairStyle: "curly" } },
  marcus: { name: "Marcus", voice: V("m", "en-US", 1.1, 1.05), look: { skin: 0x7a4a2a, hair: 0x14100c, coat: 0xe86a2a, trousers: 0x2a3a5a, kid: true, hairStyle: "short", hat: "cap", hatColor: 0x2a4aa8 } },
  wanjiru:{ name: "Wanjiru", voice: V("f", "sw-KE", 1.15, 1.0), look: { skin: 0x6a3a1a, hair: 0x14100c, coat: 0xe8a020, trousers: 0x6a3a8a, kid: true, hairStyle: "curly" } },
  mei:    { name: "Mei", voice: V("f", "zh-CN", 1.2, 1.0), look: { skin: 0xf0d4b4, hair: 0x14141a, coat: 0xd82a2a, trousers: 0x2a2a3a, kid: true, hairStyle: "ponytail" } },
  arjun:  { name: "Arjun", voice: V("m", "en-IN", 1.2, 1.05), look: { skin: 0xb07a50, hair: 0x14100c, coat: 0x2a8ad8, trousers: 0xf0ece0, kid: true, hairStyle: "short" } },
  hale:   { name: "Commander Hale", voice: V("f", "en-US", 0.95, 1.0), look: { skin: 0xd8a880, hair: 0x3a2a1a, coat: 0xf0f0f4, trousers: 0xf0f0f4, shirt: 0x2a4a8a, hairStyle: "bun", belt: 0x3a3a3a } },
};

// Mission kinds (see missions.js): cells, roundup, stack, lasers, drone, chase,
// tractor, stealth, circuit, codes, spacewalk, buggy, boss.
// lv is the difficulty (1-4). Each place has its own level file in levels/.
export const CHAPTERS = [
  { n: 1, title: "Floaters", blurb: "Professor Zero is sucking the gravity out of famous places. Find out how." },
  { n: 2, title: "The Pump", blurb: "Zero's Gravity Pump is somewhere. Follow the cells to it." },
  { n: 3, title: "Moonshot", blurb: "The Pump is in orbit and its battery is on the Moon." },
];

export const PLACES = [
  { id: "hq", ch: 1, name: "POLARIS HQ", country: "Scotland", flag: "sct", contact: "pip", lat: 56.8, lon: -5.1,
    arrive: [["frost", "Agent Rory. Something very odd is happening all over the world."], ["frost", "Things are floating. Buses, benches, a whole lighthouse in Norway. Somebody is stealing gravity."], ["pip", "So I built you a partner! Rory, meet BOLT."], ["bolt", "Hello Rory! I am BOLT. I am ninety-nine percent ready."], ["rory", "What's the other one percent?"], ["bolt", "Walking. Mostly walking."], ["pip", "Let's get you both trained. Follow the glowing beacons!"]],
    leave: [["frost", "Good work. Now, the first floating landmark has turned up in Tokyo. The plane is waiting."]],
    missions: [
      { id: "hq1", kind: "cells", lv: 1, title: "Cell School", at: [0, -6], n: 6, time: 90,
        intro: [["pip", "These blue balls are Gravity Cells. Each one holds a little bit of stolen gravity."], ["pip", "Run into them to collect them. Jump with the JUMP button. Grab all six!"]],
        outro: [["bolt", "Six cells! I counted them. Twice."]] },
      { id: "hq2", kind: "cells", lv: 1, title: "Pad Practice", at: [-2, 3], n: 5, time: 90, high: true,
        intro: [["pip", "Bounce pads throw you high into the air. Some of these cells are right up high."], ["pip", "And the bubble by the tower has hardly any gravity in it. Jump inside and float!"]],
        outro: [["rory", "That bubble was brilliant."], ["pip", "That's what Zero's machine does, but to whole cities."]] },
      { id: "hq3", kind: "roundup", lv: 1, title: "Practice Bots", at: [6, 10], n: 4, time: 90,
        intro: [["pip", "Zero's henchbots are called Floaters. These are my practice ones."], ["pip", "Your watch fires a Gravity Bubble. Press USE near a Floater and pop, off it floats!"]],
        outro: [["bolt", "I am glad I am not a Floater."]] },
      { id: "hq4", kind: "stack", lv: 1, title: "Block Drop", at: [-8, 9], n: 3, time: 120,
        intro: [["pip", "Last one. Your watch has a tractor beam too. Stand next to a block and press USE to pick it up."], ["pip", "Carry it onto the glowing pad and press USE again to drop it. Three blocks!"]],
        outro: [["frost", "Training complete. Now, I'm afraid, the real thing."]] },
    ] },
  { id: "tokyo", ch: 1, name: "Tokyo", country: "Japan", flag: "jp", contact: "yuki", lat: 35.7, lon: 139.7,
    arrive: [["yuki", "Agent Rory! Welcome to Tokyo. Look up. No, higher."], ["rory", "Tokyo Tower is floating!"], ["yuki", "Since last night. And the vending machines keep drifting away down the street."], ["bolt", "I would like one drink, please, before it leaves."], ["pip", "Rory, something on the rooftops is soaking up the gravity. Follow the beacons."]],
    leave: [["yuki", "Look! The tower is settling back down. Thank you, Rory. Thank you, BOLT."], ["bolt", "You are welcome. I did the flying."], ["frost", "Those cells were being sent somewhere hot and sandy. Egypt, Agent Rory. The pyramids are acting very oddly."]],
    missions: [
      { id: "tok1", kind: "cells", lv: 2, title: "Rooftop Cells", at: [10, 27], n: 8, time: 150,
        intro: [["pip", "The cells are up on the arcade roof and the tower next to it. Take the stairs, or bounce up on the pads."], ["yuki", "The pink pad on the arcade roof goes really high!"]],
        outro: [["rory", "Eight cells. They were humming, like they wanted to go somewhere."], ["pip", "They're tuned to a signal. Somebody is collecting them."]] },
      { id: "tok2", kind: "tractor", lv: 1, title: "Vending Machine Rescue", at: [0, 24], n: 6,
        intro: [["yuki", "Oh no, it's happening again. The machines are lifting off!"], ["pip", "Get close to anything with a pink ring under it and press PIN. Your watch will pull it back down."], ["bolt", "Do not let the drinks escape!"]],
        outro: [["yuki", "Wait. The big screens. Somebody has taken them over!"], ["zero", "Good evening, Tokyo. I am Professor Zero, and I have borrowed your gravity."], ["zero", "Every country will pay me one gold bar, or everything they own floats off into space. Toodle-oo!"], ["rory", "He waved at us. With a floating teacup."], ["frost", "Professor Zero. He was laughed out of the Space Academy for inventing floating shoes. It seems he has been busy since."]], event: "zeroScreen" },
      { id: "tok3", kind: "roundup", lv: 2, title: "Park Floaters", at: [-12, 20], n: 5, time: 120,
        intro: [["yuki", "Zero's robots are in the cherry blossom park, sticking gravity leeches to the trees!"], ["pip", "These ones run away. Sneak up on them and ZAP."]],
        outro: [["bolt", "They floated off going wheee. I think they enjoyed it."], ["yuki", "One of them dropped this. It's a map of the tower with rings drawn on it."]] },
      { id: "tok4", kind: "drone", lv: 1, title: "Tower Flight", at: [0, -14], time: 150,
        intro: [["pip", "BOLT has rocket feet! BOLT, fly up the rings round the tower and scan the top."], ["bolt", "Rocket feet ready. Mostly ready."], ["pip", "Rory, you steer him. Hold JUMP to go up, let go to come down."]],
        outro: [["bolt", "I found the machine on the top! It says Property of Professor Zero. Also it says Made in Egypt."], ["rory", "Egypt? Then that's where we go next."]] },
    ] },
  { id: "egypt", ch: 1, name: "Giza", country: "Egypt", flag: "eg", contact: "amira", lat: 30.0, lon: 31.1,
    arrive: [["amira", "Agent Rory! Thank goodness you're here. The top of the Great Pyramid has floated off!"], ["rory", "It's just hanging there in the sky."], ["amira", "And the stones keep going round and round it, like a merry-go-round."], ["bolt", "I would like to go on the merry-go-round."], ["frost", "Zero's machine was made here, Agent Rory. Find out who built it."]],
    leave: [["amira", "The top of the pyramid is sinking back down. Slowly, but it's coming!"], ["frost", "Excellent work. Sydney next, Agent Rory. Pack a sun hat."]],
    missions: [
      { id: "egy1", kind: "cells", lv: 2, title: "The Step Pyramid", at: [-18, 14], n: 8, time: 150,
        intro: [["amira", "The cells are all over the step pyramid. Each step is one big jump."], ["pip", "Climb all the way to the top. The last one is up high, so jump!"]],
        outro: [["rory", "There's a crate up here stamped ZERO INDUSTRIES. With a picture of a Floater on it."], ["amira", "Zero Industries? They rented the old tomb last summer. They said they were making hats."]] },
      { id: "egy2", kind: "stack", lv: 2, title: "Capstone Blocks", at: [-2, -4], n: 4, time: 180,
        intro: [["amira", "The Floaters knocked the capstone blocks off the plinth. Could you put them back, please?"], ["pip", "GRAB a block, carry it to the green circle and DROP it. Four blocks!"]],
        outro: [["amira", "Perfect. My grandad will be so pleased."], ["bolt", "I would like a grandad."]] },
      { id: "egy3", kind: "lasers", lv: 1, title: "Tomb of Lasers", at: [30, 17], time: 120,
        intro: [["amira", "Zero's workshop is inside the old tomb. But it's full of lasers now."], ["pip", "Don't touch the red beams. Jump over the low ones, and wait for the moving ones to pass."]],
        outro: [["rory", "Plans! For something called a Gravity Pump. It's enormous."], ["pip", "If he builds that, he could lift whole cities."], ["zero", "Oh! You found my plans. How rude. Floaters, take the buggy and run!"]] },
      { id: "egy4", kind: "chase", lv: 1, title: "Dune Chase", at: [38, 4], n: 3, time: 150,
        intro: [["amira", "A Floater is getting away across the dunes with the rest of the plans!"], ["pip", "Jump in the buggy. It drives itself forward. Steer with the stick, pull back to brake, and press JUMP for a boost."], ["pip", "Bump the Floater three times!"]],
        outro: [["rory", "Got them! The plans say the Pump's parts are shipped from Sydney."], ["bolt", "Sydney. I like the Opera House. It looks like sails. Or bread."]] },
    ] },
  { id: "sydney", ch: 1, name: "Sydney", country: "Australia", flag: "au", contact: "jack", lat: -33.9, lon: 151.2,
    arrive: [["jack", "G'day, Agent Rory! You're just in time. The Opera House roof has come unstuck!"], ["rory", "It's bobbing up and down like a boat."], ["jack", "And the ferries are floating above the water now. The passengers love it. The captains don't."], ["bolt", "I love it."], ["pip", "Zero's parts are shipped from here, Rory. Find out where they're going."]],
    leave: [["jack", "The roof's back on and the ferries are in the water. Thanks, mate!"], ["frost", "Rio de Janeiro, Agent Rory. It's carnival week. Zero will be hard to spot in a crowd, but his robots dance terribly."]],
    missions: [
      { id: "syd1", kind: "tractor", lv: 2, title: "Beach Rescue", at: [28, 14], n: 6,
        intro: [["jack", "Zero's machine is pointed at the beach. The umbrellas and surfboards are floating off!"], ["pip", "PIN them down before they get too high."]],
        outro: [["jack", "Beach saved! You're a legend."], ["bolt", "I am also a legend."]] },
      { id: "syd2", kind: "cells", lv: 2, title: "Ferry Hop", at: [-12, 34], n: 8, time: 180,
        intro: [["pip", "The cells are riding on the ferries! Jump from the end of a wharf onto a ferry as it goes past."], ["jack", "One on each deck and one on each roof. Try not to fall in, the water's freezing!"]],
        outro: [["rory", "These cells have labels on them. DESTINATION: RIO."], ["pip", "Rio de Janeiro. Zero is gathering everything in one place."]] },
      { id: "syd3", kind: "drone", lv: 2, title: "Bridge Flight", at: [-4, 28], time: 150,
        intro: [["jack", "Something is hanging under the Harbour Bridge. BOLT, can you fly out and have a look?"], ["bolt", "Rocket feet: go."]],
        outro: [["bolt", "It was a Floater. Stuck. I told it to have a nice day."], ["pip", "It had a key card. ZERO SHIPPING, back gate. That's the warehouse by the quay."]] },
      { id: "syd4", kind: "stealth", lv: 1, title: "Warehouse Sneak", at: [22, 3],
        intro: [["jack", "That's Zero's warehouse. Guard bots with searchlights walk round inside."], ["pip", "Stay behind the crates and out of the yellow light. The shipping list is in a silver case at the back."]],
        outro: [["rory", "Got it! Everything is being shipped to Rio, for the carnival."], ["jack", "A carnival? Zero's going to hide the parts in the parade floats!"]] },
    ] },
  { id: "rio", ch: 1, name: "Rio de Janeiro", country: "Brazil", flag: "br", contact: "lucas", lat: -22.9, lon: -43.2,
    arrive: [["lucas", "Olá, Agent Rory! Welcome to the carnival!"], ["rory", "Why is that parrot float hovering?"], ["lucas", "Everything is hovering this year. The drummers had to tie their drums down."], ["bolt", "Boom. Boom. Boom."], ["pip", "Zero's parts are hidden in the parade, and his robots are dancing in it. Badly."]],
    leave: [["lucas", "Obrigado, Rory! Come back next year. The carnival will be on the ground by then."], ["frost", "The Big Floater had a delivery note inside it. New York, Agent Rory. That's where the Pump is being built."]],
    missions: [
      { id: "rio1", kind: "roundup", lv: 3, title: "Carnival Floaters", at: [0, 14], n: 6, time: 120,
        intro: [["lucas", "Some of the dancers in the parade are Floaters in disguise! You can tell. They can't samba."], ["pip", "Bubble six of them. They run fast here, so corner them."]],
        outro: [["lucas", "The last one dropped a ticket. For the cable car up Sugarloaf Mountain."]] },
      { id: "rio2", kind: "cells", lv: 3, title: "Cable Car Cells", at: [14, -16], n: 7, time: 180,
        intro: [["pip", "The cells are going up the mountain in the cable cars. Climb the station stairs and ride up on a roof."], ["lucas", "Grab the ones on the cars and the ones on the stations!"]],
        outro: [["rory", "From up here you can see the whole bay. And a giant robot in the stadium."], ["lucas", "That's the Big Floater show! Except, I don't think it's a show."]] },
      { id: "rio3", kind: "chase", lv: 2, title: "Parade Chase", at: [-24, 14], n: 3, time: 150,
        intro: [["lucas", "Wait! A Floater is driving off with the key to the stadium!"], ["pip", "Chase it round the avenue in the kart. Three bumps!"]],
        outro: [["lucas", "Got it! Now the Big Floater can't lock us out of the stadium."]] },
      { id: "rio4", kind: "boss", lv: 1, title: "The Big Floater", at: [-70, 17], n: 3,
        intro: [["zero", "Ah, Agent Rory. Meet my masterpiece: the Big Floater! Big Floater, sit on him. Gently."], ["pip", "When it stomps, a ring rolls out along the ground. JUMP over it!"], ["pip", "After a stomp it gets stuck for a moment. Run round behind it and ZAP the pink battery on its back!"]],
        outro: [["rory", "It's floating away in a giant bubble."], ["zero", "My masterpiece! You'll pay for that, Agent Rory. Well, not pay. I don't need your money. Everybody else's, though."], ["frost", "Well done, Agent Rory. The Floaters are dealt with. Now we find the Pump."]] },
    ] },
  { id: "newyork", ch: 2, name: "New York", country: "USA", flag: "us", contact: "marcus", lat: 40.7, lon: -74.0,
    arrive: [["frost", "Chapter two, Agent Rory. Zero Industries has a factory somewhere under Times Square. That's where the Pump is being built."], ["marcus", "Yo, Agent Rory! Welcome to New York. Watch out for the taxis. They're flying. I mean it."], ["rory", "And the Statue of Liberty's torch is floating above her hand."], ["marcus", "She's still holding the flame, sort of. Also, all the screens just went dark."], ["bolt", "New York, New York. I would like a hot dog. I cannot eat hot dogs."]],
    leave: [["marcus", "Lights on, taxis down, Floater caught. Not bad for a Tuesday!"], ["frost", "The Floater's van was full of parts labelled BATTERY TEST: KENYA. Off you go, Agent Rory."]],
    missions: [
      { id: "ny1", kind: "tractor", lv: 2, title: "Taxi Rescue", at: [0, 14], n: 6,
        intro: [["marcus", "Here we go again. The taxis in Times Square are lifting off!"], ["pip", "PIN them down, Rory. The hot dog carts too. Especially the hot dog carts."]],
        outro: [["marcus", "The drivers say thank you. Well, one of them shouted something. I think it was thank you."]] },
      { id: "ny2", kind: "cells", lv: 3, title: "Rooftop Run", at: [34, 34], n: 8, time: 180,
        intro: [["pip", "The cells are on the rooftops by the park. Ride the window cleaner's lift up, then the pink pads take you higher."], ["marcus", "Don't look down. Actually, look down a bit. So you don't fall."]],
        outro: [["rory", "From up here I can see a door in the pavement with a Z on it."], ["marcus", "That's Zero's factory! But it needs power to open, and he's switched off the whole square."]] },
      { id: "ny3", kind: "circuit", lv: 2, title: "Power to the Square", at: [-6, 6], event: "powerOn",
        intro: [["marcus", "The power box for Times Square is right here. Zero scrambled all the wires."], ["pip", "Tap the tiles to turn them until the power runs from the battery to the lock."]],
        outro: [["marcus", "The screens are back on! Everybody's cheering!"], ["zero", "Ahem. Excuse me, Times Square. Professor Zero here. My factory is closed today. Go away."], ["rory", "His van is leaving the factory! It's full of parts!"]] },
      { id: "ny4", kind: "chase", lv: 2, title: "Taxi Chase", at: [6, 24], n: 3, time: 150,
        intro: [["marcus", "Take my uncle's taxi! He won't mind. He might mind a little."], ["pip", "Chase the van round the blocks. Three bumps and it's ours!"]],
        outro: [["rory", "Got it! The van's full of battery parts. They say BATTERY TEST: KENYA."], ["bolt", "A battery? I have a battery. It is small but brave."]] },
    ] },
  { id: "kenya", ch: 2, name: "The Savanna", country: "Kenya", flag: "ke", contact: "wanjiru", lat: -1.5, lon: 35.1,
    arrive: [["wanjiru", "Jambo, Agent Rory! I'm Wanjiru. My mum is the ranger here."], ["wanjiru", "Something is very wrong. The animals keep floating up off the ground. The elephants are furious."], ["rory", "What's that tower with lightning coming out of it?"], ["wanjiru", "It appeared last week. Zero's robots guard it. They say it's a battery test."], ["bolt", "I do not like that battery. It is showing off."]],
    leave: [["wanjiru", "The animals are back on the ground where they belong. Asante sana, Rory!"], ["frost", "The tower's computer was talking to a relay on the Great Wall of China. Zero must be controlling the Pump from there."]],
    missions: [
      { id: "ken1", kind: "tractor", lv: 2, title: "Floating Animals", at: [0, 14], n: 6,
        intro: [["wanjiru", "Oh no, here they go! The zebras, the giraffes, even the elephants!"], ["pip", "PIN them down, gently. Very gently. They are very cross."]],
        outro: [["wanjiru", "One elephant is still sulking. But she's on the ground."], ["bolt", "I also sulk when I float."]] },
      { id: "ken2", kind: "chase", lv: 3, title: "Safari Chase", at: [10, 4], n: 3, time: 160,
        intro: [["wanjiru", "A Floater stole my mum's radio! It's getting away in a jeep!"], ["pip", "Take the ranger's jeep. The hills are bumpy, so hold on. Three bumps!"]],
        outro: [["wanjiru", "Mum's radio! And the Floater left a map of the watering hole, with crosses on it."]] },
      { id: "ken3", kind: "roundup", lv: 3, title: "Watering Hole", at: [-12, 6], n: 6, time: 120,
        intro: [["wanjiru", "The Floaters are putting gravity leeches round the watering hole, where the animals drink."], ["pip", "Bubble all six. They're quick, so chase them into the water's edge."]],
        outro: [["wanjiru", "The animals can drink in peace. Look, the zebras are coming already."]] },
      { id: "ken4", kind: "codes", lv: 2, title: "Shut Down the Tower", at: [14, -10],
        intro: [["pip", "The tower's control box has a code lock. It plays a tune, and you play it back."], ["wanjiru", "Listen carefully. Then turn that thing off!"]],
        outro: [["rory", "The lightning's stopped. The battery cells have gone dark."], ["zero", "My battery tower! Do you know how long that took to build? Three whole Tuesdays!"], ["wanjiru", "He sounds very grumpy for someone who stole the gravity."]] },
    ] },
  { id: "china", ch: 2, name: "The Great Wall", country: "China", flag: "cn", contact: "mei", lat: 40.4, lon: 116.6,
    arrive: [["mei", "Nǐ hǎo, Agent Rory! I'm Mei. My family has looked after this part of the Great Wall for a hundred years."], ["mei", "And now bits of it keep floating off! Zero's relay is in the big fort at the far end."], ["rory", "Then we walk the wall."], ["bolt", "It is very long. I will walk the first bit. Then you can carry me."]],
    leave: [["mei", "Xièxie, Rory! Come back one day and walk the whole wall properly."], ["frost", "India next, Agent Rory. The relay was talking to a secret workshop under the gardens of the Taj Mahal."]],
    missions: [
      { id: "chn1", kind: "cells", lv: 3, title: "Walk the Wall", at: [-10, 10], n: 10, time: 210,
        intro: [["mei", "The cells are spread all along the wall. Run the whole way, up the hills and through the watchtowers!"], ["pip", "Some are up high inside the towers, so jump for them."]],
        outro: [["mei", "The wall's stopped wobbling! But listen. The temple gong is ringing all by itself."]] },
      { id: "chn2", kind: "codes", lv: 3, title: "Temple Bells", at: [-26, 37],
        intro: [["mei", "Zero's robots rigged our temple bells to send his signals. They play a tune over and over."], ["pip", "Play the tune back to jam the signal. It gets longer each time."]],
        outro: [["mei", "Silence. Beautiful silence."], ["bolt", "I liked the tune. I will hum it later."]] },
      { id: "chn3", kind: "drone", lv: 3, title: "Lantern Flight", at: [-8, 14], time: 170,
        intro: [["pip", "The relay's signal bounces off the lanterns along the wall. BOLT, fly through every one to scramble it."], ["bolt", "Scrambling. Like eggs."]],
        outro: [["bolt", "All scrambled. The relay is now very confused."], ["mei", "The fort doors just opened by themselves. I think that means come in."]] },
      { id: "chn4", kind: "lasers", lv: 3, title: "The Relay Room", at: [40, 38], time: 150,
        intro: [["mei", "The relay room is at the back of the fort. Zero filled it with lasers."], ["pip", "Same as Egypt, only faster. Jump the low ones, wait for the moving ones."]],
        outro: [["rory", "The relay! It's sending orders to India. To the gardens of the Taj Mahal."], ["zero", "Stop poking my relays, Agent Rory! I am trying to steal the world's gravity in peace!"]] },
    ] },
  { id: "india", ch: 2, name: "The Taj Mahal", country: "India", flag: "in", contact: "arjun", lat: 27.2, lon: 78.0,
    arrive: [["arjun", "Namaste, Agent Rory! I'm Arjun. I show visitors round the gardens. Well, I did, until the robots came."], ["arjun", "They walk the west garden all night with searchlights. And the air round the minarets has gone all floaty."], ["rory", "Zero's workshop is under here somewhere."], ["bolt", "This is the most beautiful building I have ever seen. I have seen four."]],
    leave: [["arjun", "Dhanyavaad, Rory! The gardens are ours again."], ["frost", "The workshop plans say the Pump is finished, and it's on Zero's own island. This is it, Agent Rory. His secret base."]],
    missions: [
      { id: "ind1", kind: "stealth", lv: 2, title: "Garden Guards", at: [-18, 30],
        intro: [["arjun", "The hatch to the workshop is at the far end of the west garden. Three guard bots walk the paths between the hedges."], ["pip", "Hide behind the hedges. Wait for the lights to pass, then go through the gaps."]],
        outro: [["rory", "The hatch! It's locked with a power lock."], ["arjun", "And the fountain in the east garden has been pulled apart. I think the lock and the fountain are connected."]] },
      { id: "ind2", kind: "stack", lv: 3, title: "Fountain Fix", at: [14, 10], n: 4, time: 180,
        intro: [["arjun", "The Floaters took the fountain stones and scattered them round the garden."], ["pip", "GRAB them and stack four back on the fountain. The fountain powers the hatch lock."]],
        outro: [["arjun", "Water's flowing again! Listen, the hatch just clicked."]] },
      { id: "ind3", kind: "circuit", lv: 3, title: "Workshop Hatch", at: [-14, -20],
        intro: [["pip", "Last step, Rory. Turn the tiles and connect the fountain's power to the hatch."]],
        outro: [["rory", "It's open. There are blueprints everywhere. And a model of the Pump... on an island shaped like a Z."], ["zero", "Get out of my workshop! Those are my private doodles!"], ["arjun", "His robots are climbing the minarets to signal the island! Stop them!"]] },
      { id: "ind4", kind: "cells", lv: 3, title: "Minaret Signals", at: [0, -30], n: 8, time: 200,
        intro: [["arjun", "The robots left signal cells on the minaret balconies. The air round them is so floaty you can jump and jump."], ["pip", "Bounce up off the pink pads, then keep jumping in the bubbles. Get every cell!"]],
        outro: [["rory", "Signals stopped. Zero's island won't know we're coming."], ["bolt", "I will be very quiet. Beep. Sorry."]] },
    ] },
  { id: "island", ch: 2, name: "Zero's Island", country: "Somewhere secret", flag: "zz", contact: null, lat: -12.0, lon: -150.0,
    arrive: [["pip", "Rory, you're on Zero's island. It's shaped like a Z. Of course it is."], ["pip", "BOLT's scanner says the Pump is on a rocket in the silo at the far end."], ["frost", "Stop that launch, Agent Rory. Whatever it takes."], ["bolt", "It is raining. I am waterproof. Mostly."]],
    leave: [["frost", "POLARIS has a rocket of its own, Agent Rory. Get to the launch base. You're going to space."], ["rory", "Space. Actual space."], ["bolt", "I have always wanted to float on purpose."]],
    missions: [
      { id: "isl1", kind: "lasers", lv: 4, title: "Laser Beach", at: [-24, 34], time: 150,
        intro: [["pip", "The beach is fenced with lasers. The only way in is straight through."], ["pip", "They're fast here. Watch the pattern, then go."]],
        outro: [["rory", "Through! The base is up the path."], ["zero", "Who let him through the laser fence? Floaters! Guard the yard!"]] },
      { id: "isl2", kind: "stealth", lv: 2, title: "Base Patrol", at: [-16, -18],
        intro: [["pip", "The silo codes are in a case at the back of the yard. Two guards with searchlights."], ["pip", "Keep to the walls and behind the crates. Wait for them to walk away."]],
        outro: [["rory", "Got the silo codes!"], ["bolt", "I was very quiet. I did not beep once. Beep."]] },
      { id: "isl3", kind: "circuit", lv: 4, title: "Silo Doors", at: [14, -22],
        intro: [["pip", "The silo control panel. Connect the power to the door lock and we can get to the rocket."]],
        outro: [["rory", "The doors are opening!"], ["zero", "No, no, no! Floater Prime, deal with him! I have a launch to do!"]] },
      { id: "isl4", kind: "boss", lv: 2, title: "Floater Prime", at: [28, -21], n: 4, event: "launch",
        intro: [["zero", "Meet Floater Prime, the biggest and best of my Floaters. Prime, squash him flat. Politely."], ["pip", "Same trick as Rio, Rory. Jump the rings, then zap the battery on its back when it's stuck. Four hits this time!"]],
        outro: [["rory", "Floater Prime is floating off in a bubble!"], ["zero", "Too late, Agent Rory! Three, two, one... launch!"], ["rory", "The rocket! It's taking the Pump up into space!"], ["zero", "From orbit, my Pump can reach the whole world. Toodle-oo!"], ["frost", "Agent Rory. How would you feel about going to space?"], ["rory", "I've been waiting my whole life for someone to ask me that."]] },
    ] },
  { id: "launch", ch: 3, name: "POLARIS Launch Base", country: "The coast", flag: "polaris", contact: "hale", lat: 28.5, lon: -80.6, leaveEvent: "launch",
    arrive: [["frost", "Chapter three, Agent Rory. Moonshot."], ["hale", "Welcome to the launch base, Agent Rory. I'm Commander Hale. I'll be flying you up."], ["hale", "The Pump is in orbit, sucking gravity up from the whole planet. We have to stop it before it's charged."], ["bolt", "I have packed. I packed myself."]],
    leave: [["hale", "All systems go. Strap in, you two."], ["hale", "Three. Two. One. Lift off!"], ["rory", "We're going up! We're going UP!"], ["bolt", "Wheeeeeee."]],
    missions: [
      { id: "lb1", kind: "codes", lv: 3, title: "Launch Sequence", at: [-6, 20],
        intro: [["hale", "Somebody has scrambled the launch computer. I think we know who."], ["pip", "It wants the launch sequence played back. Watch the lights, then repeat."]],
        outro: [["hale", "Launch computer is happy. Next, the gantry. Zero's Floaters left things up there."]] },
      { id: "lb2", kind: "cells", lv: 3, title: "Gantry Climb", at: [18, -18], n: 8, time: 200,
        intro: [["hale", "The red tower beside the rocket is the gantry. The yellow lift goes all the way up."], ["pip", "There are cells on every level. Hop off the lift at each one, then back on."]],
        outro: [["hale", "Gantry's clear. Now let's check the rocket for any more surprises."]] },
      { id: "lb3", kind: "drone", lv: 3, title: "Rocket Check", at: [0, 14], time: 170,
        intro: [["hale", "BOLT, can you fly up round the rocket and scan it on the way?"], ["bolt", "Rocket feet, meet rocket. Rocket, meet rocket feet."]],
        outro: [["bolt", "The rocket is clean. Except for one Floater sticker. I took it off."], ["hale", "Wait. There's a Floater heading for the fuel line with a spanner!"]] },
      { id: "lb4", kind: "chase", lv: 3, title: "Pad Chase", at: [10, 32], n: 3, time: 160,
        intro: [["hale", "Take the buggy! It's going round the ring road. Stop it before it reaches the pad!"], ["pip", "Three bumps, Rory. You know the drill."]],
        outro: [["rory", "Got it! And its spanner."], ["hale", "Then we are go for launch. Suit up, Agent Rory!"]] },
    ] },
  { id: "station", ch: 3, name: "The Pump Station", country: "Orbit", flag: "zz", contact: null, orbit: true, suit: true, lat: 10, lon: -40,
    arrive: [["hale", "Docking complete. Welcome to Zero's station, Agent Rory. Mind the gap. The gap is space."], ["rory", "Look at the Pump. It's as big as a stadium."], ["pip", "It's pulling gravity up off the whole world through that pink beam. Your suit has a jetpack. Hold JET to fly, let go to drift down."], ["bolt", "My feet have rockets. I was born for this."]],
    leave: [["zero", "Enough! You may have switched off my Pump, but its battery is safe on the Moon, and so am I. Catch me if you can!"], ["hale", "He's launched an escape pod towards the Moon. Everyone back in the rocket."], ["rory", "The Moon. Obviously the Moon."]],
    missions: [
      { id: "sta1", kind: "cells", lv: 3, title: "Solar Cells", at: [0, 14], n: 8, time: 200,
        intro: [["pip", "Zero's Floaters stuck cells on the solar wings, above the deck. Fly up with the jetpack and grab them."], ["hale", "Don't drift too far. Space is very big."]],
        outro: [["rory", "Flying is the best thing ever."], ["bolt", "I agree. Beep."]] },
      { id: "sta2", kind: "circuit", lv: 3, title: "Power Reroute", at: [10, 2],
        intro: [["pip", "The station's power runs through this box. Reroute it away from the Pump."]],
        outro: [["pip", "The Pump's slowing down. Zero's going to notice that."], ["zero", "Who is fiddling with my wires? Floaters! Deck! Now!"]] },
      { id: "sta3", kind: "roundup", lv: 3, title: "Deck Floaters", at: [2, 22], n: 6, time: 130,
        intro: [["pip", "Here they come. Bubble six Floaters before they reach the power box."]],
        outro: [["bolt", "They floated away into space. They look happy out there."]] },
      { id: "sta4", kind: "lasers", lv: 4, title: "Airlock Lasers", at: [20, -2], time: 150,
        intro: [["pip", "The airlock to the Pump controls is full of lasers. Walk, don't fly. Jetpacks and lasers don't mix."]],
        outro: [["rory", "Through. And there's a crate of spare parts floating off the deck!"]] },
      { id: "sta5", kind: "tractor", lv: 3, title: "Loose Cargo", at: [2, 0], n: 6,
        intro: [["hale", "The Pump is pulling loose things off the deck. If they float away we'll never get them back."], ["pip", "PIN them down, Rory!"]],
        outro: [["hale", "Deck secure. Now the Pump controls."]] },
      { id: "sta6", kind: "codes", lv: 4, title: "Pump Controls", at: [-6, -8],
        intro: [["pip", "The Pump's off switch has a code lock. It's a long one, Rory. Seven notes."], ["bolt", "I will hum along. Quietly."]],
        outro: [["rory", "The beam's gone! The Pump's switched off!"], ["pip", "Everything on Earth is floating back down. Slowly, but it's happening!"]] },
      { id: "sta7", kind: "drone", lv: 4, title: "Pump Flight", at: [0, -6], time: 190,
        intro: [["pip", "BOLT, fly round the Pump's ring and scan it. We need to know where its battery is."], ["bolt", "Flying round a giant space doughnut. Best day."]],
        outro: [["bolt", "The scan says: battery on the Moon. In a crater. Next to a sign that says ZERO'S MOON BASE, KEEP OUT."], ["rory", "Subtle."]] },
      { id: "sta8", kind: "stealth", lv: 3, title: "Core Sneak", at: [-9, -4],
        intro: [["pip", "Zero's console has the Moon base codes. Two guards. Sneak between the crates."]],
        outro: [["rory", "Moon base codes, got them!"], ["zero", "My codes! Right. That's it. I'm going home."]] },
    ] },
  { id: "moon", ch: 3, name: "The Moon", country: "Space", flag: "zz", contact: null, moon: true, suit: true, lat: 0, lon: 0,
    arrive: [["hale", "Touchdown. You're on the Moon, Agent Rory. Take small steps. Or big ones. Everything's floaty here."], ["rory", "I'm on the Moon. I'm actually on the Moon."], ["bolt", "I am the first robot called BOLT on the Moon. I checked."], ["pip", "Zero's base is over by the purple domes, and the Pump's battery is in the big crater. Let's end this."]],
    leave: [],
    missions: [
      { id: "moon1", kind: "drive", lv: 3, title: "Moon Buggy", at: [2, 12], n: 8, time: 240,
        intro: [["hale", "The lander carried a moon buggy. Cells from the Pump have rained down all over these craters."], ["pip", "Drive over every one. The buggy bounces a lot up here, so go easy on the bumps."]],
        outro: [["rory", "That was the best drive of my entire life."], ["bolt", "I was not in the buggy. I watched. It looked good."]] },
      { id: "moon2", kind: "cells", lv: 3, title: "Crater Hops", at: [-30, -8], n: 8, time: 200,
        intro: [["pip", "More cells round the rim of that crater, and some up high. The gravity's so low you can jump really far."], ["bolt", "Jump like a kangaroo. A space kangaroo."]],
        outro: [["pip", "Got them. The battery's losing power without its cells."]] },
      { id: "moon3", kind: "stack", lv: 3, title: "Signal Tower", at: [-6, 6], n: 4, time: 200,
        intro: [["hale", "We need to talk to Earth, and Zero's jamming the radio. Stack four blocks on the pad to build a signal tower."], ["pip", "They're light up here, so they bounce. Drop them gently."]],
        outro: [["frost", "Agent Rory! We can hear you. Everyone on Earth is watching. No pressure."], ["rory", "Hi, everyone!"]] },
      { id: "moon4", kind: "tractor", lv: 3, title: "Moon Mess", at: [6, 10], n: 6,
        intro: [["hale", "The battery is pulling our kit off the ground. Crates, fuel barrels, everything."], ["pip", "PIN it down before it floats off into space!"]],
        outro: [["hale", "Kit's secure. Zero's rover just left his base. He's heading for the battery!"]] },
      { id: "moon5", kind: "chase", lv: 4, title: "Rover Chase", at: [10, 20], n: 3, time: 180,
        intro: [["zero", "You'll never catch me, Agent Rory! My rover has cup holders!"], ["pip", "Buggy, Rory! Round the craters after him. Three bumps!"]],
        outro: [["zero", "Stop bumping me! Fine. Fine! I'm going inside!"], ["rory", "He's gone into his base."]] },
      { id: "moon6", kind: "lasers", lv: 4, title: "Base Lasers", at: [14, -6], time: 160,
        intro: [["pip", "His base entrance is full of lasers. The fastest ones yet."], ["bolt", "You have done this many times. You are a laser expert."]],
        outro: [["rory", "I'm in. There's the battery control panel."]] },
      { id: "moon7", kind: "circuit", lv: 4, title: "Battery Breaker", at: [8, -30],
        intro: [["pip", "Connect the power to the breaker and the battery shuts off for good."]],
        outro: [["rory", "The battery's dark. The gravity's going home!"], ["zero", "My battery! My beautiful battery! Right. You leave me no choice. Mega Floater, activate!"]] },
      { id: "moon8", kind: "boss", lv: 3, title: "Professor Zero", at: [0, 28], n: 5,
        intro: [["zero", "Behold the Mega Floater! I'm driving it myself! Look, it has my face on it!"], ["pip", "Last one, Rory. Jump the rings, zap the battery on its back. Five hits!"], ["bolt", "You can do it. I believe in you. I have a whole program about it."]],
        outro: [["zero", "Oh. Oh dear. I appear to be in a bubble."], ["rory", "It's over, Professor Zero."], ["zero", "I only wanted people to like my floating shoes."], ["frost", "Professor Zero, POLARIS has a proposal. Come and build your floating shoes for us. As toys. With the gravity left where it belongs."], ["zero", "...Toys? Children would play with my shoes? Oh. Oh, that's rather wonderful."], ["frost", "Agent Rory. BOLT. The world has its gravity back. Well done, both of you."]], event: "ending" },
    ] },
];

export const CREDITS = [
  ["Agent Rory: Zero Gravity", "A game for Rory"],
  ["Story, code and levels", "Written with Claude"],
  ["3D", "three.js, with bloom, SMAA and AgX tone mapping"],
  ["Physics", "Rapier: the character controller, the cars and every tumbling block"],
  ["Music and sound", "Tone.js synthesizers, played live"],
  ["BOLT and the Floaters", "RobotExpressive by Tomás Laulhé (Quaternius), CC0"],
  ["Coastlines", "Natural Earth, via world-atlas"],
  ["Voices", "Your device's own speech voices"],
  ["Starring", "Agent Rory, BOLT, Pip, Admiral Frost, and Professor Zero"],
];

export const ALL = PLACES.flatMap(p => p.missions.map(m => ({ ...m, place: p.id })));
export function placeOf(mid) { return PLACES.find(p => p.missions.some(m => m.id === mid)); }
