// Spectrum's clues (clues.js): the missions that end with a puzzle for Rory to crack.
// p is the kind of puzzle, lv its level (1 is the gentlest), say the lines before it,
// after the line once it's solved. The clues are a trail: the lookout in Dingle, the
// boatman's tip, the map to Lapland, the symbol code on the plans that spells MONOCHROME.
export const THEME = {
  things: ["Blotters", "paint pots", "colour drops", "grey jars"],
  boxes: ["crates", "vans", "sacks"],
  words: ["GREY", "PAINT", "JAR", "DROP", "BLOT", "MOP"],
  names: ["Max", "Ivy", "Sam", "Nell", "Otto", "Ruby", "Jay", "Mo", "Lena", "Finn"],
};

export const CLUES = {
  // ---------------------------------------------------------------- Dingle
  dg3: { p: "suspect", lv: 1, title: "WHO GREYED THE DOORS?",
    say: [["saoirse", "I saw who painted the doors grey! Well, I saw three people, and one of them had a mop."], ["pip", "Grisaille has a lookout in Dingle. Read the clues, Rory. Which one is it?"]],
    after: [["rory", "Got you. And there's grey paint on your shoes."]] },
  // ---------------------------------------------------------------- Lisbon
  lb1: { p: "count", lv: 1, title: "THE TILE LOCK",
    say: [["tiago", "The Blotters locked the tile shop! There are shapes painted on the lock."], ["pip", "Count the ones it asks for, Rory. That's the code."]],
    after: [["tiago", "It's open! All the blue tiles are still inside."]] },
  lb2: { p: "cipher", lv: 1, word: "LOT", title: "THE TRAM NOTE",
    say: [["rory", "There's a note tucked under the drops. It's all numbers."], ["pip", "Number code! A is 1, B is 2, C is 3. Crack it, Rory."]],
    after: [["rory", "LOT. Like at an auction. Somebody's collecting colour."]] },
  lb3: { p: "sum", lv: 1, title: "THE FOUNTAIN LOCK",
    say: [["tiago", "They've locked the fountain! There's a sum on the lock."], ["pip", "Add them up, Rory, and the water runs again."]],
    after: [["tiago", "It's on! Blue water!"]] },
  // ---------------------------------------------------------------- Guatapé
  gt1: { p: "order", lv: 1, title: "GRANDPA'S SAFE",
    say: [["camila", "Grandpa keeps his best paint in a safe. The code is his numbers in order."], ["pip", "Smallest first, Rory."]],
    after: [["camila", "Paint! Now we can fix the doors ourselves."]] },
  gt2: { p: "map", lv: 1, title: "THE LAKE MAP",
    say: [["camila", "From up here you can see the whole lake. Grandpa drew me a map of it."], ["pip", "Follow the steps on the map to where the grey boat is hiding."]],
    after: [["rory", "The boat's heading across the lake. We'll need a speedboat."]] },
  gt4: { p: "next", lv: 1, title: "GRANDPA'S PATTERN",
    say: [["camila", "Grandpa painted a pattern round the square, and the Blotters rubbed out the end of it."], ["pip", "What comes next, Rory? Finish his pattern."]],
    after: [["camila", "Perfect. Grandpa says you've got a painter's eye."]] },
  gt5: { p: "coins", lv: 1, title: "PAY THE BOATMAN",
    say: [["camila", "The boatman saw where the Blotters' truck went. He'll tell us, but he wants paying for his time."], ["pip", "Pay him exactly, Rory. A good spy never pays too much."]],
    after: [["camila", "He says the truck went south. A long way south. To the salt."]] },
  // ---------------------------------------------------------------- Salar de Uyuni
  uy1: { p: "count", lv: 2, title: "THE TRACKING MARKERS",
    say: [["wara", "The Blotters dropped tracking markers all over the salt. All shapes and colours."], ["pip", "Count the ones it asks for, Rory, and we'll know how many Blotters there are."]] },
  uy3: { p: "times", lv: 1, title: "THE SALT TALLY",
    say: [["wara", "The salt workers count their blocks in twos and tens. The Blotters hid the tally."], ["pip", "Do the times tables, Rory, and we'll know how many blocks they stole."]],
    after: [["wara", "That's exactly how many are missing. They took them for the machine."]] },
  uy4: { p: "suspect", lv: 2, title: "THE LOOKOUT",
    say: [["wara", "Someone was taking photos of the trains just before the machine switched on."], ["pip", "Four tourists by the old engine. One of them is Grisaille's lookout. Use the clues!"]],
    after: [["rory", "The lookout had a map. There's a red circle round Lapland."]] },
  // ---------------------------------------------------------------- Lapland
  lp1: { p: "clock", lv: 1, title: "THE BLOTTER TIMETABLE",
    say: [["aino", "The Blotters leave the ice hotel at the same time every night. It's on their timetable."], ["pip", "Which clock shows it? Then we'll know when to sneak in."]],
    after: [["rory", "Then that's when we go."]] },
  lp3: { p: "cipher", lv: 2, word: "JARS", title: "THE MACHINE NOTE",
    say: [["rory", "There's a note pinned to the machine. Numbers again."], ["pip", "Crack it, Rory. What is she keeping in there?"]] },
  lp5: { p: "story", lv: 2, things: "reindeer", boxes: "sleighs", title: "THE HERDER'S COUNT",
    say: [["aino", "The herder needs to know how many reindeer are safe. Help him work it out!"]],
    after: [["aino", "All of them! Not one missing."]] },
  // ---------------------------------------------------------------- Petra
  pt1: { p: "scale", lv: 2, title: "THE STONE JARS",
    say: [["layla", "The Blotters swapped the stone jars on the old scale. Only one has the real red in it."], ["pip", "Work out what the box weighs, Rory, and we'll know which jar is real."]],
    after: [["layla", "That's the one! The heavy red one."]] },
  pt3: { p: "map", lv: 2, title: "THE GREY TENT",
    say: [["layla", "That grey tent down there. Here's my map of the valley."], ["pip", "Follow the steps, Rory. Where's the tent?"]],
    after: [["rory", "Right in front of the Treasury. She's keeping her collection inside."]] },
  pt4: { p: "minus", lv: 2, title: "THE ALTAR BOX",
    say: [["rory", "The key's in a box with a take-away lock."], ["pip", "Quick, before the lamps come back round!"]] },
  // ---------------------------------------------------------------- Hội An
  ha1: { p: "next", lv: 2, title: "THE LANTERN PATTERN",
    say: [["linh", "The lanterns go on in a pattern, all down the street. The Blotters broke it."], ["pip", "What number comes next, Rory? Then the street lights up in order."]] },
  ha4: { p: "coins", lv: 2, title: "LANTERN PAPER",
    say: [["linh", "The bridge keeper sells lantern paper. We need some to fix the broken ones."], ["pip", "Pay him exactly, Rory."]],
    after: [["linh", "Red paper and yellow paper. We can make them all again!"]] },
  ha5: { p: "suspect", lv: 2, title: "THE MARKET SPY",
    say: [["linh", "The fruit seller saw who told the Blotters where to go. Four shoppers were at her stall."], ["pip", "One of them is working for Grisaille. Read the clues."]],
    after: [["rory", "Another map! This one has a circle round Madagascar."]] },
  // ---------------------------------------------------------------- Avenue of the Baobabs
  bb1: { p: "count", lv: 2, title: "THE CHAMELEON MESSAGE",
    say: [["palette", "My cousins left us a message in shapes. We chameleons are very artistic."], ["pip", "Count the ones they mean, Rory."]],
    after: [["palette", "That's how many Blotters are in the camp. My cousins are excellent spies."]] },
  bb2: { p: "times", lv: 2, title: "THE CHALK SUMS",
    say: [["fara", "The Blotters chalked sums on the baobabs. They're counting the trees!"], ["pip", "Times tables, Rory. How many are they after?"]],
    after: [["fara", "That's every tree on the avenue. They want them all."]] },
  bb4: { p: "story", lv: 2, things: "lemurs", boxes: "trees", title: "THE LEMUR COUNT",
    say: [["fara", "We need to count the lemurs, to be sure every one is safe."]],
    after: [["fara", "Every lemur! Even the cross one."]] },
  bb5: { p: "clock", lv: 2, title: "THE TRUCK LEAVES AT...",
    say: [["fara", "The Blotters' truck leaves the camp at a set time. Here's their note."], ["pip", "Which clock says it? We'll be there first."]],
    after: [["rory", "And they're going to Samarkand."]] },
  // ---------------------------------------------------------------- Samarkand
  sk1: { p: "sum", lv: 3, title: "THE DOME NUMBERS",
    say: [["dilnoza", "The tilers paint numbers under the dome tiles, so they know where each one goes."], ["pip", "Add them up, Rory, and we'll know which dome she's hiding in."]],
    after: [["dilnoza", "The bazaar side! I knew it."]] },
  sk2: { p: "coins", lv: 3, title: "THE SPICE SELLER",
    say: [["dilnoza", "The spice seller knows where the workshop is. He'll tell us, for a price."], ["pip", "Pay exactly, Rory. He counts every coin."]],
    after: [["dilnoza", "Behind the silk stalls. Of course."]] },
  sk3: { p: "cipher", lv: 3, word: "MONOCHROME", title: "HER SECRET PLANS",
    say: [["rory", "Her plans! But they're written in some kind of symbol code."], ["pip", "Use the key, Rory. What is she building?"]] },
  sk5: { p: "order", lv: 3, title: "THE GATE NUMBERS",
    say: [["dilnoza", "The Registan gates have a number lock. Every Blotter was carrying one of the numbers."], ["pip", "Put them in order, Rory, and the gates will open."]] },
  // ---------------------------------------------------------------- Plitvice Lakes
  pl1: { p: "next", lv: 3, title: "THE RANGER MARKERS",
    say: [["marta", "The rangers number the lakes in a pattern. Some of the markers are missing!"], ["pip", "What comes next, Rory?"]] },
  pl2: { p: "minus", lv: 3, title: "THE WATER GAUGE",
    say: [["marta", "The Blotters are draining the lakes into jars. The gauge says how much has gone."], ["pip", "Take away, Rory. How much is left?"]] },
  pl3: { p: "scale", lv: 3, title: "THE HEAVY JAR",
    say: [["pip", "The jars are sitting on a scale. The full ones are heavier. Work out what each box weighs, and we'll find them."]],
    after: [["marta", "Those two! The colour of the whole lake is in there."]] },
  pl5: { p: "story", lv: 3, title: "THE RANGER'S REPORT",
    say: [["marta", "The ranger wants a report for the park. Can you work it out?"], ["pip", "Field report, Rory. Every spy writes one."]] },
  // ---------------------------------------------------------------- Sossusvlei
  ss1: { p: "map", lv: 3, title: "THE DUNE MAP",
    say: [["tuli", "The dunes all look the same. Good thing I've got a map."], ["pip", "Follow the steps, Rory. Where did the Blotters land?"]],
    after: [["tuli", "Deadvlei. The white pan with the black trees."]] },
  ss2: { p: "times", lv: 3, title: "THE DELIVERY LIST",
    say: [["tuli", "The Blotters left a delivery list. Crates and crates of grey."], ["pip", "Times tables, Rory. How much have they taken?"]] },
  ss3: { p: "clock", lv: 3, title: "THE GANGWAY SIGN",
    say: [["rory", "The gangway's coming down from the ship. There's a sign: it goes back up at a set time."], ["pip", "Which clock is it? Then we know how long we've got."]] },
  ss4: { p: "suspect", lv: 3, title: "THE DISGUISE",
    say: [["tuli", "The people by the gangway! One of them is Grisaille herself, in disguise!"], ["pip", "Read the clues carefully, Rory. Some of them say NOT."]],
    after: [["grisaille", "You have sharp eyes, Agent Rory. Come aboard, then. If you dare."]] },
  // ---------------------------------------------------------------- The Monochrome
  mc1: { p: "cipher", lv: 4, word: "VAULT", title: "THE KEY TAG",
    say: [["rory", "The key has a tag on it. More symbols!"], ["pip", "Last code, Rory. Where does this key go?"]] },
  mc2: { p: "sum", lv: 4, title: "THE VAULT DOOR",
    say: [["pip", "Every jar has a number on it. Add them up and the vault door opens. Three sums!"]],
    after: [["rory", "It's open. Every colour in the world is in here."]] },
};
