// Spectrum's clues (clues.js, puzzles.js): the missions that end with a puzzle for Rory
// to crack. p is the kind of puzzle, lv its level (1 is the gentlest), say the lines
// before it, after the line once it's solved. The kinds are Spectrum's own (colour
// count, paint by numbers, mirror painting, fractions, azulejo tiles, the paint shop,
// grey shadows, colour squares, the drop chart), plus the three spy clues every game has
// (the line-up, the coded note, the spy map). The clues are a trail: the lookout in
// Dingle, the boatman's tip, the lookout's map to Lapland, the plans that spell MONOCHROME.
export const THEME = {
  things: ["Blotters", "paint pots", "colour drops", "grey jars"],
  boxes: ["crates", "vans", "sacks"],
  words: ["GREY", "PAINT", "JAR", "DROP", "BLOT", "MOP"],
  names: ["Max", "Ivy", "Sam", "Nell", "Otto", "Ruby", "Jay", "Mo", "Lena", "Finn"],
  // (the code's symbols are the coloured ones: this is the colour game)
  map: { tile: "#f4e8c0", ink: "#1a2440", start: "🎨" },
};

export const CLUES = {
  // ---------------------------------------------------------------- Dingle
  dg3: { p: "suspect", lv: 1, title: "WHO GREYED THE DOORS?",
    say: [["saoirse", "I saw who painted the doors grey! Well, I saw three people, and one of them had a mop."], ["pip", "Grisaille has a lookout in Dingle. Read the clues, Rory. Which one is it?"]],
    after: [["rory", "Got you. And there's grey paint on your shoes."]] },
  // ---------------------------------------------------------------- Lisbon
  lb1: { p: "tiles", lv: 1, title: "THE TILE SHOP",
    say: [["tiago", "The Blotters mopped a tile right off the tile shop wall! The pattern has a gap."], ["pip", "Which tile goes back, Rory?"]],
    after: [["tiago", "That's the one! The whole wall is blue again."]] },
  lb2: { p: "cipher", lv: 1, word: "LOT", title: "THE TRAM NOTE",
    say: [["rory", "There's a note tucked under the drops. It's all numbers."], ["pip", "Number code! A is 1, B is 2, C is 3. Crack it, Rory."]],
    after: [["rory", "LOT. Like at an auction. Somebody's collecting colour."]] },
  lb3: { p: "tiles", lv: 2, where: "The square's tiles", title: "THE SQUARE'S TILES",
    say: [["tiago", "The Blotters mopped the tiles round the fountain! There's a gap in the pattern."], ["pip", "Find the tile that fits, Rory."]] },
  // ---------------------------------------------------------------- Guatapé
  gt1: { p: "paint", lv: 1, title: "GRANDPA'S PICTURE",
    say: [["camila", "Grandpa left a picture to paint by numbers, before the Blotters came. Every square has a sum."], ["pip", "Work out each sum, and paint it the colour with that number."]],
    after: [["camila", "That's what our street looked like! Now we can paint it again."]] },
  gt2: { p: "map", lv: 1, title: "THE LAKE MAP",
    say: [["camila", "From up here you can see the whole lake. Grandpa drew me a map of it."], ["pip", "Follow the steps on the map to where the grey boat is hiding."]],
    after: [["rory", "The boat's heading across the lake. We'll need a speedboat."]] },
  gt4: { p: "mirror", lv: 1, title: "GRANDPA'S WALL",
    say: [["camila", "Grandpa's wall pattern is the same on both sides. The Blotters mopped half of it!"], ["pip", "Paint the other half so it matches, Rory."]],
    after: [["camila", "Perfect. Grandpa says you've got a painter's eye."]] },
  gt5: { p: "shop", lv: 1, who: "Camila", title: "THE BOATMAN'S PAINT",
    say: [["camila", "The boatman sells paint for the boats. Buy two pots from him and he'll tell us where the truck went."], ["pip", "Exactly the money, Rory. A good spy never pays too much."]],
    after: [["camila", "He says the truck went south. A long way south. To the salt."]] },
  // ---------------------------------------------------------------- Salar de Uyuni
  uy1: { p: "count", lv: 1, title: "PINK FEATHERS",
    say: [["wara", "Some things out here still have their colour. Count the ones it asks for, before they go grey!"]] },
  uy3: { p: "pictogram", lv: 1, title: "WARA'S DROP CHART",
    say: [["wara", "I made a chart of the drops we found on the salt. One picture for every drop."], ["pip", "Read the chart, Rory."]] },
  uy4: { p: "suspect", lv: 2, title: "THE LOOKOUT",
    say: [["wara", "Someone was taking photos of the trains just before the machine switched on."], ["pip", "Four tourists by the old engine. One of them is Grisaille's lookout. Use the clues!"]],
    after: [["rory", "The lookout had a map. There's a red circle round Lapland."]] },
  // ---------------------------------------------------------------- Lapland
  lp1: { p: "fraction", lv: 1, title: "FINNISH RED",
    say: [["aino", "The cabins are grey. My grandad always paints the door half red, half white."], ["pip", "Paint the right part, Rory. Equal parts!"]],
    after: [["aino", "Proper Finnish red!"]] },
  lp3: { p: "cipher", lv: 2, word: "JARS", title: "THE MACHINE NOTE",
    say: [["rory", "There's a note pinned to the machine. Numbers again."], ["pip", "Crack it, Rory. What is she keeping in there?"]] },
  lp5: { p: "count", lv: 2, title: "THE RED NOSES",
    say: [["aino", "The herder wants to know how many still have their colour. Can you count them?"]],
    after: [["aino", "All of them! Not one gone grey."]] },
  // ---------------------------------------------------------------- Petra
  pt1: { p: "shadow", lv: 2, title: "SHADOWS ON THE CLIFF",
    say: [["layla", "The Blotters left grey shadows on the carvings where they mopped the colour off."], ["pip", "Match each shadow to the shape that made it, Rory."]],
    after: [["layla", "That's the one! Rose red again."]] },
  pt3: { p: "map", lv: 2, title: "THE GREY TENT",
    say: [["layla", "That grey tent down there. Here's my map of the valley."], ["pip", "Follow the steps, Rory. Where's the tent?"]],
    after: [["rory", "Right in front of the Treasury. She's keeping her collection inside."]] },
  pt4: { p: "square", lv: 2, title: "THE ALTAR BOX",
    say: [["rory", "The key's in a box with a colour lock. Every colour once in each row and each column."], ["pip", "Quick, before the lamps come back round!"]] },
  // ---------------------------------------------------------------- Hội An
  ha1: { p: "mirror", lv: 2, title: "THE LANTERN",
    say: [["linh", "Every lantern is the same on both sides. This one's been half mopped!"], ["pip", "Paint the other half, Rory, and the street lights up."]] },
  ha4: { p: "shop", lv: 2, who: "Linh", title: "LANTERN PAINT",
    say: [["linh", "The bridge keeper sells lantern paint. We need two pots to fix the broken ones."], ["pip", "Exactly the money, Rory."]],
    after: [["linh", "Red and yellow. We can make them all again!"]] },
  ha5: { p: "suspect", lv: 2, title: "THE MARKET SPY",
    say: [["linh", "The fruit seller saw who told the Blotters where to go. Four shoppers were at her stall."], ["pip", "One of them is working for Grisaille. Read the clues."]],
    after: [["rory", "Another map! This one has a circle round Madagascar."]] },
  // ---------------------------------------------------------------- Avenue of the Baobabs
  bb1: { p: "shadow", lv: 2, title: "CHAMELEON SHADOWS",
    say: [["palette", "My cousins are hiding. All you can see is their shadows. We chameleons are very good at hiding."], ["pip", "Which one made the shadow, Rory?"]],
    after: [["palette", "Found him! He's been grey all week. He's very embarrassed."]] },
  bb2: { p: "paint", lv: 2, title: "THE CHALK SUMS",
    say: [["fara", "The Blotters chalked sums on the baobab bark! Grandma says it's a paint-by-numbers."], ["pip", "Work out each sum and paint it, Rory."]],
    after: [["fara", "It's a picture of the sunset! Just like it should be."]] },
  bb4: { p: "count", lv: 2, title: "COLOURFUL TAILS",
    say: [["fara", "We need to be sure the lemurs still have their colours. Count the ones it asks for!"]],
    after: [["fara", "Every lemur! Even the cross one."]] },
  bb5: { p: "pictogram", lv: 2, title: "THE DELIVERY CHART",
    say: [["fara", "The Blotters' delivery chart! Every picture is some drops taken away in the trucks."], ["pip", "Read it carefully, Rory. Look at the key."]],
    after: [["rory", "And every truck is going to Samarkand."]] },
  // ---------------------------------------------------------------- Samarkand
  sk1: { p: "tiles", lv: 3, where: "The dome's tiles", title: "THE DOME TILES",
    say: [["dilnoza", "The dome tiles go in a pattern that turns as it goes. One's been mopped out!"], ["pip", "Which tile fits the gap, Rory?"]],
    after: [["dilnoza", "Four hundred blues, and every one back in place."]] },
  sk2: { p: "shop", lv: 3, who: "Dilnoza", title: "THE SPICE SELLER",
    say: [["dilnoza", "The spice seller sells paint too. Buy two pots, and he'll tell us where the workshop is."], ["pip", "Exactly the money, Rory."]],
    after: [["dilnoza", "Behind the silk stalls. Of course."]] },
  sk3: { p: "cipher", lv: 3, word: "MONOCHROME", title: "HER SECRET PLANS",
    say: [["rory", "Her plans! But they're written in some kind of symbol code."], ["pip", "Use the key, Rory. What is she building?"]] },
  sk5: { p: "square", lv: 3, title: "THE GATE LOCK",
    say: [["dilnoza", "The Registan gates have a colour lock. Every colour once in each row and each column."], ["pip", "Fill in the white squares, Rory."]] },
  // ---------------------------------------------------------------- Plitvice Lakes
  pl1: { p: "pictogram", lv: 3, title: "THE RANGERS' CHART",
    say: [["marta", "The rangers chart the drops in each lake. Every picture stands for more than one!"], ["pip", "Look at the key, Rory."]] },
  pl2: { p: "fraction", lv: 3, title: "HOW MUCH IS LEFT?",
    say: [["marta", "The Blotters are draining the lakes into jars. The ranger's gauge shows how much is gone."], ["pip", "Paint the right fraction, Rory."]] },
  pl3: { p: "paint", lv: 3, title: "THE JAR LABELS",
    say: [["marta", "The jars have labels with sums on. Paint them in, and we'll see which jar holds the lake's colour."]],
    after: [["marta", "That one! The colour of the whole lake is in there."]] },
  pl5: { p: "mirror", lv: 3, title: "THE REFLECTION",
    say: [["marta", "The falls are reflected in the lake. The Blotters mopped the reflection!"], ["pip", "Paint the reflection so it matches, Rory."]] },
  // ---------------------------------------------------------------- Sossusvlei
  ss1: { p: "map", lv: 3, title: "THE DUNE MAP",
    say: [["tuli", "The dunes all look the same. Good thing I've got a map."], ["pip", "Follow the steps, Rory. Where did the Blotters land?"]],
    after: [["tuli", "Deadvlei. The white pan with the black trees."]] },
  ss2: { p: "shadow", lv: 3, title: "THE TREE SHADOWS",
    say: [["tuli", "The trees here throw long shadows. Which shadow goes with which shape? Look which way it's pointing."]] },
  ss3: { p: "square", lv: 4, title: "THE GANGWAY LOCK",
    say: [["rory", "The gangway has a colour lock. The biggest one yet."], ["pip", "One of each colour in every row and column, Rory."]] },
  ss4: { p: "suspect", lv: 3, title: "THE DISGUISE",
    say: [["tuli", "The people by the gangway! One of them is Grisaille herself, in disguise!"], ["pip", "Read the clues carefully, Rory. Some of them say NOT."]],
    after: [["grisaille", "You have sharp eyes, Agent Rory. Come aboard, then. If you dare."]] },
  // ---------------------------------------------------------------- The Monochrome
  mc1: { p: "cipher", lv: 4, word: "VAULT", title: "THE KEY TAG",
    say: [["rory", "The key has a tag on it. More symbols!"], ["pip", "Last code, Rory. Where does this key go?"]] },
  mc2: { p: "paint", lv: 4, title: "THE VAULT DOOR",
    say: [["pip", "The vault door is a paint-by-numbers lock, with times tables. Paint every square the right colour and it opens."]],
    after: [["rory", "It's open. Every colour in the world is in here."]] },
};
