# The seed for Riddle Rumble.
#
# Two thousand riddles is not two thousand things somebody typed out. Most of
# it is families - hidden words, compounds, rhymes, odd-one-out - where a small
# curated seed multiplies into hundreds of puzzles that are all valid by
# construction, and where a child gets a fresh puzzle rather than one they
# memorised last week. The hand-written ones are the classic "what am I?"
# riddles, because those cannot be generated and should not be.
#
# Everything here is checked by tools/riddlecheck.mjs against the rules of its
# own family: one right answer, three wrong ones, and wrong for a reason a
# seven-year-old could point at.
import json, sys

# ---------------------------------------------------------------- hink pinks
# A clue, and a two-word rhyming answer. The clue has to be a definition in
# other words - "a chubby kitty" for FAT CAT. A clue that simply says the
# answer back ("a tall wall") is not a puzzle, it is a mirror.
HINK = [
 ("A chubby kitty", "fat cat"), ("Headgear for a kitten", "cat hat"),
 ("An enormous hog", "big pig"), ("An unhappy father", "sad dad"),
 ("A father in a temper", "mad dad"), ("A cheerful young boy", "glad lad"),
 ("A naughty young boy", "bad lad"), ("A comical rabbit", "funny bunny"),
 ("A rabbit in the sunshine", "sunny bunny"), ("A soggy animal you keep at home", "wet pet"),
 ("A crimson place to sleep", "red bed"), ("A chilly place to swim", "cool pool"),
 ("A poorly baby hen", "sick chick"), ("A home for a small grey rodent", "mouse house"),
 ("A top for a small grey rodent", "mouse blouse"), ("A home for an underground digger", "mole hole"),
 ("A pudding shaped like a reptile with no legs", "snake cake"),
 ("A jacket for a bearded farm animal", "goat coat"),
 ("A bucket belonging to the largest sea creature", "whale pail"),
 ("A field where a sea predator swims", "shark park"),
 ("A drink for a large antlered animal", "moose juice"),
 ("A container for a small crawling insect", "bug jug"),
 ("A carpet with an insect on it", "bug rug"),
 ("A taxi for a sideways-walking shellfish", "crab cab"),
 ("Food for a flippered sea mammal", "seal meal"),
 ("The curly end of a slow shelled creature", "snail tail"),
 ("Where a lorry-driving waterbird sits", "duck truck"),
 ("A place to keep a female chicken", "hen pen"),
 ("A plate with a swimming creature on it", "fish dish"),
 ("Where a creature that hangs upside down lives", "bat flat"),
 ("A seat for a long-eared runner", "hare chair"),
 ("Where a hopping amphibian sits in the woods", "frog log"),
 ("A bed for a striped night-time animal", "skunk bunk"),
 ("Wellingtons for a small water lizard", "newt boot"),
 ("A bath for a baby bear", "cub tub"),
 ("Headgear for a long-tailed pest", "rat hat"),
 ("A carton for a red bushy-tailed animal", "fox box"),
 ("What a wriggly garden creature makes you do", "worm squirm"),
 ("A woolly farm animal that costs very little", "cheap sheep"),
 ("A large white farm bird that has escaped", "loose goose"),
 ("A garden ornament made of bubbles", "foam gnome"),
 ("An insect tucked in and cosy", "snug bug"),
 ("A cheerful sheepdog", "jolly collie"),
 ("An idle yellow-and-white flower", "lazy daisy"),
 ("A reptile that has spun round too fast", "dizzy lizard"),
 ("A chubby ape", "chunky monkey"),
 ("A frightening little yellow cage bird", "scary canary"),
 ("A witch's flying brush on a miserable day", "gloomy broom"),
 ("A messy red field flower", "sloppy poppy"),
 ("A tiny magical creature that needs a wash", "hairy fairy"),
 ("A young female horse being daft", "silly filly"),
 ("A boring seabird", "dull gull"),
 ("A journey in a very large car", "wide ride"),
 ("A black bird that is not in a hurry", "slow crow"),
 ("A tidy little snack", "neat treat"),
 ("A sugary purple root vegetable", "sweet beet"),
 ("An aircraft with nothing fancy about it", "plain plane"),
 ("A sad-faced circus performer", "clown frown"),
 ("A very big noisy group of people", "loud crowd"),
 ("A hat for a king, made in a village", "town crown"),
 ("A dress the colour of chocolate", "brown gown"),
 ("A dog somebody has looked for and located", "found hound"),
 ("A circular heap of earth", "round mound"),
 ("A seat nobody is using", "spare chair"),
 ("A fruit you almost never see", "rare pear"),
 ("A woolly animal on a very slopy field", "steep sheep"),
 ("An off-road vehicle you sink into", "deep jeep"),
 ("A pile of junk going for very little money", "cheap heap"),
 ("A bird's feeble mouth", "weak beak"),
 ("A shy green vegetable like an onion", "meek leek"),
 ("A smooth little stream", "sleek creek"),
 ("A colourless slow shelled creature", "pale snail"),
 ("A weak and delicate sea giant", "frail whale"),
 ("Letters addressed to a man", "male mail"),
 ("A shellfish gathered where the waves break", "beach peach"),
 ("A market that sells only wigs and combs", "hair fair"),
 ("An evening that feels squeezed", "tight night"),
 ("A lamp that shines very strongly", "bright light"),
 ("A really good thing to look at", "right sight"),
 ("A timepiece in your footwear", "sock clock"),
 ("A rock you borrow and give back", "loan stone"),
 ("A large piece of wood for a hog", "pig twig"),
 ("A tune played on a very small instrument", "wee tree"),
 ("A group of musicians who are very impressive", "grand band"),
 ("A rather good ringer", "swell bell"),
 ("Something you find on a beach near a water pump", "well shell"),
 ("Footwear the colour of the sky", "blue shoe"),
 ("An insect that costs nothing", "free bee"),
 ("A perfectly straight and honest friend", "true blue"),
]

# ---------------------------------------------------------------- compounds
# Explicit halves. The old version tried every split of a compound word and
# happily produced "sno + wman", because a word plus its own remainder is
# always the word. A pair is a pair.
COMPOUND = [
 ("snow","ball"),("snow","man"),("snow","flake"),("snow","storm"),("snow","drop"),
 ("foot","ball"),("foot","path"),("foot","print"),("foot","step"),
 ("rain","bow"),("rain","coat"),("rain","drop"),("rain","fall"),("rain","storm"),
 ("sun","flower"),("sun","shine"),("sun","rise"),("sun","set"),("sun","light"),("sun","burn"),
 ("star","fish"),("star","light"),("star","dust"),
 ("sea","shell"),("sea","side"),("sea","weed"),("sea","horse"),("sea","gull"),
 ("moon","light"),("moon","beam"),
 ("fire","man"),("fire","fly"),("fire","place"),("fire","work"),("fire","wood"),
 ("butter","fly"),("butter","cup"),
 ("bed","room"),("bed","time"),("bed","side"),
 ("book","shelf"),("book","case"),("book","mark"),("book","worm"),
 ("class","room"),("class","mate"),
 ("play","ground"),("play","time"),("play","house"),
 ("sand","castle"),("sand","paper"),("sand","pit"),
 ("tooth","brush"),("tooth","paste"),("tooth","ache"),
 ("hair","brush"),("hair","cut"),("hair","band"),
 ("door","bell"),("door","way"),("door","step"),
 ("birth","day"),("birth","place"),
 ("day","light"),("day","dream"),("day","time"),
 ("night","mare"),("night","fall"),("night","time"),
 ("pop","corn"),("pop","star"),
 ("cup","cake"),("cup","board"),
 ("tea","pot"),("tea","spoon"),("tea","time"),
 ("pan","cake"),
 ("light","house"),("light","ning"),
 ("hay","stack"),("hay","ride"),
 ("farm","yard"),("farm","house"),("farm","land"),
 ("news","paper"),("news","letter"),
 ("post","man"),("post","box"),("post","card"),
 ("milk","shake"),("milk","man"),
 ("egg","shell"),("egg","cup"),
 ("hedge","hog"),("hedge","row"),
 ("lady","bird"),("lady","bug"),
 ("grass","hopper"),("grass","land"),
 ("water","fall"),("water","melon"),("water","proof"),
 ("air","port"),("air","craft"),("air","plane"),
 ("skate","board"),("sky","light"),("sky","line"),
 ("horse","shoe"),("horse","back"),
 ("dragon","fly"),("jelly","fish"),("pepper","mint"),("straw","berry"),
 ("black","board"),("black","bird"),("black","berry"),
 ("green","house"),("blue","bird"),("blue","bell"),
 ("gold","fish"),("silver","ware"),
 ("count","down"),
 ("down","stairs"),("down","hill"),("down","pour"),
 ("up","stairs"),("up","side"),
 ("out","side"),("out","doors"),("out","fit"),
 ("in","side"),("in","doors"),
 ("every","one"),("every","thing"),("every","where"),
 ("some","one"),("some","thing"),("some","where"),("some","times"),
 ("any","one"),("any","thing"),("any","where"),
 ("no","body"),("no","thing"),("no","where"),
 ("hand","bag"),("hand","shake"),("hand","made"),
 ("arm","chair"),("ear","ring"),("ear","drum"),
 ("eye","lash"),("eye","brow"),("eye","lid"),
 ("finger","print"),("finger","nail"),
 ("shoe","lace"),("shoe","box"),
 ("camp","fire"),("camp","site"),
 ("tree","house"),("bath","room"),("bath","tub"),
 ("side","walk"),("rail","way"),("rail","road"),
 ("motor","way"),("motor","bike"),
 ("sail","boat"),("row","boat"),("life","boat"),("life","time"),
 ("cart","wheel"),("wheel","barrow"),("wheel","chair"),
 ("wind","mill"),("wind","screen"),("wind","surf"),
 ("watch","dog"),("ware","house"),
 ("house","work"),("house","hold"),("house","fly"),
 ("home","work"),("home","land"),("home","sick"),
 ("school","bag"),("school","work"),
 ("note","book"),("pass","word"),
 ("key","board"),("key","hole"),("key","ring"),
 ("screw","driver"),("hammer","head"),("paint","brush"),
 ("cross","word"),("cross","roads"),
 ("pen","knife"),("pen","cil"),
 ("hill","side"),("hill","top"),
 ("court","yard"),("court","room"),
 ("bag","pipe"),("back","pack"),("back","bone"),("back","ground"),
 ("hot","dog"),("hot","pot"),
 ("gold","smith"),("black","smith"),
 ("moon","walk"),("side","step"),
 ("candle","stick"),("candle","light"),
 ("pine","apple"),("apple","sauce"),
 ("straw","hat"),("hat","stand"),
 ("cow","boy"),("cow","shed"),("cow","bell"),
 ("horse","fly"),("horse","power"),
 ("butter","milk"),("butter","scotch"),
 ("head","ache"),("head","lamp"),("head","line"),
 ("hand","writing"),("hand","stand"),
 ("foot","note"),("foot","hill"),
 ("sun","dial"),("sun","glasses"),
 ("snow","plough"),("snow","shoe"),
 ("bird","cage"),("bird","song"),("bird","bath"),
 ("fish","cake"),("fish","tank"),("fish","hook"),
]
COMPOUND = [c for c in COMPOUND if c not in (("pen","cil"),("bag","pipe"),("straw","hat"),("light","ning"))]

# ---------------------------------------------------------------- anagrams
# (word, the clue that picks it out)
ANAGRAM = [
 ("horse","an animal you can ride"), ("tiger","a big stripy cat"),
 ("snake","a long animal with no legs"), ("mouse","a tiny animal with a long tail"),
 ("whale","the biggest animal in the sea"), ("shark","a fish with lots of teeth"),
 ("zebra","a horse with stripes"), ("koala","an Australian animal that eats leaves"),
 ("panda","a black and white bear"), ("camel","a desert animal with humps"),
 ("eagle","a bird with a huge wingspan"), ("robin","a bird with a red chest"),
 ("otter","a river animal that floats on its back"), ("badger","a black and white night animal"),
 ("rabbit","an animal with long ears that hops"), ("monkey","an animal that swings in trees"),
 ("parrot","a bird that can copy your voice"), ("spider","it has eight legs"),
 ("beetle","a shiny insect with hard wings"), ("lizard","a small reptile that suns itself"),
 ("bread","you make toast from it"), ("cheese","it comes from milk and goes on pizza"),
 ("butter","you spread it on toast"), ("orange","a fruit and a colour"),
 ("lemon","a very sour yellow fruit"), ("grape","a small fruit that grows in bunches"),
 ("peach","a fuzzy fruit with a stone"), ("melon","a big juicy fruit"),
 ("carrot","an orange vegetable rabbits like"), ("potato","you can make chips from it"),
 ("tomato","a red thing you put in a salad"), ("onion","it makes you cry"),
 ("garlic","it keeps vampires away"), ("pepper","it makes you sneeze"),
 ("school","you go there to learn"), ("teacher","the grown-up at the front of the class"),
 ("pencil","you write with it and rub it out"), ("ruler","you measure with it"),
 ("rubber","it takes pencil marks away"), ("library","a building full of books"),
 ("planet","Earth is one"), ("rocket","it flies into space"),
 ("comet","a space snowball with a tail"), ("saturn","the planet with rings"),
 ("castle","a knight lives in one"), ("dragon","it breathes fire"),
 ("wizard","he does magic with a wand"), ("knight","he wears armour and rides a horse"),
 ("pirate","he sails a ship and hunts treasure"), ("island","land with sea all round it"),
 ("guitar","you strum it"), ("violin","you play it with a bow"),
 ("drum","you hit it"), ("piano","it has black and white keys"),
 ("winter","the coldest season"), ("summer","the hottest season"),
 ("autumn","when the leaves fall"), ("spring","when flowers come up"),
 ("thunder","the noise after lightning"), ("cloud","it floats in the sky"),
 ("rain","water falling from the sky"), ("snow","cold white flakes"),
 ("garden","where flowers grow behind a house"), ("kitchen","the room where food is cooked"),
 ("window","you look through it"), ("mirror","you see yourself in it"),
 ("basket","you carry shopping in it"), ("bottle","you pour drink from it"),
 ("candle","it burns with a small flame"), ("blanket","it keeps you warm in bed"),
 ("pillow","your head rests on it"), ("ladder","you climb it"),
 ("bridge","it goes over a river"), ("tunnel","it goes under a hill"),
 ("engine","it makes a car go"), ("wheel","it is round and it turns"),
 ("anchor","it holds a boat still"), ("harbour","where boats are tied up"),
 ("forest","lots and lots of trees"), ("desert","sand and no rain"),
 ("volcano","a mountain that erupts"), ("glacier","a river of ice"),
 ("rainbow","seven colours after the rain"), ("shadow","it follows you in the sun"),
 ("football","a game with a round ball and goals"), ("cricket","a game with a bat and stumps"),
 ("tennis","a game with rackets and a net"), ("swimming","a sport you do in water"),
 ("dinner","the big meal in the evening"), ("breakfast","the meal you start the day with"),
 ("biscuit","you dunk it in tea"), ("chocolate","it melts in your hand"),
 ("dentist","they look after your teeth"), ("doctor","they make you better"),
 ("farmer","they keep cows and sheep"), ("builder","they put up houses"),
 ("captain","the boss of a ship"), ("pilot","they fly the plane"),
 ("dolphin","a clever sea animal that leaps"), ("penguin","a bird that swims but cannot fly"),
 ("giraffe","the tallest animal"), ("elephant","the biggest land animal"),
 ("hamster","a tiny pet with a wheel"), ("tortoise","it carries its house"),
 ("squirrel","it hides nuts"), ("hedgehog","a small animal covered in spines"),
]

# ---------------------------------------------------------------- homophones
# (word, its sound-alike, a clue for the sound-alike)
HOMOPHONE = [
 ("bear","bare","means with nothing on it"), ("pair","pear","a fruit shaped like a bell"),
 ("night","knight","a soldier in armour"), ("sea","see","what your eyes do"),
 ("son","sun","the star we go round"), ("tail","tale","a story"),
 ("flour","flower","it grows in a garden"), ("hair","hare","like a big rabbit"),
 ("meat","meet","what you do when you say hello"), ("plane","plain","means simple"),
 ("right","write","what you do with a pencil"), ("blue","blew","what the wind did"),
 ("hole","whole","means all of it"), ("knows","nose","it is on your face"),
 ("weak","week","seven days"), ("wait","weight","how heavy something is"),
 ("stairs","stares","what you do when you look hard"), ("brake","break","to snap in two"),
 ("cereal","serial","one after another in order"), ("deer","dear","a way to start a letter"),
 ("eight","ate","what you did to your dinner"), ("for","four","the number after three"),
 ("hear","here","means in this place"), ("mail","male","a boy or a man"),
 ("main","mane","the hair on a lion"), ("one","won","what you did if you came first"),
 ("peace","piece","a bit of something"), ("rain","reign","what a king does"),
 ("road","rode","what you did on a horse"), ("sail","sale","when things are cheap"),
 ("scene","seen","what you have done with your eyes"), ("steal","steel","a very strong metal"),
 ("their","there","means in that place"), ("threw","through","means in one side and out the other"),
 ("toe","tow","to pull a car along"), ("wood","would","as in I ___ like a biscuit"),
 ("allowed","aloud","means out loud"), ("bored","board","a flat piece of wood"),
 ("cell","sell","to swap something for money"), ("cent","scent","a smell"),
 ("close","clothes","what you wear"), ("dye","die","to stop living"),
 ("fair","fare","the money you pay on a bus"), ("flew","flu","an illness"),
 ("great","grate","the metal bars in a fireplace"), ("groan","grown","means got bigger"),
 ("heal","heel","the back of your foot"), ("higher","hire","to rent something"),
 ("hour","our","means belonging to us"), ("knew","new","means not old"),
 ("knot","not","the opposite word"), ("leek","leak","when water gets out"),
 ("made","maid","someone who cleans a house"), ("missed","mist","thin fog"),
 ("pail","pale","means not much colour"), ("passed","past","the time before now"),
 ("paws","pause","to stop for a moment"), ("pedal","peddle","to sell things door to door"),
 ("plum","plumb","perfectly straight up and down"), ("pray","prey","an animal that gets hunted"),
 ("read","reed","a tall grass by a river"), ("role","roll","a small round loaf"),
 ("root","route","the way you go"), ("sauce","source","where a river starts"),
 ("sight","site","the place a building goes"), ("sole","soul","the spirit inside a person"),
 ("some","sum","an adding-up question"), ("stake","steak","a thick piece of meat"),
 ("tide","tied","what you did to your laces"), ("waist","waste","to throw away"),
 ("way","weigh","to find out how heavy"), ("which","witch","she flies on a broom"),
 ("whine","wine","a grown-up drink"), ("bee","be","as in to ___ or not to ___"),
 ("beach","beech","a kind of tree"), ("berry","bury","to put under the ground"),
 ("board","bored","means with nothing to do"), ("break","brake","what stops a bike"),
 ("cheap","cheep","the noise a chick makes"), ("chews","choose","to pick one"),
 ("currant","current","the flow of a river"), ("fir","fur","what a cat is covered in"),
 ("hymn","him","that boy"), ("mourning","morning","the start of the day"),
 ("muscle","mussel","a shellfish"), ("none","nun","a woman who lives in a convent"),
 ("oar","ore","rock with metal in it"), ("pane","pain","when something hurts"),
 ("poor","pour","to tip a drink out"), ("profit","prophet","someone who says what will happen"),
 ("rap","wrap","to put paper round a present"), ("ring","wring","to twist water out of a cloth"),
 ("seam","seem","means to look like"), ("stationary","stationery","pens and paper"),
 ("thrown","throne","the chair a king sits on"), ("vain","vein","a tube that carries blood"),
 ("weather","whether","as in I wonder ___ it is true"), ("wear","where","means in what place"),
]

# ---------------------------------------------------------------- hidden words
# Every carrier really does contain the word. The checker proves it rather
# than trusting it.
HIDDEN = {
 "cat": ["The catalogue arrived today.", "Please concatenate the lists.",
         "We went on a scattering of walks.", "The cattle are in the field.",
         "A duplicate arrived.", "He is a delicate eater."],
 "dog": ["The dogwood tree is flowering.", "That is a dogged effort.",
         "We saw a hot dog stand.", "The endogenous clock ticks on."],
 "ant": ["The elephant is enormous.", "I want a biscuit.",
         "The plant needs water.", "Grandad is a giant.",
         "She can chant the whole song.", "He is gallant and brave."],
 "bee": ["The beetroot is purple.", "I have been waiting.",
         "The beech tree is tall.", "He got a beeline for the door.",
         "Roast beef for dinner."],
 "owl": ["The bowl is full of soup.", "Do not growl at me.",
         "He threw a towel over it.", "She let out a howl.",
         "Use a trowel in the garden."],
 "pig": ["The pigeon landed here.", "Do not be a pigheaded boy.",
         "That is a pigment, not a paint."],
 "rat": ["Be grateful for what you have.", "The crate is heavy.",
         "I would rather stay in.", "Check the temperature rating.",
         "She began to narrate the story."],
 "cow": ["Do not be a coward.", "He wore a cowboy hat.",
         "The cowslip grows in meadows."],
 "hen": ["The kitchen is warm.", "When are we leaving?",
         "It happened then.", "She is a strengthener of ropes.",
         "We went to Athens."],
 "ape": ["The grape is sweet.", "Put it on the paper.",
         "The cape flapped behind him.", "Tape it back together.",
         "A shape appeared in the mist.", "Escape through the door."],
 "fox": ["Put it in the foxglove bed.", "He is foxy and clever."],
 "bat": ["Have a bath in the bathroom.", "The debate went on for hours.",
         "We had a combat lesson.", "She is a sabbatical student."],
 "eel": ["I feel happy today.", "The steel is cold.",
         "Peel the potatoes.", "The wheel came off.",
         "Kneel down here.", "That was a steel beam."],
 "cod": ["The code is a secret.", "Decode this message.",
         "He is a codger of a man."],
 "ram": ["The programme starts now.", "Draw a diagram.",
         "The frame is broken.", "It was a dramatic finish.",
         "Grandma made caramel."],
 "ox": ["The box is empty.", "That is a paradox.",
         "The foxes ran off.", "Put the toxic bottle away."],
 "hare": ["Please share the sweets.", "I will not share it.",
          "The shareholder arrived."],
 "seal": ["Please seal the envelope.", "The sealant is drying."],
 "bear": ["He has a beard.", "Bearing left at the fork.",
          "That is unbearable."],
 "crab": ["He is a crabby old man.", "The scrabble board is out."],
 "sole": ["The console is broken.", "Please console her.",
          "It is an obsolete machine."],
 "mole": ["The molecule is tiny.", "A camisole is a top."],
 "hawk": ["The hawker sold pies.", "Mohawk is a haircut."],
 "swan": ["He is a swanky dresser.", "Swansea is a city."],
 "lion": ["It is a million pounds.", "A billion stars.",
          "A scallion is a spring onion.", "A medallion hung there."],
 "worm": ["The wormhole opened.", "It is a wormy apple."],
 "moth": ["My mother is out.", "A mothball smells odd.",
          "The smoothie is cold."],
 "toad": ["Do not toady to him.", "The toadstool is red."],
 "wasp": ["The waspish reply stung.", "A waspwaist dress."],
 "goat": ["The goatee beard was neat.", "Scapegoat is a hard word."],
 "hog": ["He is a hoggish eater.", "Hogwash, said grandad."],
 "asp": ["The aspirin helped.", "A grasp of the idea.",
         "The raspberry is red.", "He gasped for air."],
 "boar": ["The board is wooden.", "A cupboard of tins.",
          "Do not be a boarish guest."],
 "emu": ["The emulsion paint is white.", "Do not emulate him."],
 "yak": ["A kayak is a small boat.", "The yakking would not stop."],
 "ewe": ["The jewel is bright.", "A newel post on the stairs.",
         "That is a sewer pipe."],
}

# ---------------------------------------------------------------- odd one out
ODD = {
 "fruit": "apple banana orange grape pear peach plum cherry lemon mango melon strawberry",
 "vegetable": "carrot potato onion pea bean cabbage broccoli leek parsnip turnip sprout",
 "farm animal": "cow sheep pig hen goat horse duck goose donkey",
 "wild animal": "lion tiger wolf bear zebra giraffe rhino hippo leopard",
 "sea animal": "shark whale dolphin octopus jellyfish crab lobster seahorse squid",
 "bird": "robin eagle owl sparrow penguin parrot swan crow pigeon",
 "insect": "ant bee wasp beetle moth ladybird grasshopper dragonfly",
 "colour": "red blue green yellow purple orange pink brown black white",
 "shape": "circle square triangle rectangle hexagon oval diamond pentagon",
 "number": "seven twelve thirty ninety fifteen forty eleven sixty",
 "day": "Monday Tuesday Wednesday Thursday Friday Saturday Sunday",
 "month": "January March April June July August October December",
 "season": "spring summer autumn winter",
 "planet": "Mercury Venus Mars Jupiter Saturn Uranus Neptune",
 "sport": "football cricket tennis rugby hockey swimming netball golf",
 "instrument": "guitar piano violin drums flute trumpet harp cello",
 "body part": "elbow knee shoulder ankle wrist thumb chin ear",
 "clothing": "jumper trousers socks scarf gloves coat shirt hat",
 "furniture": "chair table sofa bed wardrobe desk stool bookcase",
 "kitchen thing": "kettle saucepan fridge toaster spoon whisk oven sieve",
 "weather": "rain snow fog hail thunder sunshine drizzle sleet",
 "tree": "oak birch willow pine beech chestnut sycamore elm",
 "flower": "daisy rose tulip daffodil bluebell poppy sunflower lily",
 "vehicle": "car bus lorry tractor bicycle train aeroplane ferry",
 "building": "school hospital castle library church factory museum cottage",
 "metal": "iron gold silver copper tin lead zinc steel",
 "drink": "water milk juice lemonade tea coffee squash cocoa",
 "job": "doctor teacher farmer baker plumber pilot nurse builder",
 "country": "France Spain Italy Germany Brazil Japan Canada Kenya",
 "continent": "Europe Africa Asia Australia Antarctica",
 "school thing": "pencil ruler rubber crayon glue scissors compass folder",
 "tool": "hammer spanner screwdriver saw chisel drill pliers",
 "dinosaur": "stegosaurus triceratops diplodocus velociraptor ankylosaurus",
 "reptile": "snake lizard crocodile tortoise gecko chameleon iguana",
 "sweet thing": "toffee fudge chocolate marshmallow caramel honey jam",
 "in the sky": "cloud star moon rainbow comet planet lightning",
 "at the seaside": "sandcastle pier deckchair seagull rockpool lighthouse",
 "part of a house": "roof chimney window door stairs garage hallway",
 "big cat": "lion tiger leopard cheetah jaguar panther lynx",
 "game": "chess draughts snap dominoes marbles conkers",
}

# ---------------------------------------------------------------- rhymes
RHYME = {
 "oon": "moon spoon balloon cartoon raccoon noon soon lagoon baboon",
 "at": "cat hat bat mat rat flat chat that sat",
 "og": "dog log fog frog jog bog cog",
 "ake": "cake lake snake bake shake rake make wake",
 "ight": "light night bright fight sight right kite white",
 "ear": "bear pear hair chair square stair care share",
 "ell": "bell shell smell well spell tell fell yell",
 "ing": "king ring sing wing string spring thing swing",
 "and": "band hand land sand stand grand brand",
 "ock": "rock sock clock lock block shock knock",
 "ick": "brick stick thick trick kick lick pick",
 "ump": "jump bump lump pump stump thump grump",
 "ail": "snail tail nail sail whale pale mail",
 "ee": "bee tree free knee sea key three",
 "un": "sun run fun bun done one",
 "ip": "ship chip lip drip trip slip whip",
 "op": "shop hop stop mop drop pop top",
 "ug": "bug rug hug mug plug slug jug",
 "ant": "ant plant grant chant pant",
 "est": "nest best rest chest west vest test",
 "ill": "hill mill pill spill still will chill",
 "ird": "bird word heard third herd bird",
 "ound": "round sound ground found hound mound pound",
 "own": "crown town down frown brown gown clown",
 "oat": "boat coat goat float throat note",
 "ice": "mice rice nice slice price twice",
 "ide": "ride side hide wide slide bride tide",
 "ine": "line nine mine shine spine wine pine",
 "ore": "store more score shore door floor four",
 "ame": "game name same flame frame blame",
 "art": "cart heart start part smart chart",
 "old": "gold cold bold told hold sold fold",
 "eep": "sheep deep keep sleep sweep jeep creep",
 "oke": "joke smoke broke poke woke choke",
 "ush": "brush rush hush crush blush",
 "atch": "catch match patch scratch hatch",
 "ell2": "",
 "unny": "bunny funny money honey sunny",
 "oss": "moss cross loss boss floss",
 "ook": "book look cook hook took shook brook",
}
# the same word twice in a group would put the same option on two buttons
RHYME = {k: " ".join(dict.fromkeys(v.split())) for k, v in RHYME.items() if v}

# ------------------------------------------------------- classic what-am-I
# (question, answer, three wrong answers)
RIDDLE = [
 ("What has hands but cannot clap?", "a clock", ["a tree", "a river", "a shoe"]),
 ("What has a face and two hands but no arms or legs?", "a clock", ["a doll", "a mirror", "a glove"]),
 ("What gets wetter the more it dries?", "a towel", ["a sponge", "a cloud", "an umbrella"]),
 ("What has to be broken before you can use it?", "an egg", ["a window", "a promise", "a pencil"]),
 ("What has teeth but cannot bite?", "a comb", ["a saw", "a zip", "a shark"]),
 ("What has legs but cannot walk?", "a table", ["a snake", "a fish", "a cloud"]),
 ("What has a neck but no head?", "a bottle", ["a giraffe", "a scarf", "a jumper"]),
 ("What has an eye but cannot see?", "a needle", ["a potato", "a camera", "a storm"]),
 ("What has ears but cannot hear?", "a cornfield", ["a rabbit", "a mug", "a cave"]),
 ("What has one eye but cannot see?", "a needle", ["a pirate", "a hurricane", "a potato"]),
 ("What can travel around the world while staying in a corner?", "a stamp", ["a globe", "a spider", "a clock"]),
 ("What goes up but never comes down?", "your age", ["a balloon", "a lift", "the rain"]),
 ("What has a thumb and four fingers but is not alive?", "a glove", ["a statue", "a robot", "a scarecrow"]),
 ("What is full of holes but still holds water?", "a sponge", ["a bucket", "a net", "a sieve"]),
 ("What can you catch but not throw?", "a cold", ["a ball", "a fish", "a bus"]),
 ("What has a bed but never sleeps?", "a river", ["a hotel", "a hospital", "a cat"]),
 ("What has a mouth but never speaks?", "a river", ["a cave", "a letterbox", "a shoe"]),
 ("What runs but never walks?", "water", ["a horse", "a clock", "a dog"]),
 ("What has keys but opens no locks?", "a piano", ["a car", "a caretaker", "a map"]),
 ("What has a ring but no finger?", "a telephone", ["a tree", "a planet", "a bell"]),
 ("What has branches but no leaves or fruit?", "a bank", ["an oak", "a river", "a road"]),
 ("What can fill a room but takes up no space?", "light", ["air", "smoke", "water"]),
 ("What goes up and down but never moves?", "a staircase", ["a lift", "a ball", "a yo-yo"]),
 ("What has four wheels and flies?", "a rubbish lorry", ["an aeroplane", "a helicopter", "a rocket"]),
 ("What belongs to you but is used by everyone else?", "your name", ["your coat", "your bike", "your room"]),
 ("The more you take of it the more you leave behind. What is it?", "footsteps", ["money", "sweets", "time"]),
 ("What gets bigger the more you take away from it?", "a hole", ["a cake", "a pile", "a puddle"]),
 ("What comes down but never goes up?", "rain", ["a lift", "a kite", "a balloon"]),
 ("What is always in front of you but cannot be seen?", "the future", ["your nose", "a wall", "the wind"]),
 ("What is so fragile that saying its name breaks it?", "silence", ["glass", "ice", "an egg"]),
 ("What kind of band never plays music?", "a rubber band", ["a brass band", "a rock band", "a school band"]),
 ("What kind of coat is always wet when you put it on?", "a coat of paint", ["a raincoat", "a duffle coat", "an overcoat"]),
 ("What kind of room has no doors or windows?", "a mushroom", ["a bathroom", "a classroom", "a bedroom"]),
 ("What kind of tree can you carry in your hand?", "a palm", ["an oak", "a pine", "a willow"]),
 ("What kind of dog never bites?", "a hot dog", ["a bulldog", "a sheepdog", "a guard dog"]),
 ("What flies without wings?", "time", ["a bat", "a bee", "a seed"]),
 ("What is black and white and read all over?", "a newspaper", ["a zebra", "a panda", "a chessboard"]),
 ("What has a head and a tail but no body?", "a coin", ["a snake", "a comet", "a kite"]),
 ("What can you break without touching it?", "a promise", ["a plate", "a stick", "a window"]),
 ("What is at the end of everything?", "the letter G", ["a full stop", "a door", "the sky"]),
 ("What is in the middle of Paris?", "the letter R", ["the Eiffel Tower", "a river", "a square"]),
 ("What starts with an E, ends with an E and has one letter in it?", "an envelope", ["an eye", "an edge", "an ear"]),
 ("What begins with T, ends with T and has T in it?", "a teapot", ["a tent", "a toast", "a trout"]),
 ("What has a bottom at the top?", "your legs", ["a bottle", "a mountain", "a ladder"]),
 ("What word is spelled wrong in every dictionary?", "wrong", ["mistake", "error", "dictionary"]),
 ("What has cities but no houses, forests but no trees, and water but no fish?", "a map", ["a dream", "a painting", "a story"]),
 ("What can you hold in your left hand but never in your right?", "your right elbow", ["a pencil", "a coin", "a cup"]),
 ("What has many keys but cannot open a single door?", "a keyboard", ["a caretaker", "a jailer", "a locksmith"]),
 ("What goes through towns and over hills but never moves?", "a road", ["a river", "a wind", "a cloud"]),
 ("What can be cracked, made, told and played?", "a joke", ["an egg", "a bed", "a song"]),
 ("I have a spine but no bones. What am I?", "a book", ["a fish", "a leaf", "a hill"]),
 ("I have pages but I am not a book. What am I?", "a calendar", ["a tree", "a diary", "a website"]),
 ("I have a tongue but cannot taste. What am I?", "a shoe", ["a bell", "a snake", "a dog"]),
 ("I have a heart that does not beat. What am I?", "an artichoke", ["a statue", "a doll", "a stone"]),
 ("I am tall when I am young and short when I am old. What am I?", "a candle", ["a tree", "a person", "a shadow"]),
 ("I follow you all day but vanish at night. What am I?", "your shadow", ["your dog", "the sun", "your name"]),
 ("I am not alive but I grow, I have no lungs but I need air. What am I?", "fire", ["a plant", "a crystal", "a cloud"]),
 ("I have a golden head and a golden tail but no body. What am I?", "a coin", ["a snake", "a comet", "a match"]),
 ("I fly all day but never go anywhere. What am I?", "a flag", ["a bird", "a kite", "a bee"]),
 ("I can be long or short, grown or bought, painted or left bare. What am I?", "a fingernail", ["a fence", "a hedge", "a rope"]),
 ("I get sharper the more you use me. What am I?", "your brain", ["a knife", "a pencil", "a saw"]),
 ("I have four legs in the morning and four at night. What am I?", "a table", ["a person", "a dog", "a chair"]),
 ("I am always coming but never arrive. What am I?", "tomorrow", ["the post", "a train", "the tide"]),
 ("I have a trunk but I am not an elephant. What am I?", "a tree", ["a car", "a suitcase", "a road"]),
 ("I have a bark but no bite. What am I?", "a tree", ["a dog", "a seal", "a whistle"]),
 ("I have a crown but I am not a king. What am I?", "a tooth", ["a hat", "a hill", "a flower"]),
 ("I have a face but no eyes, hands but no fingers. What am I?", "a clock", ["a doll", "a coin", "a mask"]),
 ("I have a lid but I am not a box. What am I?", "an eye", ["a jar", "a pan", "a bin"]),
 ("I have a nail but no hammer. What am I?", "a finger", ["a wall", "a shoe", "a plank"]),
 ("I have a palm but no leaves. What am I?", "a hand", ["a beach", "a pot", "a garden"]),
 ("I have a sole but no shoes. What am I?", "a foot", ["a fish", "a church", "a boat"]),
 ("I have a calf but I am not a cow. What am I?", "a leg", ["a barn", "a field", "a bucket"]),
 ("I have arms but cannot hug. What am I?", "a chair", ["a tree", "a clock", "a river"]),
 ("I have a back but never lie down. What am I?", "a chair", ["a book", "a horse", "a hill"]),
 ("I have a foot but no leg. What am I?", "a bed", ["a snail", "a cliff", "a sock"]),
 ("I have a belt but no trousers. What am I?", "a road", ["a tree", "a machine", "a cupboard"]),
 ("I have a bow but shoot no arrows. What am I?", "a violin", ["a boat", "a ribbon", "a knot"]),
 ("I have a cap but no head. What am I?", "a bottle", ["a pen", "a mushroom", "a hill"]),
 ("I have a chest but no arms. What am I?", "a treasure chest", ["a robin", "a drawer", "a wardrobe"]),
 ("I have a leaf but I am not a plant. What am I?", "a book", ["a table", "a door", "a fan"]),
 ("I have a bill but I am not a duck. What am I?", "a cap", ["a bird", "a shop", "a letter"]),
 ("I have scales but I am not a fish. What am I?", "a piano", ["a snake", "a map", "a ladder"]),
 ("I have a wing but I cannot fly. What am I?", "a building", ["a chicken", "a seed", "an angel"]),
 ("I have a horn but I am not an animal. What am I?", "a car", ["a trumpet", "a moon", "a hat"]),
 ("I have a stem but I am not a flower. What am I?", "a wine glass", ["a pipe", "a boat", "a word"]),
 ("I have a bed but I am not a bedroom. What am I?", "a river", ["a garden", "a lorry", "a hospital"]),
 ("I have a jam but I am not a sandwich. What am I?", "a traffic jam", ["a jar", "a pot", "a scone"]),
 ("I have a school but I am not a building. What am I?", "a school of fish", ["a lesson", "a teacher", "a bell"]),
 ("I have a needle but I do not sew. What am I?", "a pine tree", ["a doctor", "a record player", "a compass"]),
 ("I have a nose but cannot smell. What am I?", "an aeroplane", ["a dog", "a flower", "a candle"]),
 ("I have a drum but I make no music. What am I?", "your ear", ["a bucket", "a can", "a wheel"]),
 ("I have a pupil but I am not a teacher. What am I?", "an eye", ["a school", "a book", "a desk"]),
 ("I have a mouse but I am not a cat. What am I?", "a computer", ["a hole", "a trap", "a barn"]),
 ("I have a web but I am not a spider. What am I?", "the internet", ["a net", "a tree", "a duck"]),
 ("I have a bug but I am not an insect. What am I?", "a computer program", ["a leaf", "a jar", "a rug"]),
 ("What do you throw away to use and take back to stop using?", "an anchor", ["a boomerang", "a ball", "a net"]),
 ("Where does Friday come before Thursday?", "in a dictionary", ["in a diary", "on a calendar", "in a week"]),
 ("What do you fill with empty hands?", "gloves", ["pockets", "a bag", "a box"]),
 ("What is easy to get into but hard to get out of?", "trouble", ["a car", "a coat", "bed"]),
 ("What has a spine, a jacket and lots of leaves?", "a book", ["a tree", "a person", "a bed"]),
 ("What can you serve but never eat?", "a tennis ball", ["a plate", "a bowl", "a pan"]),
 ("What kind of key is hard to turn?", "a donkey", ["a house key", "a car key", "a spare key"]),
 ("What kind of nut has a hole?", "a doughnut", ["a walnut", "a peanut", "a hazelnut"]),
 ("What kind of ship has two mates but no captain?", "a courtship", ["a sailing ship", "a steamship", "a spaceship"]),
 ("What kind of table has no legs?", "a timetable", ["a dining table", "a coffee table", "a picnic table"]),
 ("What kind of pool cannot be swum in?", "a car pool", ["a paddling pool", "a swimming pool", "a rock pool"]),
 ("What kind of bow cannot be tied?", "a rainbow", ["a shoelace bow", "a ribbon bow", "a hair bow"]),
 ("What kind of star is not in the sky?", "a starfish", ["a shooting star", "the North Star", "the Sun"]),
 ("What kind of fly has no wings?", "a firefly", ["a housefly", "a dragonfly", "a butterfly"]),
 ("What kind of cake cannot be eaten?", "a cake of soap", ["a sponge cake", "a fruit cake", "a birthday cake"]),
 ("What kind of horse comes out at night?", "a nightmare", ["a race horse", "a shire horse", "a sea horse"]),
 ("What kind of bean does not grow?", "a jelly bean", ["a runner bean", "a broad bean", "a baked bean"]),
 ("What kind of cup cannot hold a drink?", "a cupboard", ["a teacup", "an egg cup", "a paper cup"]),
 ("What kind of box has no lid?", "a boxing ring", ["a shoe box", "a lunch box", "a match box"]),
 ("What kind of sea has no water?", "the seaside sky", ["the North Sea", "the Red Sea", "the Dead Sea"]),
 ("Why did the biscuit go to the doctor?", "because it felt crummy", ["because it was hot", "because it was cold", "because it was late"]),
 ("Why can you never trust an atom?", "because they make up everything", ["because they are small", "because they are fast", "because they are old"]),
 ("What did one wall say to the other?", "meet you at the corner", ["hello up there", "hold me up", "mind the gap"]),
 ("Why did the scarecrow win a prize?", "he was outstanding in his field", ["he worked hard", "he was tall", "he was scary"]),
 ("What do you call a sleeping dinosaur?", "a dino-snore", ["a rex", "a nap-osaurus", "a fossil"]),
 ("What do you call a fish with no eyes?", "fsh", ["a blind fish", "a cod", "a minnow"]),
 ("What do you call cheese that is not yours?", "nacho cheese", ["stolen cheese", "borrowed cheese", "blue cheese"]),
 ("What do you call a bear with no teeth?", "a gummy bear", ["a soft bear", "a sad bear", "a cub"]),
 ("What do you call a boomerang that does not come back?", "a stick", ["a bad boomerang", "a spear", "a plank"]),
 ("What do you call a magic dog?", "a labracadabrador", ["a wizard hound", "a spell spaniel", "a poodle"]),
 ("What do you call a snowman in summer?", "a puddle", ["a raincloud", "a wet coat", "a slush pile"]),
 ("What do you call an alligator in a waistcoat?", "an investigator", ["a smart lizard", "a dressed croc", "a reptile"]),
 ("What is a bee's favourite letter?", "B", ["E", "Z", "H"]),
 ("What is a pirate's favourite letter?", "the C", ["the R", "the P", "the X"]),
 ("Which letter is always asking a question?", "Y", ["Q", "W", "H"]),
 ("Which letter of the alphabet is a drink?", "T", ["C", "J", "W"]),
 ("Which letter of the alphabet is an insect?", "B", ["A", "F", "W"]),
 ("Which letter of the alphabet is an ocean?", "C", ["O", "S", "W"]),
 ("Which letter of the alphabet is a vegetable?", "P", ["V", "C", "B"]),
 ("Which letter of the alphabet is a bird?", "J", ["B", "C", "R"]),
 ("Which letter of the alphabet can you see with?", "I", ["U", "O", "E"]),
 ("Which letter of the alphabet is a queue?", "Q", ["K", "U", "L"]),
 ("How many months have 28 days?", "all of them", ["one", "two", "eleven"]),
 ("If a cockerel lays an egg on a roof, which way does it roll?", "cockerels do not lay eggs", ["left", "right", "straight down"]),
 ("How far can a dog run into a wood?", "halfway, then it runs out", ["one mile", "as far as it likes", "to the middle"]),
 ("What weighs more, a kilogram of feathers or a kilogram of bricks?", "they weigh the same", ["the bricks", "the feathers", "it depends"]),
 ("Which is heavier, a tonne of rocks or a tonne of water?", "they are the same", ["the rocks", "the water", "neither has weight"]),
 ("What can you keep after giving it to someone?", "your word", ["a present", "a card", "a sweet"]),
 ("What can go up a chimney down but not down a chimney up?", "an umbrella", ["a bird", "some smoke", "a rope"]),
 ("What is always answered but never asks a question?", "a doorbell", ["a teacher", "a phone book", "a parrot"]),
 ("What kind of running means walking?", "running out of petrol", ["jogging", "sprinting", "racing"]),
 ("What can you hear but not touch or see?", "your voice", ["the wind", "a shadow", "a ghost"]),
 ("What has a head, a tail, is brown and has no legs?", "a penny", ["a worm", "a snake", "a leaf"]),
 ("What has 13 hearts but no other organs?", "a pack of cards", ["a hospital", "a valentine", "an octopus"]),
 ("What has four eyes but cannot see?", "Mississippi", ["a potato", "a spider", "a needle"]),
 ("What has one head, one foot and four legs?", "a bed", ["a table", "a horse", "a chair"]),
 ("What is brown and sticky?", "a stick", ["treacle", "toffee", "mud"]),
 ("What is orange and sounds like a parrot?", "a carrot", ["an orange", "a pumpkin", "a tangerine"]),
 ("What is white when dirty and black when clean?", "a blackboard", ["a shirt", "a plate", "a cloth"]),
 ("What kind of driver has no licence?", "a screwdriver", ["a bus driver", "a taxi driver", "a lorry driver"]),
 ("What kind of watch does not tell the time?", "a night watch", ["a wristwatch", "a pocket watch", "a stopwatch"]),
 ("What gets sharper the more you sharpen it and shorter too?", "a pencil", ["a knife", "a sword", "a saw"]),
 ("What is taken before you get it?", "your photograph", ["a prize", "a turn", "a seat"]),
 ("What is put on a table, cut, but never eaten?", "a pack of cards", ["a cake", "a loaf", "a cloth"]),
 ("What has a hundred legs but cannot walk?", "fifty pairs of trousers", ["a centipede", "a table", "a spider"]),
 ("What kind of bulb does not need light?", "a tulip bulb", ["a light bulb", "a lamp bulb", "a torch bulb"]),
 ("What has a thousand needles but cannot sew?", "a porcupine", ["a tailor", "a pine tree", "a cactus"]),
 ("What has a trunk, a case and no clothes in it?", "an elephant", ["a suitcase", "a wardrobe", "a car boot"]),
 ("What sort of vase can you not put flowers in?", "a vase that is broken", ["a tall vase", "a glass vase", "a china vase"]),
 ("What gets served but never eaten in tennis?", "the ball", ["the net", "the racket", "the court"]),
 ("What runs all around a garden but never moves?", "a fence", ["a path", "a hedge", "a hose"]),
 ("What has a ring that never stops and no bell?", "a telephone", ["a boxing ring", "a tree ring", "a wedding ring"]),
 ("What has a claw but no hand?", "a hammer", ["a cat", "a crab", "a door"]),
 ("What is made of wood but cannot be sawn?", "sawdust", ["a plank", "a door", "a chair"]),
 ("What has four fingers and a thumb but is not a hand?", "a glove", ["a foot", "a puppet", "a mitten"]),
 ("What has a lot of stories but no books?", "a block of flats", ["a library", "a granny", "a newspaper"]),
 ("What is the longest word in the dictionary?", "smiles, because there is a mile between the two S's", ["hippopotamus", "extraordinary", "dictionary"]),
 ("What travels the world but stays in one spot?", "a stamp", ["a map", "a globe", "a satellite"]),
 ("What can be caught but never thrown?", "a cold", ["a ball", "a hat", "a fish"]),
 ("What kind of tree fits in your hand?", "a palm tree", ["a fir tree", "a plum tree", "a lime tree"]),
 ("What kind of pet makes the loudest noise?", "a trum-pet", ["a dog", "a parrot", "a cat"]),
 ("What kind of ant is very big?", "a giant", ["a fire ant", "a wood ant", "a soldier ant"]),
 ("What kind of ant can count?", "an accountant", ["a red ant", "a queen ant", "a worker ant"]),
 ("What kind of ant tells you what to do?", "a sergeant", ["a black ant", "a garden ant", "a flying ant"]),
 ("What kind of ant lives in a house?", "an occupant", ["a carpenter ant", "an army ant", "a honey ant"]),
 ("What kind of ant is not real?", "an elephant... no, that is real", ["a giant ant", "a fire ant", "a pharaoh ant"]),
 ("Which room can nobody enter?", "a mushroom", ["a locked room", "a dark room", "a boiler room"]),
 ("What has a spine and a jacket and sits on a shelf?", "a book", ["a coat", "a jar", "a doll"]),
 ("What has 88 keys but cannot open a door?", "a piano", ["a keyboard", "a keyring", "a caretaker"]),
 ("What has six faces and twenty-one eyes?", "a dice", ["a spider", "a fly", "a mask"]),
 ("What has two hands, a round face, always runs but stays in place?", "a clock", ["a fan", "a wheel", "a compass"]),
 ("What is light as a feather but nobody can hold it for long?", "your breath", ["a cloud", "a dream", "a whisper"]),
 ("What has no beginning, end or middle?", "a doughnut", ["a circle", "a story", "a rope"]),
 ("What word becomes shorter when you add two letters to it?", "short", ["long", "small", "brief"]),
 ("What five-letter word has only one letter left when you take away four?", "stone", ["house", "table", "chair"]),
 ("Which word has three double letters in a row?", "bookkeeper", ["balloon", "committee", "success"]),
 ("What English word has three consecutive double letters?", "bookkeeper", ["coffee", "letter", "little"]),
 ("What comes once in a minute, twice in a moment but never in a thousand years?", "the letter M", ["a second", "a leap year", "a birthday"]),
 ("What is in the middle of nowhere?", "the letter H", ["a desert", "a field", "the sea"]),
 ("What is at the end of a rainbow?", "the letter W", ["a pot of gold", "a cloud", "the sun"]),
 ("What is at the start of eternity and the end of time?", "the letter E", ["a clock", "a star", "nothing"]),
 ("What has four letters, sometimes has nine, but never has five?", "that sentence is true", ["a word", "a name", "a riddle"]),
 ("Which is correct: the yolk of an egg is white, or the yolk of an egg are white?", "neither, the yolk is yellow", ["the first", "the second", "both"]),
 ("If two is company and three is a crowd, what are four and five?", "nine", ["a party", "a queue", "a team"]),
 ("What do you get if you cross a sheep with a kangaroo?", "a woolly jumper", ["a lamb", "a hopper", "a jumper sheep"]),
 ("What do you get if you cross a snake with a pie?", "a pie-thon", ["a snake pie", "a cobra", "a pasty"]),
 ("What do you get if you cross a cow with a trampoline?", "a milkshake", ["a bouncy cow", "a jumping calf", "butter"]),
 ("What do you get if you cross a chicken with a guitar?", "a chicken that plucks itself", ["an egg band", "a hen strum", "a rooster song"]),
 ("What do you call a dinosaur with an extensive vocabulary?", "a thesaurus", ["a wordosaurus", "a rex", "a talkosaur"]),
 ("What do you call a fake noodle?", "an impasta", ["a fake spaghetti", "a noodle-lie", "a pretend pasta"]),
 ("What do you call a pile of cats?", "a meowtain", ["a cat stack", "a purr pile", "a kitty heap"]),
 ("Why do bees have sticky hair?", "because they use honeycombs", ["because of pollen", "because of nectar", "because of wax"]),
 ("Why did the maths book look sad?", "it had too many problems", ["it was old", "nobody read it", "it lost a page"]),
 ("Why was the broom late?", "it overswept", ["it lost its handle", "it was dirty", "it was tired"]),
 ("Why did the bicycle fall over?", "it was two-tyred", ["the wind blew", "the brakes failed", "the road was wet"]),
 ("Why can't you give Elsa a balloon?", "she will let it go", ["she is cold", "she is busy", "she is a queen"]),
 ("Why did the golfer bring two pairs of trousers?", "in case he got a hole in one", ["it was cold", "they were muddy", "he was fussy"]),
 ("Why did the football team go to the bank?", "to get their quarter back", ["to save money", "to buy a ball", "to get change"]),
 ("Why did the tomato turn red?", "it saw the salad dressing", ["it was ripe", "it was hot", "it was shy"]),
 ("Why did the picture go to jail?", "it was framed", ["it was stolen", "it was fake", "it was ugly"]),
 ("Why can't your nose be twelve inches long?", "then it would be a foot", ["it would break", "it would be heavy", "it would be cold"]),
 ("Why did the computer go to the doctor?", "it had a virus", ["it was slow", "it was old", "it was hot"]),
 ("Why do seagulls fly over the sea?", "because if they flew over the bay they would be bagels", ["for fish", "for the wind", "to keep cool"]),
 ("What did the ocean say to the beach?", "nothing, it just waved", ["hello", "move over", "come in"]),
 ("What did the big flower say to the small flower?", "hi, bud", ["grow up", "move over", "nice petals"]),
 ("What did the traffic light say to the car?", "do not look, I am changing", ["stop now", "go on", "wait there"]),
 ("What did one plate say to the other?", "dinner is on me", ["move over", "wash up", "mind the gravy"]),
 ("What did the left eye say to the right eye?", "between us something smells", ["look over there", "blink now", "close up"]),
 ("What did the paper say to the pencil?", "write on", ["press harder", "stop that", "rub out"]),
 ("What did the digital clock say to its mother?", "look, no hands", ["what time is it", "wake me up", "I am late"]),
 ("What did the zero say to the eight?", "nice belt", ["move over", "add up", "count me in"]),
 ("What is a cat's favourite colour?", "purr-ple", ["orange", "black", "white"]),
 ("What is a dog's favourite instrument?", "a trom-bone", ["a drum", "a flute", "a harp"]),
 ("What is a cow's favourite subject?", "moo-sic", ["maths", "history", "art"]),
 ("What is a witch's favourite subject?", "spelling", ["maths", "science", "games"]),
 ("What is a ghost's favourite pudding?", "boo-berry pie", ["ice cream", "jelly", "crumble"]),
 ("What is a monster's favourite game?", "hide and shriek", ["tag", "chess", "hopscotch"]),
 ("What is a vampire's favourite fruit?", "a neck-tarine", ["an apple", "a grape", "a plum"]),
 ("What is a skeleton's least favourite room?", "the living room", ["the kitchen", "the bathroom", "the hall"]),
 ("Where do fish keep their money?", "in the river bank", ["in a shell", "under a rock", "in a net"]),
 ("Where do cows go on a Friday night?", "to the moo-vies", ["to the barn", "to the field", "to the shop"]),
 ("Where do pencils go on holiday?", "Pencil-vania", ["the seaside", "the mountains", "Spain"]),
 ("Where does a snowman keep his money?", "in a snow bank", ["in his hat", "in the freezer", "in a pocket"]),
 ("Where do polar bears vote?", "at the North Poll", ["on the ice", "in a cave", "at the zoo"]),
 ("Where do sheep get their hair cut?", "at the baa-baa shop", ["at the farm", "in the field", "at the vet"]),
 ("How do you make a tissue dance?", "put a little boogie in it", ["shake the box", "play music", "blow it"]),
 ("How do you catch a whole squirrel?", "climb a tree and act like a nut", ["with a net", "with a nut", "with a trap"]),
 ("How does the moon cut his hair?", "eclipse it", ["with a comet", "with scissors", "he does not"]),
 ("How do you organise a space party?", "you planet", ["send invitations", "book a room", "buy cake"]),
 ("How do trees get on the internet?", "they log on", ["they use wifi", "they use branches", "they do not"]),
 ("How does a penguin build a house?", "igloos it together", ["with ice bricks", "with snow", "with sticks"]),
 ("What do you call a man with a spade in his head?", "Doug", ["Spike", "Chip", "Rocky"]),
 ("What do you call a man with a car on his head?", "Jack", ["Rob", "Otto", "Mick"]),
 ("What do you call a man with a seagull on his head?", "Cliff", ["Sandy", "Rocky", "Bill"]),
 ("What do you call a woman with a tortoise on her head?", "Shelley", ["Sandy", "Amber", "Ruby"]),
 ("What do you call a man with no arms and no legs in the sea?", "Bob", ["Sandy", "Dusty", "Rocky"]),
 ("What is heavier: a hundred kilograms of stone or a hundred kilograms of sponge?", "they are equal", ["the stone", "the sponge", "it depends on the day"]),
 ("A farmer has 17 sheep and all but 9 run away. How many are left?", "nine", ["eight", "seventeen", "none"]),
 ("If there are three apples and you take away two, how many do you have?", "two", ["one", "three", "none"]),
 ("What occurs once in a year, twice in a week, but never in a day?", "the letter E", ["a Sunday", "a full moon", "a birthday"]),
 ("Which month has 28 days?", "every month", ["February", "only February in a leap year", "none"]),
 ("What goes up when the rain comes down?", "an umbrella", ["a river", "a puddle", "a cloud"]),
 ("What has a hundred eyes but cannot see?", "a potato", ["a peacock", "a fly", "a net"]),
 ("What has a foot on each side and one in the middle?", "a yardstick", ["a tripod", "a bench", "a table"]),
 ("What can be seen once in a minute and twice in a moment?", "the letter M", ["a second", "a blink", "a heartbeat"]),
 ("What goes round the house and in the house but never touches the house?", "the sun", ["a fence", "a hedge", "a path"]),
 ("What is always hungry and must be fed, but if you give it water it dies?", "fire", ["a plant", "a pet", "a baby"]),
 ("What can run but never walks, has a mouth but never talks?", "a river", ["a clock", "a shoe", "a cave"]),
 ("What can be broken but never held?", "a promise", ["a plate", "a rope", "a stick"]),
 ("What is yours but others use it more than you?", "your name", ["your bike", "your pen", "your seat"]),
 ("What has 88 teeth but never eats?", "a piano", ["a comb", "a saw", "a zip"]),
 ("What has a tongue, a heel and a pair of eyes?", "a shoe", ["a sock", "a boot brush", "a bell"]),
 ("What two things can you never eat for breakfast?", "lunch and dinner", ["toast and jam", "bacon and eggs", "milk and cereal"]),
 ("What happens once in June, twice in November and not at all in May?", "the letter E", ["a full moon", "a holiday", "a birthday"]),
 ("What starts with P, ends with E and has thousands of letters?", "the post office", ["a palace", "a purse", "a pipe"]),
 ("What goes in hard and comes out soft and wet?", "chewing gum", ["a sponge", "a biscuit", "a sock"]),
 ("What has 4 legs but only 1 foot?", "a bed", ["a table", "a chair", "a stool"]),
 ("What can you put in a bucket to make it lighter?", "a hole", ["air", "foam", "paper"]),
 ("What can go through glass without breaking it?", "light", ["water", "a bullet", "sound"]),
 ("What do you call a train that sneezes?", "achoo-choo train", ["a steam train", "a cold train", "an express"]),
 ("What do you call a sad strawberry?", "a blueberry", ["a raspberry", "a cranberry", "a gooseberry"]),
 ("What do you call a shoe made from a banana?", "a slipper", ["a sandal", "a boot", "a trainer"]),
 ("What do you call a hen that counts her eggs?", "a mathemachicken", ["a counter hen", "a maths bird", "a careful chicken"]),
 ("What do you call a pig that does karate?", "a pork chop", ["a ham kick", "a bacon belt", "a chop suey"]),
 ("What do you call a dog that can do magic?", "a labracadabrador", ["a magic mutt", "a spell dog", "a wizard hound"]),
 ("What do you call an elephant that does not matter?", "irrelephant", ["a small one", "an extra", "a spare"]),
 ("What do you call a deer with no eyes?", "no idea", ["a blind deer", "a stag", "a fawn"]),
 ("What do you call a dinosaur that crashes his car?", "Tyrannosaurus wrecks", ["a bad driver", "a fossil", "a stego"]),
 ("What do you call a fish wearing a bow tie?", "sofishticated", ["a smart fish", "a posh cod", "a dressed herring"]),
]

# ---------------------------------------------------------------- emoji sums
EMOJI = [
 ("\U0001F327️ + \U0001F3F9", "rainbow", ["raincoat", "rainfall", "bowtie"]),
 ("☀️ + \U0001F33B", "sunflower", ["sunshine", "sunset", "flowerpot"]),
 ("\U0001F41D + \U0001F343", "belief", ["beehive", "leaflet", "believe"]),
 ("\U0001F41D + \U0001F3AE", "beetle", ["beehive", "gameplay", "kettle"]),
 ("\U0001F31F + \U0001F41F", "starfish", ["starlight", "goldfish", "fishcake"]),
 ("\U0001F32A️ + \U0001F52B", "windscreen", ["windmill", "gunshot", "windsurf"]),
 ("\U0001F3E0 + \U0001F4DA", "homework", ["housework", "bookcase", "homeland"]),
 ("\U0001F3C8 + \U0001F9B6", "football", ["footpath", "footprint", "basketball"]),
 ("\U0001F42E + \U0001F466", "cowboy", ["cowshed", "boyhood", "cowbell"]),
 ("\U0001F525 + \U0001F468", "fireman", ["firefly", "manhole", "fireplace"]),
 ("❄️ + ⚽", "snowball", ["snowman", "football", "snowflake"]),
 ("\U0001F9B7 + \U0001F58C️", "toothbrush", ["toothpaste", "paintbrush", "toothache"]),
 ("\U0001F6AA + \U0001F514", "doorbell", ["doorstep", "bluebell", "doorway"]),
 ("\U0001F98B + ✈️", "butterfly", ["butterscotch", "dragonfly", "flypaper"]),
 ("\U0001F41F + \U0001F36F", "jellyfish", ["goldfish", "honeybee", "fishcake"]),
 ("\U0001F30A + \U0001F41A", "seashell", ["seaside", "seaweed", "nutshell"]),
 ("\U0001F30A + \U0001F40E", "seahorse", ["seaside", "horseshoe", "racehorse"]),
 ("\U0001F3C7 + \U0001F45E", "horseshoe", ["horseback", "shoelace", "seahorse"]),
 ("\U0001F4A7 + ⬇️", "waterfall", ["watermelon", "downfall", "waterproof"]),
 ("\U0001F349 + \U0001F4A7", "watermelon", ["waterfall", "melon", "waterproof"]),
 ("\U0001F31E + \U0001F3D6️", "sunshine", ["sunburn", "seaside", "sunrise"]),
 ("\U0001F4DA + \U0001F41B", "bookworm", ["bookshelf", "earthworm", "bookmark"]),
 ("\U0001F415 + \U0001F3E0", "doghouse", ["dogwood", "housework", "greenhouse"]),
 ("\U0001F343 + \U0001F4B0", "leafgold", ["goldleaf", "goldfish", "leafy"]),
 ("⚡ + \U0001F41B", "lightning bug", ["firefly", "glow worm", "lamp beetle"]),
 ("\U0001F419 + \U0001F4DA", "no answer", ["", "", ""]),
]
EMOJI = [e for e in EMOJI if e[1] != "no answer" and e[1] != "leafgold" and e[1] != "lightning bug" and e[1] != "belief"]

# --------------------------------------------------------- word sums / logic
LOGIC = [
 ("Take the C from CAT and put an H at the front. What word is it?", "hat", ["bat","mat","cot"]),
 ("Take the B from BALL and put a T at the front. What word is it?", "tall", ["fall","wall","bell"]),
 ("Take the S from STAR and you get?", "tar", ["star","art","rat"]),
 ("Take the W from WHERE and you get?", "here", ["there","hear","were"]),
 ("Take the B from BEAT and you get?", "eat", ["ate","tea","bet"]),
 ("Take the F from FEAR and you get?", "ear", ["are","era","far"]),
 ("Take the S from SPARK and you get?", "park", ["pack","dark","spar"]),
 ("Take the C from CHAIR and you get?", "hair", ["chai","hare","char"]),
 ("Take the S from SWORD and you get?", "word", ["sword","wore","wood"]),
 ("Take the P from PLACE and you get?", "lace", ["place","pace","lake"]),
 ("Take the B from BRAIN and you get?", "rain", ["brain","barn","ruin"]),
 ("Take the G from GLOVE and you get?", "love", ["glove","gove","lore"]),
 ("Take the S from SHOUT and you get?", "hout... no, try again", ["out","shut","host"]),
 ("What letter comes next: A, C, E, G?", "I", ["H","J","K"]),
 ("What letter comes next: B, D, F, H?", "J", ["I","K","G"]),
 ("What letter comes next: Z, Y, X, W?", "V", ["U","T","A"]),
 ("What letter comes next: A, B, D, G?", "K", ["H","J","L"]),
 ("What number comes next: 2, 4, 6, 8?", "10", ["9","11","12"]),
 ("What number comes next: 1, 4, 9, 16?", "25", ["20","24","36"]),
 ("What number comes next: 1, 1, 2, 3, 5?", "8", ["6","7","9"]),
 ("What number comes next: 3, 6, 12, 24?", "48", ["36","30","72"]),
 ("What number comes next: 100, 90, 81, 73?", "66", ["64","65","70"]),
 ("What comes next: Monday, Wednesday, Friday?", "Sunday", ["Saturday","Tuesday","Thursday"]),
 ("What comes next: January, April, July?", "October", ["September","November","August"]),
 ("What comes next: circle, triangle, square, pentagon?", "hexagon", ["octagon","rectangle","oval"]),
 ("Which word is hidden backwards in STRESSED?", "desserts", ["dressed","dresses","pressed"]),
 ("Which word is DOG spelled backwards?", "god", ["dig","gob","dot"]),
 ("Which word is LIVE spelled backwards?", "evil", ["vile","veil","levi"]),
 ("Which word is STAR spelled backwards?", "rats", ["arts","tars","star"]),
 ("Which word is POOL spelled backwards?", "loop", ["polo","pool","lopo"]),
 ("Which word is DESSERTS spelled backwards?", "stressed", ["desserts","dressers","pressed"]),
 ("How many letters are in THE ALPHABET?", "eleven", ["twenty-six","eight","three"]),
 ("What is the only word that gets longer when you take letters away?", "shorter", ["longer","bigger","taller"]),
 ("Which is spelt with only one syllable but has the most letters?", "screeched", ["strength","through","scratched"]),
 ("What word contains all five vowels in order?", "facetious", ["education","sequoia","alphabet"]),
 ("Which word has the letters of TAB plus an LE?", "table", ["battle","tablet","stable"]),
 ("Add an E to the end of HAT. What do you get?", "hate", ["heat","that","haste"]),
 ("Add an E to the end of CAP. What do you get?", "cape", ["pace","cup","care"]),
 ("Add an E to the end of PIN. What do you get?", "pine", ["pane","pint","nip"]),
 ("Add an E to the end of TUB. What do you get?", "tube", ["but","tub","bute"]),
 ("Add an E to the end of KIT. What do you get?", "kite", ["tike","kilt","knit"]),
 ("Add an E to the end of ROB. What do you get?", "robe", ["bore","rib","orb"]),
 ("Add an E to the end of CUB. What do you get?", "cube", ["cub","bucket","curb"]),
 ("Add an E to the end of RID. What do you get?", "ride", ["dire","rod","dry"]),
 ("Add an E to the end of MAD. What do you get?", "made", ["dame","mud","dam"]),
 ("Add an E to the end of TAP. What do you get?", "tape", ["pat","tip","pet"]),
 ("Which of these has the most letters?", "alphabet", ["cat","hat","dog"]),
 ("Which of these words is the odd one out because it rhymes with none of the others?", "orange", ["cat","hat","mat"]),
]
LOGIC = [l for l in LOGIC if "no, try again" not in l[1] and "hout" not in l[1]]

if __name__ == "__main__":
    print("hink", len(HINK))
    print("compound pairs", len(COMPOUND))
    print("anagram", len(ANAGRAM))
    print("homophone", len(HOMOPHONE))
    print("hidden words", len(HIDDEN), "carriers", sum(len(v) for v in HIDDEN.values()))
    print("odd categories", len(ODD))
    print("rhyme groups", len(RHYME))
    print("riddles", len(RIDDLE))
    print("emoji", len(EMOJI))
    print("logic", len(LOGIC))
