// Agent Rory: Timeslip — the cast, the acts, the eras and every mission's lines. Doctor
// Hourglass is bottling history's great moments to run her Fast-Forward Engine; Rory follows her
// back through time on the POLARIS time-sled, and in the very first era a baby triceratops
// hatches in his hands and comes along: Pebble.

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS = {
  rory:      { name: "Rory", voice: V("m", "en-GB", 1.15, 1.05), look: { skin: 0xf3cfae, hair: 0x6b4423, eyes: 0x3b5f8a, coat: 0x16324f, trousers: 0x1a1f2a, shirt: 0xf4f6fa, tie: 0x0e1a2c, kid: true, earpiece: true, hairStyle: "rory" } },
  pebble:    { name: "Pebble", side: "bolt", dino: true, voice: V("f", "en-GB", 1.7, 1.1), bg: "#2a5a2a" },
  flint:     { name: "Dr Flint", voice: V("f", "en-GB", 1.0, 1.0), look: { skin: 0xe8c4a0, hair: 0x8a8a90, coat: 0xf0ece0, trousers: 0x3a4a3a, shirt: 0x2a6a4a, hairStyle: "bun", glasses: 0x2a2a2a, belt: 0x6a4a2a } },
  frost:     { name: "Admiral Frost", voice: V("m", "en-GB", 0.7, 0.92), look: { skin: 0xe8c8a8, hair: 0xe8e8e8, coat: 0x1a2440, trousers: 0x1a2440, shirt: 0xf0f0f0, tie: 0x2a4a8a, moustache: 0xe8e8e8, hairStyle: "short", hat: "captain", hatColor: 0x1a2440 } },
  pip:       { name: "Pip", voice: V("f", "en-GB", 1.25, 1.05), look: { skin: 0xf0c8a0, hair: 0xd06a2a, coat: 0x2a8a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", glasses: 0x1a1a1a } },
  hourglass: { name: "Doctor Hourglass", side: "villain", voice: V("f", "en-GB", 1.05, 1.12), look: { skin: 0xf0d8c4, hair: 0xe8c070, coat: 0x2a1a3a, trousers: 0x2a1a3a, shirt: 0xe8c070, tie: 0xe8c070, hairStyle: "bun", stern: true, belt: 0xe8c070, glasses: 0xe8c070 } },
  sandbot:   { name: "Sandbot", side: "villain", robot: "sandbot", voice: V("m", "en-GB", 1.5, 1.2), bg: "#3a2a0a" },
  wren:      { name: "Wren", voice: V("f", "en-GB", 1.2, 1.05), look: { skin: 0xf0d0b0, hair: 0x2a1a10, coat: 0x6a4a8a, trousers: 0x2a2a3a, kid: true, hairStyle: "short", glasses: 0xe8c070 } },
  tuva:      { name: "Tuva", voice: V("f", "en-GB", 1.2, 1.0), look: { skin: 0xe0b890, hair: 0x3a2414, coat: 0x8a6a4a, trousers: 0x6a4a2a, kid: true, hairStyle: "long", hat: "beanie", hatColor: 0xb8a080 } },
  nefi:      { name: "Nefi", voice: V("f", "en-GB", 1.2, 1.02), look: { skin: 0xb07a4e, hair: 0x14100c, coat: 0xf4f0e0, trousers: 0xf4f0e0, kid: true, hairStyle: "bob", belt: 0x2a8ad8 } },
  theo:      { name: "Theo", voice: V("m", "en-GB", 1.2, 1.05), look: { skin: 0xd8a878, hair: 0x2a1a10, coat: 0xf4f0e8, trousers: 0xf4f0e8, kid: true, hairStyle: "curly", belt: 0x3a6ad8 } },
  livia:     { name: "Livia", voice: V("f", "en-GB", 1.2, 1.0), look: { skin: 0xe0b890, hair: 0x2a1810, coat: 0xc03a2a, trousers: 0xe8dcc0, kid: true, hairStyle: "ponytail" } },
  sigrid:    { name: "Sigrid", voice: V("f", "en-GB", 1.15, 1.0), look: { skin: 0xf4dcc8, hair: 0xe8c880, coat: 0x2a5a8a, trousers: 0x5a4a3a, kid: true, hairStyle: "pigtails", belt: 0x8a5a2a } },
};

// Mission kinds (kinds.js). From Deep Red: cells (time sparks here), roundup, stack, tractor,
// escort, stealth, chase, codes, circuit, tide, valves, dive, boatchase, starmap, boss. New in
// Timeslip: dig, timeline, echo and ride. lv is the difficulty.
export const CHAPTERS = [
  { n: 1, title: "Deep Time", blurb: "Somebody is stealing history. Follow them back to the dinosaurs." },
  { n: 2, title: "Clockwork", blurb: "From castles to the future: Hourglass is nearly ready." },
];

// Each era: when is shown where a place would show its country. Pebble grows in each one.
// Before the first era: POLARIS HQ, today, in the Time Room. Not a stop on the tour (no missions,
// no golden ammonites): Frost's briefing, the Chrono-watch from Dr Flint's bench, and the launch.
// A line's third word is the camera shot for it (the level's shots), and a cue if the level has
// one of that name (the roof opening, the ring powering up).
export const PROLOGUE = { id: "hq", ch: 0, hq: true, name: "POLARIS HQ", when: "Today", year: 2026, contact: null, missions: [],
  brief: [
    ["frost", "Agent Rory. Thank you for coming so quickly. History is leaking.", "frost"],
    ["rory", "Leaking?", "room"],
    ["frost", "Great moments are going missing. A cave painting. The top stone of the Great Pyramid. The Olympic flame. One after another.", "screens"],
    ["pip", "And every time one goes, the present goes a bit wobbly. Look at my tea! It turned back into tea leaves. In the cup!", "tea"],
    ["pip", "And the clock's been going backwards all day.", "clock"],
    ["frost", "The one taking them is Doctor Hourglass. She's bottling history's great moments to power a machine that skips the whole world straight into the future.", "hourglass"],
    ["rory", "Why would anyone want to skip everything?", "room"],
    ["frost", "She can't bear to wait for anything. Not even the kettle.", "frost"],
    ["flint", "Which is where I come in. I'm Dr Flint, and this is my time-sled.", "sled"],
    ["flint", "The leak starts a very long way back: sixty-six million years. Collect your Chrono-watch from my bench, and we'll follow it.", "bench"],
  ],
  watch: [
    ["flint", "That's the Chrono-watch. At the moment it only tells the time.", "bench"],
    ["rory", "Only?", "bench"],
    ["flint", "It learns. Every few eras it'll pick up a new trick. You'll see.", "flint"],
    ["flint", "Now, the time-sled. The front seat's yours.", "sled"],
  ],
  launch: [
    ["flint", "Strapped in? Good. Pip, open the roof!", "riders"],
    ["pip", "Opening the roof!", "roof"],
    ["frost", "Bring history back, Agent Rory. All of it.", "frost"],
    ["rory", "See you soon. Or a very long time ago.", "riders"],
    ["pip", "Time-sled launching in three... two... one!", "launch"],
  ],
  // what they say if Rory goes and talks to them (Dr Flint: before the watch, and after)
  chat: {
    frost: [["frost", "The whole of history is counting on you, Agent Rory. No pressure."]],
    pip: [["pip", "I'll be watching you on the time map. You'll be the little flashing dot."]],
    flint: [["flint", "The Chrono-watch is on my bench. Over by the blackboard."]],
    flint2: [["flint", "Hop on the front seat. I'll sit behind and hold on tight."]],
  },
};

export const PLACES = [
  // ------------------------------------------------------------ 1. Dinosaur Valley
  { id: "dino", ch: 1, name: "Dinosaur Valley", when: "66 million years ago", year: -66000000, contact: "flint", pebble: 1.0,
    arrive: [["flint", "Sixty-six million years ago. Welcome to the age of the dinosaurs."], ["rory", "It's so warm. And everything is enormous!"], ["frost", "We can hear you, Rory. The leak is strongest right where you've landed."], ["flint", "Those glowing sparks are bits of broken time. Grab them and we can follow the trail."]],
    leave: [["flint", "The Sandbots' cart went back into the time tunnel. The trail leads to the Ice Age."], ["rory", "Pebble, you can't come. It's cold there. And you're a dinosaur."], ["pebble", "Honk!"], ["flint", "She's already on the sled. I don't think she's asking."]],
    missions: [
      { id: "dino1", kind: "puzzle", p: "whose", lv: 1, owner: "sandbot", title: "Strange Footprints",
        intro: [["flint", "Look at the mud. Footprints! All sorts of creatures have walked through here."], ["pip", "Whose tracks are they, Rory? Look at the toes, then tap who made them."]],
        outro: [["rory", "Little round ones with sand in them. Not a dinosaur's. And they go all the way to the nests."], ["flint", "Something's stealing from the dinosaurs. Come on, quietly."]],
        intel: { title: "Sandy footprints", text: "Small round footprints with sand in them lead across the valley to the dinosaur nests." } },
      { id: "dino2", kind: "puzzle", p: "wrongtime", lv: 1, era: "dino", title: "Egg Thieves",
        intro: [["pip", "Robots! Shaped like egg timers. They're stealing dinosaur eggs!"], ["flint", "And dropping things from our time all over the valley. Tap whatever doesn't belong here, Rory, and we'll find the robot."]],
        outro: [["rory", "Got one! Upside down you go."], ["sandbot", "Upside down! Now I have to wait for my sand. I hate waiting!"], ["rory", "Who sent you?"], ["sandbot", "Doctor Hourglass. She'll be very cross. She's cross about most things."]],
        intel: { title: "Doctor Hourglass", text: "The egg-timer robots are Sandbots. They work for Doctor Hourglass, who hates waiting." } },
      { id: "dino3", kind: "puzzle", p: "fossil", lv: 1, title: "Back to the Nest",
        intro: [["flint", "The Sandbots dug up the nests, looking for eggs. And they've jumbled up an old fossil underneath."], ["flint", "Even in the age of the dinosaurs, there are fossils. Of much older dinosaurs!"], ["pip", "Tap the stones to turn them until the skeleton is whole, Rory. Then the eggs can go back on top."]],
        outro: [["rory", "The fossil's fixed, and the eggs are back in the nest, all safe and warm. Wait. That one's wobbling."], ["flint", "Rory. It's hatching. Right now. In your hands."], ["pebble", "Honk?"], ["rory", "Hello. I'm Rory. I'm not your mum."], ["pip", "She's decided. You're hers now. What shall we call her?"], ["rory", "Pebble. She looks like a pebble with legs."]],
        intel: { title: "Pebble", text: "A baby triceratops hatched in Rory's hands. She's called Pebble, and she thinks Rory is her mum." } },
      { id: "dino5", kind: "puzzle", p: "crossing", lv: 1, river: "valley", title: "Tiptoe Past the T. rex",
        intro: [["flint", "The Sandbots' cart went over the river, right past a sleeping T. rex."], ["pip", "The raft holds Rory and one more. Get everyone across, quietly, before it wakes!"], ["pebble", "Mrrp."]],
        outro: [["rory", "Past it, with time to spare. Pebble didn't make a sound."], ["flint", "Clever girl. And there's the cart, full of eggs."]],
        intel: { title: "The egg cart", text: "The Sandbots are getting away down the valley with a cart full of eggs." } },
      { id: "dino6", kind: "chase", lv: 1, title: "The Egg Cart", time: 150,
        intro: [["flint", "They're getting away with the eggs! Take the time-sled. It hovers."], ["pip", "Drag to steer. Catch the cart and TAG it!"]],
        outro: [["rory", "Tagged! The eggs are safe. But the Sandbots jumped into a glowing hole in the air."], ["flint", "A time tunnel. We follow it."]],
        intel: { title: "A time tunnel", text: "The Sandbots escaped through a time tunnel. It leads to the Ice Age." } },
    ] },
  // ------------------------------------------------------------ 2. the Ice Age
  { id: "iceage", ch: 1, name: "The Ice Age", when: "20,000 years ago", year: -20000, contact: "tuva", pebble: 1.15, disguise: { coat: 0x8a6a4a, trousers: 0x5a4030, shirt: 0xd8c8a8, tie: 0x6a4a2a },
    arrive: [["rory", "It's freezing! Pebble, stay close."], ["pebble", "Honk. Brrr."], ["tuva", "Who are you? And what is that?"], ["rory", "I'm Rory. This is Pebble. She's a dinosaur."], ["tuva", "I'm Tuva. My family paints the cave. And this morning our best painting was gone. Just gone, off the wall."], ["pip", "A great moment: the first painting of the great horse. Hourglass has taken it."]],
    leave: [["tuva", "The horse is back on the wall! Thank you, Rory. And thank you, Pebble."], ["pebble", "Honk!"], ["flint", "The Sandbots left something behind: a chip of gold stone. From Egypt."], ["frost", "Next stop, the pyramids. Four and a half thousand years ago."]],
    missions: [
      { id: "ice2", kind: "puzzle", p: "eras", lv: 1, title: "Falling Icicles",
        intro: [["flint", "Your watch has a new power, Rory. Hold SLOW and the world slows right down. Everything but you."], ["tuva", "The Sandbots dropped their stolen things under the icicles at the cave mouth. Strange things!"], ["pip", "They're from all through history. Put each one back in its own time, Rory."]],
        outro: [["rory", "And if one falls, I'll use SLOW."], ["flint", "Don't use it too long. It needs time to charge. Which is funny, if you think about it."]],
        intel: { title: "SLOW", text: "Rory's watch can slow the world down. It needs time to charge after." } },
      { id: "ice3", kind: "puzzle", p: "dots", lv: 1, title: "The Painted Cave",
        intro: [["tuva", "Our painters mark out every picture in dots first. Here's one they never finished."], ["pip", "Join the dots in ABC order, Rory, and see what it is. Then we'll go deeper in."]],
        outro: [["rory", "Paintings everywhere! Horses, deer, handprints. But there's a gap where the big one was."], ["tuva", "The great horse. My great-great-great-grandmother painted it. The Sandbots took it."]],
        intel: { title: "The missing horse", text: "The Sandbots stole the great horse painting from the cave wall." } },
      { id: "ice4", kind: "puzzle", p: "shapes", lv: 1, look: "snow", title: "Snow Wall",
        intro: [["tuva", "The storm is coming back, and there's a hole in our snow wall."], ["pip", "Tap a snow block, Rory, then tap the gap where it fits. Fill it up before the wind gets in!"]],
        outro: [["tuva", "The wind's stopped! Everyone can stay warm."], ["rory", "And look. Sandbots, out on the glacier, with something rolled up like a rug."]],
        intel: { title: "Over the glacier", text: "The Sandbots are escaping over the glacier with the painting. Only a mammoth is fast enough." } },
      { id: "ice5", kind: "ride", lv: 1, title: "Mammoth Ride", time: 120,
        intro: [["tuva", "The Sandbots are escaping over the glacier! The mammoths are faster than anything. Climb up!"], ["pip", "Drag to steer. JUMP over the cracks and grab the sparks!"]],
        outro: [["rory", "Best ride ever. Sorry, time-sled."], ["tuva", "The Sandbots dropped the painting! It's rolled up, like a rug."]],
        intel: { title: "The painting", text: "The Sandbots dropped the painting. It only stays on the wall if the handprints are touched in order." } },
      { id: "ice6", kind: "codes", lv: 1, title: "Handprints", time: 120,
        intro: [["tuva", "The painting goes back on the wall, but it only stays if you touch the handprints round it in the right order."], ["pip", "Watch the handprints glow one by one, then tap them in the same order."]],
        outro: [["tuva", "It's back! Exactly where it was. The great horse."], ["flint", "And the present stops wobbling. Pip, how's your tea?"], ["pip", "It's tea again! Hot and everything."]],
        intel: { title: "Gold stone", text: "The Sandbots left a chip of gold stone from Ancient Egypt." } },
    ] },
  // ------------------------------------------------------------ 3. ancient Egypt
  { id: "egypt", ch: 1, name: "Ancient Egypt", when: "4,500 years ago", year: -2500, contact: "nefi", pebble: 1.3, disguise: { coat: 0xf0e8d4, trousers: 0xe8dcc0, shirt: 0xf8f4e8, tie: 0x2a8ad8 },
    arrive: [["nefi", "Stop! Who goes there? And why is your lizard so big?"], ["rory", "She's a dinosaur. I'm Rory. We're looking for some very small robots."], ["nefi", "I'm Nefi. I'm learning to be a scribe. The robots came at dawn. They took the golden capstone!"], ["pip", "The gold stone that goes on the very top of the Great Pyramid. Today's the day they put it there."], ["nefi", "Was the day."]],
    leave: [["nefi", "The capstone is on top! It shines like the sun."], ["pebble", "Honk!"], ["flint", "The Sandbots' tunnel goes to Greece. To Olympia, and the very first games."], ["rory", "Pebble's getting bigger. She was up to my knee. Now she's up to my middle."]],
    missions: [
      { id: "egy1", kind: "boatchase", lv: 1, title: "Down the Nile", time: 150,
        intro: [["nefi", "The Sandbots stole a boat and went down the river! Take my uncle's reed boat."], ["pip", "Drag to steer. Mind the hippos. Catch them and TAG them!"]],
        outro: [["rory", "Tagged! They jumped ashore by the pyramid."], ["nefi", "My uncle will want his boat back. It's his favourite."]],
        intel: { title: "By the pyramid", text: "The Sandbots jumped ashore by the pyramid. Its door has a picture lock." } },
      { id: "egy2", kind: "codes", lv: 2, title: "Hieroglyphs", time: 120,
        intro: [["nefi", "The door to the pyramid is sealed with a picture lock. The signs light up one at a time."], ["pip", "Watch the signs, then tap them in the same order. Nefi will read them out."]],
        outro: [["nefi", "It says: the stone is safe inside. Liars. It's not safe at all."]],
        intel: { title: "The stone inside", text: "The picture lock says 'the stone is safe inside'. The Sandbots are after something in the pyramid." } },
      { id: "egy3", kind: "puzzle", p: "suspect", lv: 2, title: "Who Let Them In?",
        intro: [["flint", "Another power, Rory. Press BACK and you jump back to where you were three seconds ago."], ["nefi", "Somebody let the Sandbots into the tunnel and set sunbeam traps. One of the workers!"], ["pip", "Read the clues, Rory. Which worker was it?"]],
        outro: [["rory", "Got you. You've got sand on your sandals."], ["nefi", "They paid him in sand! What a terrible thing to be paid in."]],
        intel: { title: "BACK", text: "Rory's watch can jump back three seconds. The Sandbots buried something in the sand outside." } },
      { id: "egy4", kind: "dig", lv: 1, title: "The Buried Stone", time: 150,
        intro: [["nefi", "The Sandbots buried something in the sand here. Pebble can smell it!"], ["pebble", "Sniff sniff. Honk!"], ["pip", "Brush the sand away, and tap harder on rock. Don't crack what's underneath!"]],
        outro: [["rory", "It's the golden capstone! They hid it in the sand."], ["nefi", "Now it has to go up. All the way up."]],
        intel: { title: "The capstone", text: "The Sandbots buried the golden capstone. It has to go on top of the pyramid." } },
      { id: "egy6", kind: "puzzle", p: "shapes", lv: 2, look: "sand", title: "Mend the Ramp",
        intro: [["nefi", "The Sandbots pulled stones out of the ramp up the pyramid. The workers can't haul the capstone over a hole!"], ["pip", "Fit the blocks into the gap, Rory. Tap a block, then tap where it goes."]],
        outro: [["nefi", "Here it comes, on the workers' ropes. The capstone!"], ["rory", "And the Sandbots at the top are running off into a tunnel."], ["frost", "Well done, Agent. Another moment saved."]],
        intel: { title: "Off to Greece", text: "The Sandbots ran into a tunnel that goes to Olympia, in Ancient Greece." } },
    ] },
  // ------------------------------------------------------------ 4. ancient Greece
  { id: "greece", ch: 1, name: "Olympia, Ancient Greece", when: "2,700 years ago", year: -700, contact: "theo", pebble: 1.45, disguise: { coat: 0xf4f0e8, trousers: 0xf0ece0, shirt: 0xf4f0e8, tie: 0x3a6ad8 },
    arrive: [["theo", "Are you here for the games? You're too late. The flame's gone out. It's never gone out."], ["rory", "I'm Rory. This is Pebble. We're after the robots that did it."], ["theo", "I'm Theo. I'm running in the boys' race. If there's a race. Without the flame, there are no games."], ["flint", "Hourglass has bottled the lighting of the flame. Get the moment back, and the games begin."]],
    leave: [["theo", "The flame is burning! And I came second. Second! Next time, first."], ["pebble", "Honk!"], ["flint", "The trail goes west, to Rome. To a brand-new aqueduct."], ["pip", "An aqueduct is a bridge for water. The Romans built them everywhere."]],
    missions: [
      { id: "gre2", kind: "echo", lv: 1, title: "Temple Doors", time: 150,
        intro: [["flint", "The temple doors only stay open while someone stands on the plate. And you can't be in two places at once."], ["flint", "Or can you? Your watch has one more power. Echo."], ["pip", "Stand on the plate, then press ECHO. A copy of you replays what you did, while you walk through the door!"]],
        outro: [["rory", "I held the door open for myself! That's the weirdest thing I've ever done."], ["pebble", "Honk?"], ["rory", "Yes, Pebble. There were two of me."]],
        intel: { title: "ECHO", text: "Rory's watch can make an echo of him, which copies what he did." } },
      { id: "gre3", kind: "timeline", lv: 1, title: "The Games in Order", time: 120,
        intro: [["theo", "The Sandbots mixed up the order of the games. The judges are all confused."], ["pip", "Put the pictures in order: the flame, the march, the races, and last the crowns of olive leaves."]],
        outro: [["theo", "That's right! The judges can start. All we need is the flame."]],
        intel: { title: "The flame", text: "The games are ready to start. All they need is the flame." } },
      { id: "gre4", kind: "chase", lv: 3, title: "Chariot Race", time: 150,
        intro: [["theo", "The Sandbots have the flame in a jar, on a chariot! Take ours!"], ["pip", "Drag to steer round the track. Catch them and TAG them!"]],
        outro: [["rory", "Got it! The flame's in a glass jar with an hourglass on the lid."], ["flint", "Doctor Hourglass signs everything. She's very proud of her work."]],
        intel: { title: "Hourglass signs everything", text: "The flame was in a jar with an hourglass on the lid. Doctor Hourglass signs her work." } },
      { id: "gre5", kind: "circuit", lv: 2, title: "Mirror Flame", time: 150,
        intro: [["theo", "The flame is lit with the sun, and a curved mirror. But the mirror's been turned the wrong way."], ["pip", "Join up the mirrors so the sunbeam reaches the altar."]],
        outro: [["theo", "It's alight! The flame of the games!"], ["pebble", "Honk honk honk!"]],
        intel: { title: "Crowns", text: "The flame is lit. But the Sandbots are trying to steal the olive crowns." } },
      { id: "gre6", kind: "puzzle", p: "cipher", lv: 2, word: "ROME", title: "Sandbots in the Stadium",
        intro: [["theo", "We caught the last Sandbot! It had a note in its sand. In code."], ["pip", "Use the key, Rory. Each symbol is one letter. Where's Hourglass?"]],
        outro: [["sandbot", "Upside down again. This is the worst day of my life. And I've had a lot of days. In a lot of years."], ["rory", "ROME. She's gone to Rome."], ["sandbot", "She likes Rome. Very punctual, the Romans."]],
        intel: { title: "Rome", text: "Doctor Hourglass has gone to Rome, to a brand-new aqueduct." } },
    ] },
  // ------------------------------------------------------------ 5. the Roman aqueduct
  { id: "aqueduct", ch: 1, name: "The Roman Aqueduct", when: "2,000 years ago", year: 20, contact: "livia", pebble: 1.6, disguise: { coat: 0xc03a2a, trousers: 0xe8dcc0, shirt: 0xf0e8d8, tie: 0xe8c070 },
    arrive: [["livia", "Oi! Dinosaurs aren't allowed on the aqueduct. Or anywhere. I've never seen one before."], ["rory", "She's with me. I'm Rory."], ["livia", "I'm Livia. My dad built this aqueduct. Today the water was meant to reach the town for the first time. And it's dry!"], ["flint", "Hourglass has bottled the moment the water arrives. The whole town's waiting in the square with cups."]],
    leave: [["livia", "The water's here! Listen to the fountains. Dad's crying. Happy crying."], ["pebble", "Honk!"], ["flint", "One more tunnel. It goes north, a thousand years on. To the Vikings."], ["frost", "And Hourglass herself has gone through it. This time we might catch her."]],
    missions: [
      { id: "aq1", kind: "puzzle", p: "mosaic", lv: 3, title: "Along the Arches",
        intro: [["livia", "Every arch has a mosaic sign. The Sandbots smashed one, so nobody could find where they stopped the water."], ["pip", "Copy the little pattern, Rory. Tap a colour, then tap the squares that need it."]],
        outro: [["rory", "The sign's mended. And look, under that arch! There's sand jammed in the channel."], ["livia", "And the sluice gates are shut. The water's stuck in the hills."]],
        intel: { title: "Shut gates", text: "The Sandbots shut the aqueduct's sluice gates, up in the hills." } },
      { id: "aq2", kind: "tide", lv: 1, title: "Sluice Gates", time: 150,
        intro: [["livia", "The Sandbots shut the sluice gates. The water's stuck behind them, up in the hills."], ["pip", "Open and shut the gates so the water flows all the way to the town."]],
        outro: [["livia", "It's flowing! I can hear it in the channel."]],
        intel: { title: "The fountains", text: "The water flows again, but the town's fountains are all wrong." } },
      { id: "aq3", kind: "valves", lv: 1, title: "The Fountains", time: 150,
        intro: [["livia", "Now the town's fountains. Too much water and they burst. Too little and they dribble."], ["pip", "Turn the valves until every fountain is in the green."]],
        outro: [["livia", "Every fountain, just right! Dad will be so proud."]],
        intel: { title: "The last gate", text: "The last gate needs two levers pulled at once, far apart." } },
      { id: "aq5", kind: "echo", lv: 2, title: "Two Levers", time: 150,
        intro: [["livia", "The last gate needs two levers pulled at once, and they're far apart."], ["pip", "Pull one, then ECHO. Your echo pulls it again while you get to the other one!"]],
        outro: [["livia", "Both at once! You and... you. How does that work?"], ["rory", "No idea. It just does."]],
        intel: { title: "The last bottle", text: "Doctor Hourglass is escaping down the Roman road with the last bottle of water." } },
      { id: "aq6", kind: "chase", lv: 4, title: "The Roman Road", time: 150,
        intro: [["livia", "Doctor Hourglass! She's escaping down the road in a cart with the last bottle!"], ["pip", "Take the cart. Drag to steer, and TAG her!"]],
        outro: [["hourglass", "Tagged? Me? Oh, you are annoying. Do you know how long it took me to get here?"], ["rory", "Two thousand years?"], ["hourglass", "Exactly! And I hate waiting. Goodbye, Agent Rory."], ["flint", "She's dropped the bottle! The water's free. But she's gone to the Vikings."]],
        intel: { title: "To the Vikings", text: "Hourglass dropped the bottle and fled through a tunnel to the Vikings." } },
    ] },
  // ------------------------------------------------------------ 6. Viking seas
  { id: "fjord", ch: 1, name: "The Viking Fjord", when: "1,000 years ago", year: 1000, contact: "sigrid", pebble: 1.8, disguise: { coat: 0x3a5a8a, trousers: 0x5a4a3a, shirt: 0xd8ccb0, tie: 0x8a5a2a },
    arrive: [["sigrid", "A dragon! No. A very small dragon. With horns."], ["rory", "She's a dinosaur. Pebble. I'm Rory."], ["sigrid", "I'm Sigrid. I build ships. Our biggest longship sails for Iceland today, but her sail is gone. A woman in a coat of glass buttons took it!"], ["pip", "That's her. Hourglass. And she's still here."]],
    leave: [["sigrid", "The sail is up! She's away, all the way to Iceland!"], ["pebble", "Honk honk!"], ["rory", "Pebble's almost as tall as me. When did that happen?"], ["flint", "Every era, a little bit bigger. Like everybody."]],
    missions: [
      { id: "vik2", kind: "codes", lv: 3, title: "Rune Stones", time: 150,
        intro: [["sigrid", "Hourglass left a message on the rune stones. The runes glow, one after another."], ["pip", "Watch the runes, then tap them in the same order to read her message."]],
        outro: [["rory", "It says: Why wait? Love, H."], ["sigrid", "She signed it. With a love. Strange woman."]],
        intel: { title: "Why wait?", text: "Hourglass's rune message says 'Why wait? Love, H.'" } },
      { id: "vik3", kind: "starmap", lv: 1, title: "Steer by the Stars", time: 150,
        intro: [["sigrid", "Hourglass's ship left at night. We can follow her by the stars, like my grandad does."], ["pip", "Join the stars to draw the pictures that point the way."]],
        outro: [["sigrid", "She went to the island at the mouth of the fjord! Her ship's there."]],
        intel: { title: "The island", text: "Hourglass's ship is at the island at the mouth of the fjord." } },
      { id: "vik4", kind: "puzzle", p: "map", lv: 3, title: "The Sail Loft",
        intro: [["sigrid", "The Sandbots stole our sail. Her Sandbots are guarding the boathouse. It must be in there."], ["pip", "I've mapped the way past their lanterns. Follow the spy map, Rory, and tap where you end up."]],
        outro: [["rory", "The sail isn't here. But there's a note: 'Look under the water, slowcoach.'"], ["sigrid", "That's so rude. They threw it in the fjord!"]],
        intel: { title: "Under the water", text: "The Sandbots threw the sail into the fjord, in pieces." } },
      { id: "vik5", kind: "puzzle", p: "runes", lv: 3, title: "Under the Fjord",
        intro: [["sigrid", "The sail sank in pieces, down on the fjord bed. Grandad's rune path on the shore shows the divers where."], ["pip", "Start on the glowing stone and step on every stone just once, Rory. Then the runes light the way."]],
        outro: [["rory", "Every piece. We can sew it back together."], ["sigrid", "My mum can sew a sail in an hour. She's the fastest in the fjord."]],
        intel: { title: "The Sand Serpent", text: "Doctor Hourglass is waiting with her biggest machine yet: a Sand Serpent." } },
      { id: "vik6", kind: "boss", lv: 1, title: "The Sand Serpent", time: 180,
        intro: [["hourglass", "Why wait for a sail? I'll take the whole fjord. Meet my Sand Serpent!"], ["pip", "It's a giant snake made of sand! Bubble the glowing hourglasses on its back!"], ["pebble", "HONK!"]],
        outro: [["hourglass", "My Serpent! It's a beach now. A beach!"], ["rory", "Give up, Hourglass."], ["hourglass", "Give up? I'm only getting started. The future's where I'm going, Agent Rory. And it's nearly ready."], ["flint", "She's gone forward in time. And look. She dropped a drawing. It's signed: Wren."]],
        intel: { title: "Wren", text: "Hourglass has gone into the future. She dropped a drawing signed by someone called Wren." } },
    ] },
];

export const CREDITS = [
  ["Agent Rory: Timeslip", "A game for Rory"],
  ["Story, code and eras", "Written with Claude"],
  ["3D", "three.js, with bloom, SMAA and AgX tone mapping"],
  ["Physics", "Rapier: Rory, Pebble, the time-sled and every tumbling crate"],
  ["Music and sound", "Tone.js synthesizers, played live"],
  ["The Sandbots", "RobotExpressive by Tomás Laulhé (Quaternius), CC0"],
  ["Voices", "Kokoro-82M, an open neural voice model"],
  ["Starring", "Agent Rory, Pebble, Pip, Dr Flint, Admiral Frost, and Doctor Hourglass"],
];

export const ALL = PLACES.flatMap(p => p.missions.map(m => ({ ...m, place: p.id })));
export function placeOf(mid) { return PLACES.find(p => p.missions.some(m => m.id === mid)); }
