// Agent Rory: Timeslip — the cast, the acts, the eras and every mission's lines. Doctor
// Hourglass is bottling history's great moments to run her Fast-Forward Engine; Rory follows her
// back through time on the POLARIS time-sled, and in the very first era a baby triceratops
// hatches in his hands and comes along: Pebble.

const V = (g, lang, pitch = 1, rate = 1) => ({ g, langs: [lang, "en-GB"], pitch, rate });
export const CHARS = {
  rory:      { name: "Rory", voice: V("m", "en-GB", 1.15, 1.05), look: { skin: 0xf3cfae, hair: 0x6b4423, eyes: 0x3b5f8a, coat: 0x16324f, trousers: 0x1a1f2a, shirt: 0xf4f6fa, tie: 0x0e1a2c, kid: true, earpiece: true, hairStyle: "rory" } },
  pebble:    { name: "Pebble", side: "bolt", dino: true, voice: V("f", "en-GB", 1.7, 1.1), bg: "#2a5a2a" },
  flint:     { name: "Dr Flint", voice: V("f", "en-GB", 1.0, 1.0), look: { skin: 0xe8c4a0, hair: 0x8a8a90, coat: 0xf0ece0, trousers: 0x3a4a3a, shirt: 0x2a6a4a, hairStyle: "bun", glasses: 0x2a2a2a, belt: 0x6a4a2a } },
  frost:     { name: "Admiral Frost", voice: V("m", "en-GB", 0.7, 0.92), look: { skin: 0xe8c8a8, hair: 0xe8e8e8, coat: 0x1a2440, trousers: 0x1a2440, shirt: 0xf0f0f0, tie: 0x2a4a8a, moustache: 0xe8e8e8, hairStyle: "short", hat: "captain", hatColor: 0x1a2440 } },
  pip:       { name: "Pip", voice: V("f", "en-GB", 1.25, 1.05), look: { skin: 0xf0c8a0, hair: 0xd06a2a, coat: 0x2a8a6a, trousers: 0x2a2a3a, kid: true, hairStyle: "pigtails", glasses: 0x1a1a1a } },
  hourglass: { name: "Doctor Hourglass", side: "villain", voice: V("f", "en-GB", 1.05, 1.12), look: { skin: 0xf0d8c4, hair: 0xe8c070, coat: 0x2a1a3a, trousers: 0x2a1a3a, shirt: 0xe8c070, tie: 0xe8c070, hairStyle: "bun", stern: true, belt: 0xe8c070, glasses: 0xe8c070 } },
  sandbot:   { name: "Sandbot", side: "villain", robot: "sandbot", voice: V("m", "en-GB", 1.5, 1.2), bg: "#3a2a0a" },
  wren:      { name: "Wren", voice: V("f", "en-GB", 1.2, 1.05), look: { skin: 0xf0d0b0, hair: 0x2a1a10, coat: 0x6a4a8a, trousers: 0x2a2a3a, kid: true, hairStyle: "short", glasses: 0xe8c070 } },
  tuva:      { name: "Tuva", voice: V("f", "en-GB", 1.2, 1.0), look: { skin: 0xe0b890, hair: 0x3a2414, coat: 0x8a6a4a, trousers: 0x6a4a2a, kid: true, hairStyle: "long", hat: "beanie", hatColor: 0xb8a080 } },
  nefi:      { name: "Nefi", voice: V("f", "en-GB", 1.2, 1.02), look: { skin: 0xb07a4e, hair: 0x14100c, coat: 0xf4f0e0, trousers: 0xf4f0e0, kid: true, hairStyle: "bob", belt: 0x2a8ad8 } },
  theo:      { name: "Theo", voice: V("m", "en-GB", 1.2, 1.05), look: { skin: 0xd8a878, hair: 0x2a1a10, coat: 0xf4f0e8, trousers: 0xf4f0e8, kid: true, hairStyle: "curly", belt: 0x3a6ad8 } },
  livia:     { name: "Livia", voice: V("f", "en-GB", 1.2, 1.0), look: { skin: 0xe0b890, hair: 0x2a1810, coat: 0xc03a2a, trousers: 0xe8dcc0, kid: true, hairStyle: "ponytail" } },
  sigrid:    { name: "Sigrid", voice: V("f", "en-GB", 1.15, 1.0), look: { skin: 0xf4dcc8, hair: 0xe8c880, coat: 0x2a5a8a, trousers: 0x5a4a3a, kid: true, hairStyle: "pigtails", belt: 0x8a5a2a } },
};

// Mission kinds (kinds.js). From Deep Red: cells (time sparks here), roundup, stack, tractor,
// escort, stealth, chase, codes, circuit, tide, valves, dive, boatchase, starmap, boss. New in
// Timeslip: dig, timeline, echo and ride. lv is the difficulty.
export const CHAPTERS = [
  { n: 1, title: "Deep Time", blurb: "Somebody is stealing history. Follow them back to the dinosaurs." },
  { n: 2, title: "Clockwork", blurb: "From castles to the future: Hourglass is nearly ready." },
];

// Each era: when is shown where a place would show its country. Pebble grows in each one.
export const PLACES = [
  // ------------------------------------------------------------ 1. Dinosaur Valley
  { id: "dino", ch: 1, name: "Dinosaur Valley", when: "66 million years ago", year: -66000000, contact: "flint", pebble: 1.0,
    arrive: [["frost", "Agent Rory. History is leaking."], ["rory", "Leaking?"], ["frost", "Great moments are vanishing. Somebody is taking them. And every time one goes, the present goes a bit wobbly."], ["pip", "This morning my tea turned back into tea leaves. In the cup!"], ["flint", "I'm Dr Flint. I built the time-sled you just rode in. The leak starts here: sixty-six million years ago."], ["flint", "Those glowing sparks are bits of broken time. Grab them and we can follow the trail."]],
    leave: [["flint", "The Sandbots' cart went back into the time tunnel. The trail leads to the Ice Age."], ["rory", "Pebble, you can't come. It's cold there. And you're a dinosaur."], ["pebble", "Honk!"], ["flint", "She's already on the sled. I don't think she's asking."]],
    missions: [
      { id: "dino1", kind: "cells", lv: 1, title: "Time Sparks", n: 6, time: 100,
        intro: [["flint", "Six sparks, all over the valley. Run into them, and jump for the high ones."], ["pip", "Mind the ferns. Some of them are taller than you."]],
        outro: [["rory", "Six sparks. They fizz!"], ["flint", "And look: footprints. Little round ones, with sand in them."]] },
      { id: "dino2", kind: "roundup", lv: 1, title: "Egg Thieves", n: 4, time: 110,
        intro: [["pip", "Robots! Shaped like egg timers. They're stealing dinosaur eggs!"], ["flint", "Press USE near one and your watch pops it in a bubble. It'll flip upside down."]],
        outro: [["sandbot", "Upside down! Now I have to wait for my sand. I hate waiting!"], ["rory", "Who sent you?"], ["sandbot", "Doctor Hourglass. She'll be very cross. She's cross about most things."]] },
      { id: "dino3", kind: "stack", lv: 1, title: "Back to the Nest", n: 3, time: 120,
        intro: [["flint", "The eggs they dropped need to go back in the nest before their mum comes back."], ["pip", "GRAB an egg with the tractor beam, carry it to the nest and DROP it. Gently!"]],
        outro: [["rory", "Three eggs, safe and warm. Wait. That one's wobbling."], ["flint", "Rory. It's hatching. Right now. In your hands."]] },
      { id: "dino4", kind: "escort", lv: 1, title: "Hatchling", time: 150,
        intro: [["pebble", "Honk?"], ["rory", "Hello. I'm Rory. I'm not your mum."], ["pebble", "Honk!"], ["flint", "She thinks you are. A baby triceratops! And her brothers and sisters have wandered off."], ["pip", "Walk near the babies and they'll follow you. Lead them all back to the nest!"]],
        outro: [["flint", "All home. Their mother is on her way back."], ["pebble", "Honk honk!"], ["rory", "She's still following me."], ["pip", "She's decided. You're hers now. What shall we call her?"], ["rory", "Pebble. She looks like a pebble with legs."]] },
      { id: "dino5", kind: "stealth", lv: 1, title: "Tiptoe Past the T. rex", time: 150,
        intro: [["flint", "The Sandbots' cart went down the valley, past a sleeping T. rex."], ["pip", "It sleeps with one eye open. Stay out of where it's looking, and don't wake it!"], ["pebble", "Mrrp."]],
        outro: [["rory", "Past it. Pebble didn't make a sound."], ["flint", "Clever girl. And there's the cart, full of eggs."]] },
      { id: "dino6", kind: "chase", lv: 1, title: "The Egg Cart", time: 150,
        intro: [["flint", "They're getting away with the eggs! Take the time-sled. It hovers."], ["pip", "Drag to steer. Catch the cart and TAG it!"]],
        outro: [["rory", "Tagged! The eggs are safe. But the Sandbots jumped into a glowing hole in the air."], ["flint", "A time tunnel. We follow it."]] },
    ] },
  // ------------------------------------------------------------ 2. the Ice Age
  { id: "iceage", ch: 1, name: "The Ice Age", when: "20,000 years ago", year: -20000, contact: "tuva", pebble: 1.15, disguise: { coat: 0x8a6a4a, trousers: 0x5a4030, shirt: 0xd8c8a8, tie: 0x6a4a2a },
    arrive: [["rory", "It's freezing! Pebble, stay close."], ["pebble", "Honk. Brrr."], ["tuva", "Who are you? And what is that?"], ["rory", "I'm Rory. This is Pebble. She's a dinosaur."], ["tuva", "I'm Tuva. My family paints the cave. And this morning our best painting was gone. Just gone, off the wall."], ["pip", "A great moment: the first painting of the great horse. Hourglass has taken it."]],
    leave: [["tuva", "The horse is back on the wall! Thank you, Rory. And thank you, Pebble."], ["pebble", "Honk!"], ["flint", "The Sandbots left something behind: a chip of gold stone. From Egypt."], ["frost", "Next stop, the pyramids. Four and a half thousand years ago."]],
    missions: [
      { id: "ice1", kind: "escort", lv: 2, title: "Lost Calf", n: 1, time: 150,
        intro: [["tuva", "A baby mammoth has lost its herd. The storm split them up."], ["pip", "Walk near the calf and it will follow. Lead it back to its mum!"]],
        outro: [["tuva", "Home! Its mum is so big. Look at the tusks."], ["pebble", "Honk!"], ["rory", "Pebble, you can't ride a mammoth. Not yet."]] },
      { id: "ice2", kind: "tractor", lv: 1, title: "Falling Icicles", time: 110,
        intro: [["flint", "Rory, your watch has a new power. Hold SLOW and the world slows right down. Everything but you."], ["tuva", "The cave mouth is full of icicles. They fall when you walk under them!"], ["pip", "Use SLOW to catch them before they land. Catch them with the tractor beam!"]],
        outro: [["rory", "That was so cool. Everything went slow, like syrup."], ["flint", "Don't use it too long. It needs time to charge. Which is funny, if you think about it."]] },
      { id: "ice3", kind: "cells", lv: 2, title: "The Painted Cave", n: 8, time: 150,
        intro: [["tuva", "The cave is very dark. The sparks are in there, where the painting was."], ["pip", "Your watch has a lamp. Follow the sparks deep into the cave."]],
        outro: [["rory", "Eight sparks. And paintings everywhere! Horses, deer, handprints."], ["tuva", "My great-great-great-grandmother's hand. And mine, next to it."]] },
      { id: "ice4", kind: "stack", lv: 2, title: "Snow Wall", n: 4, time: 150,
        intro: [["tuva", "The storm is coming back. Our camp needs a wall of snow blocks, fast."], ["pip", "GRAB the snow blocks and stack them on the glowing pads."]],
        outro: [["tuva", "The wind's stopped! Everyone can stay warm."], ["pebble", "Mrrp."], ["rory", "She's asleep in the snow. Dinosaurs are allowed to nap."]] },
      { id: "ice5", kind: "ride", lv: 1, title: "Mammoth Ride", time: 120,
        intro: [["tuva", "The Sandbots are escaping over the glacier! The mammoths are faster than anything. Climb up!"], ["pip", "Drag to steer. JUMP over the cracks and grab the sparks!"]],
        outro: [["rory", "Best ride ever. Sorry, time-sled."], ["tuva", "The Sandbots dropped the painting! It's rolled up, like a rug."]] },
      { id: "ice6", kind: "codes", lv: 1, title: "Handprints", time: 120,
        intro: [["tuva", "The painting goes back on the wall, but it only stays if you touch the handprints round it in the right order."], ["pip", "Watch the handprints glow one by one, then tap them in the same order."]],
        outro: [["tuva", "It's back! Exactly where it was. The great horse."], ["flint", "And the present stops wobbling. Pip, how's your tea?"], ["pip", "It's tea again! Hot and everything."]] },
    ] },
  // ------------------------------------------------------------ 3. ancient Egypt
  { id: "egypt", ch: 1, name: "Ancient Egypt", when: "4,500 years ago", year: -2500, contact: "nefi", pebble: 1.3, disguise: { coat: 0xf0e8d4, trousers: 0xe8dcc0, shirt: 0xf8f4e8, tie: 0x2a8ad8 },
    arrive: [["nefi", "Stop! Who goes there? And why is your lizard so big?"], ["rory", "She's a dinosaur. I'm Rory. We're looking for some very small robots."], ["nefi", "I'm Nefi. I'm learning to be a scribe. The robots came at dawn. They took the golden capstone!"], ["pip", "The gold stone that goes on the very top of the Great Pyramid. Today's the day they put it there."], ["nefi", "Was the day."]],
    leave: [["nefi", "The capstone is on top! It shines like the sun."], ["pebble", "Honk!"], ["flint", "The Sandbots' tunnel goes to Greece. To Olympia, and the very first games."], ["rory", "Pebble's getting bigger. She was up to my knee. Now she's up to my middle."]],
    missions: [
      { id: "egy1", kind: "boatchase", lv: 1, title: "Down the Nile", time: 150,
        intro: [["nefi", "The Sandbots stole a boat and went down the river! Take my uncle's reed boat."], ["pip", "Drag to steer. Mind the hippos. Catch them and TAG them!"]],
        outro: [["rory", "Tagged! They jumped ashore by the pyramid."], ["nefi", "My uncle will want his boat back. It's his favourite."]] },
      { id: "egy2", kind: "codes", lv: 2, title: "Hieroglyphs", time: 120,
        intro: [["nefi", "The door to the pyramid is sealed with a picture lock. The signs light up one at a time."], ["pip", "Watch the signs, then tap them in the same order. Nefi will read them out."]],
        outro: [["nefi", "It says: the stone is safe inside. Liars. It's not safe at all."]] },
      { id: "egy3", kind: "lasers", lv: 1, title: "Sunbeam Traps", time: 150,
        intro: [["flint", "Another new power, Rory. Press BACK and you jump back to where you were three seconds ago."], ["pip", "Hourglass has put sunbeam traps in the tunnel. Touch a beam and you're back at the start. Unless you use BACK first!"]],
        outro: [["rory", "I only needed BACK twice. Well, three times."], ["pebble", "Honk."], ["rory", "Pebble walked straight through the beams. They don't work on dinosaurs."]] },
      { id: "egy4", kind: "dig", lv: 1, title: "The Buried Stone", time: 150,
        intro: [["nefi", "The Sandbots buried something in the sand here. Pebble can smell it!"], ["pebble", "Sniff sniff. Honk!"], ["pip", "Brush the sand away, and tap harder on rock. Don't crack what's underneath!"]],
        outro: [["rory", "It's the golden capstone! They hid it in the sand."], ["nefi", "Now it has to go up. All the way up."]] },
      { id: "egy5", kind: "stack", lv: 3, title: "The Ramp", n: 5, time: 180,
        intro: [["nefi", "The workers' ramp was knocked down. We need to build it again, block by block."], ["pip", "Stack the blocks on the pads to make steps. Big ones at the bottom!"]],
        outro: [["nefi", "A ramp! Now we can take the capstone up."], ["rory", "Or I can climb up there first and see what's waiting."]] },
      { id: "egy6", kind: "cells", lv: 3, title: "Up the Pyramid", n: 8, time: 180,
        intro: [["flint", "Hourglass's Sandbots are at the top, trying to bottle the moment the capstone goes on."], ["pip", "Climb the pyramid's steps. Grab the sparks all the way up!"]],
        outro: [["rory", "Top of the world! The Sandbots ran off into a tunnel."], ["nefi", "Here it comes, on the workers' ropes. The capstone!"], ["frost", "Well done, Agent. Another moment saved."]] },
    ] },
  // ------------------------------------------------------------ 4. ancient Greece
  { id: "greece", ch: 1, name: "Olympia, Ancient Greece", when: "2,700 years ago", year: -700, contact: "theo", pebble: 1.45, disguise: { coat: 0xf4f0e8, trousers: 0xf0ece0, shirt: 0xf4f0e8, tie: 0x3a6ad8 },
    arrive: [["theo", "Are you here for the games? You're too late. The flame's gone out. It's never gone out."], ["rory", "I'm Rory. This is Pebble. We're after the robots that did it."], ["theo", "I'm Theo. I'm running in the boys' race. If there's a race. Without the flame, there are no games."], ["flint", "Hourglass has bottled the lighting of the flame. Get the moment back, and the games begin."]],
    leave: [["theo", "The flame is burning! And I came second. Second! Next time, first."], ["pebble", "Honk!"], ["flint", "The trail goes west, to Rome. To a brand-new aqueduct."], ["pip", "An aqueduct is a bridge for water. The Romans built them everywhere."]],
    missions: [
      { id: "gre1", kind: "cells", lv: 3, title: "The Boys' Race", n: 8, time: 90,
        intro: [["theo", "Race me round the stadium! There are sparks all the way round."], ["pip", "Grab every spark before the time runs out. Go go go!"]],
        outro: [["theo", "You're fast! For someone in funny clothes."], ["rory", "It's a spy suit."]] },
      { id: "gre2", kind: "echo", lv: 1, title: "Temple Doors", time: 150,
        intro: [["flint", "The temple doors only stay open while someone stands on the plate. And you can't be in two places at once."], ["flint", "Or can you? Your watch has one more power. Echo."], ["pip", "Stand on the plate, then press ECHO. A copy of you replays what you did, while you walk through the door!"]],
        outro: [["rory", "I held the door open for myself! That's the weirdest thing I've ever done."], ["pebble", "Honk?"], ["rory", "Yes, Pebble. There were two of me."]] },
      { id: "gre3", kind: "timeline", lv: 1, title: "The Games in Order", time: 120,
        intro: [["theo", "The Sandbots mixed up the order of the games. The judges are all confused."], ["pip", "Put the pictures in order: the flame, the march, the races, and last the crowns of olive leaves."]],
        outro: [["theo", "That's right! The judges can start. All we need is the flame."]] },
      { id: "gre4", kind: "chase", lv: 3, title: "Chariot Race", time: 150,
        intro: [["theo", "The Sandbots have the flame in a jar, on a chariot! Take ours!"], ["pip", "Drag to steer round the track. Catch them and TAG them!"]],
        outro: [["rory", "Got it! The flame's in a glass jar with an hourglass on the lid."], ["flint", "Doctor Hourglass signs everything. She's very proud of her work."]] },
      { id: "gre5", kind: "circuit", lv: 2, title: "Mirror Flame", time: 150,
        intro: [["theo", "The flame is lit with the sun, and a curved mirror. But the mirror's been turned the wrong way."], ["pip", "Join up the mirrors so the sunbeam reaches the altar."]],
        outro: [["theo", "It's alight! The flame of the games!"], ["pebble", "Honk honk honk!"]] },
      { id: "gre6", kind: "roundup", lv: 2, title: "Sandbots in the Stadium", n: 6, time: 150,
        intro: [["theo", "The Sandbots are still running round the stadium, trying to steal the crowns!"], ["pip", "Bubble all six. Pebble can charge them too!"]],
        outro: [["sandbot", "Upside down again. This is the worst day of my life. And I've had a lot of days. In a lot of years."], ["rory", "Where's Hourglass?"], ["sandbot", "Rome. She likes Rome. Very punctual, the Romans."]] },
    ] },
  // ------------------------------------------------------------ 5. the Roman aqueduct
  { id: "aqueduct", ch: 1, name: "The Roman Aqueduct", when: "2,000 years ago", year: 20, contact: "livia", pebble: 1.6, disguise: { coat: 0xc03a2a, trousers: 0xe8dcc0, shirt: 0xf0e8d8, tie: 0xe8c070 },
    arrive: [["livia", "Oi! Dinosaurs aren't allowed on the aqueduct. Or anywhere. I've never seen one before."], ["rory", "She's with me. I'm Rory."], ["livia", "I'm Livia. My dad built this aqueduct. Today the water was meant to reach the town for the first time. And it's dry!"], ["flint", "Hourglass has bottled the moment the water arrives. The whole town's waiting in the square with cups."]],
    leave: [["livia", "The water's here! Listen to the fountains. Dad's crying. Happy crying."], ["pebble", "Honk!"], ["flint", "One more tunnel. It goes north, a thousand years on. To the Vikings."], ["frost", "And Hourglass herself has gone through it. This time we might catch her."]],
    missions: [
      { id: "aq1", kind: "cells", lv: 4, title: "Along the Arches", n: 8, time: 150,
        intro: [["livia", "The sparks are all along the top of the aqueduct. It's high. Don't look down."], ["pip", "Jump between the arches. Pebble will wait at the bottom. She doesn't like heights."]],
        outro: [["rory", "I looked down. Big mistake."], ["livia", "Everyone looks down."]] },
      { id: "aq2", kind: "tide", lv: 1, title: "Sluice Gates", time: 150,
        intro: [["livia", "The Sandbots shut the sluice gates. The water's stuck behind them, up in the hills."], ["pip", "Open and shut the gates so the water flows all the way to the town."]],
        outro: [["livia", "It's flowing! I can hear it in the channel."]] },
      { id: "aq3", kind: "valves", lv: 1, title: "The Fountains", time: 150,
        intro: [["livia", "Now the town's fountains. Too much water and they burst. Too little and they dribble."], ["pip", "Turn the valves until every fountain is in the green."]],
        outro: [["livia", "Every fountain, just right! Dad will be so proud."]] },
      { id: "aq4", kind: "dive", lv: 1, title: "The Bathhouse Drain", n: 5, time: 150,
        intro: [["livia", "The Sandbots hid sparks at the bottom of the big bath. It's deep!"], ["pip", "Hold DIVE to swim down. The bubbles at the top of the screen are your air."]],
        outro: [["rory", "I've never swum in a Roman bath before."], ["livia", "Nobody's ever swum in a Roman bath with a dinosaur before. Look at her paddle!"]] },
      { id: "aq5", kind: "echo", lv: 2, title: "Two Levers", time: 150,
        intro: [["livia", "The last gate needs two levers pulled at once, and they're far apart."], ["pip", "Pull one, then ECHO. Your echo pulls it again while you get to the other one!"]],
        outro: [["livia", "Both at once! You and... you. How does that work?"], ["rory", "No idea. It just does."]] },
      { id: "aq6", kind: "chase", lv: 4, title: "The Roman Road", time: 150,
        intro: [["livia", "Doctor Hourglass! She's escaping down the road in a cart with the last bottle!"], ["pip", "Take the cart. Drag to steer, and TAG her!"]],
        outro: [["hourglass", "Tagged? Me? Oh, you are annoying. Do you know how long it took me to get here?"], ["rory", "Two thousand years?"], ["hourglass", "Exactly! And I hate waiting. Goodbye, Agent Rory."], ["flint", "She's dropped the bottle! The water's free. But she's gone to the Vikings."]] },
    ] },
  // ------------------------------------------------------------ 6. Viking seas
  { id: "fjord", ch: 1, name: "The Viking Fjord", when: "1,000 years ago", year: 1000, contact: "sigrid", pebble: 1.8, disguise: { coat: 0x3a5a8a, trousers: 0x5a4a3a, shirt: 0xd8ccb0, tie: 0x8a5a2a },
    arrive: [["sigrid", "A dragon! No. A very small dragon. With horns."], ["rory", "She's a dinosaur. Pebble. I'm Rory."], ["sigrid", "I'm Sigrid. I build ships. Our biggest longship sails for Iceland today, but her sail is gone. A woman in a coat of glass buttons took it!"], ["pip", "That's her. Hourglass. And she's still here."]],
    leave: [["sigrid", "The sail is up! She's away, all the way to Iceland!"], ["pebble", "Honk honk!"], ["rory", "Pebble's almost as tall as me. When did that happen?"], ["flint", "Every era, a little bit bigger. Like everybody."]],
    missions: [
      { id: "vik1", kind: "boatchase", lv: 2, title: "Longship Race", time: 150,
        intro: [["sigrid", "The Sandbots have a boat with our sail rolled up in it! Take my little longship."], ["pip", "Drag to steer through the fjord. Catch them and TAG them!"]],
        outro: [["rory", "Tagged! But they threw the sail over the side."], ["sigrid", "Into the fjord? It's so cold!"]] },
      { id: "vik2", kind: "codes", lv: 3, title: "Rune Stones", time: 150,
        intro: [["sigrid", "Hourglass left a message on the rune stones. The runes glow, one after another."], ["pip", "Watch the runes, then tap them in the same order to read her message."]],
        outro: [["rory", "It says: Why wait? Love, H."], ["sigrid", "She signed it. With a love. Strange woman."]] },
      { id: "vik3", kind: "starmap", lv: 1, title: "Steer by the Stars", time: 150,
        intro: [["sigrid", "Hourglass's ship left at night. We can follow her by the stars, like my grandad does."], ["pip", "Join the stars to draw the pictures that point the way."]],
        outro: [["sigrid", "She went to the island at the mouth of the fjord! Her ship's there."]] },
      { id: "vik4", kind: "stealth", lv: 2, title: "The Sail Loft", time: 150,
        intro: [["sigrid", "Her Sandbots are guarding the boathouse. The sail must be in there."], ["pip", "Sneak past them. Stay out of their lanterns!"]],
        outro: [["rory", "The sail isn't here. But there's a note: 'Look under the water, slowcoach.'"], ["sigrid", "That's so rude."]] },
      { id: "vik5", kind: "dive", lv: 2, title: "Under the Fjord", n: 6, time: 180,
        intro: [["sigrid", "The sail sank in pieces. Six pieces, down on the fjord bed."], ["pip", "Hold DIVE to swim down. Watch your air!"]],
        outro: [["rory", "All six pieces. We can sew it back together."], ["sigrid", "My mum can sew a sail in an hour. She's the fastest in the fjord."]] },
      { id: "vik6", kind: "boss", lv: 1, title: "The Sand Serpent", time: 180,
        intro: [["hourglass", "Why wait for a sail? I'll take the whole fjord. Meet my Sand Serpent!"], ["pip", "It's a giant snake made of sand! Bubble the glowing hourglasses on its back!"], ["pebble", "HONK!"]],
        outro: [["hourglass", "My Serpent! It's a beach now. A beach!"], ["rory", "Give up, Hourglass."], ["hourglass", "Give up? I'm only getting started. The future's where I'm going, Agent Rory. And it's nearly ready."], ["flint", "She's gone forward in time. And look. She dropped a drawing. It's signed: Wren."]] },
    ] },
];

export const CREDITS = [
  ["Agent Rory: Timeslip", "A game for Rory"],
  ["Story, code and eras", "Written with Claude"],
  ["3D", "three.js, with bloom, SMAA and AgX tone mapping"],
  ["Physics", "Rapier: Rory, Pebble, the time-sled and every tumbling crate"],
  ["Music and sound", "Tone.js synthesizers, played live"],
  ["The Sandbots", "RobotExpressive by Tomás Laulhé (Quaternius), CC0"],
  ["Voices", "Kokoro-82M, an open neural voice model"],
  ["Starring", "Agent Rory, Pebble, Pip, Dr Flint, Admiral Frost, and Doctor Hourglass"],
];

export const ALL = PLACES.flatMap(p => p.missions.map(m => ({ ...m, place: p.id })));
export function placeOf(mid) { return PLACES.find(p => p.missions.some(m => m.id === mid)); }
